-- Seed data for N5 Vocabularies (Total: 662)

INSERT INTO public.vocabularies (id, level, kanji, kana, romaji, meaning, type) VALUES
('v_n5_auto_1', 'N5', '毎朝', 'まいあさ', 'maiasa', 'every morning', 'Noun'),
('v_n5_auto_2', 'N5', '問題', 'もんだい', 'mondai', 'problem', 'Noun'),
('v_n5_auto_3', 'N5', 'お茶', 'おちゃ', 'ocha', 'green tea', 'Noun'),
('v_n5_auto_4', 'N5', '黒', 'くろ', 'kuro', 'black', 'Noun'),
('v_n5_auto_5', 'N5', '台所', 'だいどころ', 'daidokoro', 'kitchen', 'Noun'),
('v_n5_auto_6', 'N5', '葉書', 'はがき', 'hagaki', 'postcard', 'Noun'),
('v_n5_auto_7', 'N5', NULL, 'ペン', 'pen', 'pen', 'Noun'),
('v_n5_auto_8', 'N5', NULL, 'ニュース', 'nyūsu', 'news', 'Noun'),
('v_n5_auto_9', 'N5', '花瓶', 'かびん', 'kabin', 'a vase', 'Noun'),
('v_n5_auto_10', 'N5', NULL, 'フォーク', 'fōku', 'fork', 'Noun'),
('v_n5_auto_11', 'N5', '引く', 'ひく', 'hiku', 'to pull', 'Noun'),
('v_n5_auto_12', 'N5', NULL, 'フィルム', 'firumu', 'roll of film', 'Noun'),
('v_n5_auto_13', 'N5', '磨く', 'みがく', 'migaku', 'to brush teeth, to polish', 'Noun'),
('v_n5_auto_14', 'N5', '押す', 'おす', 'osu', 'to push, to stamp something', 'Noun'),
('v_n5_auto_15', 'N5', '売る', 'うる', 'uru', 'to sell', 'Noun'),
('v_n5_auto_16', 'N5', '電気', 'でんき', 'denki', 'electricity, electric light', 'Noun'),
('v_n5_auto_17', 'N5', '並ぶ', 'ならぶ', 'narabu', 'to line up, to stand in a line', 'Noun'),
('v_n5_auto_18', 'N5', '病気', 'びょうき', 'byōki', 'illness', 'Noun'),
('v_n5_auto_19', 'N5', NULL, 'ポケット', 'poketto', 'pocket', 'Noun'),
('v_n5_auto_20', 'N5', '頭', 'あたま', 'atama', 'head', 'Noun'),
('v_n5_auto_21', 'N5', NULL, 'はし', 'hashi', 'chopsticks', 'Noun'),
('v_n5_auto_22', 'N5', '英語', 'えいご', 'eigo', 'English language', 'Noun'),
('v_n5_auto_23', 'N5', '家', 'いえ', 'ie', 'house', 'Noun'),
('v_n5_auto_24', 'N5', '一月', 'ひとつき', 'hitotsuki', 'one month', 'Noun'),
('v_n5_auto_25', 'N5', '暑い', 'あつい', 'atsui', 'hot', 'Noun'),
('v_n5_auto_26', 'N5', '遊ぶ', 'あ��ぶ', 'asobu', 'to play, to make a visit', 'Noun'),
('v_n5_auto_27', 'N5', '取る', 'とる', 'toru', 'to take something', 'Noun'),
('v_n5_auto_28', 'N5', '九', 'きゅう / く', 'kyū / ku', 'nine', 'Noun'),
('v_n5_auto_29', 'N5', '閉める', 'しめる', 'shimeru', 'to close something', 'Noun'),
('v_n5_auto_30', 'N5', NULL, 'たいへん', 'taihen', 'very', 'Noun'),
('v_n5_auto_31', 'N5', '奥さん', 'おくさん', 'okusan', '(honorable) wife', 'Noun'),
('v_n5_auto_32', 'N5', '作文', 'さくぶん', 'sakubun', 'composition, writing', 'Noun'),
('v_n5_auto_33', 'N5', '便利', 'べんり', 'benri', 'useful, convenient', 'Noun'),
('v_n5_auto_34', 'N5', '右', 'みぎ', 'migi', 'right side', 'Noun'),
('v_n5_auto_35', 'N5', '寒い', 'さむい', 'samui', 'cold', 'Noun'),
('v_n5_auto_36', 'N5', NULL, 'あびる', 'abiru', 'to bathe, to shower', 'Noun'),
('v_n5_auto_37', 'N5', '十', 'じゅう  とお', 'jū  tō', 'ten', 'Noun'),
('v_n5_auto_38', 'N5', '中', 'なか', 'naka', 'middle', 'Noun'),
('v_n5_auto_39', 'N5', '消す', 'けす', 'kesu', 'to erase, to turn off power', 'Noun'),
('v_n5_auto_40', 'N5', '近く', 'ちかく', 'chikaku', 'near', 'Noun'),
('v_n5_auto_41', 'N5', '七つ', 'ななつ', 'nanatsu', 'seven', 'Noun'),
('v_n5_auto_42', 'N5', NULL, 'テープレコーダー', 'tēpurekōdā', 'tape recorder', 'Noun'),
('v_n5_auto_43', 'N5', '目', 'め', 'me', 'eye', 'Noun'),
('v_n5_auto_44', 'N5', '空', 'そら', 'sora', 'sky', 'Noun'),
('v_n5_auto_45', 'N5', '六日', 'むいか', 'muika', 'six days, sixth day of the month', 'Noun'),
('v_n5_auto_46', 'N5', '座る', 'すわる', 'suwaru', 'to sit', 'Noun'),
('v_n5_auto_47', 'N5', '年', 'とし', 'toshi', 'year', 'Noun'),
('v_n5_auto_48', 'N5', '男の子', 'おとこのこ', 'otokonoko', 'boy', 'Noun'),
('v_n5_auto_49', 'N5', '狭い', 'せまい', 'semai', 'narrow', 'Noun'),
('v_n5_auto_50', 'N5', '冷蔵庫', 'れいぞうこ', 'reizōko', 'refrigerator', 'Noun'),
('v_n5_auto_51', 'N5', NULL, 'カメラ', 'kamera', 'camera', 'Noun'),
('v_n5_auto_52', 'N5', '玄関', 'げんかん', 'genkan', 'entry hall', 'Noun'),
('v_n5_auto_53', 'N5', '違う', 'ちがう', 'chigau', 'to differ', 'Noun'),
('v_n5_auto_54', 'N5', '危ない', 'あぶない', 'abunai', 'dangerous', 'Noun'),
('v_n5_auto_55', 'N5', '分かる', 'わかる', 'wakaru', 'to be understood', 'Noun'),
('v_n5_auto_56', 'N5', '言う', 'いう', 'iu', 'to say', 'Noun'),
('v_n5_auto_57', 'N5', '飲む', 'のむ', 'nomu', 'to drink', 'Noun'),
('v_n5_auto_58', 'N5', '練習', 'れんしゅうする', 'renshūsuru', 'to practice', 'Noun'),
('v_n5_auto_59', 'N5', '何', 'なん / なに', 'nan / nani', 'what', 'Noun'),
('v_n5_auto_60', 'N5', '厚い', 'あつい', 'atsui', 'kind, deep, thick', 'Noun'),
('v_n5_auto_61', 'N5', '毎月', 'まいげつ / まいつき', 'maigetsu / maitsuki', 'every month', 'Noun'),
('v_n5_auto_62', 'N5', '閉まる', 'しまる', 'shimaru', 'to close, to be closed', 'Noun'),
('v_n5_auto_63', 'N5', '脱ぐ', 'ぬぐ', 'nugu', 'to take off clothes', 'Noun'),
('v_n5_auto_64', 'N5', '黒い', 'くろい', 'kuroi', 'black', 'Noun'),
('v_n5_auto_65', 'N5', '登る', 'のぼる', 'noboru', 'to climb', 'Noun'),
('v_n5_auto_66', 'N5', '汚い', 'きたない', 'kitanai', 'dirty', 'Noun'),
('v_n5_auto_67', 'N5', '雨', 'あめ', 'ame', 'rain', 'Noun'),
('v_n5_auto_68', 'N5', 'お皿', 'おさら', 'osara', 'plate, dish', 'Noun'),
('v_n5_auto_69', 'N5', '速い', 'はやい', 'hayai', 'quick', 'Noun'),
('v_n5_auto_70', 'N5', 'お風呂', 'おふろ', 'ofuro', 'bath', 'Noun'),
('v_n5_auto_71', 'N5', '新しい', 'あたらしい', 'atarashii', 'new', 'Noun'),
('v_n5_auto_72', 'N5', '廊下', 'ろうか', 'rōka', 'corridor', 'Noun'),
('v_n5_auto_73', 'N5', '茶色', 'ちゃいろ', 'chairo', 'brown', 'Noun'),
('v_n5_auto_74', 'N5', NULL, 'コート', 'kōto', 'coat, tennis court', 'Noun'),
('v_n5_auto_75', 'N5', '手紙', 'てがみ', 'tegami', 'letter', 'Noun'),
('v_n5_auto_76', 'N5', '要る', 'いる', 'iru', 'to need', 'Noun'),
('v_n5_auto_77', 'N5', NULL, 'こっち', 'kotchi', 'this person or way', 'Noun'),
('v_n5_auto_78', 'N5', NULL, 'スプーン', 'supūn', 'spoon', 'Noun'),
('v_n5_auto_79', 'N5', '時々', 'ときどき', 'tokidoki', 'sometimes', 'Noun'),
('v_n5_auto_80', 'N5', '傘', 'かさ', 'kasa', 'umbrella', 'Noun'),
('v_n5_auto_81', 'N5', NULL, 'いい / よい', 'ii / yoi', 'good', 'Noun'),
('v_n5_auto_82', 'N5', '電話', 'でんわ', 'denwa', 'telephone', 'Noun'),
('v_n5_auto_83', 'N5', '勤める', 'つとめる', 'tsutomeru', 'to work for someone', 'Noun'),
('v_n5_auto_84', 'N5', '安い', 'やすい', 'yasui', 'cheap', 'Noun'),
('v_n5_auto_85', 'N5', NULL, 'どう', 'dō', 'how, in what way', 'Noun'),
('v_n5_auto_86', 'N5', '道', 'みち', 'michi', 'street', 'Noun'),
('v_n5_auto_87', 'N5', NULL, 'バス', 'basu', 'bus', 'Noun'),
('v_n5_auto_88', 'N5', NULL, 'クラス', 'kurasu', 'class', 'Noun'),
('v_n5_auto_89', 'N5', '差す', 'さす', 'sasu', 'to stretch out hands, to raise an umbrella', 'Noun'),
('v_n5_auto_90', 'N5', NULL, 'スポーツ', 'supōtsu', 'sport', 'Noun'),
('v_n5_auto_91', 'N5', NULL, 'どっち', 'dotchi', 'which', 'Noun'),
('v_n5_auto_92', 'N5', NULL, 'そば', 'soba', 'near, beside', 'Noun'),
('v_n5_auto_93', 'N5', '新聞', 'しんぶん', 'shinbun', 'newspaper', 'Noun'),
('v_n5_auto_94', 'N5', NULL, 'どうして', 'dōshite', 'for what reason', 'Noun'),
('v_n5_auto_95', 'N5', '庭', 'にわ', 'niwa', 'garden', 'Noun'),
('v_n5_auto_96', 'N5', '大きな', 'おおきな', 'ōkina', 'big', 'Noun'),
('v_n5_auto_97', 'N5', '辺', 'へん', 'hen', 'area', 'Noun'),
('v_n5_auto_98', 'N5', '番号', 'ばんごう', 'bangō', 'number', 'Noun'),
('v_n5_auto_99', 'N5', '家族', 'かぞく', 'kazoku', 'family', 'Noun'),
('v_n5_auto_100', 'N5', '下手', 'へた', 'heta', 'unskillful', 'Noun'),
('v_n5_auto_101', 'N5', '料理', 'りょうり', 'ryōri', 'cuisine', 'Noun'),
('v_n5_auto_102', 'N5', NULL, 'カレー', 'karē', 'curry', 'Noun'),
('v_n5_auto_103', 'N5', '六', 'ろく', 'roku', 'six', 'Noun'),
('v_n5_auto_104', 'N5', '今年', 'ことし', 'kotoshi', 'this year', 'Noun'),
('v_n5_auto_105', 'N5', '初めて', 'はじめて', 'hajimete', 'for the first time', 'Noun'),
('v_n5_auto_106', 'N5', '風邪', 'かぜ', 'kaze', 'a cold', 'Noun'),
('v_n5_auto_107', 'N5', '赤い', 'あかい', 'akai', 'red', 'Noun'),
('v_n5_auto_108', 'N5', '甘い', 'あまい', 'amai', 'sweet', 'Noun'),
('v_n5_auto_109', 'N5', '西', 'にし', 'nishi', 'west', 'Noun'),
('v_n5_auto_110', 'N5', '毎週', 'まいしゅう', 'maishū', 'every week', 'Noun'),
('v_n5_auto_111', 'N5', NULL, 'いつも', 'itsumo', 'always', 'Noun'),
('v_n5_auto_112', 'N5', '五つ', 'いつつ', 'itsutsu', 'five', 'Noun'),
('v_n5_auto_113', 'N5', '建物', 'たてもの', 'tatemono', 'building', 'Noun'),
('v_n5_auto_114', 'N5', NULL, 'なる', 'naru', 'to become', 'Noun'),
('v_n5_auto_115', 'N5', NULL, 'まっすぐ', 'massugu', 'straight ahead, direct', 'Noun'),
('v_n5_auto_116', 'N5', '作る', 'つくる', 'tsukuru', 'to make', 'Noun'),
('v_n5_auto_117', 'N5', '風', 'かぜ', 'kaze', 'wind', 'Noun'),
('v_n5_auto_118', 'N5', '少��', 'すこし', 'sukoshi', 'few', 'Noun'),
('v_n5_auto_119', 'N5', '大学', 'だいがく', 'daigaku', 'university', 'Noun'),
('v_n5_auto_120', 'N5', NULL, 'シャツ', 'shatsu', 'shirt', 'Noun'),
('v_n5_auto_121', 'N5', '病院', 'びょういん', 'byōin', 'hospital', 'Noun'),
('v_n5_auto_122', 'N5', '会社', 'かいしゃ', 'kaisha', 'company', 'Noun'),
('v_n5_auto_123', 'N5', '無くす', 'なくす', 'nakusu', 'to lose something', 'Noun'),
('v_n5_auto_124', 'N5', NULL, 'スリッパ', 'surippa', 'slippers', 'Noun'),
('v_n5_auto_125', 'N5', '地下鉄', 'ちかてつ', 'chikatetsu', 'underground train', 'Noun'),
('v_n5_auto_126', 'N5', NULL, 'ページ', 'pēji', 'page', 'Noun'),
('v_n5_auto_127', 'N5', '曇る', 'くもる', 'kumoru', 'to become cloudy, to become dim', 'Noun'),
('v_n5_auto_128', 'N5', '辞書', 'じしょ', 'jisho', 'dictionary', 'Noun'),
('v_n5_auto_129', 'N5', '万年筆', 'まんねんひつ', 'mannenhitsu', 'fountain pen', 'Noun'),
('v_n5_auto_130', 'N5', '海', 'うみ', 'umi', 'sea', 'Noun'),
('v_n5_auto_131', 'N5', NULL, 'エレベーター', 'erebētā', 'elevator', 'Noun'),
('v_n5_auto_132', 'N5', NULL, 'たぶん', 'tabun', 'probably', 'Noun'),
('v_n5_auto_133', 'N5', '夕方', 'ゆうがた', 'yūgata', 'evening', 'Noun'),
('v_n5_auto_134', 'N5', '東', 'ひがし', 'higashi', 'east', 'Noun'),
('v_n5_auto_135', 'N5', '声', 'こえ', 'koe', 'voice', 'Noun'),
('v_n5_auto_136', 'N5', '撮る', 'とる', 'toru', 'to take a photo or record a film', 'Noun'),
('v_n5_auto_137', 'N5', '私', 'わたくし', 'watakushi', '(humble) I, myself', 'Noun'),
('v_n5_auto_138', 'N5', '両親', 'りょうしん', 'ryōshin', 'both parents', 'Noun'),
('v_n5_auto_139', 'N5', NULL, 'きれい', 'kirei', 'pretty, clean', 'Noun'),
('v_n5_auto_140', 'N5', NULL, 'どうぞ', 'dōzo', 'please', 'Noun'),
('v_n5_auto_141', 'N5', '好き', 'すき', 'suki', 'likeable', 'Noun'),
('v_n5_auto_142', 'N5', '静か', 'しずか', 'shizuka', 'quiet', 'Noun'),
('v_n5_auto_143', 'N5', 'お父さん', 'おとうさん', 'otōsan', '(honorable) father', 'Noun'),
('v_n5_auto_144', 'N5', '人', 'ひと', 'hito', 'person', 'Noun'),
('v_n5_auto_145', 'N5', '覚える', 'おぼえる', 'oboeru', 'to remember', 'Noun'),
('v_n5_auto_146', 'N5', '休み', 'やすみ', 'yasumi', 'rest, holiday', 'Noun'),
('v_n5_auto_147', 'N5', '池', 'いけ', 'ike', 'pond', 'Noun'),
('v_n5_auto_148', 'N5', '始まる', 'はじまる', 'hajimaru', 'to begin', 'Noun'),
('v_n5_auto_149', 'N5', '困る', 'こまる', 'komaru', 'to be worried', 'Noun'),
('v_n5_auto_150', 'N5', NULL, 'ほか', 'hoka', 'other, the rest', 'Noun'),
('v_n5_auto_151', 'N5', NULL, 'ちゃわん', 'chawan', 'rice bowl', 'Noun'),
('v_n5_auto_152', 'N5', '疲れる', 'つかれる', 'tsukareru', 'to get tired', 'Noun'),
('v_n5_auto_153', 'N5', '掃除', 'そうじする', 'sōjisuru', 'to clean, to sweep', 'Noun'),
('v_n5_auto_154', 'N5', '賑やか', 'にぎやか', 'nigiyaka', 'bustling, busy', 'Noun'),
('v_n5_auto_155', 'N5', '一つ', 'ひとつ', 'hitotsu', 'one', 'Noun'),
('v_n5_auto_156', 'N5', '来週', 'らいしゅう', 'raishū', 'next week', 'Noun'),
('v_n5_auto_157', 'N5', '財布', 'さいふ', 'saifu', 'wallet', 'Noun'),
('v_n5_auto_158', 'N5', '知る', 'しる', 'shiru', 'to know', 'Noun'),
('v_n5_auto_159', 'N5', '教える', 'おしえる', 'oshieru', 'to teach, to tell', 'Noun'),
('v_n5_auto_160', 'N5', '朝御飯', 'あさごはん', 'asagohan', 'breakfast', 'Noun'),
('v_n5_auto_161', 'N5', '飛ぶ', 'とぶ', 'tobu', 'to fly, to hop', 'Noun'),
('v_n5_auto_162', 'N5', '言葉', 'ことば', 'kotoba', 'word, language', 'Noun'),
('v_n5_auto_163', 'N5', NULL, 'キロ / キログラム', 'kiro / kiroguramu', 'kilogram', 'Noun'),
('v_n5_auto_164', 'N5', '赤', 'あか', 'aka', 'red', 'Noun'),
('v_n5_auto_165', 'N5', '自分', 'じぶん', 'jibun', 'oneself', 'Noun'),
('v_n5_auto_166', 'N5', NULL, 'デパート', 'depāto', 'department store', 'Noun'),
('v_n5_auto_167', 'N5', '薄い', 'うすい', 'usui', 'thin, weak', 'Noun'),
('v_n5_auto_168', 'N5', '高い', 'たかい', 'takai', 'tall, expensive', 'Noun'),
('v_n5_auto_169', 'N5', '帰る', 'かえる', 'kaeru', 'to go back', 'Noun'),
('v_n5_auto_170', 'N5', NULL, 'はい', 'hai', 'yes', 'Noun'),
('v_n5_auto_171', 'N5', '卵', 'たまご', 'tamago', 'egg', 'Noun'),
('v_n5_auto_172', 'N5', '低い', 'ひくい', 'hikui', 'short, low', 'Noun'),
('v_n5_auto_173', 'N5', NULL, 'なぜ', 'naze', 'why', 'Noun'),
('v_n5_auto_174', 'N5', '一日', 'いちにち', 'ichinichi', '(1) one day, (2) first of month', 'Noun'),
('v_n5_auto_175', 'N5', NULL, 'いいえ', 'iie', 'no', 'Noun'),
('v_n5_auto_176', 'N5', '小さな', 'ちいさな', 'chiisana', 'little', 'Noun'),
('v_n5_auto_177', 'N5', '時間', 'じかん', 'jikan', 'time', 'Noun'),
('v_n5_auto_178', 'N5', '上げる', 'あげる', 'ageru', 'to give', 'Noun'),
('v_n5_auto_179', 'N5', NULL, 'ふろ', 'furo', 'bath', 'Noun'),
('v_n5_auto_180', 'N5', '生徒', 'せいと', 'seito', 'pupil', 'Noun'),
('v_n5_auto_181', 'N5', NULL, 'レストラン', 'resutoran', 'restaurant', 'Noun'),
('v_n5_auto_182', 'N5', '出す', 'だす', 'dasu', 'to put out', 'Noun'),
('v_n5_auto_183', 'N5', NULL, 'かわいい', 'kawaii', 'cute', 'Noun'),
('v_n5_auto_184', 'N5', '音楽', 'おんがく', 'ongaku', 'music', 'Noun'),
('v_n5_auto_185', 'N5', '歌', 'うた', 'uta', 'song', 'Noun'),
('v_n5_auto_186', 'N5', NULL, 'いちばん', 'ichiban', 'best, first', 'Noun'),
('v_n5_auto_187', 'N5', '咲く', 'さく', 'saku', 'to bloom', 'Noun'),
('v_n5_auto_188', 'N5', '山', 'やま', 'yama', 'mountain', 'Noun'),
('v_n5_auto_189', 'N5', NULL, 'テレビ', 'terebi', 'television', 'Noun'),
('v_n5_auto_190', 'N5', '授業', 'じゅぎょう', 'jugyō', 'lesson, class work', 'Noun'),
('v_n5_auto_191', 'N5', '暖かい', 'あたたかい', 'atatakai', 'warm', 'Noun'),
('v_n5_auto_192', 'N5', NULL, 'セーター', 'sētā', 'sweater, jumper', 'Noun'),
('v_n5_auto_193', 'N5', '自転車', 'じてんしゃ', 'jitensha', 'bicycle', 'Noun'),
('v_n5_auto_194', 'N5', NULL, 'ラジカセ / ラジオカセット', 'rajikase / rajiokasetto', 'radio cassette player', 'Noun'),
('v_n5_auto_195', 'N5', NULL, 'つける', 'tsukeru', 'to turn on', 'Noun'),
('v_n5_auto_196', 'N5', 'さ来年', 'さらいねん', 'sarainen', 'year after next', 'Noun'),
('v_n5_auto_197', 'N5', '学校', 'がっこう', 'gakkō', 'school', 'Noun'),
('v_n5_auto_198', 'N5', NULL, 'いくら', 'ikura', 'how much?', 'Noun'),
('v_n5_auto_199', 'N5', '四', 'し / よん', 'shi / yon', 'four', 'Noun'),
('v_n5_auto_200', 'N5', '入る', 'はいる', 'hairu', 'to enter, to contain', 'Noun');

INSERT INTO public.vocabularies (id, level, kanji, kana, romaji, meaning, type) VALUES
('v_n5_auto_201', 'N5', '曇り', 'くもり', 'kumori', 'cloudy weather', 'Noun'),
('v_n5_auto_202', 'N5', '外国', 'がいこく', 'gaikoku', 'foreign country', 'Noun'),
('v_n5_auto_203', 'N5', '温い', 'ぬるい', 'nurui', 'luke warm', 'Noun'),
('v_n5_auto_204', 'N5', NULL, 'そうして / そして', 'sōshite / soshite', 'and', 'Noun'),
('v_n5_auto_205', 'N5', NULL, 'どうも', 'dōmo', 'thanks', 'Noun'),
('v_n5_auto_206', 'N5', '仕事', 'しごと', 'shigoto', 'job', 'Noun'),
('v_n5_auto_207', 'N5', '窓', 'まど', 'mado', 'window', 'Noun'),
('v_n5_auto_208', 'N5', '晩', 'ばん', 'ban', 'evening', 'Noun'),
('v_n5_auto_209', 'N5', '難しい', 'むずかしい', 'muzukashii', 'difficult', 'Noun'),
('v_n5_auto_210', 'N5', '村', 'むら', 'mura', 'village', 'Noun'),
('v_n5_auto_211', 'N5', '鉛筆', 'えんぴつ', 'enpitsu', 'pencil', 'Noun'),
('v_n5_auto_212', 'N5', '長い', 'ながい', 'nagai', 'long', 'Noun'),
('v_n5_auto_213', 'N5', '生まれる', 'うまれる', 'umareru', 'to be born', 'Noun'),
('v_n5_auto_214', 'N5', '雑誌', 'ざっし', 'zasshi', 'magazine', 'Noun'),
('v_n5_auto_215', 'N5', '国', 'くに', 'kuni', 'country', 'Noun'),
('v_n5_auto_216', 'N5', NULL, 'おまわりさん', 'omawarisan', 'friendly term for policeman', 'Noun'),
('v_n5_auto_217', 'N5', '今朝', 'けさ', 'kesa', 'this morning', 'Noun'),
('v_n5_auto_218', 'N5', '晴れる', 'はれる', 'hareru', 'to be sunny', 'Noun'),
('v_n5_auto_219', 'N5', '夕飯', 'ゆうはん', 'yūhan', 'dinner', 'Noun'),
('v_n5_auto_220', 'N5', '一緒', 'いっしょ', 'issho', 'together', 'Noun'),
('v_n5_auto_221', 'N5', NULL, 'どれ', 'dore', 'which (of three or more)', 'Noun'),
('v_n5_auto_222', 'N5', '立つ', 'たつ', 'tatsu', 'to stand', 'Noun'),
('v_n5_auto_223', 'N5', '元気', 'げんき', 'genki', 'health, vitality', 'Noun'),
('v_n5_auto_224', 'N5', '天気', 'てんき', 'tenki', 'weather', 'Noun'),
('v_n5_auto_225', 'N5', '医者', 'いしゃ', 'isha', 'medical doctor', 'Noun'),
('v_n5_auto_226', 'N5', '七', 'しち / なな', 'shichi / nana', 'seven', 'Noun'),
('v_n5_auto_227', 'N5', NULL, 'はく', 'haku', 'to wear, to put on trousers', 'Noun'),
('v_n5_auto_228', 'N5', NULL, 'だんだん', 'dandan', 'gradually', 'Noun'),
('v_n5_auto_229', 'N5', '戸', 'と', 'to', 'Japanese style door', 'Noun'),
('v_n5_auto_230', 'N5', NULL, 'ノート', 'nōto', 'notebook, exercise book', 'Noun'),
('v_n5_auto_231', 'N5', NULL, 'また', 'mata', 'again, and', 'Noun'),
('v_n5_auto_232', 'N5', '今日', 'きょう', 'kyō', 'today', 'Noun'),
('v_n5_auto_233', 'N5', NULL, 'とても', 'totemo', 'very', 'Noun'),
('v_n5_auto_234', 'N5', '一昨年', 'おととし', 'ototoshi', 'year before last', 'Noun'),
('v_n5_auto_235', 'N5', '文章', 'ぶんしょう', 'bunshō', 'sentence, text', 'Noun'),
('v_n5_auto_236', 'N5', '公園', 'こうえん', 'kōen', 'park', 'Noun'),
('v_n5_auto_237', 'N5', '借りる', 'かりる', 'kariru', 'to borrow', 'Noun'),
('v_n5_auto_238', 'N5', '口', 'くち', 'kuchi', 'mouth, opening', 'Noun'),
('v_n5_auto_239', 'N5', '持つ', 'もつ', 'motsu', 'to hold', 'Noun'),
('v_n5_auto_240', 'N5', '上着', 'うわぎ', 'uwagi', 'jacket', 'Noun'),
('v_n5_auto_241', 'N5', '秋', 'あき', 'aki', 'autumn', 'Noun'),
('v_n5_auto_242', 'N5', '悪い', 'わるい', 'warui', 'bad', 'Noun'),
('v_n5_auto_243', 'N5', '青い', 'あおい', 'aoi', 'blue', 'Noun'),
('v_n5_auto_244', 'N5', '住む', 'すむ', 'sumu', 'to live in', 'Noun'),
('v_n5_auto_245', 'N5', NULL, 'かける', 'kakeru', 'to call by phone', 'Noun'),
('v_n5_auto_246', 'N5', '木曜日', 'もくようび', 'mokuyōbi', 'Thursday', 'Noun'),
('v_n5_auto_247', 'N5', '忘れる', 'わすれる', 'wasureru', 'to forget', 'Noun'),
('v_n5_auto_248', 'N5', 'お手洗い', 'おてあらい', 'otearai', 'bathroom', 'Noun'),
('v_n5_auto_249', 'N5', '写真', 'しゃしん', 'shashin', 'photograph', 'Noun'),
('v_n5_auto_250', 'N5', NULL, 'ゼロ', 'zero', 'zero', 'Noun'),
('v_n5_auto_251', 'N5', NULL, 'いろいろ', 'iroiro', 'various', 'Noun'),
('v_n5_auto_252', 'N5', NULL, 'もう', 'mō', 'already', 'Noun'),
('v_n5_auto_253', 'N5', '会う', 'あう', 'au', 'to meet', 'Noun'),
('v_n5_auto_254', 'N5', '南', 'みなみ', 'minami', 'south', 'Noun'),
('v_n5_auto_255', 'N5', '五日', 'いつか', 'itsuka', 'five days, fifth day', 'Noun'),
('v_n5_auto_256', 'N5', '着る', 'きる', 'kiru', 'to put on from the shoulders down', 'Noun'),
('v_n5_auto_257', 'N5', NULL, 'そこ', 'soko', 'that place', 'Noun'),
('v_n5_auto_258', 'N5', '終る', 'おわる', 'owaru', 'to finish', 'Noun'),
('v_n5_auto_259', 'N5', NULL, 'どの', 'dono', 'which', 'Noun'),
('v_n5_auto_260', 'N5', '読む', 'よむ', 'yomu', 'to read', 'Noun'),
('v_n5_auto_261', 'N5', NULL, 'それでは', 'soredeha', 'in that situation', 'Noun'),
('v_n5_auto_262', 'N5', '来月', 'らいげつ', 'raigetsu', 'next month', 'Noun'),
('v_n5_auto_263', 'N5', '果物', 'くだもの', 'kudamono', 'fruit', 'Noun'),
('v_n5_auto_264', 'N5', '止まる', 'とまる', 'tomaru', 'to come to a halt', 'Noun'),
('v_n5_auto_265', 'N5', '着く', 'つく', 'tsuku', 'to arrive at', 'Noun'),
('v_n5_auto_266', 'N5', '大好き', 'だいすき', 'daisuki', 'to be very likeable', 'Noun'),
('v_n5_auto_267', 'N5', '妹', 'いもうと', 'imōto', '(humble) younger sister', 'Noun'),
('v_n5_auto_268', 'N5', '夏', 'なつ', 'natsu', 'summer', 'Noun'),
('v_n5_auto_269', 'N5', '今晩', 'こんばん', 'konban', 'this evening', 'Noun'),
('v_n5_auto_270', 'N5', '塩', 'しお', 'shio', 'salt', 'Noun'),
('v_n5_auto_271', 'N5', '先週', 'せんしゅう', 'senshū', 'last week', 'Noun'),
('v_n5_auto_272', 'N5', '欲しい', 'ほしい', 'hoshii', 'want', 'Noun'),
('v_n5_auto_273', 'N5', '木', 'き', 'ki', 'tree, wood', 'Noun'),
('v_n5_auto_274', 'N5', NULL, 'ほんとう', 'hontō', 'truth', 'Noun'),
('v_n5_auto_275', 'N5', '薬', 'くすり', 'kusuri', 'medicine', 'Noun'),
('v_n5_auto_276', 'N5', 'お菓子', 'おかし', 'okashi', 'sweets, candy', 'Noun'),
('v_n5_auto_277', 'N5', '金曜日', 'きんようび', 'kin''yōbi', 'Friday', 'Noun'),
('v_n5_auto_278', 'N5', NULL, 'まずい', 'mazui', 'unpleasant', 'Noun'),
('v_n5_auto_279', 'N5', 'お酒', 'おさけ', 'osake', 'alcohol, rice wine', 'Noun'),
('v_n5_auto_280', 'N5', '多い', 'おおい', 'ōi', 'many', 'Noun'),
('v_n5_auto_281', 'N5', '動物', 'どうぶつ', 'dōbutsu', 'animal', 'Noun'),
('v_n5_auto_282', 'N5', '切符', 'きっぷ', 'kippu', 'ticket', 'Noun'),
('v_n5_auto_283', 'N5', NULL, 'キロ / キロメートル', 'kiro / kiromētoru', 'kilometre', 'Noun'),
('v_n5_auto_284', 'N5', '呼ぶ', 'よぶ', 'yobu', 'to call out, to invite', 'Noun'),
('v_n5_auto_285', 'N5', '体', 'からだ', 'karada', 'body', 'Noun'),
('v_n5_auto_286', 'N5', NULL, 'ゆっくりと', 'yukkurito', 'slowly', 'Noun'),
('v_n5_auto_287', 'N5', '二日', 'ふつか', 'futsuka', 'two days, second day of the month', 'Noun'),
('v_n5_auto_288', 'N5', '大人', 'おとな', 'otona', 'adult', 'Noun'),
('v_n5_auto_289', 'N5', '歯', 'は', 'ha', 'tooth', 'Noun'),
('v_n5_auto_290', 'N5', '冬', 'ふゆ', 'fuyu', 'winter', 'Noun'),
('v_n5_auto_291', 'N5', '所', 'ところ', 'tokoro', 'place', 'Noun'),
('v_n5_auto_292', 'N5', '吹く', 'ふく', 'fuku', 'to blow', 'Noun'),
('v_n5_auto_293', 'N5', '足', 'あし', 'ashi', 'foot, leg', 'Noun'),
('v_n5_auto_294', 'N5', '箱', 'はこ', 'hako', 'box', 'Noun'),
('v_n5_auto_295', 'N5', '八', 'はち', 'hachi', 'eight', 'Noun'),
('v_n5_auto_296', 'N5', '朝', 'あさ', 'asa', 'morning', 'Noun'),
('v_n5_auto_297', 'N5', '一昨日', 'おととい', 'ototoi', 'day before yesterday', 'Noun'),
('v_n5_auto_298', 'N5', '有名', 'ゆうめい', 'yūmei', 'famous', 'Noun'),
('v_n5_auto_299', 'N5', '二十日', 'はつか', 'hatsuka', 'twenty days, twentieth', 'Noun'),
('v_n5_auto_300', 'N5', '近い', 'ちかい', 'chikai', 'near', 'Noun'),
('v_n5_auto_301', 'N5', NULL, 'ください', 'kudasai', 'please', 'Noun'),
('v_n5_auto_302', 'N5', '時計', 'とけい', 'tokei', 'watch, clock', 'Noun'),
('v_n5_auto_303', 'N5', '午後', 'ごご', 'gogo', 'afternoon', 'Noun'),
('v_n5_auto_304', 'N5', '食べ物', 'たべもの', 'tabemono', 'food', 'Noun'),
('v_n5_auto_305', 'N5', '降る', 'ふる', 'furu', 'to fall, e.g. rain or snow', 'Noun'),
('v_n5_auto_306', 'N5', '易しい', 'やさしい', 'yasashii', 'easy, simple', 'Noun'),
('v_n5_auto_307', 'N5', '大使館', 'たいしかん', 'taishikan', 'embassy', 'Noun'),
('v_n5_auto_308', 'N5', '誰', 'だれ', 'dare', 'who', 'Noun'),
('v_n5_auto_309', 'N5', '上', 'うえ', 'ue', 'on top of', 'Noun'),
('v_n5_auto_310', 'N5', '五', 'ご', 'go', 'five', 'Noun'),
('v_n5_auto_311', 'N5', '十日', 'とおか', 'tōka', 'ten days, the tenth day', 'Noun'),
('v_n5_auto_312', 'N5', NULL, 'どちら', 'dochira', 'which of two', 'Noun'),
('v_n5_auto_313', 'N5', NULL, 'プール', 'pūru', 'swimming pool', 'Noun'),
('v_n5_auto_314', 'N5', '小さい', 'ちいさい', 'chiisai', 'little', 'Noun'),
('v_n5_auto_315', 'N5', '今週', 'こんしゅう', 'konshū', 'this week', 'Noun'),
('v_n5_auto_316', 'N5', '肉', 'にく', 'niku', 'meat', 'Noun'),
('v_n5_auto_317', 'N5', '零', 'れい', 'rei', 'zero', 'Noun'),
('v_n5_auto_318', 'N5', '豚肉', 'ぶたにく', 'butaniku', 'pork', 'Noun'),
('v_n5_auto_319', 'N5', '広い', 'ひろい', 'hiroi', 'spacious, wide', 'Noun'),
('v_n5_auto_320', 'N5', '靴下', 'くつした', 'kutsushita', 'socks', 'Noun'),
('v_n5_auto_321', 'N5', '一人', 'ひとり', 'hitori', 'one person', 'Noun'),
('v_n5_auto_322', 'N5', NULL, 'かぎ', 'kagi', 'key', 'Noun'),
('v_n5_auto_323', 'N5', '向こう', 'むこう', 'mukō', 'over there', 'Noun'),
('v_n5_auto_324', 'N5', '上手', 'じょうず', 'jōzu', 'skillful', 'Noun'),
('v_n5_auto_325', 'N5', '牛肉', 'ぎゅうにく', 'gyūniku', 'beef', 'Noun'),
('v_n5_auto_326', 'N5', '話', 'はなし', 'hanashi', 'talk, story', 'Noun'),
('v_n5_auto_327', 'N5', '毎晩', 'まいばん', 'maiban', 'every night', 'Noun'),
('v_n5_auto_328', 'N5', '三つ', 'みっつ', 'mittsu', 'three', 'Noun'),
('v_n5_auto_329', 'N5', '吸う', 'すう', 'sū', 'to smoke, to suck', 'Noun'),
('v_n5_auto_330', 'N5', '銀行', 'ぎんこう', 'ginkō', 'bank', 'Noun'),
('v_n5_auto_331', 'N5', '大切', 'たいせつ', 'taisetsu', 'important', 'Noun'),
('v_n5_auto_332', 'N5', '学生', 'がくせい', 'gakusei', 'student', 'Noun'),
('v_n5_auto_333', 'N5', '部屋', 'へや', 'heya', 'room', 'Noun'),
('v_n5_auto_334', 'N5', '昼御飯', 'ひるごはん', 'hirugohan', 'midday meal', 'Noun'),
('v_n5_auto_335', 'N5', '下', 'した', 'shita', 'below', 'Noun'),
('v_n5_auto_336', 'N5', '二つ', 'ふたつ', 'futatsu', 'two', 'Noun'),
('v_n5_auto_337', 'N5', '百', 'ひゃく', 'hyaku', 'hundred', 'Noun'),
('v_n5_auto_338', 'N5', '地図', 'ちず', 'chizu', 'map', 'Noun'),
('v_n5_auto_339', 'N5', '八百屋', 'やおや', 'yaoya', 'greengrocer', 'Noun'),
('v_n5_auto_340', 'N5', NULL, 'ネクタイ', 'nekutai', 'tie, necktie', 'Noun'),
('v_n5_auto_341', 'N5', '去年', 'きょねん', 'kyonen', 'last year', 'Noun'),
('v_n5_auto_342', 'N5', '火曜日', 'かようび', 'kayōbi', 'Tuesday', 'Noun'),
('v_n5_auto_343', 'N5', '乗る', 'のる', 'noru', 'to get on, to ride', 'Noun'),
('v_n5_auto_344', 'N5', '弟', 'おとうと', 'otōto', 'younger brother', 'Noun'),
('v_n5_auto_345', 'N5', NULL, 'あなた', 'anata', 'you', 'Noun'),
('v_n5_auto_346', 'N5', '千', 'せん', 'sen', 'thousand', 'Noun'),
('v_n5_auto_347', 'N5', '緑', 'みどり', 'midori', 'green', 'Noun'),
('v_n5_auto_348', 'N5', 'とり肉', 'とりにく', 'toriniku', 'chicken meat', 'Noun'),
('v_n5_auto_349', 'N5', '軽い', 'かるい', 'karui', 'light', 'Noun'),
('v_n5_auto_350', 'N5', NULL, 'あまり', 'amari', 'not very', 'Noun'),
('v_n5_auto_351', 'N5', '帽子', 'ぼうし', 'bōshi', 'hat', 'Noun'),
('v_n5_auto_352', 'N5', '丈夫', 'じょうぶ', 'jōbu', 'strong, durable', 'Noun'),
('v_n5_auto_353', 'N5', '入れる', 'いれる', 'ireru', 'to put in', 'Noun'),
('v_n5_auto_354', 'N5', '二十歳', 'はたち', 'hatachi', '20 years old, 20th year', 'Noun'),
('v_n5_auto_355', 'N5', '三日', 'みっか', 'mikka', 'three days, third day of the month', 'Noun'),
('v_n5_auto_356', 'N5', '遠い', 'とおい', 'tōi', 'far', 'Noun'),
('v_n5_auto_357', 'N5', '夏休み', 'なつやすみ', 'natsuyasumi', 'summer holiday', 'Noun'),
('v_n5_auto_358', 'N5', '友達', 'ともだち', 'tomodachi', 'friend', 'Noun'),
('v_n5_auto_359', 'N5', '横', 'よこ', 'yoko', 'beside, side, width', 'Noun'),
('v_n5_auto_360', 'N5', '冷たい', 'つめたい', 'tsumetai', 'cold to the touch', 'Noun'),
('v_n5_auto_361', 'N5', '夜', 'よる', 'yoru', 'evening, night', 'Noun'),
('v_n5_auto_362', 'N5', NULL, 'トイレ', 'toire', 'toilet', 'Noun'),
('v_n5_auto_363', 'N5', NULL, 'おなか', 'onaka', 'stomach', 'Noun'),
('v_n5_auto_364', 'N5', NULL, 'どこ', 'doko', 'where', 'Noun'),
('v_n5_auto_365', 'N5', '暇', 'ひま', 'hima', 'free time', 'Noun'),
('v_n5_auto_366', 'N5', '鳴く', 'なく', 'naku', 'animal noise. to chirp, roar or croak etc.', 'Noun'),
('v_n5_auto_367', 'N5', '隣', 'となり', 'tonari', 'next door to', 'Noun'),
('v_n5_auto_368', 'N5', '先生', 'せんせい', 'sensei', 'teacher, doctor', 'Noun'),
('v_n5_auto_369', 'N5', '出口', 'でぐち', 'deguchi', 'exit', 'Noun'),
('v_n5_auto_370', 'N5', '後ろ', 'うしろ', 'ushiro', 'behind', 'Noun'),
('v_n5_auto_371', 'N5', '先月', 'せんげつ', 'sengetsu', 'last month', 'Noun'),
('v_n5_auto_372', 'N5', NULL, 'テープ', 'tēpu', 'tape', 'Noun'),
('v_n5_auto_373', 'N5', 'お姉さん', 'おねえさん', 'oneesan', '(honorable) older sister', 'Noun'),
('v_n5_auto_374', 'N5', NULL, 'じゃ / じゃあ', 'ja / jaa', 'well then…', 'Noun'),
('v_n5_auto_375', 'N5', '本', 'ほん', 'hon', 'book', 'Noun'),
('v_n5_auto_376', 'N5', '泳ぐ', 'およぐ', 'oyogu', 'to swim', 'Noun'),
('v_n5_auto_377', 'N5', '灰皿', 'はいざら', 'haizara', 'ashtray', 'Noun'),
('v_n5_auto_378', 'N5', '門', 'もん', 'mon', 'gate', 'Noun'),
('v_n5_auto_379', 'N5', '荷物', 'にもつ', 'nimotsu', 'luggage', 'Noun'),
('v_n5_auto_380', 'N5', NULL, 'この', 'kono', 'this', 'Noun'),
('v_n5_auto_381', 'N5', '書く', 'かく', 'kaku', 'to write', 'Noun'),
('v_n5_auto_382', 'N5', '毎年', 'まいねん / まいとし', 'mainen / maitoshi', 'every year', 'Noun'),
('v_n5_auto_383', 'N5', '明日', 'あした', 'ashita', 'tomorrow', 'Noun'),
('v_n5_auto_384', 'N5', NULL, 'ホテル', 'hoteru', 'hotel', 'Noun'),
('v_n5_auto_385', 'N5', '降りる', 'おりる', 'oriru', 'to get off, to descend', 'Noun'),
('v_n5_auto_386', 'N5', '重い', 'おもい', 'omoi', 'heavy', 'Noun'),
('v_n5_auto_387', 'N5', '電車', 'でんしゃ', 'densha', 'electric train', 'Noun'),
('v_n5_auto_388', 'N5', '痛い', 'いたい', 'itai', 'painful', 'Noun'),
('v_n5_auto_389', 'N5', '話す', 'はなす', 'hanasu', 'to speak', 'Noun'),
('v_n5_auto_390', 'N5', NULL, 'りっぱ', 'rippa', 'splendid', 'Noun'),
('v_n5_auto_391', 'N5', NULL, 'つまらない', 'tsumaranai', 'boring', 'Noun'),
('v_n5_auto_392', 'N5', NULL, 'よく', 'yoku', 'often, well', 'Noun'),
('v_n5_auto_393', 'N5', '嫌', 'いや', 'iya', 'unpleasant', 'Noun'),
('v_n5_auto_394', 'N5', '宿題', 'しゅくだい', 'shukudai', 'homework', 'Noun'),
('v_n5_auto_395', 'N5', '死ぬ', 'しぬ', 'shinu', 'to die', 'Noun'),
('v_n5_auto_396', 'N5', NULL, 'みんな', 'minna', 'everyone', 'Noun'),
('v_n5_auto_397', 'N5', '万', 'まん', 'man', 'ten thousand', 'Noun'),
('v_n5_auto_398', 'N5', '映画', 'えいが', 'eiga', 'movie', 'Noun'),
('v_n5_auto_399', 'N5', '遅���', 'おそい', 'osoi', 'late, slow', 'Noun'),
('v_n5_auto_400', 'N5', '耳', 'みみ', 'mimi', 'ear', 'Noun');

INSERT INTO public.vocabularies (id, level, kanji, kana, romaji, meaning, type) VALUES
('v_n5_auto_401', 'N5', NULL, 'かかる', 'kakaru', 'to take time or money', 'Noun'),
('v_n5_auto_402', 'N5', NULL, 'でも', 'demo', 'but', 'Noun'),
('v_n5_auto_403', 'N5', '四つ', 'よっつ', 'yottsu', 'four', 'Noun'),
('v_n5_auto_404', 'N5', '机', 'つくえ', 'tsukue', 'desk', 'Noun'),
('v_n5_auto_405', 'N5', NULL, 'あっち', 'atchi', 'over there', 'Noun'),
('v_n5_auto_406', 'N5', '買う', 'かう', 'kau', 'to buy', 'Noun'),
('v_n5_auto_407', 'N5', '開く', 'あく', 'aku', 'to open, to become open', 'Noun'),
('v_n5_auto_408', 'N5', '教室', 'きょうしつ', 'kyōshitsu', 'classroom', 'Noun'),
('v_n5_auto_409', 'N5', NULL, 'かばん', 'kaban', 'bag, basket', 'Noun'),
('v_n5_auto_410', 'N5', NULL, 'マッチ', 'matchi', 'match', 'Noun'),
('v_n5_auto_411', 'N5', '短い', 'みじかい', 'mijikai', 'short', 'Noun'),
('v_n5_auto_412', 'N5', '姉', 'あね', 'ane', '(humble) older sister', 'Noun'),
('v_n5_auto_413', 'N5', '大勢', 'おおぜい', 'ōzei', 'great number of people', 'Noun'),
('v_n5_auto_414', 'N5', '開ける', 'あける', 'akeru', 'to open', 'Noun'),
('v_n5_auto_415', 'N5', '忙しい', 'いそがしい', 'isogashii', 'busy, irritated', 'Noun'),
('v_n5_auto_416', 'N5', NULL, 'おばあさん', 'obaasan', 'grandmother, female senior-citizen', 'Noun'),
('v_n5_auto_417', 'N5', '店', 'みせ', 'mise', 'shop', 'Noun'),
('v_n5_auto_418', 'N5', NULL, 'ワイシャツ', 'waishatsu', 'business shirt', 'Noun'),
('v_n5_auto_419', 'N5', '北', 'きた', 'kita', 'north', 'Noun'),
('v_n5_auto_420', 'N5', NULL, 'ラジオ', 'rajio', 'radio', 'Noun'),
('v_n5_auto_421', 'N5', NULL, 'すぐに', 'suguni', 'instantly', 'Noun'),
('v_n5_auto_422', 'N5', NULL, 'ハンカチ', 'hankachi', 'handkerchief', 'Noun'),
('v_n5_auto_423', 'N5', NULL, 'いつ', 'itsu', 'when', 'Noun'),
('v_n5_auto_424', 'N5', '全部', 'ぜんぶ', 'zenbu', 'all', 'Noun'),
('v_n5_auto_425', 'N5', '橋', 'はし', 'hashi', 'bridge', 'Noun'),
('v_n5_auto_426', 'N5', '川 / 河', 'かわ', 'kawa', 'river', 'Noun'),
('v_n5_auto_427', 'N5', NULL, 'バター', 'batā', 'butter', 'Noun'),
('v_n5_auto_428', 'N5', NULL, 'もっと', 'motto', 'more', 'Noun'),
('v_n5_auto_429', 'N5', '入口', 'いりぐち', 'iriguchi', 'entrance', 'Noun'),
('v_n5_auto_430', 'N5', NULL, 'など', 'nado', 'et cetera', 'Noun'),
('v_n5_auto_431', 'N5', '太い', 'ふとい', 'futoi', 'fat', 'Noun'),
('v_n5_auto_432', 'N5', NULL, 'やる', 'yaru', 'to do', 'Noun'),
('v_n5_auto_433', 'N5', '自動車', 'じどうしゃ', 'jidōsha', 'automobile', 'Noun'),
('v_n5_auto_434', 'N5', '昼', 'ひる', 'hiru', 'noon, daytime', 'Noun'),
('v_n5_auto_435', 'N5', '色', 'いろ', 'iro', 'colour', 'Noun'),
('v_n5_auto_436', 'N5', '黄色', 'きいろ', 'kiiro', 'yellow', 'Noun'),
('v_n5_auto_437', 'N5', '左', 'ひだり', 'hidari', 'left hand side', 'Noun'),
('v_n5_auto_438', 'N5', '野菜', 'やさい', 'yasai', 'vegetable', 'Noun'),
('v_n5_auto_439', 'N5', NULL, 'シャワー', 'shawā', 'shower', 'Noun'),
('v_n5_auto_440', 'N5', '散歩', 'さんぽする', 'sanposuru', 'to stroll', 'Noun'),
('v_n5_auto_441', 'N5', '三', 'さん', 'san', 'three', 'Noun'),
('v_n5_auto_442', 'N5', '消える', 'きえる', 'kieru', 'to disappear', 'Noun'),
('v_n5_auto_443', 'N5', '映画館', 'えいがかん', 'eigakan', 'cinema', 'Noun'),
('v_n5_auto_444', 'N5', NULL, 'いす', 'isu', 'chair', 'Noun'),
('v_n5_auto_445', 'N5', '誕生日', 'たんじょうび', 'tanjōbi', 'birthday', 'Noun'),
('v_n5_auto_446', 'N5', '切る', 'きる', 'kiru', 'to cut', 'Noun'),
('v_n5_auto_447', 'N5', '七日', 'なのか', 'nanoka', 'seven days, the seventh day', 'Noun'),
('v_n5_auto_448', 'N5', '洗う', 'あらう', 'arau', 'to wash', 'Noun'),
('v_n5_auto_449', 'N5', NULL, 'あれ', 'are', 'that', 'Noun'),
('v_n5_auto_450', 'N5', NULL, 'グラム', 'guramu', 'gram', 'Noun'),
('v_n5_auto_451', 'N5', '習う', 'ならう', 'narau', 'to learn', 'Noun'),
('v_n5_auto_452', 'N5', '後', 'あと', 'ato', 'afterwards', 'Noun'),
('v_n5_auto_453', 'N5', '猫', 'ねこ', 'neko', 'cat', 'Noun'),
('v_n5_auto_454', 'N5', '図書館', 'としょかん', 'toshokan', 'library', 'Noun'),
('v_n5_auto_455', 'N5', '並べる', 'ならべる', 'naraberu', 'to line up, to set up', 'Noun'),
('v_n5_auto_456', 'N5', NULL, 'しかし', 'shikashi', 'however', 'Noun'),
('v_n5_auto_457', 'N5', '大きい', 'おおきい', 'ōkii', 'big', 'Noun'),
('v_n5_auto_458', 'N5', '八日', 'ようか', 'yōka', 'eight days, eighth day of the month', 'Noun'),
('v_n5_auto_459', 'N5', '歩く', 'あるく', 'aruku', 'to walk', 'Noun'),
('v_n5_auto_460', 'N5', NULL, 'ズボン', 'zubon', 'trousers', 'Noun'),
('v_n5_auto_461', 'N5', '九日', 'ここのか', 'kokonoka', 'nine days, ninth day', 'Noun'),
('v_n5_auto_462', 'N5', NULL, 'そっち', 'sotchi', 'over there', 'Noun'),
('v_n5_auto_463', 'N5', NULL, 'たて', 'tate', 'length, height', 'Noun'),
('v_n5_auto_464', 'N5', NULL, 'カップ', 'kappu', 'cup', 'Noun'),
('v_n5_auto_465', 'N5', NULL, 'あの', 'ano', 'that over there', 'Noun'),
('v_n5_auto_466', 'N5', '頼む', 'たのむ', 'tanomu', 'to ask', 'Noun'),
('v_n5_auto_467', 'N5', 'お兄さん', 'おにいさん', 'oniisan', '(honorable) older brother', 'Noun'),
('v_n5_auto_468', 'N5', '手', 'て', 'te', 'hand', 'Noun'),
('v_n5_auto_469', 'N5', NULL, 'ええ', 'ee', 'yes', 'Noun'),
('v_n5_auto_470', 'N5', '毎日', 'まいにち', 'mainichi', 'every day', 'Noun'),
('v_n5_auto_471', 'N5', '花', 'はな', 'hana', 'flower', 'Noun'),
('v_n5_auto_472', 'N5', '一', 'いち', 'ichi', 'one', 'Noun'),
('v_n5_auto_473', 'N5', '居る', 'いる', 'iru', 'to be, to have (used for people and animals)', 'Noun'),
('v_n5_auto_474', 'N5', '砂糖', 'さとう', 'satō', 'sugar', 'Noun'),
('v_n5_auto_475', 'N5', NULL, 'カレンダー', 'karendā', 'calendar', 'Noun'),
('v_n5_auto_476', 'N5', '今', 'いま', 'ima', 'now', 'Noun'),
('v_n5_auto_477', 'N5', '旅行', 'りょこう', 'ryokō', 'travel', 'Noun'),
('v_n5_auto_478', 'N5', NULL, 'できる', 'dekiru', 'to be able to', 'Noun'),
('v_n5_auto_479', 'N5', '春', 'はる', 'haru', 'spring', 'Noun'),
('v_n5_auto_480', 'N5', NULL, 'する', 'suru', 'to do', 'Noun'),
('v_n5_auto_481', 'N5', '八つ', 'やっつ', 'yattsu', 'eight', 'Noun'),
('v_n5_auto_482', 'N5', '町', 'まち', 'machi', 'town, city', 'Noun'),
('v_n5_auto_483', 'N5', '渡す', 'わたす', 'watasu', 'to hand over', 'Noun'),
('v_n5_auto_484', 'N5', '青', 'あお', 'ao', 'blue', 'Noun'),
('v_n5_auto_485', 'N5', '白', 'しろ', 'shiro', 'white', 'Noun'),
('v_n5_auto_486', 'N5', NULL, 'ある', 'aru', 'to be, to have (used for inanimate objects)', 'Noun'),
('v_n5_auto_487', 'N5', NULL, 'ベッド', 'beddo', 'bed', 'Noun'),
('v_n5_auto_488', 'N5', '水', 'みず', 'mizu', 'water', 'Noun'),
('v_n5_auto_489', 'N5', NULL, 'いくつ', 'ikutsu', 'how many?, how old?', 'Noun'),
('v_n5_auto_490', 'N5', '楽しい', 'たのしい', 'tanoshii', 'enjoyable', 'Noun'),
('v_n5_auto_491', 'N5', '御飯', 'ごはん', 'gohan', 'cooked rice, meal', 'Noun'),
('v_n5_auto_492', 'N5', '皆さん', 'みなさん', 'minasan', 'everyone', 'Noun'),
('v_n5_auto_493', 'N5', NULL, 'おいしい', 'oishii', 'delicious', 'Noun'),
('v_n5_auto_494', 'N5', NULL, 'ペット', 'petto', 'pet', 'Noun'),
('v_n5_auto_495', 'N5', '外', 'そと', 'soto', 'outside', 'Noun'),
('v_n5_auto_496', 'N5', '前', 'まえ', 'mae', 'before', 'Noun'),
('v_n5_auto_497', 'N5', '来る', 'くる', 'kuru', 'to come', 'Noun'),
('v_n5_auto_498', 'N5', NULL, 'おもしろい', 'omoshiroi', 'interesting', 'Noun'),
('v_n5_auto_499', 'N5', '貸す', 'かす', 'kasu', 'to lend', 'Noun'),
('v_n5_auto_500', 'N5', '早い', 'はやい', 'hayai', 'early', 'Noun'),
('v_n5_auto_501', 'N5', '弱い', 'よわい', 'yowai', 'weak', 'Noun'),
('v_n5_auto_502', 'N5', '洗濯', 'せんたく', 'sentaku', 'washing', 'Noun'),
('v_n5_auto_503', 'N5', '九つ', 'ここのつ', 'kokonotsu', 'nine', 'Noun'),
('v_n5_auto_504', 'N5', '来年', 'らいねん', 'rainen', 'next year', 'Noun'),
('v_n5_auto_505', 'N5', '眼鏡', 'めがね', 'megane', 'glasses', 'Noun'),
('v_n5_auto_506', 'N5', '背', 'せ', 'se', 'height, stature', 'Noun'),
('v_n5_auto_507', 'N5', '水曜日', 'すいようび', 'suiyōbi', 'Wednesday', 'Noun'),
('v_n5_auto_508', 'N5', 'お金', 'おかね', 'okane', 'money', 'Noun'),
('v_n5_auto_509', 'N5', '同じ', 'おなじ', 'onaji', 'same', 'Noun'),
('v_n5_auto_510', 'N5', '弾く', 'ひく', 'hiku', 'to play an instrument with strings, including piano', 'Noun'),
('v_n5_auto_511', 'N5', '土曜日', 'どようび', 'doyōbi', 'Saturday', 'Noun'),
('v_n5_auto_512', 'N5', '階段', 'かいだん', 'kaidan', 'stairs', 'Noun'),
('v_n5_auto_513', 'N5', '煩い', 'うるさい', 'urusai', 'noisy, annoying', 'Noun'),
('v_n5_auto_514', 'N5', '半分', 'はんぶん', 'hanbun', 'half minute', 'Noun'),
('v_n5_auto_515', 'N5', '背広', 'せびろ', 'sebiro', 'business suit', 'Noun'),
('v_n5_auto_516', 'N5', '晴れ', 'はれ', 'hare', 'clear weather', 'Noun'),
('v_n5_auto_517', 'N5', '見せる', 'みせる', 'miseru', 'to show', 'Noun'),
('v_n5_auto_518', 'N5', '飲み物', 'のみもの', 'nomimono', 'a drink', 'Noun'),
('v_n5_auto_519', 'N5', '雪', 'ゆき', 'yuki', 'snow', 'Noun'),
('v_n5_auto_520', 'N5', '買い物', 'かいもの', 'kaimono', 'shopping', 'Noun'),
('v_n5_auto_521', 'N5', '交差点', 'こうさてん', 'kōsaten', 'intersection', 'Noun'),
('v_n5_auto_522', 'N5', '駅', 'えき', 'eki', 'station', 'Noun'),
('v_n5_auto_523', 'N5', '大丈夫', 'だいじょうぶ', 'daijōbu', 'all right', 'Noun'),
('v_n5_auto_524', 'N5', NULL, 'ボールペン', 'bōrupen', 'ball-point pen', 'Noun'),
('v_n5_auto_525', 'N5', '勉強', 'べんきょうする', 'benkyōsuru', 'to study', 'Noun'),
('v_n5_auto_526', 'N5', '兄弟', 'きょうだい', 'kyōdai', '(humble) siblings', 'Noun'),
('v_n5_auto_527', 'N5', '封筒', 'ふうとう', 'fūtō', 'envelope', 'Noun'),
('v_n5_auto_528', 'N5', NULL, 'レコード', 'rekōdo', 'record', 'Noun'),
('v_n5_auto_529', 'N5', NULL, 'コーヒー', 'kōhī', 'coffee', 'Noun'),
('v_n5_auto_530', 'N5', '漢字', 'かんじ', 'kanji', 'Chinese character', 'Noun'),
('v_n5_auto_531', 'N5', '喫茶店', 'きっさてん', 'kissaten', 'coffee lounge', 'Noun'),
('v_n5_auto_532', 'N5', NULL, 'その', 'sono', 'that', 'Noun'),
('v_n5_auto_533', 'N5', '子供', 'こども', 'kodomo', 'child', 'Noun'),
('v_n5_auto_534', 'N5', NULL, 'ちょっと', 'chotto', 'somewhat', 'Noun'),
('v_n5_auto_535', 'N5', '女の子', 'おんなのこ', 'onnanoko', 'girl', 'Noun'),
('v_n5_auto_536', 'N5', '紙', 'かみ', 'kami', 'paper', 'Noun'),
('v_n5_auto_537', 'N5', '字引', 'じびき', 'jibiki', 'dictionary', 'Noun'),
('v_n5_auto_538', 'N5', NULL, 'あさって', 'asatte', 'day after tomorrow', 'Noun'),
('v_n5_auto_539', 'N5', '嫌い', 'きらい', 'kirai', 'hate', 'Noun'),
('v_n5_auto_540', 'N5', '先', 'さき', 'saki', 'the future, previous', 'Noun'),
('v_n5_auto_541', 'N5', '答える', 'こたえる', 'kotaeru', 'to answer', 'Noun'),
('v_n5_auto_542', 'N5', '食堂', 'しょくどう', 'shokudō', 'dining hall', 'Noun'),
('v_n5_auto_543', 'N5', NULL, 'テーブル', 'tēburu', 'table', 'Noun'),
('v_n5_auto_544', 'N5', NULL, 'コピーする', 'kopīsuru', 'to copy', 'Noun'),
('v_n5_auto_545', 'N5', '働く', 'はたらく', 'hataraku', 'to work', 'Noun'),
('v_n5_auto_546', 'N5', NULL, 'こんな', 'konna', 'such', 'Noun'),
('v_n5_auto_547', 'N5', NULL, 'たくさん', 'takusan', 'many', 'Noun'),
('v_n5_auto_548', 'N5', NULL, 'ドア', 'doa', 'Western style door', 'Noun'),
('v_n5_auto_549', 'N5', '見る  観る', 'みる', 'miru', 'to see, to watch', 'Noun'),
('v_n5_auto_550', 'N5', '交番', 'こうばん', 'kōban', 'police box', 'Noun'),
('v_n5_auto_551', 'N5', NULL, 'ナイフ', 'naifu', 'knife', 'Noun'),
('v_n5_auto_552', 'N5', '辛い', 'からい', 'karai', 'spicy', 'Noun'),
('v_n5_auto_553', 'N5', '洋服', 'ようふく', 'yōfuku', 'western-style clothes', 'Noun'),
('v_n5_auto_554', 'N5', '晩御飯', 'ばんごはん', 'bangohan', 'evening meal', 'Noun'),
('v_n5_auto_555', 'N5', '車', 'くるま', 'kuruma', 'car, vehicle', 'Noun'),
('v_n5_auto_556', 'N5', NULL, 'ちょうど', 'chōdo', 'exactly', 'Noun'),
('v_n5_auto_557', 'N5', 'もう一度', 'もういちど', 'mōichido', 'again', 'Noun'),
('v_n5_auto_558', 'N5', NULL, 'ポスト', 'posuto', 'post', 'Noun'),
('v_n5_auto_559', 'N5', '服', 'ふく', 'fuku', 'clothes', 'Noun'),
('v_n5_auto_560', 'N5', NULL, 'メートル', 'mētoru', 'metre', 'Noun'),
('v_n5_auto_561', 'N5', NULL, 'パン', 'pan', 'bread', 'Noun'),
('v_n5_auto_562', 'N5', '半', 'はん', 'han', 'half', 'Noun'),
('v_n5_auto_563', 'N5', '若い', 'わかい', 'wakai', 'young', 'Noun'),
('v_n5_auto_564', 'N5', '食べる', 'たべる', 'taberu', 'to eat', 'Noun'),
('v_n5_auto_565', 'N5', '四日', 'よっか', 'yokka', 'four days, fouth day of the month', 'Noun'),
('v_n5_auto_566', 'N5', '警官', 'けいかん', 'keikan', 'policeman', 'Noun'),
('v_n5_auto_567', 'N5', '伯父 / 叔父', 'おじさん', 'ojisan', 'uncle, middle-aged man', 'Noun'),
('v_n5_auto_568', 'N5', NULL, 'これ', 'kore', 'this', 'Noun'),
('v_n5_auto_569', 'N5', NULL, 'アパート', 'apāto', 'apartment', 'Noun'),
('v_n5_auto_570', 'N5', '鳥', 'とり', 'tori', 'bird', 'Noun'),
('v_n5_auto_571', 'N5', NULL, 'ここ', 'koko', 'here', 'Noun'),
('v_n5_auto_572', 'N5', '方', 'かた', 'kata', 'person, way of doing', 'Noun'),
('v_n5_auto_573', 'N5', NULL, 'タクシー', 'takushī', 'taxi', 'Noun'),
('v_n5_auto_574', 'N5', NULL, 'では', 'deha', 'with that...', 'Noun'),
('v_n5_auto_575', 'N5', NULL, 'しょうゆ', 'shōyu', 'soy sauce', 'Noun'),
('v_n5_auto_576', 'N5', '少ない', 'すくない', 'sukunai', 'a few', 'Noun'),
('v_n5_auto_577', 'N5', '白い', 'しろい', 'shiroi', 'white', 'Noun'),
('v_n5_auto_578', 'N5', '待つ', 'まつ', 'matsu', 'to wait', 'Noun'),
('v_n5_auto_579', 'N5', '次', 'つぎ', 'tsugi', 'next', 'Noun'),
('v_n5_auto_580', 'N5', '行く', 'いく', 'iku', 'to go', 'Noun'),
('v_n5_auto_581', 'N5', '角', 'かど', 'kado', 'a corner', 'Noun'),
('v_n5_auto_582', 'N5', '男', 'おとこ', 'otoko', 'man', 'Noun'),
('v_n5_auto_583', 'N5', NULL, 'ギター', 'gitā', 'guitar', 'Noun'),
('v_n5_auto_584', 'N5', '聞く', 'きく', 'kiku', 'to hear, to listen to, to ask', 'Noun'),
('v_n5_auto_585', 'N5', '走る', 'はしる', 'hashiru', 'to run', 'Noun'),
('v_n5_auto_586', 'N5', 'お母さん', 'おかあさん', 'okaasan', '(honorable) mother', 'Noun'),
('v_n5_auto_587', 'N5', '意味', 'いみ', 'imi', 'meaning', 'Noun'),
('v_n5_auto_588', 'N5', '物', 'もの', 'mono', 'thing', 'Noun'),
('v_n5_auto_589', 'N5', '強い', 'つよい', 'tsuyoi', 'powerful', 'Noun'),
('v_n5_auto_590', 'N5', '魚', 'さかな', 'sakana', 'fish', 'Noun'),
('v_n5_auto_591', 'N5', '切手', 'きって', 'kitte', 'postage stamp', 'Noun'),
('v_n5_auto_592', 'N5', '暗い', 'くらい', 'kurai', 'gloomy', 'Noun'),
('v_n5_auto_593', 'N5', '出る', 'でる', 'deru', 'to appear, to leave', 'Noun'),
('v_n5_auto_594', 'N5', '犬', 'いぬ', 'inu', 'dog', 'Noun'),
('v_n5_auto_595', 'N5', '女', 'おんな', 'onna', 'woman', 'Noun'),
('v_n5_auto_596', 'N5', '飛行機', 'ひこうき', 'hikōki', 'aeroplane', 'Noun'),
('v_n5_auto_597', 'N5', '日曜日', 'にちようび', 'nichiyōbi', 'Sunday', 'Noun'),
('v_n5_auto_598', 'N5', NULL, 'より、ほう', 'yori,hō', 'Used for comparison.', 'Noun'),
('v_n5_auto_599', 'N5', '午前', 'ごぜん', 'gozen', 'morning', 'Noun'),
('v_n5_auto_600', 'N5', '名前', 'なまえ', 'namae', 'name', 'Noun');

INSERT INTO public.vocabularies (id, level, kanji, kana, romaji, meaning, type) VALUES
('v_n5_auto_601', 'N5', '丸い / 円い', 'まるい', 'marui', 'round, circular', 'Noun'),
('v_n5_auto_602', 'N5', '曲る', 'まがる', 'magaru', 'to turn, to bend', 'Noun'),
('v_n5_auto_603', 'N5', '鼻', 'はな', 'hana', 'nose', 'Noun'),
('v_n5_auto_604', 'N5', 'お弁当', 'おべんとう', 'obentō', 'boxed lunch', 'Noun'),
('v_n5_auto_605', 'N5', NULL, 'コップ', 'koppu', 'a glass', 'Noun'),
('v_n5_auto_606', 'N5', '結婚', 'けっこん', 'kekkon', 'marriage', 'Noun'),
('v_n5_auto_607', 'N5', '置く', 'おく', 'oku', 'to put', 'Noun'),
('v_n5_auto_608', 'N5', '渡る', 'わたる', 'wataru', 'to go across', 'Noun'),
('v_n5_auto_609', 'N5', '伯母さん / 叔母さん', 'おばさん', 'obasan', 'aunt', 'Noun'),
('v_n5_auto_610', 'N5', NULL, 'それから', 'sorekara', 'after that', 'Noun'),
('v_n5_auto_611', 'N5', '明い', 'あかるい', 'akarui', 'bright', 'Noun'),
('v_n5_auto_612', 'N5', '家庭', 'かてい', 'katei', 'household', 'Noun'),
('v_n5_auto_613', 'N5', NULL, 'パーティー', 'pātī', 'party', 'Noun'),
('v_n5_auto_614', 'N5', NULL, 'あちら', 'achira', 'there', 'Noun'),
('v_n5_auto_615', 'N5', NULL, 'スカート', 'sukāto', 'skirt', 'Noun'),
('v_n5_auto_616', 'N5', '靴', 'くつ', 'kutsu', 'shoes', 'Noun'),
('v_n5_auto_617', 'N5', NULL, 'ボタン', 'botan', 'button', 'Noun'),
('v_n5_auto_618', 'N5', '今月', 'こんげつ', 'kongetsu', 'this month', 'Noun'),
('v_n5_auto_619', 'N5', '返す', 'かえす', 'kaesu', 'to return something', 'Noun'),
('v_n5_auto_620', 'N5', NULL, 'いかが', 'ikaga', 'how', 'Noun'),
('v_n5_auto_621', 'N5', NULL, 'ストーブ', 'sutōbu', 'heater', 'Noun'),
('v_n5_auto_622', 'N5', '二人', 'ふたり', 'futari', 'two people', 'Noun'),
('v_n5_auto_623', 'N5', '起きる', 'おきる', 'okiru', 'to get up', 'Noun'),
('v_n5_auto_624', 'N5', NULL, 'さあ', 'saa', 'well…', 'Noun'),
('v_n5_auto_625', 'N5', NULL, 'あそこ', 'asoko', 'over there', 'Noun'),
('v_n5_auto_626', 'N5', '古い', 'ふるい', 'furui', 'old (not used for people)', 'Noun'),
('v_n5_auto_627', 'N5', '黄色い', 'きいろい', 'kiiroi', 'yellow', 'Noun'),
('v_n5_auto_628', 'N5', NULL, 'まだ', 'mada', 'yet, still', 'Noun'),
('v_n5_auto_629', 'N5', '歌う', 'うたう', 'utau', 'to sing', 'Noun'),
('v_n5_auto_630', 'N5', '飴', 'あめ', 'ame', 'candy', 'Noun'),
('v_n5_auto_631', 'N5', '寝る', 'ねる', 'neru', 'to go to bed, to sleep', 'Noun'),
('v_n5_auto_632', 'N5', NULL, 'それ', 'sore', 'that', 'Noun'),
('v_n5_auto_633', 'N5', '質問', 'しつもん', 'shitsumon', 'question', 'Noun'),
('v_n5_auto_634', 'N5', NULL, 'どなた', 'donata', 'who', 'Noun'),
('v_n5_auto_635', 'N5', '牛乳', 'ぎゅうにゅう', 'gyūnyū', 'milk', 'Noun'),
('v_n5_auto_636', 'N5', '二', 'に', 'ni', 'two', 'Noun'),
('v_n5_auto_637', 'N5', '紅茶', 'こうちゃ', 'kōcha', 'black tea', 'Noun'),
('v_n5_auto_638', 'N5', NULL, 'そちら', 'sochira', 'over there', 'Noun'),
('v_n5_auto_639', 'N5', '出かける', 'でかける', 'dekakeru', 'to go out', 'Noun'),
('v_n5_auto_640', 'N5', '兄', 'あに', 'ani', '(humble) older brother', 'Noun'),
('v_n5_auto_641', 'N5', '留学生', 'りゅうがくせい', 'ryūgakusei', 'overseas student', 'Noun'),
('v_n5_auto_642', 'N5', '月曜日', 'げつようび', 'getsuyōbi', 'Monday', 'Noun'),
('v_n5_auto_643', 'N5', '締める', 'しめる', 'shimeru', 'to tie', 'Noun'),
('v_n5_auto_644', 'N5', '熱い', 'あつい', 'atsui', 'hot to the touch', 'Noun'),
('v_n5_auto_645', 'N5', '郵便局', 'ゆうびんきょく', 'yūbinkyoku', 'post office', 'Noun'),
('v_n5_auto_646', 'N5', '細い', 'ほそい', 'hosoi', 'thin', 'Noun'),
('v_n5_auto_647', 'N5', '六つ', 'むっつ', 'muttsu', 'six', 'Noun'),
('v_n5_auto_648', 'N5', '本棚', 'ほんだな', 'hondana', 'bookshelves', 'Noun'),
('v_n5_auto_649', 'N5', '結構', 'けっこう', 'kekkō', 'splendid, enough', 'Noun'),
('v_n5_auto_650', 'N5', NULL, 'こちら', 'kochira', 'this person or way', 'Noun'),
('v_n5_auto_651', 'N5', '昨夜', 'ゆうべ', 'yūbe', 'last night', 'Noun'),
('v_n5_auto_652', 'N5', '外国人', 'がいこくじん', 'gaikokujin', 'foreigner', 'Noun'),
('v_n5_auto_653', 'N5', '絵', 'え', 'e', 'picture', 'Noun'),
('v_n5_auto_654', 'N5', '使う', 'つかう', 'tsukau', 'to use', 'Noun'),
('v_n5_auto_655', 'N5', '休む', 'やすむ', 'yasumu', 'to rest', 'Noun'),
('v_n5_auto_656', 'N5', NULL, 'テスト', 'tesuto', 'test', 'Noun'),
('v_n5_auto_657', 'N5', '貼る', 'はる', 'haru', 'to stick', 'Noun'),
('v_n5_auto_658', 'N5', NULL, 'たばこ', 'tabako', 'tobacco, cigarettes', 'Noun'),
('v_n5_auto_659', 'N5', '涼しい', 'すずしい', 'suzushii', 'refreshing', 'Noun'),
('v_n5_auto_660', 'N5', '昨日', 'きのう', 'kinō', 'yesterday', 'Noun'),
('v_n5_auto_661', 'N5', NULL, 'せっけん', 'sekken', 'soap', 'Noun'),
('v_n5_auto_662', 'N5', '初め / 始め', 'はじめ', 'hajime', 'beginning', 'Noun');

