-- Seed data tambahan untuk menggenapkan N5 Vocabularies menjadi 800 (Kosakata 663 - 800)

INSERT INTO public.vocabularies (id, level, kanji, kana, romaji, meaning, type) VALUES
('v_n5_auto_663', 'N5', '天ぷら', 'てんぷら', 'tenpura', 'tempura (deep-fried fish and vegetables)', 'Noun'),
('v_n5_auto_664', 'N5', 'お土産', 'おみやげ', 'omiyage', 'souvenir', 'Noun'),
('v_n5_auto_665', 'N5', 'お祭り', 'おまつり', 'omatsuri', 'festival', 'Noun'),
('v_n5_auto_666', 'N5', '桜', 'さくら', 'sakura', 'cherry blossom', 'Noun'),
('v_n5_auto_667', 'N5', '日本語', 'にほんご', 'nihongo', 'Japanese language', 'Noun'),
('v_n5_auto_668', 'N5', 'ひらがな', 'ひらがな', 'hiragana', 'hiragana (Japanese syllabary)', 'Noun'),
('v_n5_auto_669', 'N5', 'カタカナ', 'カタカナ', 'katakana', 'katakana (Japanese syllabary)', 'Noun'),
('v_n5_auto_670', 'N5', '消しゴム', 'けしごむ', 'keshigomu', 'eraser', 'Noun'),
('v_n5_auto_671', 'N5', '定規', 'じょうぎ', 'jougi', 'ruler', 'Noun'),
('v_n5_auto_672', 'N5', '着物', 'きもの', 'kimono', 'kimono', 'Noun'),
('v_n5_auto_673', 'N5', '定期券', 'ていきけん', 'teikiken', 'commuter pass', 'Noun'),
('v_n5_auto_674', 'N5', 'パスポート', 'パスポート', 'pasupōto', 'passport', 'Noun'),
('v_n5_auto_675', 'N5', 'パソコン', 'パソコン', 'pasokon', 'personal computer', 'Noun'),
('v_n5_auto_676', 'N5', '携帯電話', 'けいたいでんわ', 'keitaidenwa', 'mobile phone', 'Noun'),
('v_n5_auto_677', 'N5', '畳', 'たたみ', 'tatami', 'tatami mat', 'Noun'),
('v_n5_auto_678', 'N5', '布団', 'ふとん', 'futon', 'futon (sleeping mat)', 'Noun'),
('v_n5_auto_679', 'N5', 'エスカレーター', 'エスカレーター', 'esukarētā', 'escalator', 'Noun'),
('v_n5_auto_680', 'N5', '体育館', 'たいいくかん', 'taiikukan', 'gymnasium', 'Noun'),
('v_n5_auto_681', 'N5', '薬局', 'やっきょく', 'yakkyoku', 'pharmacy', 'Noun'),
('v_n5_auto_682', 'N5', '空港', 'くうこう', 'kūkō', 'airport', 'Noun'),
('v_n5_auto_683', 'N5', 'スーパー', 'スーパー', 'sūpā', 'supermarket', 'Noun'),
('v_n5_auto_684', 'N5', 'コンビニ', 'コンビニ', 'konbini', 'convenience store', 'Noun'),
('v_n5_auto_685', 'N5', '美術館', 'びじゅつかん', 'bijutsukan', 'art museum', 'Noun'),
('v_n5_auto_686', 'N5', '動物園', 'どうぶつえん', 'dōbutsuen', 'zoo', 'Noun'),
('v_n5_auto_687', 'N5', '温泉', 'おんせん', 'onsen', 'hot spring', 'Noun'),
('v_n5_auto_688', 'N5', 'お寺', 'おてら', 'otera', 'temple', 'Noun'),
('v_n5_auto_689', 'N5', '神社', 'じんじゃ', 'jinja', 'shrine', 'Noun'),
('v_n5_auto_690', 'N5', '教会', 'きょうかい', 'kyōkai', 'church', 'Noun'),
('v_n5_auto_691', 'N5', '信号', 'しんごう', 'shingō', 'traffic light', 'Noun'),
('v_n5_auto_692', 'N5', '踏切', 'ふみきり', 'fumikiri', 'railway crossing', 'Noun'),
('v_n5_auto_693', 'N5', 'こんにちは', 'こんにちは', 'konnichiwa', 'hello, good afternoon', 'Expression'),
('v_n5_auto_694', 'N5', 'こんばんは', 'こんばんは', 'konbanwa', 'good evening', 'Expression'),
('v_n5_auto_695', 'N5', 'さようなら', 'さようなら', 'sayōnara', 'goodbye', 'Expression'),
('v_n5_auto_696', 'N5', 'ありがとう', 'ありがとう', 'arigatō', 'thank you', 'Expression'),
('v_n5_auto_697', 'N5', 'すみません', 'すみません', 'sumimasen', 'excuse me, sorry', 'Expression'),
('v_n5_auto_698', 'N5', 'ごめんなさい', 'ごめんなさい', 'gomennasai', 'I''m sorry', 'Expression'),
('v_n5_auto_699', 'N5', 'はじめまして', 'はじめまして', 'hajimemashite', 'nice to meet you', 'Expression'),
('v_n5_auto_700', 'N5', 'よろしく', 'よろしく', 'yoroshiku', 'please treat me well', 'Expression'),
('v_n5_auto_701', 'N5', 'もしもし', 'もしもし', 'moshimoshi', 'hello (on the phone)', 'Expression'),
('v_n5_auto_702', 'N5', 'ただいま', 'ただいま', 'tadaima', 'I''m home', 'Expression'),
('v_n5_auto_703', 'N5', 'お帰りなさい', 'おかえりなさい', 'okaerinasai', 'welcome home', 'Expression'),
('v_n5_auto_704', 'N5', '行ってきます', 'いってきます', 'ittekimasu', 'I''m off, see you later', 'Expression'),
('v_n5_auto_705', 'N5', '行ってらっしゃい', 'いってらっしゃい', 'itterasshai', 'have a good day, see you', 'Expression'),
('v_n5_auto_706', 'N5', 'いただきます', 'いただきます', 'itadakimasu', 'thank you for this food (before eating)', 'Expression'),
('v_n5_auto_707', 'N5', 'ごちそうさま', 'ごちそうさま', 'gochisousama', 'thank you for the feast (after eating)', 'Expression'),
('v_n5_auto_708', 'N5', 'おめでとう', 'おめでとう', 'omedetō', 'congratulations', 'Expression'),
('v_n5_auto_709', 'N5', 'お元気ですか', 'おげんきですか', 'ogenkidesuka', 'how are you?', 'Expression'),
('v_n5_auto_710', 'N5', '富士山', 'ふじさん', 'fujisan', 'Mount Fuji', 'Noun'),
('v_n5_auto_711', 'N5', '日本', 'にほん', 'nihon', 'Japan', 'Noun'),
('v_n5_auto_712', 'N5', '東京', 'とうきょう', 'tōkyō', 'Tokyo', 'Noun'),
('v_n5_auto_713', 'N5', 'カレーライス', 'カレーライス', 'karēraisu', 'curry rice', 'Noun'),
('v_n5_auto_714', 'N5', 'ラーメン', 'ラーメン', 'rāmen', 'ramen (Japanese noodle soup)', 'Noun'),
('v_n5_auto_715', 'N5', 'お寿司', 'おすし', 'osushi', 'sushi', 'Noun'),
('v_n5_auto_716', 'N5', '天候', 'てんこう', 'tenkō', 'weather conditions', 'Noun'),
('v_n5_auto_717', 'N5', 'スキー', 'スキー', 'sukī', 'skiing', 'Noun'),
('v_n5_auto_718', 'N5', 'ピアノ', 'ピアノ', 'piano', 'piano', 'Noun'),
('v_n5_auto_719', 'N5', 'ノートパソコン', 'ノートパソコン', 'nōtopasokon', 'laptop', 'Noun'),
('v_n5_auto_720', 'N5', 'メール', 'メール', 'mēru', 'email', 'Noun'),
('v_n5_auto_721', 'N5', 'エアコン', 'エアコン', 'eakon', 'air conditioner', 'Noun'),
('v_n5_auto_722', 'N5', '扇風機', 'せんぷうき', 'senpūki', 'electric fan', 'Noun'),
('v_n5_auto_723', 'N5', '洗濯機', 'せんたくき', 'sentakuki', 'washing machine', 'Noun'),
('v_n5_auto_724', 'N5', '掃除機', 'そうじき', 'sōjiki', 'vacuum cleaner', 'Noun'),
('v_n5_auto_725', 'N5', '電子レンジ', 'でんしレンジ', 'denshirenji', 'microwave', 'Noun'),
('v_n5_auto_726', 'N5', '洋間', 'ようま', 'yōma', 'Western-style room', 'Noun'),
('v_n5_auto_727', 'N5', '和室', 'わしつ', 'washitsu', 'Japanese-style room', 'Noun'),
('v_n5_auto_728', 'N5', 'ベランダ', 'ベランダ', 'beranda', 'veranda, balcony', 'Noun'),
('v_n5_auto_729', 'N5', '駐車場', 'ちゅうしゃじょう', 'chūshajō', 'parking lot', 'Noun'),
('v_n5_auto_730', 'N5', '駐輪場', 'ちゅうりんじょう', 'chūrinjō', 'bicycle parking lot', 'Noun'),
('v_n5_auto_731', 'N5', '運動場', 'うんどうじょう', 'undōjō', 'playground, athletic field', 'Noun'),
('v_n5_auto_732', 'N5', '市役所', 'しやくしょ', 'shiyakusho', 'city hall', 'Noun'),
('v_n5_auto_733', 'N5', '港', 'みなと', 'minato', 'port, harbor', 'Noun'),
('v_n5_auto_734', 'N5', 'パン屋', 'パンや', 'panya', 'bakery', 'Noun'),
('v_n5_auto_735', 'N5', '本屋', 'ほんや', 'honya', 'bookstore', 'Noun'),
('v_n5_auto_736', 'N5', '花屋', 'はなや', 'hanaya', 'florist, flower shop', 'Noun'),
('v_n5_auto_737', 'N5', '魚屋', 'さかなや', 'sakanaya', 'fish market', 'Noun'),
('v_n5_auto_738', 'N5', '肉屋', 'にくや', 'nikuya', 'butcher shop', 'Noun'),
('v_n5_auto_739', 'N5', '居酒屋', 'いざかや', 'izakaya', 'Japanese pub', 'Noun'),
('v_n5_auto_740', 'N5', '遊園地', 'ゆうえんち', 'yūenchi', 'amusement park', 'Noun'),
('v_n5_auto_741', 'N5', '海辺', 'うみべ', 'umibe', 'seaside, beach', 'Noun'),
('v_n5_auto_742', 'N5', '山登り', 'やまのぼり', 'yamanobori', 'mountain climbing', 'Noun'),
('v_n5_auto_743', 'N5', '神社', 'じんじゃ', 'jinja', 'shrine (Shinto)', 'Noun'),
('v_n5_auto_744', 'N5', '神様', 'かみさま', 'kamisama', 'God', 'Noun'),
('v_n5_auto_745', 'N5', '歩道', 'ほどう', 'hodō', 'sidewalk', 'Noun'),
('v_n5_auto_746', 'N5', '車道', 'しゃどう', 'shadō', 'roadway, street', 'Noun'),
('v_n5_auto_747', 'N5', '横断歩道', 'おうだんほどう', 'ōdanhodō', 'pedestrian crossing', 'Noun'),
('v_n5_auto_748', 'N5', '地下道', 'ちかどう', 'chikadō', 'underground passage', 'Noun'),
('v_n5_auto_749', 'N5', '急行', 'きゅうこう', 'kyūkō', 'express train', 'Noun'),
('v_n5_auto_750', 'N5', '普通電車', 'ふつうでんしゃ', 'futsūdensha', 'local train', 'Noun'),
('v_n5_auto_751', 'N5', '切符売り場', 'きっぷうりば', 'kippuuriba', 'ticket office', 'Noun'),
('v_n5_auto_752', 'N5', '改札口', 'かいさつぐち', 'kaisatsuguchi', 'ticket gate', 'Noun'),
('v_n5_auto_753', 'N5', 'ホーム', 'ほーむ', 'hōmu', 'station platform', 'Noun'),
('v_n5_auto_754', 'N5', '売店', 'ばいてん', 'baiten', 'kiosk, shop booth', 'Noun'),
('v_n5_auto_755', 'N5', '忘れ物', 'わすれもの', 'wasuremono', 'lost property, forgotten item', 'Noun'),
('v_n5_auto_756', 'N5', '落とし物', 'おとしもの', 'otoshimono', 'lost item', 'Noun'),
('v_n5_auto_757', 'N5', '拾い物', 'ひろいもの', 'hiroimono', 'found item', 'Noun'),
('v_n5_auto_758', 'N5', '宅配便', 'たくはいびん', 'takuhaibin', 'courier, home delivery service', 'Noun'),
('v_n5_auto_759', 'N5', 'お土産屋', 'おみやげや', 'omiyageya', 'souvenir shop', 'Noun'),
('v_n5_auto_760', 'N5', 'おもちゃ屋', 'おもちゃや', 'omochaya', 'toy store', 'Noun'),
('v_n5_auto_761', 'N5', '文房具屋', 'ぶんぼうぐや', 'bunbōguya', 'stationery store', 'Noun'),
('v_n5_auto_762', 'N5', '洋服屋', 'ようふくや', 'yōfukuya', 'clothing store', 'Noun'),
('v_n5_auto_763', 'N5', '靴屋', 'くつや', 'kutsuya', 'shoe store', 'Noun'),
('v_n5_auto_764', 'N5', '薬屋', 'くすりや', 'kusuriya', 'drugstore', 'Noun'),
('v_n5_auto_765', 'N5', '時計屋', 'とけいや', 'tokeiya', 'watchmaker''s shop', 'Noun'),
('v_n5_auto_766', 'N5', '眼鏡屋', 'めがねや', 'meganeya', 'optician''s shop', 'Noun'),
('v_n5_auto_767', 'N5', '自転車屋', 'じてんしゃや', 'jitenshaya', 'bicycle shop', 'Noun'),
('v_n5_auto_768', 'N5', '床屋', 'とこや', 'tokoya', 'barbershop', 'Noun'),
('v_n5_auto_769', 'N5', '美容院', 'びよういん', 'biyōin', 'beauty salon', 'Noun'),
('v_n5_auto_770', 'N5', '写真館', 'しゃしんかん', 'shashinkan', 'photo studio', 'Noun'),
('v_n5_auto_771', 'N5', '体育館', 'たいいくかん', 'taiikukan', 'gymnasium, sports hall', 'Noun'),
('v_n5_auto_772', 'N5', '博物館', 'はくぶつかん', 'hakubutsukan', 'museum', 'Noun'),
('v_n5_auto_773', 'N5', '水族館', 'すいぞくかん', 'suizokukan', 'aquarium', 'Noun'),
('v_n5_auto_774', 'N5', '美術館', 'びじゅつかん', 'bijutsukan', 'art museum', 'Noun'),
('v_n5_auto_775', 'N5', '旅館', 'りょかん', 'ryokan', 'Japanese-style inn', 'Noun'),
('v_n5_auto_776', 'N5', '料理屋', 'りょうりや', 'ryōriya', 'restaurant', 'Noun'),
('v_n5_auto_777', 'N5', '弁当屋', 'べんとうや', 'bentōya', 'bento shop', 'Noun'),
('v_n5_auto_778', 'N5', '居酒屋', 'いざかや', 'izakaya', 'Japanese pub', 'Noun'),
('v_n5_auto_779', 'N5', 'ラーメン屋', 'ラーメンや', 'rāmenya', 'ramen shop', 'Noun'),
('v_n5_auto_780', 'N5', '寿司屋', 'すしや', 'sushiya', 'sushi restaurant', 'Noun'),
('v_n5_auto_781', 'N5', '焼き肉屋', 'やきにくや', 'yakinikuya', 'yakiniku (Korean BBQ) restaurant', 'Noun'),
('v_n5_auto_782', 'N5', 'カフェ', 'カフェ', 'kafe', 'cafe', 'Noun'),
('v_n5_auto_783', 'N5', 'バー', 'バー', 'bā', 'bar', 'Noun'),
('v_n5_auto_784', 'N5', 'お年玉', 'おとしだま', 'otoshidama', 'New Year''s monetary gift', 'Noun'),
('v_n5_auto_785', 'N5', 'お正月', 'おしょうがつ', 'oshōgatsu', 'New Year', 'Noun'),
('v_n5_auto_786', 'N5', 'アニメ', 'アニメ', 'anime', 'anime (Japanese animation)', 'Noun'),
('v_n5_auto_787', 'N5', 'カラオケ', 'カラオケ', 'karaoke', 'karaoke', 'Noun'),
('v_n5_auto_788', 'N5', '新幹線', 'しんかんせん', 'shinkansen', 'bullet train', 'Noun'),
('v_n5_auto_789', 'N5', '地震', 'じしん', 'jishin', 'earthquake', 'Noun'),
('v_n5_auto_790', 'N5', '台風', 'たいふう', 'taifū', 'typhoon', 'Noun'),
('v_n5_auto_791', 'N5', '花火', '花火', 'hanabi', 'fireworks', 'Noun'),
('v_n5_auto_792', 'N5', '緑茶', 'りょくちゃ', 'ryokucha', 'green tea', 'Noun'),
('v_n5_auto_793', 'N5', '温泉街', 'おんせんがい', 'onsengai', 'hot spring town', 'Noun'),
('v_n5_auto_794', 'N5', '浴衣', 'ゆかた', 'yukata', 'yukata (casual summer kimono)', 'Noun'),
('v_n5_auto_795', 'N5', '歴史', 'れきし', 'rekishi', 'history', 'Noun'),
('v_n5_auto_796', 'N5', '自然', 'しぜん', 'shizen', 'nature', 'Noun'),
('v_n5_auto_797', 'N5', '平和', 'へいわ', 'heiwa', 'peace', 'Noun'),
('v_n5_auto_798', 'N5', '安全', 'あんぜん', 'anzen', 'safety', 'Noun'),
('v_n5_auto_799', 'N5', '夢', 'ゆめ', 'yume', 'dream', 'Noun'),
('v_n5_auto_800', 'N5', '心', 'こころ', 'kokoro', 'heart, mind', 'Noun');

INSERT INTO public.vocabulary_examples (id, vocab_id, japanese, reading, translation) VALUES
('ex_n5_auto_663', 'v_n5_auto_663', '天ぷらを食べます。', 'てんぷら', 'Saya makan tempura.'),
('ex_n5_auto_664', 'v_n5_auto_664', '日本のお土産を買いました。', 'おみやげ', 'Saya membeli oleh-oleh khas Jepang.'),
('ex_n5_auto_665', 'v_n5_auto_665', '夏祭りに行きました。', 'おまつり', 'Saya pergi ke festival musim panas.'),
('ex_n5_auto_666', 'v_n5_auto_666', '桜が綺麗に咲いています。', 'さくら', 'Bunga sakura mekar dengan indah.'),
('ex_n5_auto_667', 'v_n5_auto_667', '日本語を勉強しています。', 'にほんご', 'Saya sedang belajar bahasa Jepang.'),
('ex_n5_auto_668', 'v_n5_auto_668', 'ひらがなを書くことができます。', 'ひらがな', 'Saya bisa menulis hiragana.'),
('ex_n5_auto_669', 'v_n5_auto_669', 'カタカナは難しいですね。', 'カタカナ', 'Katakana sulit ya.'),
('ex_n5_auto_670', 'v_n5_auto_670', '消しゴムを貸してください。', 'けしごむ', 'Tolong pinjamkan penghapus.'),
('ex_n5_auto_671', 'v_n5_auto_671', '定規で線を引きます。', 'じょうぎ', 'Saya menggambar garis dengan penggaris.'),
('ex_n5_auto_672', 'v_n5_auto_672', '着物を着てみたいです。', 'きもの', 'Saya ingin mencoba mengenakan kimono.'),
('ex_n5_auto_673', 'v_n5_auto_673', '定期券を失くしました。', 'ていきけん', 'Saya kehilangan kartu pas komuter.'),
('ex_n5_auto_674', 'v_n5_auto_674', 'パスポートを見せてください。', 'パスポート', 'Tolong tunjukkan paspor Anda.'),
('ex_n5_auto_675', 'v_n5_auto_675', '新しいパソコンが欲しいです。', 'パソコン', 'Saya ingin komputer pribadi baru.'),
('ex_n5_auto_676', 'v_n5_auto_676', '携帯電話を忘れました。', 'けいたいでんわ', 'Saya lupa membawa ponsel.'),
('ex_n5_auto_677', 'v_n5_auto_677', '私の部屋は畳があります。', 'たたみ', 'Kamar saya memiliki tikar tatami.'),
('ex_n5_auto_678', 'v_n5_auto_678', '布団で寝ます。', 'ふとん', 'Saya tidur di atas futon.'),
('ex_n5_auto_679', 'v_n5_auto_679', 'エスカレーターに乗りましょう。', 'エスカレーター', 'Mari naik eskalator.'),
('ex_n5_auto_680', 'v_n5_auto_680', '体育館でバスケをします。', 'たいいくかん', 'Bermain basket di gedung olahraga.'),
('ex_n5_auto_681', 'v_n5_auto_681', '薬局で薬を買います。', 'やっきょく', 'Membeli obat di apotek.'),
('ex_n5_auto_682', 'v_n5_auto_682', '空港へ友達を迎えに行きます。', 'くうこう', 'Pergi ke bandara untuk menjemput teman.'),
('ex_n5_auto_683', 'v_n5_auto_683', 'スーパーで買い物をします。', 'スーパー', 'Berbelanja di supermarket.'),
('ex_n5_auto_684', 'v_n5_auto_684', 'コンビニで水を買いました。', 'コンビニ', 'Saya membeli air di toko kelontong.'),
('ex_n5_auto_685', 'v_n5_auto_685', '美術館で絵を見ます。', 'びじゅつかん', 'Melihat lukisan di museum seni.'),
('ex_n5_auto_686', 'v_n5_auto_686', '動物園にはパンダがいます。', 'どうぶつえん', 'Ada panda di kebun binatang.'),
('ex_n5_auto_687', 'v_n5_auto_687', '温泉に入って休みたい。', 'おんせん', 'Saya ingin mandi di pemandian air panas dan beristirahat.'),
('ex_n5_auto_688', 'v_n5_auto_688', '古いお寺を訪ねました。', 'おてら', 'Saya mengunjungi kuil kuno.'),
('ex_n5_auto_689', 'v_n5_auto_689', '神社でお祈りをします。', 'じんじゃ', 'Berdoa di kuil Shinto.'),
('ex_n5_auto_690', 'v_n5_auto_690', '日曜日に教会へ行きます。', 'きょうかい', 'Pergi ke gereja pada hari Minggu.'),
('ex_n5_auto_691', 'v_n5_auto_691', '信号が赤に変わりました。', 'しんごう', 'Lampu lalu lintas berubah menjadi merah.'),
('ex_n5_auto_692', 'v_n5_auto_692', '踏切が閉まっています。', 'ふみきり', 'Pintu perlintasan kereta api sedang tertutup.'),
('ex_n5_auto_693', 'v_n5_auto_693', '皆さん、こんにちは。', 'こんにちは', 'Halo semuanya.'),
('ex_n5_auto_694', 'v_n5_auto_694', 'こんばんは、お元気ですか。', 'こんばんは', 'Selamat malam, apa kabar?'),
('ex_n5_auto_695', 'v_n5_auto_695', '先生、さようなら。', 'さようなら', 'Selamat tinggal, Guru.'),
('ex_n5_auto_696', 'v_n5_auto_696', '手伝ってくれてありがとう。', 'ありがとう', 'Terima kasih telah membantu saya.'),
('ex_n5_auto_697', 'v_n5_auto_697', 'すみません、道を教えてください。', 'すみません', 'Permisi, tolong beri tahu saya jalannya.'),
('ex_n5_auto_698', 'v_n5_auto_698', '遅れてごめんなさい。', 'ごめんなさい', 'Maaf karena terlambat.'),
('ex_n5_auto_699', 'v_n5_auto_699', 'はじめまして、アグスです。', 'はじめまして', 'Perkenalkan, saya Agus.'),
('ex_n5_auto_700', 'v_n5_auto_700', 'どうぞよろしくお願いします。', 'よろしく', 'Mohon bantuannya ya.'),
('ex_n5_auto_701', 'v_n5_auto_701', 'もしもし、お母さんですか。', 'もしもし', 'Halo, apakah ini Ibu?'),
('ex_n5_auto_702', 'v_n5_auto_702', 'ただいま、帰りました。', 'ただいま', 'Saya pulang!'),
('ex_n5_auto_703', 'v_n5_auto_703', 'お帰りなさい、お疲れ様です。', 'おかえりなさい', 'Selamat datang kembali, terima kasih atas kerja kerasnya.'),
('ex_n5_auto_704', 'v_n5_auto_704', '学校に行ってきます。', 'いってきます', 'Saya pergi ke sekolah dulu ya.'),
('ex_n5_auto_705', 'v_n5_auto_705', '気をつけて行ってらっしゃい。', 'いってらっしゃい', 'Hati-hati di jalan ya.'),
('ex_n5_auto_706', 'v_n5_auto_706', 'ご飯をいただきます。', 'いただきます', 'Selamat makan.'),
('ex_n5_auto_707', 'v_n5_auto_707', 'ごちそうさまでした、美味しかったです。', 'ごちそうさま', 'Terima kasih atas hidangannya, sangat enak.'),
('ex_n5_auto_708', 'v_n5_auto_708', 'お誕生日おめでとう！', 'おめでとう', 'Selamat ulang tahun!'),
('ex_n5_auto_709', 'v_n5_auto_709', 'お久しぶりです、お元気ですか。', 'おげんきですか', 'Lama tidak bertemu, apa kabar?'),
('ex_n5_auto_710', 'v_n5_auto_710', '富士山に登ってみたいです。', 'ふじさん', 'Saya ingin mencoba mendaki Gunung Fuji.'),
('ex_n5_auto_711', 'v_n5_auto_711', '日本はとても美しい国です。', 'にほん', 'Jepang adalah negara yang sangat indah.'),
('ex_n5_auto_712', 'v_n5_auto_712', '東京は日本の首都です。', 'とうきょう', 'Tokyo adalah ibu kota Jepang.'),
('ex_n5_auto_713', 'v_n5_auto_713', '今日の晩御飯 is カレーライスです。', 'カレーライス', 'Makan malam hari ini adalah nasi kari.'),
('ex_n5_auto_714', 'v_n5_auto_714', '日本のラーメンは最高です。', 'ラーメン', 'Ramen Jepang adalah yang terbaik.'),
('ex_n5_auto_715', 'v_n5_auto_715', '週末にお寿司を食べに行きます。', 'おすし', 'Saya akan pergi makan sushi di akhir pekan.'),
('ex_n5_auto_716', 'v_n5_auto_716', '明日の天候はどうですか。', 'てんこう', 'Bagaimana kondisi cuaca besok?'),
('ex_n5_auto_717', 'v_n5_auto_717', '北海道でスキーをします。', 'スキー', 'Bermain ski di Hokkaido.'),
('ex_n5_auto_718', 'v_n5_auto_718', '毎日ピアノを練習します。', 'ピアノ', 'Saya berlatih piano setiap hari.'),
('ex_n5_auto_719', 'v_n5_auto_719', 'ノートパソコンを持ち歩きます。', 'ノートパソコン', 'Saya membawa laptop bepergian.'),
('ex_n5_auto_720', 'v_n5_auto_720', '先生にメールを送りました。', 'メール', 'Saya telah mengirim email kepada Guru.'),
('ex_n5_auto_721', 'v_n5_auto_721', 'エアコンをつけてください。', 'エアコン', 'Tolong nyalakan pendingin ruangan.'),
('ex_n5_auto_722', 'v_n5_auto_722', '扇風機が回っています。', 'せんぷうき', 'Kipas angin sedang berputar.'),
('ex_n5_auto_723', 'v_n5_auto_723', '洗濯機で服を洗います。', 'せんたくき', 'Mencuci pakaian dengan mesin cuci.'),
('ex_n5_auto_724', 'v_n5_auto_724', '掃除機で部屋をきれいにします。', 'そうじき', 'Membersihkan kamar dengan penyedot debu.'),
('ex_n5_auto_725', 'v_n5_auto_725', '電子レンジで温めます。', 'でんしレンジ', 'Menghangatkannya di microwave.'),
('ex_n5_auto_726', 'v_n5_auto_726', 'この家には洋間が多いです。', 'ようま', 'Rumah ini memiliki banyak kamar gaya Barat.'),
('ex_n5_auto_727', 'v_n5_auto_727', '和室で畳の香りを楽しみます。', 'わしつ', 'Meniki aroma tatami di kamar bergaya Jepang.'),
('ex_n5_auto_728', 'v_n5_auto_728', 'ベランダで洗濯物を干します。', 'ベランダ', 'Menjemur cucian di balkon.'),
('ex_n5_auto_729', 'v_n5_auto_729', '駐車場はどこですか。', 'ちゅうしゃじょう', 'Di mana area parkir?'),
('ex_n5_auto_730', 'v_n5_auto_730', 'ここに自転車を止めます。', 'ちゅうりんじょう', 'Memarkir sepeda di sini.'),
('ex_n5_auto_731', 'v_n5_auto_731', '子供たちが運動場で走っています。', 'うんどうじょう', 'Anak-anak sedang berlari di lapangan olahraga.'),
('ex_n5_auto_732', 'v_n5_auto_732', '市役所に書類を出します。', 'しやくしょ', 'Menyerahkan dokumen ke balai kota.'),
('ex_n5_auto_733', 'v_n5_auto_733', '港に船がたくさんあります。', 'みなと', 'Ada banyak kapal di pelabuhan.'),
('ex_n5_auto_734', 'v_n5_auto_734', '毎朝パン屋で買います。', 'パンや', 'Setiap pagi saya membeli di toko roti.'),
('ex_n5_auto_735', 'v_n5_auto_735', '本屋で新しい本を探します。', 'ほんや', 'Mencari buku baru di toko buku.'),
('ex_n5_auto_736', 'v_n5_auto_736', '花屋で母の日のプレゼントを買う。', 'はなや', 'Membeli kado hari ibu di toko bunga.'),
('ex_n5_auto_737', 'v_n5_auto_737', '魚屋で新鮮な魚を買いましょう。', 'さかなや', 'Mari membeli ikan segar di pasar ikan.'),
('ex_n5_auto_738', 'v_n5_auto_738', '肉屋でコロッケを買いました。', 'にくや', 'Saya membeli kroket di toko daging.'),
('ex_n5_auto_739', 'v_n5_auto_739', '居酒屋でビールを飲みました。', 'いざかや', 'Minum bir di kedai minum Jepang.'),
('ex_n5_auto_740', 'v_n5_auto_740', '子供と遊園地に行きました。', 'ゆうえんち', 'Pergi ke taman hiburan bersama anak.'),
('ex_n5_auto_741', 'v_n5_auto_741', '海辺を散歩するのが好きです。', 'うみべ', 'Saya suka berjalan-jalan di tepi pantai.'),
('ex_n5_auto_742', 'v_n5_auto_742', '週末は山登りをします。', 'やまのぼり', 'Saya mendaki gunung di akhir pekan.'),
('ex_n5_auto_743', 'v_n5_auto_743', '神社でお参りをします。', 'じんじゃ', 'Berdoa di kuil Shinto.'),
('ex_n5_auto_744', 'v_n5_auto_744', '神様に感謝します。', 'かみさま', 'Saya bersyukur kepada Tuhan.'),
('ex_n5_auto_745', 'v_n5_auto_745', '歩道を安全に歩きます。', 'ほどう', 'Berjalan dengan aman di trotoar.'),
('ex_n5_auto_746', 'v_n5_auto_746', '車道に飛び出してはいけません。', 'しゃどう', 'Tidak boleh melompat ke jalan raya.'),
('ex_n5_auto_747', 'v_n5_auto_747', '横断歩道を渡ります。', 'おうだんほどう', 'Menyeberang di zebra cross.'),
('ex_n5_auto_748', 'v_n5_auto_748', '地下道を通って駅に行きます。', 'ちかどう', 'Pergi ke stasiun melewati jalan bawah tanah.'),
('ex_n5_auto_749', 'v_n5_auto_749', '急行電車に乗りました。', 'きゅうこう', 'Saya naik kereta ekspres.'),
('ex_n5_auto_750', 'v_n5_auto_750', '普通電車は各駅に止まります。', 'ふつうでんしゃ', 'Kereta lokal berhenti di setiap stasiun.'),
('ex_n5_auto_751', 'v_n5_auto_751', '切符売り場はあそこです。', 'きっぷうりば', 'Loket penjualan tiket di sebelah sana.'),
('ex_n5_auto_752', 'v_n5_auto_752', '改札口を通ってください。', 'かいさつぐち', 'Tolong lewati gerbang tiket.'),
('ex_n5_auto_753', 'v_n5_auto_753', '３番線ホームで待ちます。', 'ほーむ', 'Menunggu di peron jalur 3.'),
('ex_n5_auto_754', 'v_n5_auto_754', '売店で新聞を買います。', 'ばいてん', 'Membeli koran di kios.'),
('ex_n5_auto_755', 'v_n5_auto_755', '車内に忘れ物をしました。', 'わすれもの', 'Saya meninggalkan barang di dalam gerbong.'),
('ex_n5_auto_756', 'v_n5_auto_756', '落とし物を警察に届けました。', 'おとしもの', 'Saya melaporkan barang hilang ke polisi.'),
('ex_n5_auto_757', 'v_n5_auto_757', '道路で拾い物をしました。', 'ひろいもの', 'Saya menemukan barang di jalan.'),
('ex_n5_auto_758', 'v_n5_auto_758', '宅配便で荷物を送ります。', 'たくはいびん', 'Mengirim paket menggunakan jasa kurir.'),
('ex_n5_auto_759', 'v_n5_auto_759', 'お土産屋でキーホルダーを買う。', 'おみやげや', 'Membeli gantungan kunci di toko oleh-oleh.'),
('ex_n5_auto_760', 'v_n5_auto_760', 'おもちゃ屋は子供でいっぱいです。', 'おもちゃや', 'Toko mainan dipenuhi oleh anak-anak.'),
('ex_n5_auto_761', 'v_n5_auto_761', '文房具屋でノートを買いました。', 'ぶんぼうぐや', 'Saya membeli buku catatan di toko alat tulis.'),
('ex_n5_auto_762', 'v_n5_auto_762', '洋服屋で新しいジーンズを買う。', 'ようふくや', 'Membeli celana jins baru di toko pakaian.'),
('ex_n5_auto_763', 'v_n5_auto_763', '靴屋でスニーカーを選びます。', 'くつや', 'Memilih sepatu kets di toko sepatu.'),
('ex_n5_auto_764', 'v_n5_auto_764', '薬屋でマスクを買います。', 'くすりや', 'Membeli masker di apotek.'),
('ex_n5_auto_765', 'v_n5_auto_765', '時計屋で電池を交換します。', 'とけいや', 'Mengganti baterai di toko jam.'),
('ex_n5_auto_766', 'v_n5_auto_766', '眼鏡屋で新しい眼鏡を作ります。', 'めがねや', 'Membuat kacamata baru di toko kacamata.'),
('ex_n5_auto_767', 'v_n5_auto_767', '自転車屋でタイヤを直します。', 'じてんしゃや', 'Memperbaiki ban di bengkel sepeda.'),
('ex_n5_auto_768', 'v_n5_auto_768', '床屋で髪を切ります。', 'とこや', 'Memotong rambut di pangkas rambut.'),
('ex_n5_auto_769', 'v_n5_auto_769', '美容院で髪を染めます。', 'びよういん', 'Mewarnai rambut di salon kecantikan.'),
('ex_n5_auto_770', 'v_n5_auto_770', '写真館で家族写真を撮りました。', 'しゃしんかん', 'Mengambil foto keluarga di studio foto.'),
('ex_n5_auto_771', 'v_n5_auto_771', '体育館でバドミントンをする。', 'たいいくかん', 'Bermain bulu tangkis di gedung olahraga.'),
('ex_n5_auto_772', 'v_n5_auto_772', '博物館で恐竜の骨を見ました。', 'はくぶつかん', 'Melihat tulang dinosaurus di museum.'),
('ex_n5_auto_773', 'v_n5_auto_773', '水族館でイルカのショーを見る。', 'すいぞくかん', 'Menonton pertunjukan lumba-lumba di akuarium.'),
('ex_n5_auto_774', 'v_n5_auto_774', '美術館で静かに鑑賞します。', 'びじゅつかん', 'Menikmatinya dengan tenang di galeri seni.'),
('ex_n5_auto_775', 'v_n5_auto_775', '京都の旅館に泊まりました。', 'りょかん', 'Saya menginap di penginapan bergaya Jepang di Kyoto.'),
('ex_n5_auto_776', 'v_n5_auto_776', '高級な料理屋で食事をする。', 'りょうりや', 'Makan di restoran mewah.'),
('ex_n5_auto_777', 'v_n5_auto_777', '弁当屋で唐揚げ弁当を買いました。', 'べんとうや', 'Saya membeli bento ayam goreng di toko bento.'),
('ex_n5_auto_778', 'v_n5_auto_778', '金曜日の夜は居酒屋に行きます。', 'いざかや', 'Saya pergi ke izakaya pada Jumat malam.'),
('ex_n5_auto_779', 'v_n5_auto_779', '駅前のラーメン屋は人気です。', 'ラーメンや', 'Kedai ramen di depan stasiun sangat populer.'),
('ex_n5_auto_780', 'v_n5_auto_780', '回転寿司屋でお腹いっぱい食べる。', 'すしや', 'Makan sepuasnya di restoran sushi putar.'),
('ex_n5_auto_781', 'v_n5_auto_781', '誕生日のお祝いに焼き肉屋へ行く。', 'やきにくや', 'Pergi ke restoran yakiniku untuk merayakan ulang tahun.'),
('ex_n5_auto_782', 'v_n5_auto_782', '静かなカフェで勉強します。', 'カフェ', 'Belajar di kafe yang tenang.'),
('ex_n5_auto_783', 'v_n5_auto_783', '大人向けのバーでお酒を飲む。', 'バー', 'Minum alkohol di bar untuk dewasa.'),
('ex_n5_auto_784', 'v_n5_auto_784', 'お年玉をたくさんもらいました。', 'おとしだま', 'Saya mendapat banyak hadiah uang Tahun Baru.'),
('ex_n5_auto_785', 'v_n5_auto_785', 'お正月は家族と過ごします。', 'おしょうがつ', 'Saya menghabiskan liburan Tahun Baru bersama keluarga.'),
('ex_n5_auto_786', 'v_n5_auto_786', '日本のアニメがとても人気です。', 'アニメ', 'Anime Jepang sangatlah populer.'),
('ex_n5_auto_787', 'v_n5_auto_787', '週末に友達とカラオケに行きます。', 'カラオケ', 'Pergi karaoke bersama teman di akhir pekan.'),
('ex_n5_auto_788', 'v_n5_auto_788', '新幹線で京都に行きました。', 'しんかんせん', 'Saya pergi ke Kyoto dengan kereta peluru Shinkansen.'),
('ex_n5_auto_789', 'v_n5_auto_789', '日本は地震が多い国です。', 'じしん', 'Jepang adalah negara yang sering mengalami gempa bumi.'),
('ex_n5_auto_790', 'v_n5_auto_790', '台風で電車が止まりました。', 'たいふう', 'Kereta api berhenti karena angin topan.'),
('ex_n5_auto_791', 'v_n5_auto_791', '夜空に綺麗な花火が上がりました。', '花火', 'Kembang api yang indah meluncur di langit malam.'),
('ex_n5_auto_792', 'v_n5_auto_792', '温かい緑茶が大好きです。', 'りょくちゃ', 'Saya sangat suka teh hijau hangat.'),
('ex_n5_auto_793', 'v_n5_auto_793', '温泉街を浴衣で散歩します。', 'おんせんがい', 'Jalan-jalan di kota pemandian air panas dengan yukata.'),
('ex_n5_auto_794', 'v_n5_auto_794', 'お祭りで浴衣を着ました。', 'ゆかた', 'Saya mengenakan yukata di festival.'),
('ex_n5_auto_795', 'v_n5_auto_795', '日本の歴史を勉強しています。', 'れきし', 'Saya sedang belajar sejarah Jepang.'),
('ex_n5_auto_796', 'v_n5_auto_796', '自然豊かな場所が好きです。', 'しぜん', 'Saya suka tempat yang kaya akan alam.'),
('ex_n5_auto_797', 'v_n5_auto_797', '世界の平和を願っています。', 'へいわ', 'Saya mengharapkan perdamaian dunia.'),
('ex_n5_auto_798', 'v_n5_auto_798', 'ここは安全な場所です。', 'あんぜん', 'Di sini adalah tempat yang aman.'),
('ex_n5_auto_799', 'v_n5_auto_799', '私の夢は日本に行くことです。', 'ゆめ', 'Mimpi saya adalah pergi ke Jepang.'),
('ex_n5_auto_800', 'v_n5_auto_800', '心が温かくなりました。', 'こころ', 'Hati saya menjadi hangat.');
