-- Seed data for N5 Vocabularies
INSERT INTO public.vocabularies (id, level, kanji, kana, romaji, meaning, type) VALUES
('v_n5_1', 'N5', '私', 'わたし', 'watashi', 'Saya', 'Noun'),
('v_n5_2', 'N5', '食べる', 'たべる', 'taberu', 'Makan', 'Verb (Ichidan)'),
('v_n5_3', 'N5', '飲む', 'のむ', 'nomu', 'Minum', 'Verb (Godan)'),
('v_n5_4', 'N5', '大きい', 'おおきい', 'ookii', 'Besar', 'Adjective (I)'),
('v_n5_5', 'N5', '行く', 'いく', 'iku', 'Pergi', 'Verb (Godan)'),
('v_n5_6', 'N5', '見る', 'みる', 'miru', 'Melihat, Menonton', 'Verb (Ichidan)'),
('v_n5_7', 'N5', '新しい', 'あたらしい', 'atarashii', 'Baru', 'Adjective (I)'),
('v_n5_8', 'N5', '先生', 'せんせい', 'sensei', 'Guru', 'Noun'),
('v_n5_9', 'N5', '今日', 'きょう', 'kyou', 'Hari ini', 'Noun (Temporal)'),
('v_n5_10', 'N5', '水', 'みず', 'mizu', 'Air', 'Noun'),
('v_n5_11', 'N5', '車', 'くるま', 'kuruma', 'Mobil', 'Noun'),
('v_n5_12', 'N5', '学生', 'がくせい', 'gakusei', 'Murid / Siswa', 'Noun'),
('v_n5_13', 'N5', '本', 'ほん', 'hon', 'Buku', 'Noun'),
('v_n5_14', 'N5', '高い', 'たかい', 'takai', 'Tinggi / Mahal', 'Adjective (I)'),
('v_n5_15', 'N5', '安い', 'やすい', 'yasui', 'Murah', 'Adjective (I)'),
('v_n5_16', 'N5', '学校', 'がっこう', 'gakkou', 'Sekolah', 'Noun'),
('v_n5_17', 'N5', '来る', 'くる', 'kuru', 'Datang', 'Verb (Irregular)'),
('v_n5_18', 'N5', 'する', 'する', 'suru', 'Melakukan', 'Verb (Irregular)'),
('v_n5_19', 'N5', '友達', 'ともだち', 'tomodachi', 'Teman', 'Noun'),
('v_n5_20', 'N5', '美味しい', 'おいしい', 'oishii', 'Enak', 'Adjective (I)'),
('v_n5_21', 'N5', '犬', 'いぬ', 'inu', 'Anjing', 'Noun'),
('v_n5_22', 'N5', '猫', 'ねこ', 'neko', 'Kucing', 'Noun'),
('v_n5_23', 'N5', '明日', 'あした', 'ashita', 'Besok', 'Noun (Temporal)'),
('v_n5_24', 'N5', '昨日', 'きのう', 'kinou', 'Kemarin', 'Noun (Temporal)'),
('v_n5_25', 'N5', '今', 'いま', 'ima', 'Sekarang', 'Noun (Temporal)'),
('v_n5_26', 'N5', '読む', 'よむ', 'yomu', 'Membaca', 'Verb (Godan)'),
('v_n5_27', 'N5', '書く', 'かく', 'kaku', 'Menulis', 'Verb (Godan)'),
('v_n5_28', 'N5', '聞く', 'きく', 'kiku', 'Mendengar / Bertanya', 'Verb (Godan)'),
('v_n5_29', 'N5', '話す', 'はなす', 'hanasu', 'Berbicara', 'Verb (Godan)'),
('v_n5_30', 'N5', '小さい', 'ちいさい', 'chiisai', 'Kecil', 'Adjective (I)');

-- Seed data for N5 Vocabulary Examples
INSERT INTO public.vocabulary_examples (id, vocab_id, japanese, reading, translation) VALUES
('ex_1_1', 'v_n5_1', '私は学生です。', 'わたし は がくせい です。', 'Saya adalah seorang siswa.'),
('ex_2_1', 'v_n5_2', '朝ご飯を食べる。', 'あさごはん を たべる。', 'Makan sarapan pagi.'),
('ex_3_1', 'v_n5_3', '水を飲みます。', 'みず を のみます。', 'Saya minum air.'),
('ex_4_1', 'v_n5_4', '大きい家ですね。', 'おおきい いえ です ね。', 'Rumah yang besar ya.'),
('ex_5_1', 'v_n5_5', '学校へ行く。', 'がっこう へ いく。', 'Pergi ke sekolah.'),
('ex_6_1', 'v_n5_6', 'テレビを見る。', 'テレビ を みる。', 'Menonton TV.'),
('ex_7_1', 'v_n5_7', '新しい車を買いました。', 'あたらしい くるま を かいました。', 'Saya membeli mobil baru.'),
('ex_8_1', 'v_n5_8', 'あの人は先生です。', 'あの ひと は せんせい です。', 'Orang itu adalah guru.'),
('ex_9_1', 'v_n5_9', '今日は暑いですね。', 'きょう は あつい です ね。', 'Hari ini panas ya.'),
('ex_10_1', 'v_n5_10', '水をください。', 'みず を ください。', 'Tolong airnya.'),
('ex_11_1', 'v_n5_11', '車で来ました。', 'くるま で きました。', 'Saya datang dengan mobil.'),
('ex_12_1', 'v_n5_12', '彼は学生です。', 'かれ は がくせい です。', 'Dia adalah murid.'),
('ex_13_1', 'v_n5_13', '本を読みます。', 'ほん を よみます。', 'Membaca buku.'),
('ex_14_1', 'v_n5_14', 'この本は高いです。', 'この ほん は たかい です。', 'Buku ini mahal.'),
('ex_15_1', 'v_n5_15', '安いですね。', 'やすい です ね。', 'Murah ya.'),
('ex_16_1', 'v_n5_16', '学校はどこですか。', 'がっこう は どこ です か。', 'Sekolah di mana?'),
('ex_17_1', 'v_n5_17', '明日来ますか。', 'あした きます か。', 'Apakah besok datang?'),
('ex_18_1', 'v_n5_18', '勉強をします。', 'べんきょう を します。', 'Saya belajar (melakukan pembelajaran).'),
('ex_19_1', 'v_n5_19', '友達と遊びます。', 'ともだち と あそびます。', 'Bermain bersama teman.'),
('ex_20_1', 'v_n5_20', '美味しいケーキです。', 'おいしい ケーキ です。', 'Kue yang enak.');
