-- ============================================================
-- Extra N3 seed data (IDs >= 1726)
-- Total: 580 entries
-- ============================================================

INSERT INTO public.vocabularies (id, level, kanji, kana, romaji, meaning, type) VALUES
('v_n3_auto_1726', 'N3', NULL, 'しきりに', 'shikirini', 'sering kali / terus-menerus', 'Adverb'),
('v_n3_auto_1727', 'N3', NULL, 'じっと', 'jitto', 'diam / menatap lekat-lekat / dengan tenang', 'Adverb'),
('v_n3_auto_1728', 'N3', NULL, 'しばしば', 'shibashiba', 'sering / berkali-kali', 'Adverb'),
('v_n3_auto_1729', 'N3', NULL, 'しゃべる', 'shaberu', 'berbicara / mengobrol', 'Verb (Godan)'),
('v_n3_auto_1730', 'N3', NULL, 'すっぱい', 'suppai', 'asam', 'Adjective (i)'),
('v_n3_auto_1731', 'N3', NULL, 'すてき', 'suteki', 'bagus / indah / menakjubkan', 'Adjective (na)'),
('v_n3_auto_1732', 'N3', NULL, 'ずれる', 'zureru', 'bergeser / meleset', 'Verb (Ichidan)'),
('v_n3_auto_1733', 'N3', NULL, 'あちこち', 'achikochi', 'sana-sini / di berbagai tempat', 'Noun / Adverb'),
('v_n3_auto_1734', 'N3', NULL, 'あらゆる', 'arayuru', 'segala / semua', 'Pre-noun adjective'),
('v_n3_auto_1735', 'N3', NULL, 'ありがとう', 'arigatou', 'terima kasih', 'Expression'),
('v_n3_auto_1736', 'N3', NULL, 'あんなに', 'annani', 'sejauh itu / begitu', 'Adverb'),
('v_n3_auto_1737', 'N3', NULL, 'あんまり', 'anmari', 'tidak begitu / tidak terlalu', 'Adverb'),
('v_n3_auto_1738', 'N3', NULL, 'いけない', 'ikenai', 'tidak boleh / buruk / salah', 'Adjective (i) / Expression'),
('v_n3_auto_1739', 'N3', NULL, 'いたずら', 'itazura', 'nakal / usil / keisengan', 'Noun / Adjective (na)'),
('v_n3_auto_1740', 'N3', NULL, 'いただきます', 'itadakimasu', 'selamat makan / ungkapan terima kasih sebelum makan', 'Expression'),
('v_n3_auto_1741', 'N3', NULL, 'いつか', 'itsuka', 'suatu saat / kapan-kapan / kelak', 'Adverb'),
('v_n3_auto_1742', 'N3', NULL, 'いつのまにか', 'itsunomanika', 'tanpa disadari', 'Adverb'),
('v_n3_auto_1743', 'N3', NULL, 'いつまでも', 'itsumademo', 'selamanya / sampai kapan pun', 'Adverb'),
('v_n3_auto_1744', 'N3', NULL, 'いらいら', 'iraira', 'jengkel / kesal / tidak sabar', 'Adverb / Noun with suru'),
('v_n3_auto_1745', 'N3', NULL, 'いらっしゃい', 'irasshai', 'selamat datang', 'Expression'),
('v_n3_auto_1746', 'N3', NULL, 'いわゆる', 'iwayuru', 'yang biasa disebut / yang dinamakan', 'Pre-noun adjective'),
('v_n3_auto_1747', 'N3', NULL, 'うがい', 'ugai', 'berkumur', 'Noun / Verb (Irregular)'),
('v_n3_auto_1748', 'N3', NULL, 'うなる', 'unaru', 'mengerang / menderu / meraung', 'Verb (Godan)'),
('v_n3_auto_1749', 'N3', NULL, 'おめでとう', 'omedetou', 'selamat', 'Expression'),
('v_n3_auto_1750', 'N3', NULL, 'がっかり', 'gakkari', 'kecewa / patah semangat', 'Adverb / Noun with suru'),
('v_n3_auto_1751', 'N3', NULL, 'かもしれない', 'kamoshirenai', 'mungkin / barangkali', 'Expression'),
('v_n3_auto_1752', 'N3', NULL, 'かゆい', 'kayui', 'gatal', 'Adjective (i)'),
('v_n3_auto_1753', 'N3', NULL, 'きつい', 'kitsui', 'ketat / keras / berat', 'Adjective (i)'),
('v_n3_auto_1754', 'N3', NULL, 'ぐっすり', 'gussuri', 'nyenyak', 'Adverb'),
('v_n3_auto_1755', 'N3', NULL, 'けち', 'kechi', 'pelit / kikir', 'Noun / Adjective (na)'),
('v_n3_auto_1756', 'N3', NULL, 'こぼす', 'kobosu', 'menumpahkan', 'Verb (Godan)'),
('v_n3_auto_1757', 'N3', NULL, 'こぼれる', 'koboreru', 'tumpah / meluap', 'Verb (Ichidan)'),
('v_n3_auto_1758', 'N3', NULL, 'ごめんなさい', 'gomennasai', 'maaf', 'Expression'),
('v_n3_auto_1759', 'N3', NULL, 'これら', 'korera', 'ini semua / hal-hal ini', 'Pronoun'),
('v_n3_auto_1760', 'N3', NULL, 'こんなに', 'konnani', 'seperti ini / begini', 'Adverb'),
('v_n3_auto_1761', 'N3', NULL, 'こんにちは', 'konnichiha', 'halo / selamat siang', 'Expression'),
('v_n3_auto_1762', 'N3', NULL, 'ざっと', 'zatto', 'secara ringkas / sekilas', 'Adverb'),
('v_n3_auto_1763', 'N3', NULL, 'さっぱり', 'sappari', 'segar / sama sekali tidak (dengan negatif)', 'Adverb / Noun with suru'),
('v_n3_auto_1764', 'N3', NULL, 'もしかすると', 'moshikasuruto', 'barangkali / mungkin saja', 'Adverb'),
('v_n3_auto_1765', 'N3', NULL, 'もったいない', 'mottainai', 'mubazir / sayang sekali / sia-sia', 'Adjective (i)'),
('v_n3_auto_1766', 'N3', NULL, 'やや', 'yaya', 'agak / sedikit', 'Adverb'),
('v_n3_auto_1767', 'N3', NULL, 'より', 'yori', 'lebih / daripada', 'Adverb / Noun'),
('v_n3_auto_1768', 'N3', NULL, 'わがまま', 'wagamama', 'egois / manja', 'Noun / Adjective (na)'),
('v_n3_auto_1769', 'N3', NULL, 'ことによると', 'kotonyoruto', 'mungkin saja / tergantung situasi', 'Adverb'),
('v_n3_auto_1770', 'N3', NULL, 'そこで', 'sokode', 'oleh karena itu / maka / di situ', 'Conjunction'),
('v_n3_auto_1771', 'N3', NULL, 'そっくり', 'sokkuri', 'mirip sekali / persis', 'Adjective (na) / Adverb'),
('v_n3_auto_1772', 'N3', NULL, 'そのまま', 'sonomama', 'biarkan begitu saja / apa adanya', 'Adverb / Noun'),
('v_n3_auto_1773', 'N3', NULL, 'それぞれ', 'sorezore', 'masing-masing', 'Noun / Adverb'),
('v_n3_auto_1774', 'N3', NULL, 'それと', 'soreto', 'dan juga / selain itu', 'Conjunction'),
('v_n3_auto_1775', 'N3', NULL, 'だが', 'daga', 'tetapi / namun', 'Conjunction'),
('v_n3_auto_1776', 'N3', NULL, 'だけど', 'dakedo', 'tetapi / namun', 'Conjunction'),
('v_n3_auto_1777', 'N3', NULL, 'たしか', 'tashika', 'seingat saya / pasti', 'Adverb / Adjective (na)'),
('v_n3_auto_1778', 'N3', NULL, 'だって', 'datte', 'habisnya / karena / tapi', 'Conjunction'),
('v_n3_auto_1779', 'N3', NULL, 'たびたび', 'tabitabi', 'sering kali / berulang kali', 'Adverb'),
('v_n3_auto_1780', 'N3', NULL, 'たまらない', 'tamaranai', 'tidak tertahankan / sangat (tidak tahan)', 'Adjective (i)'),
('v_n3_auto_1781', 'N3', NULL, 'ちょうだい', 'choudai', 'tolong berikan / beri saya', 'Expression'),
('v_n3_auto_1782', 'N3', NULL, 'できれば', 'dekireba', 'kalau bisa / jika memungkinkan', 'Adverb'),
('v_n3_auto_1783', 'N3', NULL, 'ですから', 'desukara', 'oleh karena itu / jadi', 'Conjunction'),
('v_n3_auto_1784', 'N3', NULL, 'どうぞよろしく', 'douzoyoroshiku', 'senang bertemu dengan Anda', 'Expression'),
('v_n3_auto_1785', 'N3', NULL, 'どこか', 'dokoka', 'suatu tempat / entah di mana', 'Adverb / Noun'),
('v_n3_auto_1786', 'N3', NULL, 'とんでもない', 'tondemonai', 'tidak mungkin / sama sekali tidak / keterlaluan', 'Adjective (i)'),
('v_n3_auto_1787', 'N3', NULL, 'どんなに', 'donnani', 'bagaimanapun / seberapa pun', 'Adverb'),
('v_n3_auto_1788', 'N3', NULL, 'なにも', 'nanimo', 'apa pun tidak (dengan kalimat negatif)', 'Adverb'),
('v_n3_auto_1789', 'N3', NULL, 'にっこり', 'nikkori', 'tersenyum ramah / tersenyum lebar', 'Adverb / Onomatopoeia'),
('v_n3_auto_1790', 'N3', NULL, 'のんびり', 'nonbiri', 'santai / rileks', 'Adverb / Noun with suru'),
('v_n3_auto_1791', 'N3', NULL, 'はさみ', 'hasami', 'gunting', 'Noun'),
('v_n3_auto_1792', 'N3', NULL, 'ばったり', 'battari', 'tidak sengaja bertemu / tiba-tiba', 'Adverb / Onomatopoeia'),
('v_n3_auto_1793', 'N3', NULL, 'ぴったり', 'pittari', 'pas / cocok sekali / tepat', 'Adverb / Noun with suru'),
('v_n3_auto_1794', 'N3', NULL, 'ぶつかる', 'butsukaru', 'menabrak / bertabrakan', 'Verb (Godan)'),
('v_n3_auto_1795', 'N3', NULL, 'ぶつける', 'butsakeru', 'menabrakkan / membenturkan', 'Verb (Ichidan)'),
('v_n3_auto_1796', 'N3', NULL, 'まあ', 'maa', 'ya ampun / wah / yah', 'Expression'),
('v_n3_auto_1797', 'N3', NULL, 'まさに', 'masani', 'tepat / benar-benar / pas', 'Adverb'),
('v_n3_auto_1798', 'N3', NULL, 'まぶしい', 'mabushii', 'silau', 'Adjective (i)'),
('v_n3_auto_1799', 'N3', NULL, 'と', 'to', 'dan / dengan', 'Conjunction'),
('v_n3_auto_1800', 'N3', NULL, 'ほっと', 'hotto', 'merasa lega', 'Adverb / Noun with suru'),
('v_n3_auto_1801', 'N3', 'ジーンズ', 'ジーンズ', 'jiinzu', 'celana jin', 'Katakana'),
('v_n3_auto_1802', 'N3', 'スイッチ', 'スイッチ', 'suicchi', 'sakelar', 'Katakana'),
('v_n3_auto_1803', 'N3', 'スープ', 'スープ', 'suupu', 'sup', 'Katakana'),
('v_n3_auto_1804', 'N3', 'スケート', 'スケート', 'sukeeto', 'seluncur es / skate', 'Katakana'),
('v_n3_auto_1805', 'N3', 'スター', 'スター', 'sutaa', 'bintang / selebriti', 'Katakana'),
('v_n3_auto_1806', 'N3', 'スタイル', 'スタイル', 'sutairu', 'gaya / bentuk tubuh', 'Katakana'),
('v_n3_auto_1807', 'N3', 'スタンド', 'スタンド', 'sutando', 'lampu meja / stan', 'Katakana'),
('v_n3_auto_1808', 'N3', 'スピーチ', 'スピーチ', 'supiichi', 'pidato', 'Katakana'),
('v_n3_auto_1809', 'N3', 'セット', 'セット', 'setto', 'set / setelan', 'Katakana'),
('v_n3_auto_1810', 'N3', 'アイスクリーム', 'アイスクリーム', 'aisukuriimu', 'es krim', 'Katakana'),
('v_n3_auto_1811', 'N3', 'アウト', 'アウト', 'auto', 'keluar / mati (olahraga)', 'Katakana'),
('v_n3_auto_1812', 'N3', 'アルバム', 'アルバム', 'arubamu', 'album', 'Katakana'),
('v_n3_auto_1813', 'N3', 'イメージ', 'イメージ', 'imeeji', 'citra / bayangan / imajinasi', 'Katakana'),
('v_n3_auto_1814', 'N3', 'インク', 'インク', 'inku', 'tinta', 'Katakana'),
('v_n3_auto_1815', 'N3', 'インタビュー', 'インタビュー', 'intabyuu', 'wawancara', 'Katakana'),
('v_n3_auto_1816', 'N3', 'ウイスキー', 'ウイスキー', 'uisukii', 'wiski', 'Katakana'),
('v_n3_auto_1817', 'N3', 'エンジン', 'エンジン', 'enjin', 'mesin', 'Katakana'),
('v_n3_auto_1818', 'N3', 'オフィス', 'オフィス', 'ofisu', 'kantor', 'Katakana'),
('v_n3_auto_1819', 'N3', 'カー', 'カー', 'kaa', 'mobil', 'Katakana'),
('v_n3_auto_1820', 'N3', 'カード', 'カード', 'kaado', 'kartu', 'Katakana'),
('v_n3_auto_1821', 'N3', 'キャプテン', 'キャプテン', 'kyaputen', 'kapten', 'Katakana'),
('v_n3_auto_1822', 'N3', 'クラシック', 'クラシック', 'kurashikku', 'klasik / musik klasik', 'Katakana'),
('v_n3_auto_1823', 'N3', 'グラス', 'グラス', 'gurasu', 'gelas', 'Katakana'),
('v_n3_auto_1824', 'N3', 'グランド', 'グランド', 'gurando', 'lapangan / tanah', 'Katakana'),
('v_n3_auto_1825', 'N3', 'クリーム', 'クリーム', 'kuriimu', 'krim', 'Katakana'),
('v_n3_auto_1826', 'N3', 'グループ', 'グループ', 'guruupu', 'kelompok / grup', 'Katakana'),
('v_n3_auto_1827', 'N3', 'ケース', 'ケース', 'keesu', 'kotak / wadah / kasus', 'Katakana'),
('v_n3_auto_1828', 'N3', 'コード', 'コード', 'koodo', 'kabel / kode', 'Katakana'),
('v_n3_auto_1829', 'N3', 'サイン', 'サイン', 'sain', 'tanda tangan / isyarat', 'Katakana'),
('v_n3_auto_1830', 'N3', 'ママ', 'ママ', 'mama', 'mama / ibu', 'Katakana'),
('v_n3_auto_1831', 'N3', 'ミス', 'ミス', 'misu', 'kesalahan / kegagalan', 'Katakana'),
('v_n3_auto_1832', 'N3', 'ミルク', 'ミルク', 'miruku', 'susu', 'Katakana'),
('v_n3_auto_1833', 'N3', 'メモ', 'メモ', 'memo', 'catatan', 'Katakana'),
('v_n3_auto_1834', 'N3', 'メンバー', 'メンバー', 'menbaa', 'anggota', 'Katakana'),
('v_n3_auto_1835', 'N3', 'ユーモア', 'ユーモア', 'yuumoa', 'humor / jenaka', 'Katakana'),
('v_n3_auto_1836', 'N3', 'ヨーロッパ', 'ヨーロッパ', 'yoroppa', 'Eropa', 'Katakana'),
('v_n3_auto_1837', 'N3', 'ヨット', 'ヨット', 'yotto', 'kapal pesiar / yacht', 'Katakana'),
('v_n3_auto_1838', 'N3', 'ライター', 'ライター', 'raitaa', 'korek gas / penulis', 'Katakana'),
('v_n3_auto_1839', 'N3', 'ラケット', 'ラケット', 'raketto', 'raket', 'Katakana'),
('v_n3_auto_1840', 'N3', 'レベル', 'レベル', 'reberu', 'tingkat / level', 'Katakana'),
('v_n3_auto_1841', 'N3', 'ロケット', 'ロケット', 'roketto', 'roket', 'Katakana'),
('v_n3_auto_1842', 'N3', 'ワイン', 'ワイン', 'wain', 'anggur (minuman)', 'Katakana'),
('v_n3_auto_1843', 'N3', 'アップ', 'アップ', 'appu', 'naik / meningkat', 'Katakana'),
('v_n3_auto_1844', 'N3', 'アンケート', 'アンケート', 'ankeeto', 'kuesioner / angket', 'Katakana'),
('v_n3_auto_1845', 'N3', 'コンテスト', 'コンテスト', 'kontesto', 'kontes / lomba', 'Katakana'),
('v_n3_auto_1846', 'N3', 'センター', 'センター', 'sentaa', 'pusat / tengah', 'Katakana'),
('v_n3_auto_1847', 'N3', 'ソファー', 'ソファー', 'sofaa', 'sofa', 'Katakana'),
('v_n3_auto_1848', 'N3', 'タイプライター', 'タイプライター', 'taipuraitaa', 'mesin tik', 'Katakana'),
('v_n3_auto_1849', 'N3', 'ダイヤ', 'ダイヤ', 'daiya', 'jadwal kereta / berlian', 'Katakana'),
('v_n3_auto_1850', 'N3', 'タオル', 'タオル', 'taoru', 'handuk', 'Katakana'),
('v_n3_auto_1851', 'N3', 'ダンス', 'ダンス', 'dansu', 'tarian / berdansa', 'Katakana'),
('v_n3_auto_1852', 'N3', 'チーズ', 'チーズ', 'chiizu', 'keju', 'Katakana'),
('v_n3_auto_1853', 'N3', 'チャンス', 'チャンス', 'chansu', 'kesempatan / peluang', 'Katakana'),
('v_n3_auto_1854', 'N3', 'デート', 'デート', 'deeto', 'kencan', 'Katakana'),
('v_n3_auto_1855', 'N3', 'デモ', 'デモ', 'demo', 'demo / demonstrasi', 'Katakana'),
('v_n3_auto_1856', 'N3', 'テント', 'テント', 'tento', 'tenda', 'Katakana'),
('v_n3_auto_1857', 'N3', 'トップ', 'トップ', 'toppu', 'teratas / puncak', 'Katakana'),
('v_n3_auto_1858', 'N3', 'ドライブ', 'ドライブ', 'doraibu', 'berkendara / menyetir', 'Katakana'),
('v_n3_auto_1859', 'N3', 'トラック', 'トラック', 'torakku', 'truk / lintasan', 'Katakana'),
('v_n3_auto_1860', 'N3', 'トランプ', 'トランプ', 'torampu', 'kartu remi', 'Katakana'),
('v_n3_auto_1861', 'N3', 'トレーニング', 'トレーニング', 'toreeningu', 'latihan / training', 'Katakana'),
('v_n3_auto_1862', 'N3', 'ドレス', 'ドレス', 'doresu', 'gaun', 'Katakana'),
('v_n3_auto_1863', 'N3', 'トン', 'トン', 'ton', 'ton (satuan berat)', 'Katakana'),
('v_n3_auto_1864', 'N3', 'トンネル', 'トンネル', 'tonneru', 'terowongan', 'Katakana'),
('v_n3_auto_1865', 'N3', 'ノー', 'ノー', 'noo', 'tidak / no', 'Katakana'),
('v_n3_auto_1866', 'N3', 'ノック', 'ノック', 'nokku', 'ketukan pintu / mengetuk', 'Katakana'),
('v_n3_auto_1867', 'N3', 'パーセント', 'パーセント', 'paasento', 'persen', 'Katakana'),
('v_n3_auto_1868', 'N3', 'バイオリン', 'バイオリン', 'baiorin', 'biola', 'Katakana'),
('v_n3_auto_1869', 'N3', 'パイプ', 'パイプ', 'paipu', 'pipa', 'Katakana'),
('v_n3_auto_1870', 'N3', 'パイロット', 'パイロット', 'pairotto', 'pilot', 'Katakana'),
('v_n3_auto_1871', 'N3', 'パス', 'パス', 'pasu', 'lulus / mengoper / pass', 'Katakana'),
('v_n3_auto_1872', 'N3', 'バッグ', 'バッグ', 'baggu', 'tas', 'Katakana'),
('v_n3_auto_1873', 'N3', 'バランス', 'バランス', 'baransu', 'keseimbangan', 'Katakana'),
('v_n3_auto_1874', 'N3', 'ハンサム', 'ハンサム', 'hansamu', 'tampan', 'Katakana'),
('v_n3_auto_1875', 'N3', 'ピクニック', 'ピクニック', 'pikunikku', 'piknik', 'Katakana'),
('v_n3_auto_1876', 'N3', NULL, 'ビデオ', 'bideo', 'video / kaset video', 'Katakana'),
('v_n3_auto_1877', 'N3', NULL, 'ピン', 'pin', 'pin / peniti', 'Katakana'),
('v_n3_auto_1878', 'N3', NULL, 'プラス', 'purasu', 'tambah / plus / keuntungan', 'Katakana'),
('v_n3_auto_1879', 'N3', NULL, 'プラスチック', 'purasuchikku', 'plastik', 'Katakana'),
('v_n3_auto_1880', 'N3', NULL, 'プラン', 'puran', 'rencana / program', 'Katakana'),
('v_n3_auto_1881', 'N3', NULL, 'ブレーキ', 'bureeki', 'rem', 'Katakana'),
('v_n3_auto_1882', 'N3', NULL, 'プロ', 'puro', 'profesional / ahli', 'Katakana'),
('v_n3_auto_1883', 'N3', NULL, 'ベルト', 'beruto', 'sabuk / ikat pinggang', 'Katakana'),
('v_n3_auto_1884', 'N3', NULL, 'ペンキ', 'penki', 'cat', 'Katakana'),
('v_n3_auto_1885', 'N3', NULL, 'ベンチ', 'benchi', 'bangku', 'Katakana'),
('v_n3_auto_1886', 'N3', NULL, 'ボーイ', 'booi', 'pelayan pria / porter', 'Katakana'),
('v_n3_auto_1887', 'N3', NULL, 'ボート', 'booto', 'perahu / bot', 'Katakana'),
('v_n3_auto_1888', 'N3', NULL, 'ホーム', 'hoomu', 'peron stasiun / rumah', 'Katakana'),
('v_n3_auto_1889', 'N3', NULL, 'ボール', 'booru', 'bola', 'Katakana'),
('v_n3_auto_1890', 'N3', NULL, 'マーケット', 'maaketto', 'pasar', 'Katakana'),
('v_n3_auto_1891', 'N3', NULL, 'マイク', 'maiku', 'mikrofon', 'Katakana'),
('v_n3_auto_1892', 'N3', NULL, 'マイナス', 'mainasu', 'kurang / minus', 'Katakana'),
('v_n3_auto_1893', 'N3', NULL, 'マスター', 'masutaa', 'menguasai / pemilik bar', 'Katakana'),
('v_n3_auto_1894', 'N3', NULL, 'ショック', 'shokku', 'syok / terkejut', 'Katakana'),
('v_n3_auto_1895', 'N3', NULL, 'ストレス', 'sutoresu', 'stres', 'Katakana'),
('v_n3_auto_1896', 'N3', NULL, 'タイトル', 'taitoru', 'judul', 'Katakana'),
('v_n3_auto_1897', 'N3', NULL, 'ダウン', 'daun', 'turun / jatuh / pingsan', 'Katakana'),
('v_n3_auto_1898', 'N3', NULL, 'チャイム', 'chaimu', 'bel pintu / lonceng', 'Katakana'),
('v_n3_auto_1899', 'N3', NULL, 'デザイン', 'dezain', 'desain / rancangan', 'Katakana'),
('v_n3_auto_1900', 'N3', NULL, 'マスコミ', 'masukomi', 'media massa', 'Katakana'),
('v_n3_auto_1901', 'N3', NULL, 'マッサージ', 'massaaji', 'pijat / pijatan', 'Katakana'),
('v_n3_auto_1902', 'N3', NULL, 'メッセージ', 'messeeji', 'pesan', 'Katakana'),
('v_n3_auto_1903', 'N3', NULL, 'ラベル', 'raberu', 'label / merek', 'Katakana'),
('v_n3_auto_1904', 'N3', NULL, 'ルール', 'ruuru', 'aturan', 'Katakana'),
('v_n3_auto_1905', 'N3', '作法', 'さほう', 'sahou', 'tata krama / etiket / tata cara', 'Noun'),
('v_n3_auto_1906', 'N3', '様々', 'さまざま', 'samazama', 'bermacam-macam / beragam', 'Adjective (na) / Noun'),
('v_n3_auto_1907', 'N3', '冷ます', 'さます', 'samasu', 'mendinginkan', 'Verb (Godan)'),
('v_n3_auto_1908', 'N3', '冷める', 'さめる', 'sameru', 'menjadi dingin / mereda', 'Verb (Ichidan)'),
('v_n3_auto_1909', 'N3', '左右', 'さゆう', 'sayuu', 'kiri dan kanan / memengaruhi', 'Noun / Verb (Irregular)'),
('v_n3_auto_1910', 'N3', '皿', 'さら', 'sara', 'piring', 'Noun'),
('v_n3_auto_1911', 'N3', '去る', 'さる', 'saru', 'pergi / meninggalkan', 'Verb (Godan)'),
('v_n3_auto_1912', 'N3', '騒ぎ', 'さわぎ', 'sawagi', 'keributan / kehebohan / kekacauan', 'Noun'),
('v_n3_auto_1913', 'N3', '参考', 'さんこう', 'sankou', 'referensi / rujukan', 'Noun / Verb (Irregular)'),
('v_n3_auto_1914', 'N3', '賛成', 'さんせい', 'sansei', 'persetujuan / setuju', 'Noun / Verb (Irregular)'),
('v_n3_auto_1915', 'N3', '酸素', 'さんそ', 'sanso', 'oksigen', 'Noun'),
('v_n3_auto_1916', 'N3', '幸せ', 'しあわせ', 'shiawase', 'kebahagiaan', 'Noun / Adjective (na)'),
('v_n3_auto_1917', 'N3', 'ジェット機', 'ジェットき', 'jettoki', 'pesawat jet', 'Noun'),
('v_n3_auto_1918', 'N3', '四角', 'しかく', 'shikaku', 'segi empat', 'Noun / Adjective (na)'),
('v_n3_auto_1919', 'N3', '直に', 'じかに', 'jikani', 'secara langsung', 'Adverb'),
('v_n3_auto_1920', 'N3', '四季', 'しき', 'shiki', 'empat musim', 'Noun'),
('v_n3_auto_1921', 'N3', '直', 'じき', 'jiki', 'segera / langsung', 'Noun / Adverb'),
('v_n3_auto_1922', 'N3', '支給', 'しきゅう', 'shikyuu', 'pembayaran / pemberian tunjangan', 'Noun / Verb (Irregular)'),
('v_n3_auto_1923', 'N3', '刺激', 'しげき', 'shigeki', 'rangsangan / stimulasi / dorongan', 'Noun / Verb (Irregular)'),
('v_n3_auto_1924', 'N3', '自殺', 'じさつ', 'jisatsu', 'bunuh diri', 'Noun / Verb (Irregular)'),
('v_n3_auto_1925', 'N3', '事情', 'じじょう', 'jijou', 'keadaan / situasi / alasan', 'Noun'),
('v_n3_auto_1926', 'N3', '詩人', 'しじん', 'shijin', 'penyair / pujangga', 'Noun'),
('v_n3_auto_1927', 'N3', '沈む', 'しずむ', 'shizumu', 'tenggelam / terbenam', 'Verb (Godan)'),
('v_n3_auto_1928', 'N3', '思想', 'しそう', 'shisou', 'pemikiran / ideologi / gagasan', 'Noun'),
('v_n3_auto_1929', 'N3', '舌', 'した', 'shita', 'lidah', 'Noun'),
('v_n3_auto_1930', 'N3', '次第', 'しだい', 'shidai', 'segera setelah / tergantung pada / keadaan', 'Noun / Conjunction'),
('v_n3_auto_1931', 'N3', '質', 'しつ', 'shitsu', 'kualitas / mutu / sifat', 'Noun'),
('v_n3_auto_1932', 'N3', '失業', 'しつぎょう', 'shitsugyou', 'pengangguran', 'Noun / Verb (Irregular)'),
('v_n3_auto_1933', 'N3', '湿気', 'しっけ', 'shikke', 'kelembapan', 'Noun'),
('v_n3_auto_1934', 'N3', '実行', 'じっこう', 'jikkou', 'pelaksanaan / praktik / realisasi', 'Noun / Verb (Irregular)'),
('v_n3_auto_1935', 'N3', '実際', 'じっさい', 'jissai', 'kenyataan / sebenarnya', 'Noun / Adverb'),
('v_n3_auto_1936', 'N3', '実力', 'じつりょく', 'jitsuryoku', 'kemampuan asli / kekuatan nyata', 'Noun'),
('v_n3_auto_1937', 'N3', '支店', 'してん', 'shiten', 'kantor cabang / cabang toko', 'Noun'),
('v_n3_auto_1938', 'N3', '指導', 'しどう', 'shidou', 'bimbingan / arahan / pelatihan', 'Noun / Verb (Irregular)'),
('v_n3_auto_1939', 'N3', '自動', 'じどう', 'jidou', 'otomatis', 'Noun'),
('v_n3_auto_1940', 'N3', '品', 'しな', 'shina', 'barang / produk / benda', 'Noun'),
('v_n3_auto_1941', 'N3', '支配', 'しはい', 'shihai', 'pengendalian / dominasi / kekuasaan', 'Noun / Verb (Irregular)'),
('v_n3_auto_1942', 'N3', '芝居', 'しばい', 'shibai', 'pertunjukan drama / sandiwara / lakon', 'Noun'),
('v_n3_auto_1943', 'N3', '芝生', '芝生', 'shibafu', 'halaman rumput', 'Noun'),
('v_n3_auto_1944', 'N3', '支払', 'しはらい', 'shiharai', 'pembayaran', 'Noun'),
('v_n3_auto_1945', 'N3', '支払う', 'しはらう', 'shiharau', 'membayar', 'Verb (Godan)'),
('v_n3_auto_1946', 'N3', '死亡', 'しぼう', 'shibou', 'kematian / wafat', 'Noun / Verb (Irregular)'),
('v_n3_auto_1947', 'N3', '資本', 'しほん', 'shihon', 'modal / kapital / dana', 'Noun'),
('v_n3_auto_1948', 'N3', '姉妹', 'しまい', 'shimai', 'saudara perempuan / bersaudari', 'Noun'),
('v_n3_auto_1949', 'N3', '自慢', 'じまん', 'jiman', 'kebanggaan / membanggakan / pamer', 'Noun / Verb (Irregular)'),
('v_n3_auto_1950', 'N3', '下', 'しも', 'shimo', 'bagian bawah / hilir', 'Noun'),
('v_n3_auto_1951', 'N3', '週', 'しゅう', 'shuu', 'minggu', 'Noun / Suffix'),
('v_n3_auto_1952', 'N3', '銃', 'じゅう', 'juu', 'senjata api / senapan / pistol', 'Noun'),
('v_n3_auto_1953', 'N3', '周囲', 'しゅうい', 'shuui', 'sekeliling / sekitar / lingkar', 'Noun'),
('v_n3_auto_1954', 'N3', '収穫', 'しゅうかく', 'shuukaku', 'panen / memanen', 'Noun / Verb (Irregular)'),
('v_n3_auto_1955', 'N3', '宗教', 'しゅうきょう', 'shuukyou', 'agama / kepercayaan', 'Noun'),
('v_n3_auto_1956', 'N3', '重視', 'じゅうし', 'juushi', 'mengutamakan / mementingkan / memandang penting', 'Noun / Verb (Irregular)'),
('v_n3_auto_1957', 'N3', '修正', 'しゅうせい', 'shuusei', 'koreksi / revisi / perbaikan', 'Noun / Verb (Irregular)'),
('v_n3_auto_1958', 'N3', '重大', 'じゅうだい', 'juudai', 'serius / penting / besar', 'Adjective (na) / Noun'),
('v_n3_auto_1959', 'N3', '住宅', 'じゅうたく', 'juutaku', 'perumahan / tempat tinggal', 'Noun'),
('v_n3_auto_1960', 'N3', '集団', 'しゅうだん', 'shuudan', 'kelompok / grup / massa', 'Noun'),
('v_n3_auto_1961', 'N3', '集中', 'しゅうちゅう', 'shuuchuu', 'konsentrasi / memusatkan', 'Noun / Verb (Irregular)'),
('v_n3_auto_1962', 'N3', '主義', 'しゅぎ', 'shugi', 'prinsip / paham / doktrin', 'Noun'),
('v_n3_auto_1963', 'N3', '宿泊', 'しゅくはく', 'shukuhaku', 'menginap / pondokan', 'Noun / Verb (Irregular)'),
('v_n3_auto_1964', 'N3', '首相', 'しゅしょう', 'shushou', 'perdana menteri', 'Noun'),
('v_n3_auto_1965', 'N3', '手段', 'しゅだん', 'shudan', 'cara / sarana / metode', 'Noun'),
('v_n3_auto_1966', 'N3', '出場', 'しゅつじょう', 'shutsujou', 'tampil / berpartisipasi (dalam lomba/acara)', 'Noun / Verb (Irregular)'),
('v_n3_auto_1967', 'N3', '出身', 'しゅっしん', 'shusshin', 'asal (daerah/sekolah) / kelahiran', 'Noun'),
('v_n3_auto_1968', 'N3', '出版', 'しゅっぱん', 'shuppan', 'penerbitan / publikasi / menerbitkan', 'Noun / Verb (Irregular)'),
('v_n3_auto_1969', 'N3', '首都', 'しゅと', 'shuto', 'ibu kota', 'Noun'),
('v_n3_auto_1970', 'N3', '主婦', 'しゅふ', 'shufu', 'ibu rumah tangga', 'Noun'),
('v_n3_auto_1971', 'N3', '主要', 'しゅよう', 'shuyou', 'utama / penting / pokok', 'Adjective (na) / Noun'),
('v_n3_auto_1972', 'N3', '種類', 'しゅるい', 'shurui', 'jenis / macam / kategori', 'Noun'),
('v_n3_auto_1973', 'N3', '順', 'じゅん', 'jun', 'urutan / giliran', 'Noun / Suffix'),
('v_n3_auto_1974', 'N3', '瞬間', 'しゅんかん', 'shunkan', 'seketika / sesaat / momen', 'Noun / Adverb'),
('v_n3_auto_1975', 'N3', '順調', 'じゅんちょう', 'junchou', 'lancar / baik / tanpa kendala', 'Adjective (na) / Noun'),
('v_n3_auto_1976', 'N3', '使用', 'しよう', 'shiyou', 'penggunaan / pemakaian / menggunakan', 'Noun / Verb (Irregular)'),
('v_n3_auto_1977', 'N3', '小', 'しょう', 'shou', 'kecil', 'Prefix / Noun'),
('v_n3_auto_1978', 'N3', '上', 'じょう', 'jou', 'volume pertama / kualitas unggul / di atas', 'Noun / Suffix'),
('v_n3_auto_1979', 'N3', '障害', 'しょうがい', 'shougai', 'hambatan / rintangan / gangguan / disabilitas', 'Noun'),
('v_n3_auto_1980', 'N3', '乗客', 'じょうきゃく', 'joukyaku', 'penumpang', 'Noun'),
('v_n3_auto_1981', 'N3', '正午', 'しょうご', 'shougo', 'tengah hari / jam 12 siang', 'Noun'),
('v_n3_auto_1982', 'N3', '常識', 'じょうしき', 'joushiki', 'akal sehat / pengetahuan umum / kepatutan', 'Noun'),
('v_n3_auto_1983', 'N3', '少女', 'しょうじょ', 'shoujo', 'gadis muda / anak perempuan', 'Noun'),
('v_n3_auto_1984', 'N3', '少々', 'しょうしょう', 'shoushou', 'sedikit / sebentar (sopan)', 'Adverb / Noun'),
('v_n3_auto_1985', 'N3', '生じる', 'しょうじる', 'shoujiru', 'terjadi / muncul / timbul', 'Verb (Ichidan)'),
('v_n3_auto_1986', 'N3', '状態', 'じょうたい', 'joutai', 'keadaan / kondisi / situasi', 'Noun'),
('v_n3_auto_1987', 'N3', '上達', 'じょうたつ', 'joutatsu', 'kemajuan / peningkatan (keterampilan)', 'Noun / Verb (Irregular)'),
('v_n3_auto_1988', 'N3', '冗談', 'じょうだん', 'joudan', 'candaan / lelucon / gurauan', 'Noun'),
('v_n3_auto_1989', 'N3', '上等', 'じょうとう', 'joutou', 'kelas atas / kualitas unggul / sangat baik', 'Adjective (na) / Noun'),
('v_n3_auto_1990', 'N3', '衝突', 'しょうとつ', 'shoutotsu', 'tabrakan / bentrokan / perselisihan', 'Noun / Verb (Irregular)'),
('v_n3_auto_1991', 'N3', '少年', 'しょうねん', 'shounen', 'anak laki-laki / pemuda', 'Noun'),
('v_n3_auto_1992', 'N3', '商売', 'しょうばい', 'shoubai', 'bisnis / perdagangan / usaha dagang', 'Noun / Verb (Irregular)'),
('v_n3_auto_1993', 'N3', '商品', 'しょうひん', 'shouhin', 'barang dagangan / produk / komoditas', 'Noun'),
('v_n3_auto_1994', 'N3', '消防', 'しょうぼう', 'shoubou', 'pemadam kebakaran', 'Noun'),
('v_n3_auto_1995', 'N3', '省略', 'しょうりゃく', 'shouryaku', 'penyingkatan / pemotongan / kelalaian', 'Noun / Verb (Irregular)'),
('v_n3_auto_1996', 'N3', '女王', 'じょおう', 'joou', 'ratu', 'Noun'),
('v_n3_auto_1997', 'N3', '職', 'しょく', 'shoku', 'pekerjaan / jabatan / karier', 'Noun'),
('v_n3_auto_1998', 'N3', '食卓', 'しょくたく', 'shokutaku', 'meja makan', 'Noun'),
('v_n3_auto_1999', 'N3', '食品', 'しょくひん', 'shokuhin', 'bahan makanan / produk makanan', 'Noun'),
('v_n3_auto_2000', 'N3', '食物', 'しょくもつ', 'shokumotsu', 'makanan / zat makanan', 'Noun'),
('v_n3_auto_2001', 'N3', '食料', 'しょくりょう', 'shokuryou', 'bahan pangan / makanan', 'Noun'),
('v_n3_auto_2002', 'N3', '書斎', 'しょさい', 'shosai', 'ruang belajar / perpustakaan pribadi', 'Noun'),
('v_n3_auto_2003', 'N3', '女子', 'じょし', 'joshi', 'anak perempuan / wanita', 'Noun'),
('v_n3_auto_2004', 'N3', '助手', 'じょしゅ', 'joshu', 'asisten / pembantu', 'Noun'),
('v_n3_auto_2005', 'N3', '署名', 'しょめい', 'shomei', 'tanda tangan / membubuhi tanda tangan', 'Noun / Verb (Irregular)'),
('v_n3_auto_2006', 'N3', '書物', 'しょもつ', 'shomotsu', 'buku / kitab / literatur', 'Noun'),
('v_n3_auto_2007', 'N3', '女優', 'じょゆう', 'joyuu', 'aktris / pemeran wanita', 'Noun'),
('v_n3_auto_2008', 'N3', '処理', 'しょり', 'shori', 'pengolahan / pemrosesan / penanganan', 'Noun / Verb (Irregular)'),
('v_n3_auto_2009', 'N3', '書類', 'しょるい', 'shorui', 'dokumen / berkas berkas resmi', 'Noun'),
('v_n3_auto_2010', 'N3', '知らせ', 'しらせ', 'shirase', 'kabar / pemberitahuan / pengumuman', 'Noun'),
('v_n3_auto_2011', 'N3', '尻', 'しり', 'shiri', 'pantat / bagian belakang', 'Noun'),
('v_n3_auto_2012', 'N3', '知合い', 'しりあい', 'shiriai', 'kenalan', 'Noun'),
('v_n3_auto_2013', 'N3', '印', 'しるし', 'shirushi', 'tanda / simbol / bukti', 'Noun'),
('v_n3_auto_2014', 'N3', '城', 'しろ', 'shiro', 'istana / kastel', 'Noun'),
('v_n3_auto_2015', 'N3', '進学', 'しんがく', 'shingaku', 'melanjutkan sekolah (ke jenjang lebih tinggi)', 'Noun / Verb (Irregular)'),
('v_n3_auto_2016', 'N3', '神経', 'しんけい', 'shinkei', 'saraf / kepekaan / urat', 'Noun'),
('v_n3_auto_2017', 'N3', '信号', 'しんごう', 'shingou', 'lampu lalu lintas / sinyal', 'Noun'),
('v_n3_auto_2018', 'N3', '診察', 'しんさつ', 'shinsatsu', 'pemeriksaan medis (oleh dokter)', 'Noun / Verb (Irregular)'),
('v_n3_auto_2019', 'N3', '人種', 'じんしゅ', 'jinshu', 'ras / golongan bangsa', 'Noun'),
('v_n3_auto_2020', 'N3', '人生', 'じんせい', 'jinsei', 'kehidupan (manusia)', 'Noun'),
('v_n3_auto_2021', 'N3', '親戚', 'しんせき', 'shinseki', 'kerabat / saudara sepupu', 'Noun'),
('v_n3_auto_2022', 'N3', '心臓', 'しんぞう', 'shinzou', 'jantung', 'Noun'),
('v_n3_auto_2023', 'N3', '身体', 'しんたい', 'shintai', 'tubuh / fisik / badan', 'Noun'),
('v_n3_auto_2024', 'N3', '審判', 'しんぱん', 'shinpan', 'wasit / juri / vonis / pengadilan', 'Noun / Verb (Irregular)'),
('v_n3_auto_2025', 'N3', '人物', 'じんぶつ', 'jinbutsu', 'tokoh / karakter / figur / pribadi', 'Noun'),
('v_n3_auto_2026', 'N3', NULL, 'しまった', 'shimatta', 'aduh / celaka / gawat', 'Expression'),
('v_n3_auto_2027', 'N3', NULL, 'すみません', 'sumimasen', 'maaf / permisi', 'Expression'),
('v_n3_auto_2028', 'N3', NULL, 'よろしく', 'yoroshiku', 'mohon bantuannya / salam', 'Expression'),
('v_n3_auto_2029', 'N3', NULL, 'はあ', 'haa', 'ya / oh / hah (hela napas)', 'Expression'),
('v_n3_auto_2030', 'N3', '親友', 'しんゆう', 'shinyuu', 'sahabat / teman dekat', 'Noun'),
('v_n3_auto_2031', 'N3', '心理', 'しんり', 'shinri', 'mentalitas / keadaan psikologis', 'Noun'),
('v_n3_auto_2032', 'N3', '人類', 'じんるい', 'jinrui', 'umat manusia / kemanusiaan', 'Noun'),
('v_n3_auto_2033', 'N3', '巣', 'す', 'su', 'sarang', 'Noun'),
('v_n3_auto_2034', 'N3', '図', 'ず', 'zu', 'gambar / diagram / bagan', 'Noun'),
('v_n3_auto_2035', 'N3', '水準', 'すいじゅん', 'suijun', 'tingkat / standar / level', 'Noun'),
('v_n3_auto_2036', 'N3', '推薦', 'すいせん', 'suisen', 'rekomendasi / rujukan', 'Noun / Verb (Irregular)'),
('v_n3_auto_2037', 'N3', '数', 'すう', 'suu', 'jumlah / angka / beberapa', 'Noun'),
('v_n3_auto_2038', 'N3', '数字', 'すうじ', 'suuji', 'angka / digit', 'Noun'),
('v_n3_auto_2039', 'N3', '末', 'すえ', 'sue', 'akhir / ujung / masa depan', 'Noun'),
('v_n3_auto_2040', 'N3', '姿', 'すがた', 'sugata', 'wujud / sosok / penampilan', 'Noun'),
('v_n3_auto_2041', 'N3', '救う', 'すくう', 'sukuu', 'menyelamatkan / menolong', 'Verb (Godan)'),
('v_n3_auto_2042', 'N3', '優れる', 'すぐれる', 'sugureru', 'unggul / menonjol / luar biasa', 'Verb (Ichidan)'),
('v_n3_auto_2043', 'N3', '少しも', 'すこしも', 'sukoshimo', 'sedikit pun (tidak)', 'Adverb'),
('v_n3_auto_2044', 'N3', '過ごす', 'すごす', 'sugosu', 'menghabiskan waktu / melewatkan', 'Verb (Godan)'),
('v_n3_auto_2045', 'N3', '筋', 'すじ', 'suji', 'otot / serat / alur cerita', 'Noun'),
('v_n3_auto_2046', 'N3', '頭痛', 'ずつう', 'zutsuu', 'sakit kepala', 'Noun'),
('v_n3_auto_2047', 'N3', '全て', 'すべて', 'subete', 'semua / seluruhnya', 'Noun / Adverb'),
('v_n3_auto_2048', 'N3', '済ませる', 'すませる', 'sumaseru', 'menyelesaikan / membereskan', 'Verb (Ichidan)'),
('v_n3_auto_2049', 'N3', '角', 'すみ', 'sumi', 'sudut / pojok', 'Noun'),
('v_n3_auto_2050', 'N3', 'すれ違う', 'すれちがう', 'surechigau', 'berpapasan', 'Verb (Godan)'),
('v_n3_auto_2051', 'N3', '正', 'せい', 'sei', 'kebenaran / keadilan / positif', 'Noun / Prefix'),
('v_n3_auto_2052', 'N3', '税', 'ぜい', 'zei', 'pajak', 'Noun / Suffix'),
('v_n3_auto_2053', 'N3', '世紀', 'せいき', 'seiki', 'abad', 'Noun'),
('v_n3_auto_2054', 'N3', '請求', 'せいきゅう', 'seikyuu', 'tagihan / tuntutan / klaim', 'Noun / Verb (Irregular)'),
('v_n3_auto_2055', 'N3', '制限', 'せいげん', 'seigen', 'pembatasan / batas / limit', 'Noun / Verb (Irregular)'),
('v_n3_auto_2056', 'N3', '正式', 'せいしき', 'seishiki', 'resmi / formal', 'Adjective (na) / Noun'),
('v_n3_auto_2057', 'N3', '性質', 'せいしつ', 'seishitsu', 'sifat / watak / karakter', 'Noun'),
('v_n3_auto_2058', 'N3', '精神', 'せいしん', 'seishin', 'mental / jiwa / roh / semangat', 'Noun'),
('v_n3_auto_2059', 'N3', '成人', 'せいじん', 'seijin', 'orang dewasa', 'Noun / Verb (Irregular)'),
('v_n3_auto_2060', 'N3', '贅沢', 'ぜいたく', 'zeitaku', 'kemewahan / boros', 'Adjective (na) / Noun'),
('v_n3_auto_2061', 'N3', '成長', 'せいちょう', 'seichou', 'pertumbuhan / berkembang', 'Noun / Verb (Irregular)'),
('v_n3_auto_2062', 'N3', '青年', 'せいねん', 'seinen', 'pemuda / masa muda', 'Noun'),
('v_n3_auto_2063', 'N3', '生年月日', 'せいねんがっぴ', 'seinengappi', 'tanggal lahir', 'Noun'),
('v_n3_auto_2064', 'N3', '製品', 'せいひん', 'seihin', 'produk / barang buatan / barang jadi', 'Noun'),
('v_n3_auto_2065', 'N3', '生命', 'せいめい', 'seimei', 'kehidupan / nyawa', 'Noun'),
('v_n3_auto_2066', 'N3', '整理', 'せいり', 'seiri', 'pembenahan / pengaturan / merapikan', 'Noun / Verb (Irregular)'),
('v_n3_auto_2067', 'N3', '咳', 'せき', 'seki', 'batuk', 'Noun'),
('v_n3_auto_2068', 'N3', '石炭', 'せきたん', 'sekitan', 'batu bara', 'Noun'),
('v_n3_auto_2069', 'N3', '石油', 'sekiyu', 'sekiyu', 'minyak bumi / minyak tanah', 'Noun'),
('v_n3_auto_2070', 'N3', '世間', 'せけん', 'seken', 'masyarakat / dunia luar / publik', 'Noun'),
('v_n3_auto_2071', 'N3', '説', 'せつ', 'setsu', 'teori / pandangan / pendapat', 'Noun / Suffix'),
('v_n3_auto_2072', 'N3', '設計', 'せっけい', 'sekkei', 'rancangan / desain / rancang bangun', 'Noun / Verb (Irregular)'),
('v_n3_auto_2073', 'N3', '絶対', 'ぜったい', 'zettai', 'pasti / mutlak / sama sekali (dengan negatif)', 'Noun / Adverb'),
('v_n3_auto_2074', 'N3', '愛', 'あい', 'ai', 'cinta', 'Noun'),
('v_n3_auto_2075', 'N3', '愛情', 'あいじょう', 'aijou', 'kasih sayang / cinta', 'Noun'),
('v_n3_auto_2076', 'N3', '合図', 'あいず', 'aizu', 'isyarat / tanda / sinyal', 'Noun / Verb (Irregular)'),
('v_n3_auto_2077', 'N3', '愛する', 'あいする', 'aisuru', 'mencintai', 'Verb (Irregular)'),
('v_n3_auto_2078', 'N3', '相手', 'あいて', 'aite', 'lawan / pasangan / lawan bicara', 'Noun'),
('v_n3_auto_2079', 'N3', '遭う', 'あう', 'au', 'mengalami (musibah/kecelakaan)', 'Verb (Godan)'),
('v_n3_auto_2080', 'N3', '明かり', 'あかり', 'akari', 'cahaya / penerangan', 'Noun'),
('v_n3_auto_2081', 'N3', '空き', 'あき', 'aki', 'kekosongan / lowongan / kamar kosong', 'Noun'),
('v_n3_auto_2082', 'N3', '飽きる', 'あきる', 'akiru', 'bosan / jenuh', 'Verb (Ichidan)'),
('v_n3_auto_2083', 'N3', '握手', 'あくしゅ', 'akushu', 'jabat tangan / bersalaman', 'Noun / Verb (Irregular)'),
('v_n3_auto_2084', 'N3', '悪魔', 'あくま', 'akuma', 'iblis / setan / roh jahat', 'Noun'),
('v_n3_auto_2085', 'N3', '預かる', 'あずかる', 'azukaru', 'menjaga / mengurus / dititipkan', 'Verb (Godan)'),
('v_n3_auto_2086', 'N3', '預ける', 'あずける', 'azukeru', 'menitipkan / mempercayakan', 'Verb (Ichidan)'),
('v_n3_auto_2087', 'N3', '汗', 'あせ', 'ase', 'keringat', 'Noun'),
('v_n3_auto_2088', 'N3', '温かい', 'あたたかい', 'atatakai', 'hangat (untuk benda/makanan/perasaan)', 'Adjective (i)'),
('v_n3_auto_2089', 'N3', '暖まる', 'あたたまる', 'atatamaru', 'menjadi hangat (udara/ruangan/tubuh)', 'Verb (Godan)'),
('v_n3_auto_2090', 'N3', '暖める', 'あたためる', 'atatameru', 'menghangatkan (udara/ruangan/benda)', 'Verb (Ichidan)'),
('v_n3_auto_2091', 'N3', '辺り', 'あたり', 'atari', 'sekitar / daerah sekeliling', 'Noun'),
('v_n3_auto_2092', 'N3', '当たり前', 'あたりまえ', 'atarimae', 'pantas / wajar / biasa / sewajarnya', 'Adjective (na) / Noun'),
('v_n3_auto_2093', 'N3', '扱う', 'あつかう', 'atsukau', 'menangani / memperlakukan / mengurus', 'Verb (Godan)'),
('v_n3_auto_2094', 'N3', '集まり', 'あつまり', 'atsumari', 'perkumpulan / pertemuan / arisan', 'Noun'),
('v_n3_auto_2095', 'N3', '跡', 'あと', 'ato', 'bekas / jejak / peninggalan', 'Noun'),
('v_n3_auto_2096', 'N3', '穴', 'あな', 'ana', 'lubang', 'Noun'),
('v_n3_auto_2097', 'N3', '油', 'あぶら', 'abura', 'minyak (makanan/masak/mesin)', 'Noun'),
('v_n3_auto_2098', 'N3', '誤り', 'あやまり', 'ayamari', 'kesalahan / kekeliruan', 'Noun'),
('v_n3_auto_2099', 'N3', '粗', 'あら', 'ara', 'cacat / kelemahan / duri ikan / kesalahan orang', 'Noun'),
('v_n3_auto_2100', 'N3', '新た', 'あらた', 'arata', 'baru / segar / secara baru', 'Adjective (na)'),
('v_n3_auto_2101', 'N3', '現れ', 'あらわれ', 'araware', 'perwujudan / ekspresi / tanda', 'Noun'),
('v_n3_auto_2102', 'N3', '現れる', 'あらわれる', 'arawareru', 'muncul / menampakkan diri', 'Verb (Ichidan)'),
('v_n3_auto_2103', 'N3', '有る', 'ある', 'aru', 'ada / memiliki (untuk benda mati/abstraksi)', 'Verb (Godan)'),
('v_n3_auto_2104', 'N3', '泡', 'あわ', 'awa', 'busa / gelembung', 'Noun'),
('v_n3_auto_2105', 'N3', '案', 'あん', 'an', 'rencana / usulan / ide / rancangan', 'Noun / Suffix'),
('v_n3_auto_2106', 'N3', '暗記', 'あんき', 'anki', 'menghafal / hafalan', 'Noun / Verb (Irregular)'),
('v_n3_auto_2107', 'N3', '胃', 'い', 'i', 'lambung / perut', 'Noun'),
('v_n3_auto_2108', 'N3', '委員', 'いいん', 'iin', 'anggota komite / anggota panitia', 'Noun'),
('v_n3_auto_2109', 'N3', '意外', 'いがい', 'igai', 'tak terduga / tak disangka / di luar dugaan', 'Adjective (na) / Noun'),
('v_n3_auto_2110', 'N3', '行き', 'いき', 'iki', 'tujuan / pergi ke / arah', 'Noun / Suffix'),
('v_n3_auto_2111', 'N3', '勢い', 'いきおい', 'ikioi', 'kekuatan / energi / momentum / gairah', 'Noun / Adverb'),
('v_n3_auto_2112', 'N3', '生き物', 'いきもの', 'ikimono', 'makhluk hidup', 'Noun'),
('v_n3_auto_2113', 'N3', '維持', 'いじ', 'iji', 'pemeliharaan / mempertahankan / menjaga', 'Noun / Verb (Irregular)'),
('v_n3_auto_2114', 'N3', '意識', 'いしき', 'ishiki', 'kesadaran / sadar akan', 'Noun / Verb (Irregular)'),
('v_n3_auto_2115', 'N3', '異常', 'いじょう', 'ijou', 'kejanggalan / tidak normal / kelainan', 'Adjective (na) / Noun'),
('v_n3_auto_2116', 'N3', '意地悪', 'いじわる', 'ijiwaru', 'jahat / usil / tega / dengki', 'Adjective (na) / Noun'),
('v_n3_auto_2117', 'N3', '泉', 'いずみ', 'izumi', 'mata air / pancuran air', 'Noun'),
('v_n3_auto_2118', 'N3', '以前', 'いぜん', 'izen', 'sebelumnya / yang lalu / dahulu', 'Noun / Adverb'),
('v_n3_auto_2119', 'N3', '板', 'いた', 'ita', 'papan / lempengan kayu', 'Noun'),
('v_n3_auto_2120', 'N3', '偉大', 'いだい', 'idai', 'keagungan / kebesaran / luar biasa', 'Adjective (na) / Noun'),
('v_n3_auto_2121', 'N3', '痛み', 'いたみ', 'itami', 'rasa sakit / kepedihan', 'Noun'),
('v_n3_auto_2122', 'N3', '至る', 'いたる', 'itaru', 'mencapai / berujung pada / tiba', 'Verb (Godan)'),
('v_n3_auto_2123', 'N3', '市', 'いち', 'ichi', 'kota / pasar', 'Noun / Suffix'),
('v_n3_auto_2124', 'N3', '一時', 'いちじ', 'ichiji', 'sementara / sesaat / satu waktu', 'Noun / Adverb'),
('v_n3_auto_2125', 'N3', '一度に', 'いちどに', 'ichidoni', 'sekaligus / pada saat yang sama', 'Adverb'),
('v_n3_auto_2126', 'N3', '一家', 'いっか', 'ikka', 'sekeluarga / seluruh keluarga / rumah tangga', 'Noun'),
('v_n3_auto_2127', 'N3', '一種', 'いっしゅ', 'isshu', 'sejenis / semacam', 'Noun'),
('v_n3_auto_2128', 'N3', '一瞬', 'いっしゅん', 'isshun', 'sekejap / sesaat / sekejap mata', 'Noun / Adverb'),
('v_n3_auto_2129', 'N3', '一生', 'いっしょう', 'isshou', 'seumur hidup / sepanjang hidup', 'Noun / Adverb'),
('v_n3_auto_2130', 'N3', '一層', 'いっそう', 'issou', 'lebih / jauh lebih / kian', 'Adverb'),
('v_n3_auto_2131', 'N3', '一体', 'いったい', 'ittai', 'sebenarnya (apa/siapa) / kesatuan / umumnya', 'Noun / Adverb'),
('v_n3_auto_2132', 'N3', '一致', 'いっち', 'itchi', 'kesesuaian / persetujuan / kecocokan', 'Noun / Verb (Irregular)'),
('v_n3_auto_2133', 'N3', '一般', 'いっぱん', 'ippan', 'umum / biasa / lazim', 'Noun / Adjective (na)'),
('v_n3_auto_2134', 'N3', '移動', 'いどう', 'idou', 'perpindahan / pergerakan / mobilitas', 'Noun / Verb (Irregular)'),
('v_n3_auto_2135', 'N3', '従兄弟', 'いとこ', 'itoko', 'saudara sepupu (laki-laki)', 'Noun'),
('v_n3_auto_2136', 'N3', '稲', 'いね', 'ine', 'padi / tanaman padi', 'Noun'),
('v_n3_auto_2137', 'N3', '居眠り', 'いねむり', 'inemuri', 'tidur ayam / mengantuk sampai tertidur', 'Noun / Verb (Irregular)'),
('v_n3_auto_2138', 'N3', '命', 'いのち', 'inochi', 'jiwa / nyawa / kehidupan', 'Noun'),
('v_n3_auto_2139', 'N3', '違反', 'いはん', 'ihan', 'pelanggaran / menyalahi (aturan)', 'Noun / Verb (Irregular)'),
('v_n3_auto_2140', 'N3', '衣服', 'いふく', 'ifuku', 'pakaian / busana', 'Noun'),
('v_n3_auto_2141', 'N3', '居間', 'いま', 'ima', 'ruang keluarga / ruang tamu', 'Noun'),
('v_n3_auto_2142', 'N3', '今に', 'いまに', 'imani', 'suatu saat nanti / dalam waktu dekat', 'Adverb'),
('v_n3_auto_2143', 'N3', '今にも', 'いまにも', 'imanimo', 'seketika itu juga / hampir saja / sewaktu-waktu', 'Adverb'),
('v_n3_auto_2144', 'N3', '否', 'いや', 'iya', 'tidak / penolakan / ketidaksetujuan', 'Expression / Noun'),
('v_n3_auto_2145', 'N3', '以来', 'いらい', 'irai', 'sejak itu / sejak saat itu', 'Noun / Suffix'),
('v_n3_auto_2146', 'N3', '岩', 'いわ', 'iwa', 'batu besar / batu karang', 'Noun'),
('v_n3_auto_2147', 'N3', '祝い', 'いわい', 'iwai', 'perayaan / ucapan selamat / pesta', 'Noun'),
('v_n3_auto_2148', 'N3', '祝う', 'いわう', 'iwau', 'merayakan / mengucapkan selamat', 'Verb (Godan)'),
('v_n3_auto_2149', 'N3', '印刷', 'いんさつ', 'insatsu', 'percetakan / mencetak / print', 'Noun / Verb (Irregular)'),
('v_n3_auto_2150', 'N3', '引退', 'いんたい', 'intai', 'pensiun / mundur (dari panggung/kegiatan)', 'Noun / Verb (Irregular)'),
('v_n3_auto_2151', 'N3', '引用', 'いんよう', 'inyou', 'kutipan / mengutip / sitasi', 'Noun / Verb (Irregular)'),
('v_n3_auto_2152', 'N3', '兎', 'うさぎ', 'usagi', 'kelinci', 'Noun'),
('v_n3_auto_2153', 'N3', '牛', 'うし', 'ushi', 'sapi', 'Noun'),
('v_n3_auto_2154', 'N3', '宇宙', 'うちゅう', 'uchuu', 'luar angkasa / alam semesta / kosmos', 'Noun'),
('v_n3_auto_2155', 'N3', '討つ', 'うつ', 'utsu', 'menyerang / membasmi / membalas dendam', 'Verb (Godan)'),
('v_n3_auto_2156', 'N3', '馬', 'うま', 'uma', 'kuda', 'Noun'),
('v_n3_auto_2157', 'N3', '生まれ', 'うまれ', 'umare', 'kelahiran / asal lahir', 'Noun'),
('v_n3_auto_2158', 'N3', '有無', 'うむ', 'umu', 'ada tidaknya / keberadaan', 'Noun'),
('v_n3_auto_2159', 'N3', '梅', 'うめ', 'ume', 'prem / plum', 'Noun'),
('v_n3_auto_2160', 'N3', '裏切る', 'うらぎる', 'uragiru', 'mengkhianati', 'Verb (Godan)'),
('v_n3_auto_2161', 'N3', '売れる', 'うれる', 'ureru', 'laku terjual / populer', 'Verb (Ichidan)'),
('v_n3_auto_2162', 'N3', '噂', 'うわさ', 'uwasa', 'rumor / desas-desus / gosip', 'Noun / Verb (Irregular)'),
('v_n3_auto_2163', 'N3', '運', 'うん', 'un', 'keberuntungan / nasib', 'Noun'),
('v_n3_auto_2164', 'N3', '運転', 'うんてん', 'unten', 'menyetir / mengemudi / pengoperasian', 'Noun / Verb (Irregular)'),
('v_n3_auto_2165', 'N3', '柄', 'え', 'e', 'gagang / pegangan / tangkai', 'Noun'),
('v_n3_auto_2166', 'N3', '永遠', 'えいえん', 'eien', 'keabadian / kekal', 'Noun / Adjective (na)'),
('v_n3_auto_2167', 'N3', '永久', 'えいきゅう', 'eikyuu', 'permanen / abadi / selamanya', 'Noun / Adjective (na)'),
('v_n3_auto_2168', 'N3', '営業', 'えいぎょう', 'eigyou', 'bisnis / jam buka (toko) / operasi usaha', 'Noun / Verb (Irregular)'),
('v_n3_auto_2169', 'N3', '衛星', 'えいせい', 'eisei', 'satelit', 'Noun'),
('v_n3_auto_2170', 'N3', '栄養', 'えいよう', 'eiyou', 'nutrisi / gizi', 'Noun'),
('v_n3_auto_2171', 'N3', '笑顔', 'えがお', 'egao', 'senyum / wajah tersenyum', 'Noun'),
('v_n3_auto_2172', 'N3', '描く', 'えがく', 'egaku', 'menggambar / melukis / menggambarkan', 'Verb (Godan)'),
('v_n3_auto_2173', 'N3', '餌', 'えさ', 'esa', 'pakan / umpan', 'Noun'),
('v_n3_auto_2174', 'N3', '円', 'えん', 'en', 'lingkaran / yen', 'Noun'),
('v_n3_auto_2175', 'N3', '延期', 'えんき', 'enki', 'penundaan / ditunda', 'Noun / Verb (Irregular)'),
('v_n3_auto_2176', 'N3', '演技', 'えんぎ', 'engi', 'akting / peran / pertunjukan', 'Noun / Verb (Irregular)'),
('v_n3_auto_2177', 'N3', '援助', 'えんじょ', 'enjo', 'bantuan / dukungan / sokongan', 'Noun / Verb (Irregular)'),
('v_n3_auto_2178', 'N3', '演説', 'えんぜつ', 'enzetsu', 'pidato / ceramah resmi', 'Noun / Verb (Irregular)'),
('v_n3_auto_2179', 'N3', '老い', 'おい', 'oi', 'usia tua / penuaan', 'Noun'),
('v_n3_auto_2180', 'N3', '追い付く', 'おいつく', 'oitsuku', 'menyusul / mengejar', 'Verb (Godan)'),
('v_n3_auto_2181', 'N3', '応援', 'おうえん', 'ouen', 'dukungan / sorakan semangat / menyemangati', 'Noun / Verb (Irregular)'),
('v_n3_auto_2182', 'N3', '王様', 'おうさま', 'ousama', 'raja', 'Noun'),
('v_n3_auto_2183', 'N3', '王子', 'おうじ', 'ouji', 'pangeran', 'Noun'),
('v_n3_auto_2184', 'N3', '横断', 'おうだん', 'oudan', 'penyeberangan / menyeberang / melintasi', 'Noun / Verb (Irregular)'),
('v_n3_auto_2185', 'N3', '覆う', 'おおう', 'oou', 'menutupi / menyelimuti / menyembunyikan', 'Verb (Godan)'),
('v_n3_auto_2186', 'N3', '大家', 'おおや', 'ooya', 'pemilik kontrakan / tuan tanah / landlord', 'Noun'),
('v_n3_auto_2187', 'N3', '丘', 'おか', 'oka', 'bukit', 'Noun'),
('v_n3_auto_2188', 'N3', '沖', 'おき', 'oki', 'lepas pantai / laut lepas', 'Noun'),
('v_n3_auto_2189', 'N3', '贈る', 'おくる', 'okuru', 'menghadiahkan / memberikan hadiah', 'Verb (Godan)'),
('v_n3_auto_2190', 'N3', '幼い', 'おさない', 'osanai', 'sangat muda / kekanak-kanakan / balita', 'Adjective (i)'),
('v_n3_auto_2191', 'N3', 'お辞儀', 'おじぎ', 'ojigi', 'membungkuk (tata krama Jepang)', 'Noun / Verb (Irregular)'),
('v_n3_auto_2192', 'N3', 'お洒落', 'おしゃれ', 'oshare', 'modis / bergaya / necis / pesolek', 'Adjective (na) / Noun / Verb (Irregular)'),
('v_n3_auto_2193', 'N3', 'お喋り', 'おしゃべり', 'oshaberi', 'mengobrol / cerewet / banyak bicara', 'Adjective (na) / Noun / Verb (Irregular)'),
('v_n3_auto_2194', 'N3', '恐れる', 'おそれる', 'osoreru', 'takut / mengkhawatirkan', 'Verb (Ichidan)'),
('v_n3_auto_2195', 'N3', '恐ろしい', 'おそろしい', 'osoroshii', 'mengerikan / menakutkan / dahsyat', 'Adjective (i)'),
('v_n3_auto_2196', 'N3', 'お互い', 'おたがい', 'otagai', 'saling / satu sama lain / timbal balik', 'Noun / Adverb'),
('v_n3_auto_2197', 'N3', '男の人', 'おとこのひと', 'otokonohito', 'pria / laki-laki', 'Noun'),
('v_n3_auto_2198', 'N3', '劣る', 'おとる', 'otoru', 'kalah / lebih rendah kualitasnya / inferior', 'Verb (Godan)'),
('v_n3_auto_2199', 'N3', '鬼', 'おに', 'oni', 'iblis / raksasa jahat / ogre / penjaga (permainan petak umpet)', 'Noun'),
('v_n3_auto_2200', 'N3', '帯', 'おび', 'obi', 'obi / sabuk kimono / pita ikat', 'Noun'),
('v_n3_auto_2201', 'N3', 'お昼', 'おひる', 'ohiru', 'siang hari / makan siang', 'Noun'),
('v_n3_auto_2202', 'N3', '溺れる', 'おぼれる', 'oboreru', 'tenggelam (di air) / hanyut dalam perasaan/kecanduan', 'Verb (Ichidan)'),
('v_n3_auto_2203', 'N3', 'お前', 'おまえ', 'omae', 'kamu (kasar/akrab, biasa digunakan laki-laki)', 'Pronoun / Noun'),
('v_n3_auto_2204', 'N3', 'お目に掛かる', 'おめにかかる', 'omenikakaru', 'bertemu (sopan/merendahkan diri)', 'Verb (Godan)'),
('v_n3_auto_2205', 'N3', '思い付く', 'おもいつく', 'omoitsuku', 'terpikirkan / terlintas di pikiran / menemukan ide', 'Verb (Godan)'),
('v_n3_auto_2206', 'N3', '思い出', 'おもいで', 'omoide', 'kenangan / memori indah', 'Noun'),
('v_n3_auto_2207', 'N3', '泳ぎ', 'およぎ', 'oyogi', 'berenang / gaya renang', 'Noun'),
('v_n3_auto_2208', 'N3', '及ぼす', 'およぼす', 'oyobosu', 'memberikan pengaruh / menimbulkan / menyebabkan', 'Verb (Godan)'),
('v_n3_auto_2209', 'N3', '下す', 'おろす', 'orosu', 'menurunkan / menjatuhkan keputusan / menarik uang', 'Verb (Godan)'),
('v_n3_auto_2210', 'N3', '音', 'おん', 'on', 'bunyi / suara (benda/alat musik)', 'Noun'),
('v_n3_auto_2211', 'N3', '温暖', 'おんだん', 'ondan', 'hangat (untuk iklim/cuaca)', 'Adjective (na) / Noun'),
('v_n3_auto_2212', 'N3', '温度', 'おんど', 'ondo', 'suhu / temperatur', 'Noun'),
('v_n3_auto_2213', 'N3', '可', 'か', 'ka', 'boleh / dapat / cukup (nilai kelulusan)', 'Noun'),
('v_n3_auto_2214', 'N3', '貝', 'かい', 'kai', 'kerang / cangkang kerang', 'Noun'),
('v_n3_auto_2215', 'N3', '害', 'がい', 'gai', 'bahaya / kerugian / kerusakan / dampak buruk', 'Noun'),
('v_n3_auto_2216', 'N3', '会員', 'かいいん', 'kaiin', 'anggota / member', 'Noun'),
('v_n3_auto_2217', 'N3', '絵画', 'かいが', 'kaiga', 'lukisan / gambar seni', 'Noun'),
('v_n3_auto_2218', 'N3', '海外', 'かいがい', 'kaigai', 'luar negeri', 'Noun'),
('v_n3_auto_2219', 'N3', '会計', 'かいけい', 'kaikei', 'akuntansi / kasir / pembayaran tagihan', 'Noun / Verb (Irregular)'),
('v_n3_auto_2220', 'N3', '会合', 'かいごう', 'kaigou', 'pertemuan / rapat / majelis', 'Noun / Verb (Irregular)'),
('v_n3_auto_2221', 'N3', '開始', 'かいし', 'kaishi', 'awal / memulai / start', 'Noun / Verb (Irregular)'),
('v_n3_auto_2222', 'N3', '解釈', 'かいしゃく', 'kaishaku', 'penafsiran / interpretasi / pemahaman', 'Noun / Verb (Irregular)'),
('v_n3_auto_2223', 'N3', '外出', 'がいしゅつ', 'gaishutsu', 'pergi keluar (rumah/kantor)', 'Noun / Verb (Irregular)'),
('v_n3_auto_2224', 'N3', '回復', 'かいふく', 'kaifuku', 'pemulihan / memulihkan (kesehatan/kondisi)', 'Noun / Verb (Irregular)'),
('v_n3_auto_2225', 'N3', '帰す', 'かえす', 'kaesu', 'memulangkan / menyuruh pulang', 'Verb (Godan)'),
('v_n3_auto_2226', 'N3', '香り', 'かおり', 'kaori', 'wewangian / aroma / parfum', 'Noun'),
('v_n3_auto_2227', 'N3', '化学', 'かがく', 'kagaku', 'kimia', 'Noun'),
('v_n3_auto_2228', 'N3', '輝く', 'かがやく', 'kagayaku', 'bersinar / berkilau', 'Verb (Godan)'),
('v_n3_auto_2229', 'N3', '係', 'かかり', 'kakari', 'petugas penanggung jawab / urusan', 'Noun'),
('v_n3_auto_2230', 'N3', '罹る', 'かかる', 'kakaru', 'terjangkit (penyakit) / menderita sakit', 'Verb (Godan)'),
('v_n3_auto_2231', 'N3', '限る', 'かぎる', 'kagiru', 'membatasi / terbatas pada / yang terbaik adalah', 'Verb (Godan)'),
('v_n3_auto_2232', 'N3', '嗅ぐ', 'かぐ', 'kagu', 'mencium bau / mengendus', 'Verb (Godan)'),
('v_n3_auto_2233', 'N3', '学', 'がく', 'gaku', 'ilmu / studi / pembelajaran', 'Noun / Suffix'),
('v_n3_auto_2234', 'N3', '覚悟', 'かくご', 'kakugo', 'kesiapan mental / tekad / pasrah', 'Noun / Verb (Irregular)'),
('v_n3_auto_2235', 'N3', '確実', 'かくじつ', 'kakujitsu', 'pasti / nyata / dapat diandalkan', 'Adjective (na) / Noun'),
('v_n3_auto_2236', 'N3', '学者', 'がくしゃ', 'gakusha', 'akademisi / sarjana / ilmuwan', 'Noun'),
('v_n3_auto_2237', 'N3', '学習', 'がくしゅう', 'gakushuu', 'pembelajaran / belajar / studi', 'Noun / Verb (Irregular)'),
('v_n3_auto_2238', 'N3', '拡大', 'かくだい', 'kakudai', 'perluasan / pembesaran / ekspansi', 'Noun / Verb (Irregular)'),
('v_n3_auto_2239', 'N3', '学問', 'がくもん', 'gakumon', 'ilmu pengetahuan / studi / bidang akademis', 'Noun'),
('v_n3_auto_2240', 'N3', '影', 'かげ', 'kage', 'bayangan / refleksi / siluet', 'Noun'),
('v_n3_auto_2241', 'N3', '加減', 'かげん', 'kagen', 'penyesuaian / kondisi kesehatan / kadar', 'Noun / Verb (Irregular)'),
('v_n3_auto_2242', 'N3', '過去', 'かこ', 'kako', 'masa lalu / masa lampau', 'Noun'),
('v_n3_auto_2243', 'N3', '籠', 'かご', 'kago', 'keranjang / sangkar', 'Noun'),
('v_n3_auto_2244', 'N3', '囲む', 'かこむ', 'kakomu', 'mengelilingi / memutari', 'Verb (Godan)'),
('v_n3_auto_2245', 'N3', '火災', 'かさい', 'kasai', 'kebakaran / bencana kebakaran', 'Noun'),
('v_n3_auto_2246', 'N3', '重ねる', 'かさねる', 'kasaneru', 'menumpuk / menimbun / mengulangi', 'Verb (Ichidan)'),
('v_n3_auto_2247', 'N3', '飾り', 'かざり', 'kazari', 'hiasan / dekorasi', 'Noun'),
('v_n3_auto_2248', 'N3', '家事', 'かじ', 'kaji', 'pekerjaan rumah tangga', 'Noun'),
('v_n3_auto_2249', 'N3', '型', 'かた', 'kata', 'tipe / model / pola / cetakan', 'Noun / Suffix'),
('v_n3_auto_2250', 'N3', '方々', 'かたがた', 'katagata', 'orang-orang (sopan) / di sana-sini', 'Noun / Pronoun'),
('v_n3_auto_2251', 'N3', '片付く', 'かたづく', 'katadzuku', 'beres / rapi / selesai diatur', 'Verb (Godan)'),
('v_n3_auto_2252', 'N3', '刀', 'かたな', 'katana', 'pedang / katana', 'Noun'),
('v_n3_auto_2253', 'N3', '語る', 'かたる', 'kataru', 'bercerita / mengisahkan / berkata', 'Verb (Godan)'),
('v_n3_auto_2254', 'N3', '活躍', 'かつやく', 'katsuyaku', 'kiprah / berpartisipasi aktif / beraksi', 'Noun / Verb (Irregular)'),
('v_n3_auto_2255', 'N3', '活用', 'かつよう', 'katsuyou', 'pemanfaatan / penggunaan praktis / konjugasi kata', 'Noun / Verb (Irregular)'),
('v_n3_auto_2256', 'N3', '仮定', 'かてい', 'katei', 'pengandaian / asumsi / hipotesis', 'Noun / Verb (Irregular)'),
('v_n3_auto_2257', 'N3', '悲しむ', 'かなしむ', 'kanashimu', 'bersedih / meratap', 'Verb (Godan)'),
('v_n3_auto_2258', 'N3', '金', 'かね', 'kane', 'uang / logam emas', 'Noun'),
('v_n3_auto_2259', 'N3', '株', 'かぶ', 'kabu', 'saham / tunggul pohon', 'Noun'),
('v_n3_auto_2260', 'N3', '被る', 'かぶる', 'kaburu', 'memakai (topi) / tersiram / menanggung beban', 'Verb (Godan)'),
('v_n3_auto_2261', 'N3', '我慢', 'がまん', 'gaman', 'kesabaran / menahan diri / bersabar', 'Noun / Verb (Irregular)'),
('v_n3_auto_2262', 'N3', '神', 'かみ', 'kami', 'tuhan / dewa', 'Noun'),
('v_n3_auto_2263', 'N3', '髪の毛', 'かみのけ', 'kaminoke', 'rambut kepala', 'Noun'),
('v_n3_auto_2264', 'N3', '科目', 'かもく', 'kamoku', 'mata pelajaran / kurikulum', 'Noun'),
('v_n3_auto_2265', 'N3', '空', 'から', 'kara', 'kosong / hampa', 'Noun / Adjective (na)'),
('v_n3_auto_2266', 'N3', '刈る', 'かる', 'karu', 'memangkas / memotong (rumput/rambut)', 'Verb (Godan)'),
('v_n3_auto_2267', 'N3', '可愛そう', 'かわいそう', 'kawaisou', 'kasihan / memprihatinkan', 'Adjective (na)'),
('v_n3_auto_2268', 'N3', '可愛らしい', 'かわいらしい', 'kawairashii', 'lucu / manis / menggemaskan', 'Adjective (i)'),
('v_n3_auto_2269', 'N3', '乾かす', 'かわかす', 'kawakasu', 'mengeringkan', 'Verb (Godan)'),
('v_n3_auto_2270', 'N3', '渇く', 'かわく', 'kawaku', 'haus / kering tenggorokan', 'Verb (Godan)'),
('v_n3_auto_2271', 'N3', '缶', 'かん', 'kan', 'kaleng', 'Noun'),
('v_n3_auto_2272', 'N3', '考え', 'かんがえ', 'kangae', 'pemikiran / pendapat / ide', 'Noun'),
('v_n3_auto_2273', 'N3', '感覚', 'かんかく', 'kankaku', 'indra / indriawi / perasaan sensorik', 'Noun'),
('v_n3_auto_2274', 'N3', '歓迎', 'かんげい', 'kangei', 'sambutan / menyambut baik', 'Noun / Verb (Irregular)'),
('v_n3_auto_2275', 'N3', '観察', 'かんさつ', 'kansatsu', 'pengamatan / observasi', 'Noun / Verb (Irregular)'),
('v_n3_auto_2276', 'N3', '感じ', 'かんじ', 'kanji', 'perasaan / kesan / sensasi', 'Noun'),
('v_n3_auto_2277', 'N3', '患者', 'かんじゃ', 'kanja', 'pasien / orang sakit', 'Noun'),
('v_n3_auto_2278', 'N3', '感心', 'かんしん', 'kanshin', 'kagum / terkesan', 'Noun / Adjective (na) / Verb (Irregular)'),
('v_n3_auto_2279', 'N3', '関する', 'かんする', 'kansuru', 'mengenai / berkaitan dengan', 'Verb (Irregular)'),
('v_n3_auto_2280', 'N3', '完成', 'かんせい', 'kansei', 'penyelesaian / rampung / selesai dibuat', 'Noun / Verb (Irregular)'),
('v_n3_auto_2281', 'N3', '乾燥', 'かんそう', 'kansou', 'kekeringan / mengering / dehidrasi', 'Noun / Verb (Irregular)'),
('v_n3_auto_2282', 'N3', '感動', 'かんどう', 'kandou', 'terharu / tersentuh perasaan', 'Noun / Verb (Irregular)'),
('v_n3_auto_2283', 'N3', '監督', 'kantoku', 'kantoku', 'pengawas / sutradara / pelatih kepala', 'Noun / Verb (Irregular)'),
('v_n3_auto_2284', 'N3', '完了', 'かんりょう', 'kanryou', 'selesai / rampung / tuntas', 'Noun / Verb (Irregular)'),
('v_n3_auto_2285', 'N3', '関連', 'かんれん', 'kanren', 'hubungan / kaitan / asosiasi', 'Noun / Verb (Irregular)'),
('v_n3_auto_2286', 'N3', '議員', 'ぎいん', 'giin', 'anggota parlemen / anggota dewan / senator', 'Noun'),
('v_n3_auto_2287', 'N3', '記憶', 'きおく', 'kioku', 'ingatan / memori', 'Noun / Verb (Irregular)'),
('v_n3_auto_2288', 'N3', '岸', 'きし', 'kishi', 'pantai / tepi sungai / tepian', 'Noun'),
('v_n3_auto_2289', 'N3', '技師', 'ぎし', 'gishi', 'insinyur / teknisi', 'Noun'),
('v_n3_auto_2290', 'N3', '記者', 'きしゃ', 'kisha', 'wartawan / jurnalis / reporter', 'Noun'),
('v_n3_auto_2291', 'N3', '期待', 'きたい', 'kitai', 'harapan / ekspektasi / mengharapkan', 'Noun / Verb (Irregular)'),
('v_n3_auto_2292', 'N3', '帰宅', 'きたく', 'kitaku', 'pulang ke rumah', 'Noun / Verb (Irregular)'),
('v_n3_auto_2293', 'N3', '貴重', 'きちょう', 'kichou', 'berharga / bernilai tinggi', 'Adjective (na) / Noun'),
('v_n3_auto_2294', 'N3', '議長', 'ぎちょう', 'gichou', 'ketua sidang / pimpinan rapat / ketua dewan', 'Noun'),
('v_n3_auto_2295', 'N3', '気に入る', 'きにいる', 'kiniiru', 'menyukai / senang akan / cocok di hati', 'Verb (Godan)'),
('v_n3_auto_2296', 'N3', '記入', 'きにゅう', 'kinyuu', 'pengisian / mengisi (formulir) / menuliskan', 'Noun / Verb (Irregular)'),
('v_n3_auto_2297', 'N3', '記念', 'きねん', 'kinen', 'peringatan / kenang-kenangan', 'Noun / Verb (Irregular)'),
('v_n3_auto_2298', 'N3', '気の毒', 'きのどく', 'kinodoku', 'kasihan / menyedihkan / prihatin', 'Adjective (na) / Noun'),
('v_n3_auto_2299', 'N3', '基本', 'きほん', 'kihon', 'dasar / basis / fundamental', 'Noun'),
('v_n3_auto_2300', 'N3', '決まり', 'きまり', 'kimari', 'peraturan / keputusan / ketentuan', 'Noun'),
('v_n3_auto_2301', 'N3', '気味', 'きみ', 'kimi', 'perasaan agak / kecenderungan (sakit/lelah)', 'Noun / Suffix'),
('v_n3_auto_2302', 'N3', '奇妙', 'きみょう', 'kimyou', 'aneh / ganjil / ajaib', 'Adjective (na) / Noun'),
('v_n3_auto_2303', 'N3', '疑問', 'ぎもん', 'gimon', 'pertanyaan / keraguan / kemusykilan', 'Noun'),
('v_n3_auto_2304', 'N3', '逆', 'ぎゃく', 'gyaku', 'kebalikan / sebaliknya / berlawanan', 'Adjective (na) / Noun'),
('v_n3_auto_2305', 'N3', '旧', 'きゅう', 'kyuu', 'mantan / bekas / lama', 'Prefix / Noun')
ON CONFLICT (id) DO NOTHING;
