-- ============================================================
-- Extra N3 seed data (IDs >= 1726)
-- Total: 580 entries
-- ============================================================

INSERT INTO public.vocabulary_examples (id, vocab_id, japanese, reading, translation) VALUES
('ex_n3_auto_1726', 'v_n3_auto_1726', '彼はしきりに電話をかけてくる。', 'かれは しきりに でんわを かけてくる。', 'Dia terus-menerus meneleponku.'),
('ex_n3_auto_1727', 'v_n3_auto_1727', '彼はじっと目を閉じていた。', 'かれは じっと めを とじていた。', 'Dia memejamkan mata dengan tenang.'),
('ex_n3_auto_1728', 'v_n3_auto_1728', 'この道路ではしばしば事故が起こる。', 'この どうろでは しばしば じこが おこる。', 'Di jalan ini sering terjadi kecelakaan.'),
('ex_n3_auto_1729', 'v_n3_auto_1729', '授業中にしゃべらないでください。', 'じゅぎょうちゅうに しゃべらないで ください。', 'Tolong jangan mengobrol saat pelajaran.'),
('ex_n3_auto_1730', 'v_n3_auto_1730', 'このレモンはとてもすっぱい。', 'この れもんは とても すっぱい。', 'Lemon ini sangat asam.'),
('ex_n3_auto_1731', 'v_n3_auto_1731', 'すてきなプレゼントをありがとう。', 'すてきな プレゼントを ありがとう。', 'Terima kasih atas hadiah yang menakjubkan ini.'),
('ex_n3_auto_1732', 'v_n3_auto_1732', '予定の時間が少しずれた。', 'よていの じかんが すこし ずれた。', 'Waktu jadwalnya agak bergeser.'),
('ex_n3_auto_1733', 'v_n3_auto_1733', '京都のあちこちを観光した。', 'きょうとの あちこちを かんこうした。', 'Kami berwisata ke sana-sini di Kyoto.'),
('ex_n3_auto_1734', 'v_n3_auto_1734', 'あらゆる方法を試してみた。', 'あらゆる ほうほうを ためしてみた。', 'Aku sudah mencoba segala cara.'),
('ex_n3_auto_1735', 'v_n3_auto_1735', '手伝ってくれてありがとう。', 'てつだってくれて ありがとう。', 'Terima kasih sudah membantu.'),
('ex_n3_auto_1736', 'v_n3_auto_1736', 'あんなに高いビルは初めて見た。', 'あんなに たかい びるは はじめて みた。', 'Baru pertama kali ini aku melihat gedung setinggi itu.'),
('ex_n3_auto_1737', 'v_n3_auto_1737', '今日はあんまり寒くない。', 'きょうは あんまり さむくない。', 'Hari ini tidak terlalu dingin.'),
('ex_n3_auto_1738', 'v_n3_auto_1738', '嘘をついてはいけません。', 'うそを ついては いけません。', 'Tidak boleh berbohong.'),
('ex_n3_auto_1739', 'v_n3_auto_1739', '子どもがいたずらをして怒られた。', 'こどもが いたずらを して おこられた。', 'Anak itu dimarahi karena berbuat nakal.'),
('ex_n3_auto_1740', 'v_n3_auto_1740', 'ご飯を食べる前にいただきますと言う。', 'ごはんを たべる まえに いただきますと いう。', 'Sebelum makan kita mengucapkan selamat makan.'),
('ex_n3_auto_1741', 'v_n3_auto_1741', 'いつか日本へ行ってみたい。', 'いつか にほんへ いってみたい。', 'Suatu saat aku ingin mencoba pergi ke Jepang.'),
('ex_n3_auto_1742', 'v_n3_auto_1742', '外はいつのまにか雨が降っていた。', 'そとは いつのまにか あめが ふっていた。', 'Tanpa disadari di luar sudah turun hujan.'),
('ex_n3_auto_1743', 'v_n3_auto_1743', '私たちはいつまでも友達だ。', 'わたしたちは いつまでも ともだちだ。', 'Kita adalah teman selamanya.'),
('ex_n3_auto_1744', 'v_n3_auto_1744', '渋滞でいらいらする。', 'じゅうたいで いらいら する。', 'Aku merasa jengkel karena kemacetan.'),
('ex_n3_auto_1745', 'v_n3_auto_1745', 'ようこそ、我が家へいらっしゃい。', 'ようこそ、 わがやへ いらっしゃい。', 'Selamat datang di rumah kami.'),
('ex_n3_auto_1746', 'v_n3_auto_1746', '彼は、いわゆる天才だ。', 'かれは、 いわゆる てんさいだ。', 'Dia adalah orang yang biasa disebut jenius.'),
('ex_n3_auto_1747', 'v_n3_auto_1747', '帰宅したら手洗いとうがいをしよう。', 'きたくしたら てあらいと うがいを しよう。', 'Mari mencuci tangan dan berkumur setelah pulang ke rumah.'),
('ex_n3_auto_1748', 'v_n3_auto_1748', '犬が見知らぬ人に向かってうなっている。', 'いぬが みしらぬ ひとに むかって うなっている。', 'Anjing itu mengerang ke arah orang asing.'),
('ex_n3_auto_1749', 'v_n3_auto_1749', 'お誕生日おめでとうございます！', 'おたんじょうび おめでとう ございます！', 'Selamat hari ulang tahun!'),
('ex_n3_auto_1750', 'v_n3_auto_1750', '不合格と知ってがっかりした。', 'ふごうかくと しって がっかり した。', 'Aku kecewa saat tahu tidak lulus.'),
('ex_n3_auto_1751', 'v_n3_auto_1751', '明日は雨が降るかもしれない。', 'あしたは あめが ふる かもしれない。', 'Besok mungkin akan turun hujan.'),
('ex_n3_auto_1752', 'v_n3_auto_1752', '蚊に刺されて腕がかゆい。', 'かに さされて うでが かゆい。', 'Lenganku gatal karena digigit nyamuk.'),
('ex_n3_auto_1753', 'v_n3_auto_1753', 'この靴は少しきついです。', 'この くつは すこし きついです。', 'Sepatu ini agak ketat.'),
('ex_n3_auto_1754', 'v_n3_auto_1754', '昨夜はぐっすり眠れました。', 'さくやは ぐっすり ねむれました。', 'Semalam aku bisa tidur nyenyak.'),
('ex_n3_auto_1755', 'v_n3_auto_1755', '彼は大金持ちなのにけちだ。', 'かれは おおがねもちなのに けちだ。', 'Dia pelit padahal orang yang sangat kaya.'),
('ex_n3_auto_1756', 'v_n3_auto_1756', 'テーブルの上にコーヒーをこぼした。', 'テーブルの うえに コーヒーを こぼした。', 'Aku menumpahkan kopi di atas meja.'),
('ex_n3_auto_1757', 'v_n3_auto_1757', 'コップから水がこぼれた。', 'コップから みずが こぼれた。', 'Air tumpah dari gelas.'),
('ex_n3_auto_1758', 'v_n3_auto_1758', '遅くなってごめんなさい。', 'おそくなって ごめんなさい。', 'Maaf karena saya terlambat.'),
('ex_n3_auto_1759', 'v_n3_auto_1759', 'これらの本はすべて私のです。', 'これらの ほんは すべて わたしのです。', 'Buku-buku ini semuanya milikku.'),
('ex_n3_auto_1760', 'v_n3_auto_1760', 'こんなに美味しい料理は初めてだ。', 'こんなに おいしい りょうりは はじめてだ。', 'Ini pertama kalinya aku makan hidangan seenak ini.'),
('ex_n3_auto_1761', 'v_n3_auto_1761', '皆さん、こんにちは。', 'みなさん、 こんにちは。', 'Halo semuanya, selamat siang.'),
('ex_n3_auto_1762', 'v_n3_auto_1762', '資料にざっと目を通した。', 'しりょうに ざっと めを とおした。', 'Aku membaca sekilas dokumen itu.'),
('ex_n3_auto_1763', 'v_n3_auto_1763', 'シャワーを浴びてさっぱりした。', 'シャワーを あびて さっぱり した。', 'Aku merasa segar setelah mandi.'),
('ex_n3_auto_1764', 'v_n3_auto_1764', 'もしかすると彼は来ないかもしれない。', 'もしかすると かれは こない かもしれない。', 'Barangkali dia tidak akan datang.'),
('ex_n3_auto_1765', 'v_n3_auto_1765', '食べ物を残すのはもったいない。', 'たべものを のこすのは もったいない。', 'Menyisakan makanan itu mubazir.'),
('ex_n3_auto_1766', 'v_n3_auto_1766', '今年の試験は昨年よりやや難しい。', 'ことしの しけんは さくねんより やや むずかしい。', 'Ujian tahun ini agak lebih sulit dibanding tahun lalu.'),
('ex_n3_auto_1767', 'v_n3_auto_1767', '健康は富より大切だ。', 'けんこうは とみより たいせつだ。', 'Keseimbangan kesehatan lebih penting daripada kekayaan.'),
('ex_n3_auto_1768', 'v_n3_auto_1768', 'わがままな行動で皆に迷惑をかけた。', 'わがままな こうどうで みなに めいわくを かけた。', 'Perilaku egoisnya menyusahkan semua orang.'),
('ex_n3_auto_1769', 'v_n3_auto_1769', 'ことによると明日出発するかもしれない。', 'ことによると あした しゅっぱつする かもしれない。', 'Mungkin saja kami akan berangkat besok.'),
('ex_n3_auto_1770', 'v_n3_auto_1770', '雨が降り出した。そこで傘を買った。', 'あめが フリダシタ。 そこで かさを かった。', 'Hujan mulai turun. Oleh karena itu, aku membeli payung.'),
('ex_n3_auto_1771', 'v_n3_auto_1771', '彼は父親にそっくりだ。', 'かれは ちちおやに そっくりだ。', 'Dia mirip sekali dengan ayahnya.'),
('ex_n3_auto_1772', 'v_n3_auto_1772', '片付けずにそのままにしておいて。', 'かたづけずに そのままに しておいて。', 'Biarkan begitu saja tanpa dibereskan.'),
('ex_n3_auto_1773', 'v_n3_auto_1773', '人にはそれぞれ個性がある。', 'ひとには それぞれ こせいがある。', 'Setiap orang memiliki kepribadian masing-masing.'),
('ex_n3_auto_1774', 'v_n3_auto_1774', 'パンと牛乳、それと卵をください。', 'パンと ぎゅうにゅう、 それと たまごを ください。', 'Tolong roti, susu, dan juga telur.'),
('ex_n3_auto_1775', 'v_n3_auto_1775', '彼は努力した。だが、失敗した。', 'かれは どりょくした。 だが、 しっぱいした。', 'Dia sudah berusaha. Namun, dia gagal.'),
('ex_n3_auto_1776', 'v_n3_auto_1776', '行きたい。だけどお金がない。', 'いきたい。 だけど おかねが ない。', 'Aku ingin pergi. Tetapi aku tidak punya uang.'),
('ex_n3_auto_1777', 'v_n3_auto_1777', '彼の住所はたしかここだったはずだ。', 'かれの じゅうしょは たしか ここだった はずだ。', 'Seingat saya, alamatnya seharusnya di sini.'),
('ex_n3_auto_1778', 'v_n3_auto_1778', 'なぜ行かないの？だって忙しいんだもん。', 'なぜ いかないの？ だって いそがしいんだもん。', 'Kenapa tidak pergi? Habisnya sibuk sih.'),
('ex_n3_auto_1779', 'v_n3_auto_1779', '彼とはたびたび駅で会う。', 'かれとは たびたび えきで あう。', 'Aku sering kali bertemu dengannya di stasiun.'),
('ex_n3_auto_1780', 'v_n3_auto_1780', '暑くてたまらない。', 'あつくて たまらない。', 'Panasnya tidak tertahankan.'),
('ex_n3_auto_1781', 'v_n3_auto_1781', 'そのリンゴを一口ちょうだい。', 'その りんごを ひとくち ちょうだい。', 'Tolong beri aku satu gigit apel itu.'),
('ex_n3_auto_1782', 'v_n3_auto_1782', 'できれば今日中に終わらせたい。', 'できれば きょうじゅうに おわらせたい。', 'Kalau bisa aku ingin menyelesaikannya hari ini.'),
('ex_n3_auto_1783', 'v_n3_auto_1783', 'バスが遅れました。ですから遅刻しました。', 'バスが おくれました。 ですから ちこくしました。', 'Busnya terlambat. Oleh karena itu saya terlambat.'),
('ex_n3_auto_1784', 'v_n3_auto_1784', '新しいメンバーです。どうぞよろしく。', 'あたらしい めんばーです。 どうぞ よろしく。', 'Saya anggota baru. Senang bertemu dengan Anda.'),
('ex_n3_auto_1785', 'v_n3_auto_1785', '鍵をどこかに忘れてしまった。', 'かぎを どこかに わすれて しまった。', 'Aku melupakan kunci di suatu tempat.'),
('ex_n3_auto_1786', 'v_n3_auto_1786', '謙遜して「とんでもない」と答えた。', 'けんそんして 「とんでもない」と こたえた。', 'Dia menjawab "sama sekali tidak" dengan rendah hati.'),
('ex_n3_auto_1787', 'v_n3_auto_1787', 'どんなに難しくても諦めない。', 'どんなに むずかしくても あきらめない。', 'Bagaimanapun sulitnya, aku tidak akan menyerah.'),
('ex_n3_auto_1788', 'v_n3_auto_1788', '今日はなにもしたくない。', 'きょうは なにも したくない。', 'Hari ini aku tidak ingin melakukan apa pun.'),
('ex_n3_auto_1789', 'v_n3_auto_1789', '彼女はにっこり笑って挨拶した。', 'かのじょは にっこり わらって あいさつした。', 'Dia tersenyum ramah lalu menyapa.'),
('ex_n3_auto_1790', 'v_n3_auto_1790', '週末はのんびり過ごしたい。', 'しゅうまつは のんびり すごしたい。', 'Aku ingin menghabiskan akhir pekan dengan santai.'),
('ex_n3_auto_1791', 'v_n3_auto_1791', '紙をはさみできれいに切った。', 'かみを はさみで きれいに きった。', 'Aku memotong kertas dengan rapi menggunakan gunting.'),
('ex_n3_auto_1792', 'v_n3_auto_1792', '街中で古い友人にばったり会った。', 'まちなかで ふるい ゆうじんに ばったり あった。', 'Aku tidak sengaja bertemu teman lama di jalan.'),
('ex_n3_auto_1793', 'v_n3_auto_1793', 'この服はサイズがぴったりだ。', 'この ふくは さいずが ぴったりだ。', 'Ukuran baju ini pas sekali.'),
('ex_n3_auto_1794', 'v_n3_auto_1794', '自転車が電柱にぶつかった。', 'じてんしゃが でんちゅうに ぶつかった。', 'Sepeda menabrak tiang listrik.'),
('ex_n3_auto_1795', 'v_n3_auto_1795', '車を壁にぶつけてしまった。', 'くるまを かべに ぶつけて しまった。', 'Aku tidak sengaja menabrakkan mobil ke dinding.'),
('ex_n3_auto_1796', 'v_n3_auto_1796', 'まあ、なんてきれいな花でしょう。', 'まあ、 なんて きれいな はなでしょう。', 'Ya ampun, alangkah indahnya bunga ini.'),
('ex_n3_auto_1797', 'v_n3_auto_1797', 'これこそがまさに私が探していた本だ。', 'これこそが まさに わたしが さがしていた ほんだ。', 'Buku inilah yang benar-benar kucari.'),
('ex_n3_auto_1798', 'v_n3_auto_1798', '朝の太陽がまぶしい。', 'あさの たいようが まぶしい。', 'Matahari pagi sangat silau.'),
('ex_n3_auto_1799', 'v_n3_auto_1799', '友達と図書館へ行った。', 'ともだちと としょかんへ いった。', 'Aku pergi ke perpustakaan dengan teman.'),
('ex_n3_auto_1800', 'v_n3_auto_1800', '試験が終わってほっとした。', 'しけんが おわって ほっと した。', 'Aku merasa lega setelah ujian selesai.'),
('ex_n3_auto_1801', 'v_n3_auto_1801', '新しい青いジーンズを買った。', 'あたらしい あおい ジーンズを かった。', 'Aku membeli celana jin biru baru.'),
('ex_n3_auto_1802', 'v_n3_auto_1802', '部屋の電気のスイッチを押した。', 'へやの でんきの スイッチを おした。', 'Aku menekan sakelar lampu kamar.'),
('ex_n3_auto_1803', 'v_n3_auto_1803', '温かい野菜スープを作った。', 'あたたかい やさい スープを つくった。', 'Aku membuat sup sayur hangat.'),
('ex_n3_auto_1804', 'v_n3_auto_1804', '冬に湖でスケートをする。', 'ふゆに みずうみで スケートを する。', 'Bermain seluncur es di danau saat musim dingin.'),
('ex_n3_auto_1805', 'v_n3_auto_1805', '彼は映画界の人気スターだ。', 'かれは えいがかいの にんき スターだ。', 'Dia adalah bintang populer di dunia perfilman.'),
('ex_n3_auto_1806', 'v_n3_auto_1806', '彼女はスタイルがとても良い。', 'かのじょは スタイルが とても いい。', 'Dia memiliki bentuk tubuh yang sangat bagus.'),
('ex_n3_auto_1807', 'v_n3_auto_1807', '机の上に電気スタンドを置く。', 'つくえの うえに でんき スタンドを おく。', 'Meletakkan lampu meja di atas meja belajar.'),
('ex_n3_auto_1808', 'v_n3_auto_1808', '大勢の前でスピーチをした。', 'おおぜいの まえで スピーチを した。', 'Aku berpidato di depan banyak orang.'),
('ex_n3_auto_1809', 'v_n3_auto_1809', 'ハンバーガーのセットを注文した。', 'ハンバーガーの セットを ちゅうもんした。', 'Aku memesan paket hamburger set.'),
('ex_n3_auto_1810', 'v_n3_auto_1810', '暑い日はアイスクリームが食べたい。', 'あつい ひは アイスクリームが たべたい。', 'Aku ingin makan es krim di hari yang panas.'),
('ex_n3_auto_1811', 'v_n3_auto_1811', 'ボールがラインの外に出てアウトになった。', 'ボールが ラインの そとに でて アウトに なった。', 'Bola keluar garis dan dinyatakan keluar.'),
('ex_n3_auto_1812', 'v_n3_auto_1812', '家族の写真アルバムを眺める。', 'かぞくの しゃしん アルバムを ながめる。', 'Memandangi album foto keluarga.'),
('ex_n3_auto_1813', 'v_n3_auto_1813', '新しいデザインのイメージを描く。', 'あたらしい デザインの イメージを えがく。', 'Menggambar bayangan desain baru.'),
('ex_n3_auto_1814', 'v_n3_auto_1814', 'プリンターのインクが切れた。', 'プリンターの インクが きれた。', 'Tinta printer habis.'),
('ex_n3_auto_1815', 'v_n3_auto_1815', '有名な作家にインタビューする。', 'ゆうめいな さっかに インタビュー する。', 'Mewawancarai penulis terkenal.'),
('ex_n3_auto_1816', 'v_n3_auto_1816', '彼はロックでウイスキーを飲む。', 'かれは ロックで ウイスキーを のむ。', 'Dia meminum wiski dengan es batu.'),
('ex_n3_auto_1817', 'v_n3_auto_1817', '車のエンジンがかからない。', 'くるまの エンジンが かからない。', 'Mesin mobil tidak mau menyala.'),
('ex_n3_auto_1818', 'v_n3_auto_1818', '東京のオフィスで働いている。', 'とうきょうの オフィスで はたらいている。', 'Aku bekerja di kantor Tokyo.'),
('ex_n3_auto_1819', 'v_n3_auto_1819', 'パトロールカーが通り過ぎた。', 'パトロールカーが とおりすぎた。', 'Mobil patroli lewat.'),
('ex_n3_auto_1820', 'v_n3_auto_1820', 'クレジットカードで支払う。', 'クレジットカードで しはらう。', 'Membayar dengan kartu kredit.'),
('ex_n3_auto_1821', 'v_n3_auto_1821', '彼がサッカーチームのキャプテンだ。', 'かれが サッカーチームの キャプテンだ。', 'Dialah kapten tim sepak bola.'),
('ex_n3_auto_1822', 'v_n3_auto_1822', '勉強するときはクラシックを聴く。', 'べんきょうする ときは クラシックを きく。', 'Mendengarkan musik klasik saat belajar.'),
('ex_n3_auto_1823', 'v_n3_auto_1823', '冷たい水をグラスに注いだ。', 'つめたい みずを グラスに そそいだ。', 'Menuangkan air dingin ke dalam gelas.'),
('ex_n3_auto_1824', 'v_n3_auto_1824', '放課後に学校のグランドで走る。', 'ほうかごに がっこうの グランドで はしる。', 'Berlari di lapangan sekolah setelah pulang sekolah.'),
('ex_n3_auto_1825', 'v_n3_auto_1825', 'ケーキの上に生クリームをのせる。', 'ケーキの うえに なまクリームを のせる。', 'Menaruh krim segar di atas kue.'),
('ex_n3_auto_1826', 'v_n3_auto_1826', '４人のグループで旅行をする。', 'よにんの グループで りょこうを する。', 'Melakukan perjalanan dalam kelompok yang terdiri dari 4 orang.'),
('ex_n3_auto_1827', 'v_n3_auto_1827', '眼鏡をケースに収納した。', 'めがねを ケースに しゅうのうした。', 'Menyimpan kacamata ke dalam kotaknya.'),
('ex_n3_auto_1828', 'v_n3_auto_1828', 'パソコンの電源コードをつなぐ。', 'パソコンの でんげん コードを つなぐ。', 'Menghubungkan kabel daya laptop.'),
('ex_n3_auto_1829', 'v_n3_auto_1829', '契約書にサインをしてください。', 'けいやくしょに サインを してください。', 'Tolong beri tanda tangan pada dokumen kontrak.'),
('ex_n3_auto_1830', 'v_n3_auto_1830', '幼い子がママの元へ走っていく。', 'おさない こが ママの もとへ はしっていく。', 'Anak kecil itu berlari ke arah mamanya.'),
('ex_n3_auto_1831', 'v_n3_auto_1831', '簡単な計算でミスをしてしまった。', 'かんたんな けいさんで ミスを して しまった。', 'Aku membuat kesalahan dalam perhitungan yang mudah.'),
('ex_n3_auto_1832', 'v_n3_auto_1832', 'コーヒーに温かいミルクを入れる。', 'コーヒーに あたたかい ミルクを いれる。', 'Memasukkan susu hangat ke dalam kopi.'),
('ex_n3_auto_1833', 'v_n3_auto_1833', '話の内容を素早くメモした。', 'はなしの ないようを すばやく メモした。', 'Aku mencatat isi pembicaraan dengan cepat.'),
('ex_n3_auto_1834', 'v_n3_auto_1834', '彼もこのチームのメンバーです。', 'かれも この チームの メンバーです。', 'Dia juga merupakan anggota tim ini.'),
('ex_n3_auto_1835', 'v_n3_auto_1835', '彼の話にはいつもユーモアがある。', 'かれの はなしには いつも ユーモアが ある。', 'Ceritanya selalu memiliki rasa humor.'),
('ex_n3_auto_1836', 'v_n3_auto_1836', '大学を卒業したらヨーロッパに行きたい。', 'だいがくを そつぎょうしたら ヨーロッパに いきたい。', 'Aku ingin pergi ke Eropa setelah lulus kuliah.'),
('ex_n3_auto_1837', 'v_n3_auto_1837', '青い海にヨットが浮かんでいる。', 'あおい うみに ヨットが うかんでいる。', 'Kapal pesiar terapung di laut biru.'),
('ex_n3_auto_1838', 'v_n3_auto_1838', 'ライターでタバコに火をつける。', 'ライターで タバコに ひを つける。', 'Menyalakan rokok dengan korek gas.'),
('ex_n3_auto_1839', 'v_n3_auto_1839', 'テニスのラケットを新調した。', 'テニスの ラケットを しんちょうした。', 'Aku membeli raket tenis baru.'),
('ex_n3_auto_1840', 'v_n3_auto_1840', '日本語のレベルが上がってきた。', 'にほんごの レベルが あがってきた。', 'Level bahasa Jepang-ku sudah meningkat.'),
('ex_n3_auto_1841', 'v_n3_auto_1841', 'ロケットが宇宙に向かって打ち上げられた。', 'ロケットが うちゅうに むかって うちあげられた。', 'Roket diluncurkan menuju luar angkasa.'),
('ex_n3_auto_1842', 'v_n3_auto_1842', '美味しい赤ワインで乾杯する。', 'おいしい あかワインで かんぱい する。', 'Bersulang dengan anggur merah yang lezat.'),
('ex_n3_auto_1843', 'v_n3_auto_1843', '給料がアップして嬉しい。', 'きゅうりょうが アップして うれしい。', 'Aku senang karena gajiku naik.'),
('ex_n3_auto_1844', 'v_n3_auto_1844', 'アンケートにご協力ください。', 'アンケートに ごきょうりょく ください。', 'Tolong bantu mengisi kuesioner ini.'),
('ex_n3_auto_1845', 'v_n3_auto_1845', 'スピーチコンテストで優勝した。', 'スピーチ コンテストで ゆうしょうした。', 'Aku menjuarai kontes pidato.'),
('ex_n3_auto_1846', 'v_n3_auto_1846', 'ショッピングセンターへ買い物に行く。', 'ショッピング センターへ かいものに いく。', 'Pergi berbelanja ke pusat perbelanjaan.'),
('ex_n3_auto_1847', 'v_n3_auto_1847', 'リビングのソファーでテレビを見る。', 'リビングの ソファーで テレビを みる。', 'Menonton TV di sofa ruang tamu.'),
('ex_n3_auto_1848', 'v_n3_auto_1848', '昔祖父はタイプライターを使っていた。', 'むかし そふは タイプライターを つかっていた。', 'Dulu kakek menggunakan mesin tik.'),
('ex_n3_auto_1849', 'v_n3_auto_1849', '電車のダイヤが乱れている。', 'でんしゃの ダイヤが みだれている。', 'Jadwal kereta sedang kacau.'),
('ex_n3_auto_1850', 'v_n3_auto_1850', 'お風呂上がりにタオルで体を拭く。', 'おふろあがりに タオルで からだを ふく。', 'Mengeringkan tubuh dengan handuk setelah mandi.'),
('ex_n3_auto_1851', 'v_n3_auto_1851', '放課後にダンスを練習する。', 'ほうかごに ダンスを れんしゅう する。', 'Berlatih menari setelah pulang sekolah.'),
('ex_n3_auto_1852', 'v_n3_auto_1852', 'ピザの上にチーズをたっぷりかける。', 'ピザの うえに チーズを たっぷり かける。', 'Menaburkan banyak keju di atas pizza.'),
('ex_n3_auto_1853', 'v_n3_auto_1853', 'これが留学のいいチャンスだ。', 'これが りゅうがくの いい チャンスだ。', 'Ini adalah kesempatan bagus untuk belajar di luar negeri.'),
('ex_n3_auto_1854', 'v_n3_auto_1854', '週末に彼女とデートする。', 'しゅうまつに かのじょと デート する。', 'Kencan dengan pacar di akhir pekan.'),
('ex_n3_auto_1855', 'v_n3_auto_1855', '駅前で抗議のデモが行われている。', 'えきまえで こうぎの デモが おこなわれている。', 'Demonstrasi protes sedang berlangsung di depan stasiun.'),
('ex_n3_auto_1856', 'v_n3_auto_1856', '山に登ってテントを張った。', 'やまに のぼって テントを はった。', 'Mendaki gunung lalu mendirikan tenda.'),
('ex_n3_auto_1857', 'v_n3_auto_1857', '彼はクラスでトップの成績だ。', 'かれは クラスで トップの せいせきだ。', 'Dia memiliki nilai teratas di kelas.'),
('ex_n3_auto_1858', 'v_n3_auto_1858', '天気がいいのでドライブに行く。', 'てんきが いいので ドライブに いく。', 'Pergi berkendara karena cuacanya bagus.'),
('ex_n3_auto_1859', 'v_n3_auto_1859', '大型のトラックが道路を通る。', 'おおがたの トラックが どうろを とおる。', 'Truk ukuran besar melewati jalanan.'),
('ex_n3_auto_1860', 'v_n3_auto_1860', '友達とトランプで遊んだ。', 'ともだちと トランプで あそんだ。', 'Bermain kartu remi bersama teman-teman.'),
('ex_n3_auto_1861', 'v_n3_auto_1861', '毎日ジムでトレーニングしている。', 'まいにち ジムで トレーニング している。', 'Berlatih di gym setiap hari.'),
('ex_n3_auto_1862', 'v_n3_auto_1862', 'パーティーのために赤いドレスを着た。', 'パーティーの ために あかい ドレスを きた。', 'Memakai gaun merah untuk pesta.'),
('ex_n3_auto_1863', 'v_n3_auto_1863', 'この荷物は重さが３トンある。', 'この にもつは おもさが さんトン ある。', 'Barang ini memiliki berat 3 ton.'),
('ex_n3_auto_1864', 'v_n3_auto_1864', '暗いトンネルを車で通り抜けた。', 'くらい トンネルを くるまで とおりぬけた。', 'Melewati terowongan gelap dengan mobil.'),
('ex_n3_auto_1865', 'v_n3_auto_1865', '嫌ならはっきりとノーと言いなさい。', 'いやなら はっきりと ノーと いいなさい。', 'Katakan tidak dengan jelas jika kamu tidak suka.'),
('ex_n3_auto_1866', 'v_n3_auto_1866', 'ドアを３回ノックした。', 'ドアを さんかい ノックした。', 'Aku mengetuk pintu tiga kali.'),
('ex_n3_auto_1867', 'v_n3_auto_1867', 'スマートフォンの充電が残り１０パーセントだ。', 'スマートフォンの じゅうでんが のこり じゅっパーセントだ。', 'Daya baterai ponsel tersisa 10 persen.'),
('ex_n3_auto_1868', 'v_n3_auto_1868', '彼は子供の頃からバイオリンを習っている。', 'かれは こどもの ころから バイオリンを ならっている。', 'Dia belajar biola sejak kecil.'),
('ex_n3_auto_1869', 'v_n3_auto_1869', '水道のパイプから水が漏れている。', 'すいどうの パイプから みずが もれている。', 'Air bocor dari pipa saluran air.'),
('ex_n3_auto_1870', 'v_n3_auto_1870', '彼の夢は旅客機のパイロットになることだ。', 'かれの ゆめは りょかくきの パイロットに なることだ。', 'Impiannya adalah menjadi pilot pesawat penumpang.'),
('ex_n3_auto_1871', 'v_n3_auto_1871', '試験に合格して次の段階にパスした。', 'しけんに ごうかくして つぎの だんかいに パスした。', 'Lulus ujian dan melaju ke tahap berikutnya.'),
('ex_n3_auto_1872', 'v_n3_auto_1872', '買い物袋として大きなバッグを持つ。', 'かいものぶくろとして おおきな バッグを もつ。', 'Membawa tas besar untuk kantong belanja.'),
('ex_n3_auto_1873', 'v_n3_auto_1873', '仕事とプライベートのバランスを取る。', 'しごとと プライベートの バランスを とる。', 'Menjaga keseimbangan antara pekerjaan dan kehidupan pribadi.'),
('ex_n3_auto_1874', 'v_n3_auto_1874', '彼はハンサムで性格もいい。', 'かれは ハンサムで せいかくも いい。', 'Dia tampan dan kepribadiannya juga baik.'),
('ex_n3_auto_1875', 'v_n3_auto_1875', '週末に家族と公園へピクニックに行く。', 'しゅうまつに かぞくと こうえんへ ピクニックに いく。', 'Pergi piknik ke taman bersama keluarga di akhir pekan.'),
('ex_n3_auto_1876', 'v_n3_auto_1876', '子供の運動会のビデオを撮った。', 'こどもの うんどうかいの ビデオを とった。', 'Aku merekam video festival olahraga anak-anak.'),
('ex_n3_auto_1877', 'v_n3_auto_1877', '髪をピンで留める。', 'かみを ピンで とめる。', 'Menjepit rambut dengan pin.'),
('ex_n3_auto_1878', 'v_n3_auto_1878', 'この経験は将来のプラスになる。', 'この けいけんは しょうらいの プラスに なる。', 'Pengalaman ini akan menjadi keuntungan bagi masa depan.'),
('ex_n3_auto_1879', 'v_n3_auto_1879', 'この容器はプラスチック製です。', 'この ようきは プラスチックせい です。', 'Wadah ini terbuat dari plastik.'),
('ex_n3_auto_1880', 'v_n3_auto_1880', '週末の旅行プランを立てる。', 'しゅうまつの りょこう プランを たてる。', 'Membuat rencana perjalanan untuk akhir pekan.'),
('ex_n3_auto_1881', 'v_n3_auto_1881', '危ないと思って急ブレーキをかけた。', 'あぶないと おもって きゅう ブレーキを かけた。', 'Aku merasa bahaya lalu menginjak rem mendadak.'),
('ex_n3_auto_1882', 'v_n3_auto_1882', '彼はプロのカメラマンだ。', 'かれは プロの カメラマンだ。', 'Dia adalah fotografer profesional.'),
('ex_n3_auto_1883', 'v_n3_auto_1883', '新しい革のベルトを購入した。', 'あたらしい かわの ベルトを こうにゅうした。', 'Aku membeli ikat pinggang kulit yang baru.'),
('ex_n3_auto_1884', 'v_n3_auto_1884', '壁に白いペンキを塗った。', 'かべに しろい ペンキを ぬった。', 'Mengecat dinding dengan cat putih.'),
('ex_n3_auto_1885', 'v_n3_auto_1885', '公園のベンチに座って本を読む。', 'こうえんの ベンチに すわって ほんを よむ。', 'Duduk di bangku taman sambil membaca buku.'),
('ex_n3_auto_1886', 'v_n3_auto_1886', 'ホテルのボーイに荷物を預けた。', 'ホテルの ボーイに にもつを あずけた。', 'Menyerahkan barang bawaan kepada pelayan hotel.'),
('ex_n3_auto_1887', 'v_n3_auto_1887', '公園の池でボートを漕いだ。', 'こうえんの いけで ボートを こいだ。', 'Mendayung perahu di kolam taman.'),
('ex_n3_auto_1888', 'v_n3_auto_1888', '電車の到着をホームで待つ。', 'でんしゃの とうちゃくを ホームで まつ。', 'Menunggu kedatangan kereta di peron.'),
('ex_n3_auto_1889', 'v_n3_auto_1889', '子供たちがボールを投げて遊んでいる。', 'こどもたちが ボールを なげて あそんでいる。', 'Anak-anak sedang bermain dengan melempar bola.'),
('ex_n3_auto_1890', 'v_n3_auto_1890', '地元のスーパーマーケットで野菜を買う。', 'じもとの スーパーマーケットで やさいを かう。', 'Membeli sayur di supermarket lokal.'),
('ex_n3_auto_1891', 'v_n3_auto_1891', '司会者がマイクを持って話し始めた。', 'しかいしゃが マイクを もって はなしはじめた。', 'Pembawa acara mulai berbicara menggunakan mikrofon.'),
('ex_n3_auto_1892', 'v_n3_auto_1892', '今朝の気温はマイナス３度だった。', 'けさの きおんは マイナス さんど だった。', 'Suhu udara pagi ini adalah minus 3 derajat.'),
('ex_n3_auto_1893', 'v_n3_auto_1893', '英語の技術をマスターした。', 'えいごの ぎじゅつを マスター した。', 'Menguasai keterampilan bahasa Inggris.'),
('ex_n3_auto_1894', 'v_n3_auto_1894', 'テストの結果を聞いてショックを受けた。', 'テストの けっかを きいて ショックを うけた。', 'Aku syok setelah mendengar hasil ujian.'),
('ex_n3_auto_1895', 'v_n3_auto_1895', '運動をしてストレスを解消する。', 'うんどうを して ストレスを かいしょう する。', 'Berolahraga untuk menghilangkan stres.'),
('ex_n3_auto_1896', 'v_n3_auto_1896', 'この小説のタイトルは何ですか。', 'この しょうせつの タイトルは なん ですか。', 'Apa judul dari novel ini?'),
('ex_n3_auto_1897', 'v_n3_auto_1897', '風邪をひいてダウンしてしまった。', 'かぜを ひいて ダウン して しまった。', 'Aku pingsan karena terserang flu.'),
('ex_n3_auto_1898', 'v_n3_auto_1898', '授業開始のチャイムが鳴った。', 'じゅぎょう かいしの チャイムが なった。', 'Bel tanda dimulainya pelajaran berbunyi.'),
('ex_n3_auto_1899', 'v_n3_auto_1899', 'この洋服のデザインが気に入った。', 'この ようふくの デザインが きにいった。', 'Aku menyukai desain baju barat ini.'),
('ex_n3_auto_1900', 'v_n3_auto_1900', 'その事件はマスコミで大きく報道された。', 'その じけんは マスコミで おおきく ほうどう された。', 'Kasus itu diberitakan secara besar-besaran di media massa.'),
('ex_n3_auto_1901', 'v_n3_auto_1901', '肩のマッサージをしてもらった。', 'かたの マッサージを してもらった。', 'Pundakku dipijat oleh seseorang.'),
('ex_n3_auto_1902', 'v_n3_auto_1902', '友達からお祝いのメッセージが届いた。', 'ともだちから おいわいの メッセージが とどいた。', 'Pesan ucapan selamat dari teman telah tiba.'),
('ex_n3_auto_1903', 'v_n3_auto_1903', 'ボトルに貼ってあるラベルをはがす。', 'ボトルに はって ある ラベルを はがす。', 'Melepas label yang tertempel pada botol.'),
('ex_n3_auto_1904', 'v_n3_auto_1904', 'ゲームのルールを説明します。', 'ゲームの ルールを せつめい します。', 'Saya akan menjelaskan aturan permainan ini.'),
('ex_n3_auto_1905', 'v_n3_auto_1905', '茶道の作法を学ぶ。', 'さどうの さほうを まなぶ。', 'Mempelajari tata krama upacara minum teh.'),
('ex_n3_auto_1906', 'v_n3_auto_1906', '世界には様々な文化がある。', 'せかいには さまざまな ぶんかがある。', 'Di dunia ini terdapat berbagai macam budaya.'),
('ex_n3_auto_1907', 'v_n3_auto_1907', '熱いお茶を少し冷ましてから飲む。', 'あつい おちゃを すこし さましてから のむ。', 'Meminum teh panas setelah mendinginkannya sedikit.'),
('ex_n3_auto_1908', 'v_n3_auto_1908', 'スープが冷める前に食べてください。', 'スープが さめる まえに たべて ください。', 'Tolong makan supnya sebelum menjadi dingin.'),
('ex_n3_auto_1909', 'v_n3_auto_1909', '道路を渡る時は左右を確認してください。', 'どうろを わたる ときは さゆうを かくにん してください。', 'Tolong periksa kiri dan kanan saat menyeberang jalan.'),
('ex_n3_auto_1910', 'v_n3_auto_1910', '夕食の後で皿を洗った。', 'ゆうしょくの あとで さらを あらった。', 'Aku mencuci piring setelah makan malam.'),
('ex_n3_auto_1911', 'v_n3_auto_1911', '台風が去って青空が広がった。', 'たいふうが さって あおぞらが ひろがった。', 'Topan telah pergi dan langit biru membentang luas.'),
('ex_n3_auto_1912', 'v_n3_auto_1912', '外で大きな騒ぎが聞こえる。', 'そとで おおきな さわぎが きこえる。', 'Terdengar keributan besar di luar.'),
('ex_n3_auto_1913', 'v_n3_auto_1913', '先輩の意見を参考にする。', 'せんぱいの いけんを さんこうに する。', 'Menjadikan pendapat senior sebagai referensi.'),
('ex_n3_auto_1914', 'v_n3_auto_1914', '彼の提案に全員が賛成した。', 'かれの ていあんに ぜんいんが さんせい した。', 'Semua orang setuju dengan usulannya.'),
('ex_n3_auto_1915', 'v_n3_auto_1915', '人間は酸素がなければ生きられない。', 'にんげんは さんそが なければ いきられない。', 'Manusia tidak bisa hidup tanpa oksigen.'),
('ex_n3_auto_1916', 'v_n3_auto_1916', '家族みんなが健康で幸せだ。', 'かぞく みんなが けんこうで しあわせだ。', 'Seluruh keluarga sehat dan bahagia.'),
('ex_n3_auto_1917', 'v_n3_auto_1917', 'ジェット機が空を速く飛んでいった。', 'ジェットきが そらを はやく とんでいった。', 'Pesawat jet terbang cepat melewati langit.'),
('ex_n3_auto_1918', 'v_n3_auto_1918', '四角い箱にプレゼントを入れる。', 'しかくい はこに プレゼントを いれる。', 'Memasukkan hadiah ke dalam kotak segi empat.'),
('ex_n3_auto_1919', 'v_n3_auto_1919', '本人から直に理由を聞きたい。', 'ほんにんから じかに りゆうを ききたい。', 'Aku ingin mendengar alasannya langsung dari orang yang bersangkutan.'),
('ex_n3_auto_1920', 'v_n3_auto_1920', '日本には美しい四季がある。', 'にほんには うつくしい しきがある。', 'Jepang memiliki empat musim yang indah.'),
('ex_n3_auto_1921', 'v_n3_auto_1921', '雨が止んで、直に晴れるだろう。', 'あめが やんで、 じきに はれるだろう。', 'Hujan reda, dan akan segera cerah.'),
('ex_n3_auto_1922', 'v_n3_auto_1922', '会社から交通費が支給される。', 'かいしゃから こうつうひが しきゅう される。', 'Biaya transportasi dibayarkan oleh perusahaan.'),
('ex_n3_auto_1923', 'v_n3_auto_1923', 'この映画は子供には刺激が強すぎる。', 'この えいがは こどもには しげきが つよすぎる。', 'Film ini rangsangannya terlalu kuat untuk anak-anak.'),
('ex_n3_auto_1924', 'v_n3_auto_1924', '自殺を防ぐための相談窓口がある。', 'じさつを ふせぐ ための そうだん まどぐちが ある。', 'Ada layanan konsultasi untuk mencegah bunuh diri.'),
('ex_n3_auto_1925', 'v_n3_auto_1925', '彼には彼なりの事情がある。', 'かれには かれなりの じじょうが ある。', 'Dia memiliki keadaannya sendiri.'),
('ex_n3_auto_1926', 'v_n3_auto_1926', '彼は有名なロマン派の詩人だ。', 'かれは ゆうめいな ロマンはの しじんだ。', 'Dia adalah penyair aliran romantis yang terkenal.'),
('ex_n3_auto_1927', 'v_n3_auto_1927', '太陽が地平線に沈んでいく。', 'たいようが ちへいせんに しずんでいく。', 'Matahari terbenam di garis cakrawala.'),
('ex_n3_auto_1928', 'v_n3_auto_1928', '彼の思想は多くの人に影響を与えた。', 'かれの しそうは おおくの ひとに えいきょうを あたえた。', 'Pemikirannya memberikan pengaruh kepada banyak orang.'),
('ex_n3_auto_1929', 'v_n3_auto_1929', '熱いスープで舌を火傷した。', 'あつい スープで したを やけどした。', 'Lidahku terbakar karena sup yang panas.'),
('ex_n3_auto_1930', 'v_n3_auto_1930', '準備ができ次第、出発します。', 'じゅんびが でき しだい、 しゅっぱつ します。', 'Segera setelah persiapan selesai, kita akan berangkat.'),
('ex_n3_auto_1931', 'v_n3_auto_1931', '量より質を重視する。', 'りょうより しつを じゅうし する。', 'Mengutamakan kualitas daripada kuantitas.'),
('ex_n3_auto_1932', 'v_n3_auto_1932', '工場が閉鎖され、多くの人が失業した。', 'こうじょうが へいさ され、 おおくにの ひとが しつぎょう した。', 'Pabrik ditutup, dan banyak orang menjadi pengangguran.'),
('ex_n3_auto_1933', 'v_n3_auto_1933', '梅雨の時期は湿気が多い。', 'つゆの じきは しっけが おおい。', 'Saat musim hujan kelembapannya tinggi.'),
('ex_n3_auto_1934', 'v_n3_auto_1934', '計画をすぐに実行に移す。', 'けいかくを すぐに じっこうに うつす。', 'Segera memindahkan rencana ke dalam tindakan nyata.'),
('ex_n3_auto_1935', 'v_n3_auto_1935', '実際に見てみないと信じられない。', 'じっさいに みて みないと しんじられない。', 'Aku tidak bisa mempercayainya sebelum melihatnya secara langsung.'),
('ex_n3_auto_1936', 'v_n3_auto_1936', '試合で自分の実力を十分に発揮した。', 'しあいで じぶんの じつりょくを じゅうぶんに はっき した。', 'Aku benar-benar mengerahkan kemampuan asliku dalam pertandingan.'),
('ex_n3_auto_1937', 'v_n3_auto_1937', '大阪の支店に異動になりました。', 'おおさかの してんに いどうに なりました。', 'Saya dipindahkan ke kantor cabang Osaka.'),
('ex_n3_auto_1938', 'v_n3_auto_1938', '先生の指導の下で研究を行う。', 'せんせいの しどうの もとで けんきゅうを おこなう。', 'Melakukan penelitian di bawah bimbingan guru.'),
('ex_n3_auto_1939', 'v_n3_auto_1939', 'このドアは自動で開閉します。', 'この ドアは じどうで かいへい します。', 'Pintu ini membuka dan menutup secara otomatis.'),
('ex_n3_auto_1940', 'v_n3_auto_1940', 'デパートには多くの品が並んでいる。', 'デパートには おおくの しなが ならんでいる。', 'Banyak barang yang berjejer di dalam toserba.'),
('ex_n3_auto_1941', 'v_n3_auto_1941', '感情に支配されてはいけない。', 'かんじょうに しはい されては いけない。', 'Tidak boleh dikendalikan oleh emosi.'),
('ex_n3_auto_1942', 'v_n3_auto_1942', '彼の芝居はとても感動的だった。', 'かれの しばいは とても かんどうてき だった。', 'Pertunjukan sandiwaranya sangat mengharukan.'),
('ex_n3_auto_1943', 'v_n3_auto_1943', '公園の芝生の上で寝転ぶ。', 'こうえんの しばふの うえで ねころぶ。', 'Berbaring di atas halaman rumput taman.'),
('ex_n3_auto_1944', 'v_n3_auto_1944', 'お支払いは現金ですか、カードですか。', 'おしはらいは げんきんですか、 カードですか。', 'Apakah pembayarannya tunai atau kartu?'),
('ex_n3_auto_1945', 'v_n3_auto_1945', 'レジで料金を支払った。', 'レジで りょうきんを しはらった。', 'Aku membayar biayanya di kasir.'),
('ex_n3_auto_1946', 'v_n3_auto_1946', '事故による死亡者数はゼロだった。', 'じこによる しぼうしゃすうは ゼロだった。', 'Jumlah korban wafat akibat kecelakaan adalah nol.'),
('ex_n3_auto_1947', 'v_n3_auto_1947', '会社を設立するために資本を集める。', 'かいしゃを せつりつ する ために しほんを あつめる。', 'Mengumpulkan modal untuk mendirikan perusahaan.'),
('ex_n3_auto_1948', 'v_n3_auto_1948', '彼女たちは顔がよく似ている姉妹だ。', 'かのじょたちは かおが よく にている しまいだ。', 'Mereka adalah bersaudari yang wajahnya sangat mirip.'),
('ex_n3_auto_1949', 'v_n3_auto_1949', '彼はいつも自分の子供の自慢ばかりしている。', 'かれは いつも じぶんの こどもの じまんばかり している。', 'Dia selalu saja membanggakan anaknya sendiri.'),
('ex_n3_auto_1950', 'v_n3_auto_1950', '川の下流には美しい町がある。', 'かわの かりゅうには うつくしい まちがある。', 'Di hilir sungai terdapat kota yang indah.'),
('ex_n3_auto_1951', 'v_n3_auto_1951', '今週は仕事がとても忙しい。', 'こんしゅうは しごとが とても いそがしい。', 'Minggu ini pekerjaan sangat sibuk.'),
('ex_n3_auto_1952', 'v_n3_auto_1952', '犯人は銃を警察に向けて撃った。', 'はんにんは じゅうを けいさつに むけて うった。', 'Pelaku menembakkan senapan ke arah polisi.'),
('ex_n3_auto_1953', 'v_n3_auto_1953', '周囲の状況をよく確認する。', 'しゅういの じょうきょうを よく かくにん する。', 'Memeriksa situasi sekeliling dengan baik.'),
('ex_n3_auto_1954', 'v_n3_auto_1954', '秋は米の収穫の時期です。', 'あきは こめの しゅうかくの じきです。', 'Musim gugur adalah waktu panen padi.'),
('ex_n3_auto_1955', 'v_n3_auto_1955', '日本には様々な宗教が存在する。', 'にほんには さまざまな しゅうきょうが そんざい する。', 'Di Jepang terdapat berbagai macam agama.'),
('ex_n3_auto_1956', 'v_n3_auto_1956', 'わが社では経験を重視して採用する。', 'わがしゃでは けいけんを じゅうし して さいよう する。', 'Perusahaan kami merekrut dengan mementingkan pengalaman.'),
('ex_n3_auto_1957', 'v_n3_auto_1957', '計画の間違いを修正した。', 'けいかくの まちがいを しゅうせい した。', 'Aku merevisi kesalahan dalam rencana.'),
('ex_n3_auto_1958', 'v_n3_auto_1958', 'これは会社にとって重大な問題だ。', 'これは かいしゃにとって じゅうだいな もんだいだ。', 'Ini adalah masalah yang serius bagi perusahaan.'),
('ex_n3_auto_1959', 'v_n3_auto_1959', '駅の近くに新しい住宅が建てられた。', 'えきの ちかくに あたらしい じゅうたくが たてられた。', 'Perumahan baru dibangun di dekat stasiun.'),
('ex_n3_auto_1960', 'v_n3_auto_1960', '子供たちが集団で登校している。', 'こどもたちが しゅうだんで とうこう している。', 'Anak-anak pergi ke sekolah dalam kelompok.'),
('ex_n3_auto_1961', 'v_n3_auto_1961', '雑音が多くて勉強に集中できない。', 'ざつおんが おおくて べんきょうに しゅうちゅう できない。', 'Banyak suara bising sehingga aku tidak bisa konsentrasi belajar.'),
('ex_n3_auto_1962', 'v_n3_auto_1962', '彼は民主主義の理念を支持している。', 'かれは みんしゅしゅぎの りねんを しじ している。', 'Dia mendukung ideologi demokrasi.'),
('ex_n3_auto_1963', 'v_n3_auto_1963', '京都のホテルに３泊宿泊する。', 'きょうとの ホテルに さんぱく しゅくはく する。', 'Menginap selama 3 malam di hotel Kyoto.'),
('ex_n3_auto_1964', 'v_n3_auto_1964', '日本の首相が外国を訪問した。', 'にほんの しゅしょうが がいこくを ほうもん した。', 'Perdana menteri Jepang mengunjungi negara asing.'),
('ex_n3_auto_1965', 'v_n3_auto_1965', '目的を達成するためにあらゆる手段を用いる。', 'もくてきを たっせい する ために あらゆる しゅだんを もちいる。', 'Menggunakan segala cara untuk mencapai tujuan.'),
('ex_n3_auto_1966', 'v_n3_auto_1966', '彼はオリンピックに出場することが決まった。', 'かれは オリンピックに しゅつじょう することが きまった。', 'Dia diputuskan akan berpartisipasi dalam Olimpiade.'),
('ex_n3_auto_1967', 'v_n3_auto_1967', '私はインドネシアのジャカルタ出身です。', 'わたしは インドネシアの ジャカルタ しゅっしん です。', 'Saya berasal dari Jakarta, Indonesia.'),
('ex_n3_auto_1968', 'v_n3_auto_1968', '来月、彼の新しい小説が出版される。', 'らいげつ、 かれの あたらしい しょうせつが しゅっぱん される。', 'Novel barunya akan diterbitkan bulan depan.'),
('ex_n3_auto_1969', 'v_n3_auto_1969', '日本の首都は東京です。', 'にほんの しゅとは とうきょう です。', 'Ibu kota Jepang adalah Tokyo.'),
('ex_n3_auto_1970', 'v_n3_auto_1970', '彼女は主婦として毎日忙しく働いている。', 'かのjoは しゅふとして まいにち いそがしく はたらいている。', 'Dia bekerja sibuk setiap hari sebagai ibu rumah tangga.'),
('ex_n3_auto_1971', 'v_n3_auto_1971', 'これがこの都市の主要な産業です。', 'これが この としの しゅような さんぎょう です。', 'Inilah industri utama dari kota ini.'),
('ex_n3_auto_1972', 'v_n3_auto_1972', '店にはたくさんの種類の果物がある。', 'みせには たくさんの しゅるいの くだものがある。', 'Di toko ada banyak jenis buah-buahan.'),
('ex_n3_auto_1973', 'v_n3_auto_1973', '背の高い順に並んでください。', 'せの たかい じゅんに ならんで ください。', 'Tolong berbaris berdasarkan urutan tinggi badan.'),
('ex_n3_auto_1974', 'v_n3_auto_1974', 'その瞬間、電気が消えた。', 'その しゅんかん、 でんきが きえた。', 'Pada saat itu juga, lampu padam.'),
('ex_n3_auto_1975', 'v_n3_auto_1975', '仕事はすべて順調に進んでいます。', 'しごとは すべて じゅんちょうに すすんでいます。', 'Pekerjaan semuanya berjalan dengan lancar.'),
('ex_n3_auto_1976', 'v_n3_auto_1976', 'この部屋は会議のために使用されています。', 'この へやは かいぎの ために しよう されています。', 'Ruangan ini sedang digunakan untuk rapat.'),
('ex_n3_auto_1977', 'v_n3_auto_1977', '小サイズの商品を注文する。', 'しょうサイズの しょうひんを ちゅうもん する。', 'Memesan produk dengan ukuran kecil.'),
('ex_n3_auto_1978', 'v_n3_auto_1978', '歴史上、これは非常に珍しい事件だ。', 'れきしじょう、 これは ひじょうに めずらしい じけんだ。', 'Secara sejarah, ini adalah kasus yang sangat langka.'),
('ex_n3_auto_1979', 'v_n3_auto_1979', 'どんな障害も乗り越えてみせる。', 'どんな しょうがいも のりこえて みせる。', 'Aku akan menunjukkan bisa melewati rintangan apa pun.'),
('ex_n3_auto_1980', 'v_n3_auto_1980', '電車の乗客が全員降りた。', 'でんしゃの じょうきゃくが ぜんいん おりた。', 'Semua penumpang kereta telah turun.'),
('ex_n3_auto_1981', 'v_n3_auto_1981', '正午にチャイムが鳴り響く。', 'しょうごに チャイムが なりひびく。', 'Bel berbunyi keras di tengah hari.'),
('ex_n3_auto_1982', 'v_n3_auto_1982', '挨拶をすることは社会人の常識だ。', 'あいさつを することは しゃかいじんの じょうしきだ。', 'Menyapa adalah hal yang wajar bagi anggota masyarakat.'),
('ex_n3_auto_1983', 'v_n3_auto_1983', '赤い帽子をかぶった少女を見かけた。', 'あかい ぼうしを かぶった しょうじょを みかけた。', 'Aku melihat seorang anak perempuan yang memakai topi merah.'),
('ex_n3_auto_1984', 'v_n3_auto_1984', '恐れ入りますが、少々お待ちください。', 'おそれいりますが、 しょうしょう おまち ください。', 'Mohon maaf, tolong tunggu sebentar.'),
('ex_n3_auto_1985', 'v_n3_auto_1985', '二人の間に誤解が生じた。', 'ふたりの あいだに ごかいが しょうじた。', 'Telah timbul kesalahpahaman di antara mereka berdua.'),
('ex_n3_auto_1986', 'v_n3_auto_1986', 'パソコンの動作状態を確認する。', 'パソコンの どうさ じょうたいを かくにん する。', 'Memeriksa kondisi pengoperasian laptop.'),
('ex_n3_auto_1987', 'v_n3_auto_1987', '日本語が上達して嬉しい。', 'にほんごが じょうたつ して うれしい。', 'Aku senang karena bahasa Jepang-ku meningkat.'),
('ex_n3_auto_1988', 'v_n3_auto_1988', '彼はよく面白い冗談を言う。', 'かれは よく おもしろい じょうだんを いう。', 'Dia sering mengucapkan candaan yang menarik.'),
('ex_n3_auto_1989', 'v_n3_auto_1989', 'これは上等なワインですね。', 'これは じょうとうな ワイン ですね。', 'Ini adalah anggur kelas atas ya.'),
('ex_n3_auto_1990', 'v_n3_auto_1990', '車と自転車が衝突した。', 'くるまと じてんしゃが しょうとつ した。', 'Mobil dan sepeda bertabrakan.'),
('ex_n3_auto_1991', 'v_n3_auto_1991', '少年たちは公園でサッカーをしている。', 'しょうねんたちは こうえんで サッカーを している。', 'Anak-anak laki-laki sedang bermain bola di taman.'),
('ex_n3_auto_1992', 'v_n3_auto_1992', '彼は新しい商売を始めた。', 'かれは あたらしい しょうばいを はじめた。', 'Dia memulai bisnis dagang yang baru.'),
('ex_n3_auto_1993', 'v_n3_auto_1993', 'この商品は非常に人気があります。', 'この しょうひんは ひじょうに にんきが あります。', 'Produk ini memiliki kepopuleran yang sangat tinggi.'),
('ex_n3_auto_1994', 'v_n3_auto_1994', '火災が発生し、消防車が出動した。', 'かさいが はっせい し、 しょうぼうしゃが しゅつどう した。', 'Kebakaran terjadi, dan mobil pemadam kebakaran dikerahkan.'),
('ex_n3_auto_1995', 'v_n3_auto_1995', '詳しい説明は省略します。', 'くわしい せつめいは しょうりゃく します。', 'Penjelasan detailnya akan disingkat.'),
('ex_n3_auto_1996', 'v_n3_auto_1996', 'イギリスの女王がスピーチを行った。', 'イギリスの じょおうが スピーチを おこなった。', 'Ratu Inggris menyampaikan pidato.'),
('ex_n3_auto_1997', 'v_n3_auto_1997', '卒業後、新しい職を探す。', 'そつぎょうご、 あたらしい しょくを さがす。', 'Mencari pekerjaan baru setelah lulus kuliah.'),
('ex_n3_auto_1998', 'v_n3_auto_1998', '家族で食卓を囲んで夕食を食べる。', 'かぞくで しょくたくを かこんで ゆうしょくを たべる。', 'Keluarga berkumpul mengelilingi meja makan untuk makan malam.'),
('ex_n3_auto_1999', 'v_n3_auto_1999', '健康食品に関心を持つ。', 'けんこう しょくひんに かんしんを もつ。', 'Memiliki minat pada produk makanan kesehatan.'),
('ex_n3_auto_2000', 'v_n3_auto_2000', '鳥はいろいろな食物を食べる。', 'とりは いろいろな しょくもつを たべる。', 'Burung memakan berbagai macam makanan.'),
('ex_n3_auto_2001', 'v_n3_auto_2001', '被災地に食料を支援する。', 'ひさいちに しょくりょうを しえん する。', 'Menyumbang bahan pangan ke daerah bencana.'),
('ex_n3_auto_2002', 'v_n3_auto_2002', '父は書斎にこもって本を読んでいる。', 'ちちは しょさいに こもって ほんを よんでいる。', 'Ayah sedang membaca buku mengurung diri di ruang belajar.'),
('ex_n3_auto_2003', 'v_n3_auto_2003', '女子学生の割合が増えている。', 'じょしがくせいの わりあいが ふえている。', 'Rasio siswa perempuan sedang bertambah.'),
('ex_n3_auto_2004', 'v_n3_auto_2004', '教授の助手を務めている。', 'きょうじゅの じょしゅを つとめている。', 'Menjabat sebagai asisten profesor.'),
('ex_n3_auto_2005', 'v_n3_auto_2005', '反対運動の署名を集める。', 'はんたいうんどうの しょめいを あつめる。', 'Mengumpulkan tanda tangan untuk gerakan penolakan.'),
('ex_n3_auto_2006', 'v_n3_auto_2006', '古い書物から歴史を学ぶ。', 'ふるい しょもつから れきしを まなぶ。', 'Mempelajari sejarah dari buku kuno.'),
('ex_n3_auto_2007', 'v_n3_auto_2007', '彼女は世界的に有名な女優だ。', 'かのじょは せかいてきに ゆうめいな じょゆうだ。', 'Dia adalah aktris yang terkenal secara global.'),
('ex_n3_auto_2008', 'v_n3_auto_2008', '大量のゴミを処理する。', 'たいりょうの ゴミを しょり する。', 'Mengolah sampah dalam jumlah besar.'),
('ex_n3_auto_2009', 'v_n3_auto_2009', '机の上に書類を整理する。', 'つくえの うえに しょるいを せいり する。', 'Merapikan berkas-berkas dokumen di atas meja.'),
('ex_n3_auto_2010', 'v_n3_auto_2010', '合格の知らせが届いて安心した。', 'ごうかくの しらせが とどいて あんしん した。', 'Aku merasa lega karena kabar kelulusan telah tiba.'),
('ex_n3_auto_2011', 'v_n3_auto_2011', '転んで尻を強く打った。', 'ころんで しりを つよく うった。', 'Aku jatuh dan membenturkan pantat dengan keras.'),
('ex_n3_auto_2012', 'v_n3_auto_2012', '彼とは仕事の知合いです。', 'かれとは しごとの しりあい です。', 'Saya kenalan dengannya dalam pekerjaan.'),
('ex_n3_auto_2013', 'v_n3_auto_2013', 'カレンダーに予定の印をつける。', 'カレンダーに よていの しるしを つける。', 'Memberikan tanda jadwal pada kalender.'),
('ex_n3_auto_2014', 'v_n3_auto_2014', '姫路城は日本で有名な城だ。', 'ひめじじょうは にほんで ゆうめいな しろだ。', 'Kastel Himeji adalah kastel yang terkenal di Jepang.'),
('ex_n3_auto_2015', 'v_n3_auto_2015', '高校を卒業して大学に進学する。', 'こうこうを そつぎょう して だいがくに しんがく する。', 'Lulus dari SMA dan melanjutkan sekolah ke universitas.'),
('ex_n3_auto_2016', 'v_n3_auto_2016', '彼の発言は私の神経を逆なでした。', 'かれの はつげんは わたしの しんけいを さかなでした。', 'Pernyataan dia membuat saraf kepekaanku terganggu.'),
('ex_n3_auto_2017', 'v_n3_auto_2017', '信号が赤から緑に変わった。', 'しんごうが あかから みどりに かわった。', 'Lampu lalu lintas berubah dari merah menjadi hijau.'),
('ex_n3_auto_2018', 'v_n3_auto_2018', '病院で医師の診察を受ける。', 'びょういんで いしの しんさつを うける。', 'Menerima pemeriksaan dokter di rumah sakit.'),
('ex_n3_auto_2019', 'v_n3_auto_2019', '私たちは人種に関わらず皆平等だ。', 'わたしたちは じんしゅに かかわらず みな びょうどうだ。', 'Kita semua setara tanpa memandang ras.'),
('ex_n3_auto_2020', 'v_n3_auto_2020', '人生には多くの困難がある。', 'じんせいには おおくの こんなんがある。', 'Dalam kehidupan terdapat banyak kesulitan.'),
('ex_n3_auto_2021', 'v_n3_auto_2021', 'お正月に親戚が集まった。', 'おしょうがつに しんせきが あつまった。', 'Kerabat berkumpul pada tahun baru.'),
('ex_n3_auto_2022', 'v_n3_auto_2022', '緊張して心臓が激しく波打った。', 'きんちょうして しんぞうが はげしく なみうった。', 'Aku gugup dan jantungku berdegup kencang.'),
('ex_n3_auto_2023', 'v_n3_auto_2023', '規則正しい生活は身体に良い。', 'きそくただしい せいかつは しんたいに いい。', 'Kehidupan yang teratur baik bagi tubuh.'),
('ex_n3_auto_2024', 'v_n3_auto_2024', '審判の判定に従わなければならない。', 'しんぱんの はんていに したがわなければ ならない。', 'Harus mematuhi keputusan wasit.'),
('ex_n3_auto_2025', 'v_n3_auto_2025', '彼は歴史上の重要な人物です。', 'かれは れきしじょうの じゅうような じんぶつ です。', 'Dia adalah tokoh penting dalam sejarah.'),
('ex_n3_auto_2026', 'v_n3_auto_2026', 'しまった、電車のドアが閉まってしまった。', 'しまった、 でんしゃの ドアが しまって しまった。', 'Aduh, pintu kereta sudah terlanjur tertutup.'),
('ex_n3_auto_2027', 'v_n3_auto_2027', 'すみません、この近くに駅はありますか。', 'すみません、 この ちかくに えきは ありますか。', 'Permisi, apakah di dekat sini ada stasiun?'),
('ex_n3_auto_2028', 'v_n3_auto_2028', 'はじめまして、どうぞよろしくお願いします。', 'はじめまして、 どうぞ よろしく おねがい します。', 'Perkenalkan, mohon bantuannya.'),
('ex_n3_auto_2029', 'v_n3_auto_2029', 'はあ、今日も一日忙しかった。', 'はあ、 きょうも いちにち いそがしかった。', 'Haa, hari ini pun sibuk sepanjang hari.'),
('ex_n3_auto_2030', 'v_n3_auto_2030', '彼は私の高校時代からの親友だ。', 'かれは わたしの こうこう じだいからの しんゆうだ。', 'Dia adalah sahabatku sejak masa SMA.'),
('ex_n3_auto_2031', 'v_n3_auto_2031', '犯罪者の心理を分析する。', 'はんざいしゃの しんりを ぶんせき する。', 'Menganalisis keadaan psikologis pelaku kejahatan.'),
('ex_n3_auto_2032', 'v_n3_auto_2032', '科学の発展は人類の未来を支える。', 'かがくの はってんは じんるいの みらいを ささえる。', 'Perkembangan sains menopang masa depan umat manusia.'),
('ex_n3_auto_2033', 'v_n3_auto_2033', '鳥が木の上に巣を作っている。', 'とりが きの うえに すを つくっている。', 'Burung sedang membuat sarang di atas pohon.'),
('ex_n3_auto_2034', 'v_n3_auto_2034', 'データを図で表すと分かりやすい。', 'データを ずで あらわすと わかりやすい。', 'Menyajikan data dengan diagram membuatnya mudah dipahami.'),
('ex_n3_auto_2035', 'v_n3_auto_2035', 'この国の生活水準は上がっている。', 'この くにの せいかつ すいじゅんは あがっている。', 'Tingkat kehidupan di negara ini sedang meningkat.'),
('ex_n3_auto_2036', 'v_n3_auto_2036', '先生が推薦してくれた本を読む。', 'せんせいが すいせん してくれた ほんを よむ。', 'Membaca buku yang direkomendasikan oleh guru.'),
('ex_n3_auto_2037', 'v_n3_auto_2037', 'クラスの生徒の数を数える。', 'クラスの せいとの かずを かぞえる。', 'Menghitung jumlah murid di kelas.'),
('ex_n3_auto_2038', 'v_n3_auto_2038', 'パスワードを数字４桁で設定する。', 'パスワードを すうじ よんけたで せってい する。', 'Mengatur kata sandi dengan 4 digit angka.'),
('ex_n3_auto_2039', 'v_n3_auto_2039', '今月末までにレポートを提出してください。', 'こんげつすえまでに レポートを ていしゅつ してください。', 'Tolong kumpulkan laporan sebelum akhir bulan ini.'),
('ex_n3_auto_2040', 'v_n3_auto_2040', '彼女の後ろ姿を見送った。', 'かのじょの うしろすがたを みおくった。', 'Aku melepas kepergian sosok tubuhnya dari belakang.'),
('ex_n3_auto_2041', 'v_n3_auto_2041', '川に落ちた子供を救った。', 'かわに おちた こどもを すくった。', 'Menyelamatkan anak yang jatuh ke sungai.'),
('ex_n3_auto_2042', 'v_n3_auto_2042', '彼は優れた言語能力を持っている。', 'かれは すぐれた げんご のうりょくを もっている。', 'Dia memiliki kemampuan bahasa yang luar biasa unggul.'),
('ex_n3_auto_2043', 'v_n3_auto_2043', '彼の話は少しも面白くなかった。', 'かれの はなしは すこしも おもしろくなかった。', 'Ceritanya sedikit pun tidak menarik.'),
('ex_n3_auto_2044', 'v_n3_auto_2044', '休日は家族とのんびり過ごす。', 'きゅうじつは かぞくと のんびり すごす。', 'Menghabiskan hari libur dengan santai bersama keluarga.'),
('ex_n3_auto_2045', 'v_n3_auto_2045', 'この映画の筋はとても面白い。', 'この えいがの すじは とても おもしろい。', 'Alur cerita film ini sangat menarik.'),
('ex_n3_auto_2046', 'v_n3_auto_2046', '朝からひどい頭痛がする。', 'あさから ひどい ずつうが する。', 'Sakit kepala parah sejak pagi.'),
('ex_n3_auto_2047', 'v_n3_auto_2047', '宿題は全て終わりました。', 'しゅくだいは すべて おわりました。', 'Pekerjaan rumah semuanya telah selesai.'),
('ex_n3_auto_2048', 'v_n3_auto_2048', '出かける前に食事を済ませる。', 'でかける まえに しょくじを すませる。', 'Menyelesaikan makan sebelum pergi keluar.'),
('ex_n3_auto_2049', 'v_n3_auto_2049', '部屋の角にゴミ箱を置く。', 'へやの すみに ごみばこを おく。', 'Meletakkan tempat sampah di pojok ruangan.'),
('ex_n3_auto_2050', 'v_n3_auto_2050', '道で昔の友達とすれ違った。', 'みちで むかしの ともだちと すれちがった。', 'Aku berpapasan dengan teman lama di jalan.'),
('ex_n3_auto_2051', 'v_n3_auto_2051', '数学で正の数を勉強する。', 'すうがくで せいの かずを べんきょう する。', 'Mempelajari bilangan positif dalam matematika.'),
('ex_n3_auto_2052', 'v_n3_auto_2052', '日本の消費税は１０％です。', 'にほんの しょうひぜいは じっぱーせんと です。', 'Pajak konsumsi di Jepang adalah 10%.'),
('ex_n3_auto_2053', 'v_n3_auto_2053', '私たちは２１世紀に生きている。', 'わたしたちは にじゅういっせいきに いきている。', 'Kita hidup di abad ke-21.'),
('ex_n3_auto_2054', 'v_n3_auto_2054', '電気代の請求書が届いた。', 'でんきだいの せいきゅうしょが とどいた。', 'Surat tagihan biaya listrik telah tiba.'),
('ex_n3_auto_2055', 'v_n3_auto_2055', 'この道路の制限速度は時速６０キロだ。', 'この どうろの せいげん そくどは じそく ろくじっきろ だ。', 'Batas kecepatan jalan ini adalah 60 km per jam.'),
('ex_n3_auto_2056', 'v_n3_auto_2056', '二人は正式に結婚を発表した。', 'ふたりは せいしきに けっこんを はっぴょう した。', 'Keduanya mengumumkan pernikahan secara resmi.'),
('ex_n3_auto_2057', 'v_n3_auto_2057', '水と油は異なる性質を持っている。', 'みずと あぶらは ことなる せいしつを もっている。', 'Air dan minyak memiliki sifat yang berbeda.'),
('ex_n3_auto_2058', 'v_n3_auto_2058', '健全な身体に健全な精神が宿る。', 'けんぜんな しんたいに けんぜんな せいしんが やどる。', 'Di dalam tubuh yang sehat terdapat jiwa yang sehat.'),
('ex_n3_auto_2059', 'v_n3_auto_2059', '日本では１８歳から成人とみなされる。', 'にほんでは じゅうはっさいから せいじんと みなされる。', 'Di Jepang dianggap sebagai orang dewasa mulai usia 18 tahun.'),
('ex_n3_auto_2060', 'v_n3_auto_2060', 'たまには贅沢なディナーを食べる。', 'たまには ぜいたくな ディナーを たべる。', 'Sekali-sekali makan makan malam yang mewah.'),
('ex_n3_auto_2061', 'v_n3_auto_2061', '子供の成長は非常に早い。', 'こどもの せいちょうは ひじょうに はやい。', 'Pertumbuhan anak-anak sangat cepat.'),
('ex_n3_auto_2062', 'v_n3_auto_2062', '青年たちが地域活動に参加する。', 'せいねんたちが ちいき かつどうに さんか する。', 'Para pemuda berpartisipasi dalam kegiatan wilayah setempat.'),
('ex_n3_auto_2063', 'v_n3_auto_2063', '履歴書に生年月日を記入してください。', 'りれきしょに せいねんがっぴを きにゅう してください。', 'Tolong tuliskan tanggal lahir Anda pada daftar riwayat hidup.'),
('ex_n3_auto_2064', 'v_n3_auto_2064', 'この工場ではプラスチック製品を作っている。', 'この こうじょうでは プラスチック せいひんを つくっている。', 'Pabrik ini memproduksi produk-produk plastik.'),
('ex_n3_auto_2065', 'v_n3_auto_2065', '地球上には豊かな生命が存在する。', 'ちきゅうじょうには ゆたかな せいめいが そんざい する。', 'Di atas bumi terdapat kehidupan yang melimpah.'),
('ex_n3_auto_2066', 'v_n3_auto_2066', '机の上の書類を整理した。', 'つくえの うえの しょるいを せいり した。', 'Merapikan berkas-berkas dokumen di atas meja.'),
('ex_n3_auto_2067', 'v_n3_auto_2067', '風邪をひいて咳が止まらない。', 'かぜを ひいて せきが とまらない。', 'Terserang flu dan batuknya tidak berhenti.'),
('ex_n3_auto_2068', 'v_n3_auto_2068', '昔は石炭が主な燃料だった。', 'むかしは せきたんが おもな ねんりょう だった。', 'Dahulu batu bara merupakan bahan bakar utama.'),
('ex_n3_auto_2069', 'v_n3_auto_2069', '石油の価格が上昇している。', 'せきゆの かかくが じょうしょう している。', 'Harga minyak bumi sedang meningkat.'),
('ex_n3_auto_2070', 'v_n3_auto_2070', '世間の目を気にする必要はない。', 'せけんの めを きにする ひつようは ない。', 'Tidak perlu memedulikan pandangan masyarakat.'),
('ex_n3_auto_2071', 'v_n3_auto_2071', 'この歴史の出来事には諸説ある。', 'この れきしの できごとには しょせつ ある。', 'Peristiwa sejarah ini memiliki berbagai teori.'),
('ex_n3_auto_2072', 'v_n3_auto_2072', '建築家が新しいビルを設計する。', 'けんちくかが あたらしい ビルを せっけい する。', 'Arsitek merancang gedung baru.'),
('ex_n3_auto_2073', 'v_n3_auto_2073', '明日の約束は絶対に忘れません。', 'あしたの やくそくは ぜったいに わすれません。', 'Janji besok pasti tidak akan aku lupakan.'),
('ex_n3_auto_2074', 'v_n3_auto_2074', '平和と愛のために戦う。', 'へいわと あいの ために たたかう。', 'Berjuang demi perdamaian dan cinta.'),
('ex_n3_auto_2075', 'v_n3_auto_2075', '両親は子供に多くの愛情を注ぐ。', 'りょうしんは こどもに おおくの あいじょうを そそぐ。', 'Orang tua mencurahkan banyak kasih sayang kepada anaknya.'),
('ex_n3_auto_2076', 'v_n3_auto_2076', '手を振って出発の合図をした。', 'てを ふって しゅっぱつの あいずを した。', 'Melambaikan tangan untuk memberi isyarat keberangkatan.'),
('ex_n3_auto_2077', 'v_n3_auto_2077', '家族を深く愛している。', 'かぞくを ふかく あいしている。', 'Sangat mencintai keluarga.'),
('ex_n3_auto_2078', 'v_n3_auto_2078', 'テニスの相手を探している。', 'テニスの あいてを さがしている。', 'Sedang mencari pasangan untuk bermain tenis.'),
('ex_n3_auto_2079', 'v_n3_auto_2079', '旅行中に盗難に遭った。', 'りょこうちゅうに とうなんに あった。', 'Mengalami kemalingan di tengah perjalanan.'),
('ex_n3_auto_2080', 'v_n3_auto_2080', '部屋の明かりを消して眠る。', 'へやの あかりを けして ねむる。', 'Mematikan cahaya kamar lalu tidur.'),
('ex_n3_auto_2081', 'v_n3_auto_2081', '駐車場にまだ空きがありますか。', 'ちゅうしゃじょうに まだ あきが ありますか。', 'Apakah di tempat parkir masih ada kekosongan?'),
('ex_n3_auto_2082', 'v_n3_auto_2082', '毎日同じ料理ばかりで飽きてしまった。', 'まいにち おなじ りょうり ばかりで あきて しまった。', 'Aku jenuh karena setiap hari makanannya sama saja.'),
('ex_n3_auto_2083', 'v_n3_auto_2083', '自己紹介の後に握手をした。', 'じこしょうかいの あとに あくしゅを した。', 'Bersalaman setelah memperkenalkan diri.'),
('ex_n3_auto_2084', 'v_n3_auto_2084', '彼はまるで悪魔のような笑顔を浮かべた。', 'かれは まるで あくまの ような えがおを うかべた。', 'Dia menunjukkan senyuman yang persis seperti iblis.'),
('ex_n3_auto_2085', 'v_n3_auto_2085', '旅行中、友達のペットを預かった。', 'りょこうちゅう、 ともだちの ペットを あずかった。', 'Menjaga hewan peliharaan teman selama perjalanan.'),
('ex_n3_auto_2086', 'v_n3_auto_2086', '銀行にお金を預ける。', 'ぎんこうに おかねを あずける。', 'Menitipkan uang di bank.'),
('ex_n3_auto_2087', 'v_n3_auto_2087', '走ったのでたくさん汗をかいた。', 'はしったので たくさん あせを かいた。', 'Aku mengeluarkan banyak keringat karena berlari.'),
('ex_n3_auto_2088', 'v_n3_auto_2088', '温かいスープを飲んで温まる。', 'あたたかい スープを のんで あたたまる。', 'Meminum sup hangat untuk menghangatkan diri.'),
('ex_n3_auto_2089', 'v_n3_auto_2089', 'ストーブのおかげで部屋が暖まった。', 'ストーブの おかげで へやが あたたまった。', 'Berkat kompor pemanas ruangan menjadi hangat.'),
('ex_n3_auto_2090', 'v_n3_auto_2090', 'エアコンをつけて部屋を暖める。', 'エアコンを つけて へやを あたためる。', 'Menyalakan AC untuk menghangatkan ruangan.'),
('ex_n3_auto_2091', 'v_n3_auto_2091', 'この辺りは夜になると静かだ。', 'この あたりは よるに なると しずかだ。', 'Sekitar sini menjadi sunyi saat malam.'),
('ex_n3_auto_2092', 'v_n3_auto_2092', '嘘をついてはいけないのは当たり前だ。', 'うそを ついては いけないのは あたりまえだ。', 'Wajar saja jika tidak boleh berbohong.'),
('ex_n3_auto_2093', 'v_n3_auto_2093', '壊れやすい物なので慎重に扱う。', 'こわれやすい ものなので しんちょうに あつかう。', 'Karena ini barang yang mudah pecah, perlakukan dengan hati-hati.'),
('ex_n3_auto_2094', 'v_n3_auto_2094', '明日の集まりの場所はどこですか。', 'あしたの あつまりの ばしょは どこ ですか。', 'Di manakah tempat pertemuan besok?'),
('ex_n3_auto_2095', 'v_n3_auto_2095', '砂浜に足跡が残っている。', 'すなはまに あしあとが のこっている。', 'Jejak kaki tersisa di pantai berpasir.'),
('ex_n3_auto_2096', 'v_n3_auto_2096', '靴下に穴が開いてしまった。', 'くつしたに あなが あいて しまった。', 'Kaus kakiku sudah berlubang.'),
('ex_n3_auto_2097', 'v_n3_auto_2097', 'フライパンに油をひく。', 'フライパンに あぶらを ひく。', 'Mengoleskan minyak pada wajan.'),
('ex_n3_auto_2098', 'v_n3_auto_2098', '回答の誤りを訂正する。', 'かいとうの あやまりを ていせい する。', 'Memperbaiki kesalahan pada jawaban.'),
('ex_n3_auto_2099', 'v_n3_auto_2099', '他人の粗を探すのは良くない。', 'たにんの あらを さがすのは よくない。', 'Mencari-cari kesalahan orang lain itu tidak baik.'),
('ex_n3_auto_2100', 'v_n3_auto_2100', '新年を迎え、新たな気持ちでスタートする。', 'しんねんを むかえ、 あらたな きもちで スタート する。', 'Menyambut tahun baru, memulai dengan perasaan yang baru.'),
('ex_n3_auto_2101', 'v_n3_auto_2101', 'この行動は彼の優しさの現れだ。', 'この こうどうは かれの やさしさの あらわれだ。', 'Tindakan ini merupakan perwujudan dari kebaikannya.'),
('ex_n3_auto_2102', 'v_n3_auto_2102', '霧の中から人影が現れた。', 'きりの なかから ひとかげが あらわれた。', 'Sosok bayangan orang muncul dari dalam kabut.'),
('ex_n3_auto_2103', 'v_n3_auto_2103', 'この計画には問題が有る。', 'この けいかくには もんだいが ある。', 'Pada rencana ini ada masalah.'),
('ex_n3_auto_2104', 'v_n3_auto_2104', '石鹸をよく泡立てて顔を洗う。', 'せっけんを よく あわだてて かおを あらう。', 'Mencuci muka dengan membusakan sabun dengan baik.'),
('ex_n3_auto_2105', 'v_n3_auto_2105', '新しいイベントの案を提出する。', 'あたらしい イベントの あんを ていしゅつ する。', 'Mengajukan usulan acara yang baru.'),
('ex_n3_auto_2106', 'v_n3_auto_2106', '英単語を毎日１０個暗記する。', 'えいたんごを まいにち じっこ あんき する。', 'Menghafal 10 kosakata bahasa Inggris setiap hari.'),
('ex_n3_auto_2107', 'v_n3_auto_2107', 'ストレスで胃が痛くなる。', 'ストレスで いが いたくなる。', 'Lambung menjadi sakit karena stres.'),
('ex_n3_auto_2108', 'v_n3_auto_2108', 'クラスの図書委員に選ばれた。', 'クラスの としょ いいんに えらばれた。', 'Terpilih menjadi anggota komite perpustakaan kelas.'),
('ex_n3_auto_2109', 'v_n3_auto_2109', '彼の答えは非常に意外だった。', 'かれの こたえは ひじょうに いがい だった。', 'Jawabannya sangat tidak terduga.'),
('ex_n3_auto_2110', 'v_n3_auto_2110', 'この電車は東京行きです。', 'この でんしゃは とうきょう いき です。', 'Kereta ini bertujuan ke Tokyo.'),
('ex_n3_auto_2111', 'v_n3_auto_2111', '水が強い勢いで噴き出している。', 'みずが つよい いきおいで ふきだしている。', 'Air menyembur keluar dengan kekuatan yang kuat.'),
('ex_n3_auto_2112', 'v_n3_auto_2112', '川にはたくさんの生き物が住んでいる。', 'かわには たくさんの いきものが すんでいる。', 'Di sungai hidup banyak makhluk hidup.'),
('ex_n3_auto_2113', 'v_n3_auto_2113', '健康的な体重を維持する。', 'けんこうてきな たいじゅうを いじ する。', 'Mempertahankan berat badan yang sehat.'),
('ex_n3_auto_2114', 'v_n3_auto_2114', '事故の後、彼は意識を取り戻した。', 'じこの あと、 かれは いしきを とりもどした。', 'Setelah kecelakaan, dia mendapatkan kembali kesadarannya.'),
('ex_n3_auto_2115', 'v_n3_auto_2115', '機械の動作に異常は見られない。', 'きかいの どうさに いじょうは みられない。', 'Tidak terlihat adanya kejanggalan pada pengoperasian mesin.'),
('ex_n3_auto_2116', 'v_n3_auto_2116', '意地悪な質問に困ってしまった。', 'いじわるな しつもんに こまって しまった。', 'Aku kesulitan karena pertanyaan yang usil.'),
('ex_n3_auto_2117', 'v_n3_auto_2117', '森の奥に美しい泉を見つけた。', 'もりの おくに うつくしい いずみを みつけた。', 'Menemukan mata air yang indah di kedalaman hutan.'),
('ex_n3_auto_2118', 'v_n3_auto_2118', '以前に一度、ここに来たことがある。', 'いぜんに いちど、 ここに きたことが ある。', 'Dahulu aku pernah datang ke sini sekali.'),
('ex_n3_auto_2119', 'v_n3_auto_2119', '木の板を使って棚を作る。', 'きの いたを つかって たなを つくる。', 'Membuat rak menggunakan papan kayu.'),
('ex_n3_auto_2120', 'v_n3_auto_2120', '彼は歴史に残る偉大な発明家だ。', 'かれは れきしに のこる いだいな はつめいか だ。', 'Dia adalah penemu luar biasa yang tersisa dalam sejarah.'),
('ex_n3_auto_2121', 'v_n3_auto_2121', '薬を飲むと痛みが和らいだ。', 'くすりを のむと いたみが やわらいだ。', 'Rasa sakitnya mereda setelah meminum obat.'),
('ex_n3_auto_2122', 'v_n3_auto_2122', '交渉は合意に至った。', 'こうしょうは ごういに いたった。', 'Negosiasi berujung pada kesepakatan.'),
('ex_n3_auto_2123', 'v_n3_auto_2123', 'この市には多くの観光客が訪れる。', 'この いちには おおくの かんこうきゃくが おとずれる。', 'Banyak wisatawan mengunjungi kota ini.'),
('ex_n3_auto_2124', 'v_n3_auto_2124', '大雨のため、電車が一時運転を見合わせた。', 'おおあめの ため、 でんしゃが いちじ うんてんを みあわせた。', 'Karena hujan lebat, kereta menunda pengoperasian untuk sementara.'),
('ex_n3_auto_2125', 'v_n3_auto_2125', 'たくさんの仕事を一度に引き受ける。', 'たくさんの しごとを いちどに ひきうける。', 'Menerima banyak pekerjaan sekaligus.'),
('ex_n3_auto_2126', 'v_n3_auto_2126', '来月、一家で北海道へ引っ越す。', 'らいげつ、 いっかで ほっかいどうへ ひっこす。', 'Bulan depan sekeluarga pindah ke Hokkaido.'),
('ex_n3_auto_2127', 'v_n3_auto_2127', 'これは非常に珍しい植物の一種だ。', 'これは ひじょうに めずらしい しょくぶつの いっしゅ だ。', 'Ini adalah sejenis tanaman yang sangat langka.'),
('ex_n3_auto_2128', 'v_n3_auto_2128', '流れ星が一瞬のうちに消え去った。', 'ながれぼしが いっしゅんの うちに きえさった。', 'Bintang jatuh menghilang dalam sekejap mata.'),
('ex_n3_auto_2129', 'v_n3_auto_2129', '君の恩は一生忘れません。', 'きみの おんは いっしょう わすれません。', 'Kebaikanmu tidak akan kulupakan seumur hidup.'),
('ex_n3_auto_2130', 'v_n3_auto_2130', '努力を重ねて、一層の向上を目指す。', 'どりょくを かさねて、 いっそうの こうじょうを めざす。', 'Menumpuk usaha dan menargetkan peningkatan yang lebih jauh.'),
('ex_n3_auto_2131', 'v_n3_auto_2131', '彼は一体どこへ行ってしまったのだろう。', 'かれは いったい どこへ いって しまったのだろう。', 'Dia sebenarnya sudah pergi ke mana ya?'),
('ex_n3_auto_2132', 'v_n3_auto_2132', '二人の意見が完全に一致した。', 'ふたりの いけんが かんぜんに いっち した。', 'Pendapat mereka berdua benar-benar cocok sepenuhnya.'),
('ex_n3_auto_2133', 'v_n3_auto_2133', 'これは一般の常識として知られている。', 'これは いっぱんの じょうしきとして しられている。', 'Ini diketahui sebagai akal sehat yang umum.'),
('ex_n3_auto_2134', 'v_n3_auto_2134', '机を窓の近くに移動させる。', 'つくえを まどの ちかくに いどう させる。', 'Memindahkan meja ke dekat jendela.'),
('ex_n3_auto_2135', 'v_n3_auto_2135', '私の従兄弟は東京の大学に通っている。', 'わたしの いとこは とうきょうの だいがくに かよっている。', 'Saudara sepupuku kuliah di universitas Tokyo.'),
('ex_n3_auto_2136', 'v_n3_auto_2136', '田んぼの稲が青々と茂っている。', 'たんぼの いねが あおあおと しげっている。', 'Padi di sawah tumbuh subur menghijau.'),
('ex_n3_auto_2137', 'v_n3_auto_2137', '授業中に居眠りをして怒られた。', 'じゅぎょうちゅうに いねむりをして おこられた。', 'Aku dimarahi karena tidur ayam saat pelajaran berlangsung.'),
('ex_n3_auto_2138', 'v_n3_auto_2138', 'すべての命を大切にしなければならない。', 'すべての いのちを たいせつに しなければ ならない。', 'Semua nyawa harus dijaga dengan berharga.'),
('ex_n3_auto_2139', 'v_n3_auto_2139', '交通規則に違反して切符を切られた。', 'こうつう きそくに いはん して きっぷを きられた。', 'Kena tilang karena melanggar aturan lalu lintas.'),
('ex_n3_auto_2140', 'v_n3_auto_2140', '季節に合わせて衣服を替える。', 'きせつに あわせて いふくを かえる。', 'Mengganti pakaian disesuaikan dengan musim.'),
('ex_n3_auto_2141', 'v_n3_auto_2141', '家族みんなで居間に集まってテレビを見る。', 'かぞく みんなで いまに あつまって テレビを みる。', 'Seluruh keluarga berkumpul di ruang keluarga menonton TV.'),
('ex_n3_auto_2142', 'v_n3_auto_2142', '彼の努力は今に実を結ぶだろう。', 'かれの どりょくは いまに みを むすぶだろう。', 'Usahanya suatu saat nanti pasti akan membuahkan hasil.'),
('ex_n3_auto_2143', 'v_n3_auto_2143', '空が暗くなり、今にも雨が降り出しそうだ。', 'そらが くらくなり、 いまにも あめが ふりだしそうだ。', 'Langit menjadi gelap, hampir saja hujan turun.'),
('ex_n3_auto_2144', 'v_n3_auto_2144', '否と言えない性格を直したい。', 'いやと いえない せいかくを なおしたい。', 'Aku ingin memperbaiki kepribadianku yang tidak bisa berkata tidak.'),
('ex_n3_auto_2145', 'v_n3_auto_2145', '日本に来て以来、毎日忙しい。', 'にほんに きて いらい、 まいにち いそがしい。', 'Sejak datang ke Jepang, setiap hari sibuk.'),
('ex_n3_auto_2146', 'v_n3_auto_2146', '海岸には大きな岩がたくさん並んでいる。', 'かいがんには おおきな いわが たくさん ならんでいる。', 'Di pantai berjejer banyak batu karang yang besar.'),
('ex_n3_auto_2147', 'v_n3_auto_2147', '合格の祝いに家族で食事に行く。', 'ごうかくの いわいに かぞくで しょくじに いく。', 'Pergi makan bersama keluarga untuk perayaan kelulusan.'),
('ex_n3_auto_2148', 'v_n3_auto_2148', '友達の誕生日を盛大に祝った。', 'ともだちの たんじょうびを せいだいに いわった。', 'Merayakan ulang tahun teman dengan meriah.'),
('ex_n3_auto_2149', 'v_n3_auto_2149', 'レポートをプリンターで印刷する。', 'レポートを プリンターで いんさつ する。', 'Mencetak laporan dengan pencetak.'),
('ex_n3_auto_2150', 'v_n3_auto_2150', '彼は今年で現役を引退することを決めた。', 'かれは ことしで げんえきを いんたい することを きめた。', 'Dia memutuskan pensiun dari dunia aktif pada tahun ini.'),
('ex_n3_auto_2151', 'v_n3_auto_2151', '論文から一部を引用する。', 'ろんぶんから いちぶを いんよう する。', 'Mengutip sebagian dari tesis.'),
('ex_n3_auto_2152', 'v_n3_auto_2152', '白い兎が草の上を跳ねている。', 'しろい うさぎが くさの うえを はねている。', 'Kelinci putih sedang melompat di atas rumput.'),
('ex_n3_auto_2153', 'v_n3_auto_2153', '牧場でたくさんの牛が草を食べている。', 'ぼくじょうで たくさんの うしが くさを たべている。', 'Banyak sapi sedang memakan rumput di peternakan.'),
('ex_n3_auto_2154', 'v_n3_auto_2154', '宇宙旅行が現実になる日も近いだろう。', 'うちゅう りょこうが げんじつに なる ひも ちかいだろう。', 'Hari di mana perjalanan luar angkasa menjadi kenyataan mungkin sudah dekat.'),
('ex_n3_auto_2155', 'v_n3_auto_2155', '武士が主君の敵を討つ。', 'ぶしが しゅくんの かたきを うつ。', 'Busbi (ksatria) menyerang musuh junjungannya.'),
('ex_n3_auto_2156', 'v_n3_auto_2156', '草原を速いスピードで馬が走る。', 'そうげんを はやい スピードで うまが はしる。', 'Kuda berlari dengan kecepatan tinggi di padang rumput.'),
('ex_n3_auto_2157', 'v_n3_auto_2157', '私はジャカルタ生まれのジャカルタ育ちです。', 'わたしは ジャカルタ うまれの ジャカルタ そだち です。', 'Saya lahir dan besar di Jakarta.'),
('ex_n3_auto_2158', 'v_n3_auto_2158', '経験の有無にかかわらず、応募を歓迎します。', 'けいけんの うむに かかわらず、 おうぼを かんげい します。', 'Kami menyambut baik lamaran Anda dengan atau tanpa pengalaman.'),
('ex_n3_auto_2159', 'v_n3_auto_2159', '庭の梅の花が綺麗に咲いた。', 'にわの うめの はなが きれいに さいた。', 'Bunga prem di taman mekar dengan indah.'),
('ex_n3_auto_2160', 'v_n3_auto_2160', '信頼していた友達に裏切られた。', 'しんらい していた ともだちに うらぎられた。', 'Dikhianati oleh teman yang telah dipercayai.'),
('ex_n3_auto_2161', 'v_n3_auto_2161', '彼の新しい本は非常によく売れている。', 'かれの あたらしい ほんは ひじょうに よく うれている。', 'Buku barunya terjual dengan sangat baik.'),
('ex_n3_auto_2162', 'v_n3_auto_2162', '彼の噂を街で耳にした。', 'かれの うわさを まちで みみに した。', 'Aku mendengar rumor tentang dia di kota.'),
('ex_n3_auto_2163', 'v_n3_auto_2163', '宝くじが当たるのは運次第だ。', 'たからくじが あたるのは うん しだいだ。', 'Memenangkan lotre bergantung pada keberuntungan.'),
('ex_n3_auto_2164', 'v_n3_auto_2164', '安全運転を心がけてください。', 'あんぜん うんてんを こころがけて ください。', 'Tolong usahakan berkendara dengan aman.'),
('ex_n3_auto_2165', 'v_n3_auto_2165', '包丁の柄が壊れてしまった。', 'ほうちょうの えが こわれて しまった。', 'Gagang pisau dapur sudah rusak.'),
('ex_n3_auto_2166', 'v_n3_auto_2166', '二人の愛が永遠に続くことを祈る。', 'ふたりの あいが えいえんに つづく ことを いのる。', 'Mendoakan cinta mereka berdua bertahan selamanya.'),
('ex_n3_auto_2167', 'v_n3_auto_2167', 'この条約は永久に効力を有する。', 'この じょうやくは えいきゅうに こうりょくを ゆうする。', 'Perjanjian ini memiliki kekuatan hukum secara permanen.'),
('ex_n3_auto_2168', 'v_n3_auto_2168', 'このデパートは午後８時まで営業している。', 'この デパートは ごご はちじまで えいぎょう している。', 'Toserba ini buka hingga pukul 8 malam.'),
('ex_n3_auto_2169', 'v_n3_auto_2169', '月は地球の唯一の天然の衛星だ。', 'つきは ちきゅうの ゆいいつの てんねんの えいせいだ。', 'Bulan adalah satu-satunya satelit alami bumi.'),
('ex_n3_auto_2170', 'v_n3_auto_2170', 'バランスの良い食事で栄養を摂る。', 'バランスの いい しょくじで えいようを とる。', 'Mendapatkan gizi dengan makan makanan yang seimbang.'),
('ex_n3_auto_2171', 'v_n3_auto_2171', '彼女の笑顔を見ると元気が出る。', 'かのじょの えがおを みると げんきが でる。', 'Melihat wajah tersenyumnya membuatku menjadi bersemangat.'),
('ex_n3_auto_2172', 'v_n3_auto_2172', '白い紙に花の絵を描く。', 'しろい かみに はなの えを えがく。', 'Melukis gambar bunga di kertas putih.'),
('ex_n3_auto_2173', 'v_n3_auto_2173', '水槽の金魚に餌を与える。', 'すいそうの きんぎょに えさを あたえる。', 'Memberikan pakan kepada ikan mas koki di akuarium.'),
('ex_n3_auto_2174', 'v_n3_auto_2174', '黒板にきれいな円を描いた。', 'こくばんに きれいな えんを えがいた。', 'Menggambar lingkaran yang indah di papan tulis.'),
('ex_n3_auto_2175', 'v_n3_auto_2175', '雨のため試合が来週に延期された。', 'あめの ため しあいが らいしゅうに えんき された。', 'Karena hujan pertandingan ditunda hingga minggu depan.'),
('ex_n3_auto_2176', 'v_n3_auto_2176', '彼の素晴らしい演技に観客が感動した。', 'かれの すばらしい えんぎに かんきゃくが かんどう した。', 'Penonton tersentuh oleh aktingnya yang luar biasa.'),
('ex_n3_auto_2177', 'v_n3_auto_2177', '政府は被災地に経済的な援助を行う。', 'せいふは ひさいちに けいざいてきな えんじょを おこなう。', 'Pemerintah memberikan bantuan ekonomi kepada daerah bencana.'),
('ex_n3_auto_2178', 'v_n3_auto_2178', '大統領が国民に向けて演説を行った。', 'だいとうりょうが こくみんに むけて えんぜつを おこなった。', 'Presiden menyampaikan pidato yang ditujukan kepada rakyat.'),
('ex_n3_auto_2179', 'v_n3_auto_2179', '誰でも老いを避けることはできない。', 'だれでも おいを さける ことは できない。', 'Siapa pun tidak bisa menghindari usia tua.'),
('ex_n3_auto_2180', 'v_n3_auto_2180', '走って前のランナーに追い付いた。', 'はしって まえの ランナーに おいついた。', 'Aku berlari dan menyusul pelari di depanku.'),
('ex_n3_auto_2181', 'v_n3_auto_2181', 'サポーターがスタジアムでチームを応援する。', 'サポーターが スタジアムで チームを おうえん する。', 'Pendukung menyemangati tim di stadion.'),
('ex_n3_auto_2182', 'v_n3_auto_2182', '昔々、ある国に優しい王様がいました。', 'むかしむかし、 ある くにに やさしい おうさまが いました。', 'Dahulu kala, ada seorang raja yang baik hati di suatu negara.'),
('ex_n3_auto_2183', 'v_n3_auto_2183', '童話に出てくる王子様はハンサムだ。', 'どうわに でてくる おうじさまは ハンサムだ。', 'Pangeran yang muncul di dongeng itu tampan.'),
('ex_n3_auto_2184', 'v_n3_auto_2184', '横断歩道を渡って向こう側に行く。', 'おうだんほどうを わたって むこうがわに いく。', 'Menyeberangi tempat penyeberangan jalan untuk pergi ke sisi sebelah sana.'),
('ex_n3_auto_2185', 'v_n3_auto_2185', '山頂が白い雪で覆われている。', 'さんちょうが しろい ゆきで おおわれている。', 'Puncak gunung diselimuti oleh salju putih.'),
('ex_n3_auto_2186', 'v_n3_auto_2186', 'アパートの大家さんに家賃を支払う。', 'アパートの おおやさんに やちんを しはらう。', 'Membayar uang sewa kamar kepada pemilik kontrakan apartemen.'),
('ex_n3_auto_2187', 'v_n3_auto_2187', '丘の上にぽつんと一本の木が立っている。', 'おかの うえに ぽつんと いっぽんの きが たっている。', 'Sebatang pohon berdiri tegak sendirian di atas bukit.'),
('ex_n3_auto_2188', 'v_n3_auto_2188', '漁船が沖に向かって進んでいく。', 'ぎょせんが おきに むかって すすんでいく。', 'Perahu nelayan melaju menuju lepas pantai.'),
('ex_n3_auto_2189', 'v_n3_auto_2189', '母の日に感謝の花束を贈る。', 'ははの ひに かんしゃの はなたばを おくる。', 'Menghadiahkan buket bunga ucapan terima kasih pada Hari Ibu.'),
('ex_n3_auto_2190', 'v_n3_auto_2190', '幼い子供たちが公園で遊んでいる。', 'おさない こどもたちが こうえんで あそんでいる。', 'Anak-anak yang sangat muda sedang bermain di taman.'),
('ex_n3_auto_2191', 'v_n3_auto_2191', '先生に会ったらきちんとお辞儀をする。', 'せんせいに あったら きちんと おじぎを する。', 'Membungkuk dengan sopan saat bertemu dengan guru.'),
('ex_n3_auto_2192', 'v_n3_auto_2192', '彼女はとてもお洒落な服を着ている。', 'かのじょは とても おしゃれな ふくを きている。', 'Dia memakai pakaian yang sangat modis.'),
('ex_n3_auto_2193', 'v_n3_auto_2193', '授業中にお喋りをしてはいけない。', 'じゅぎょうちゅうに おしゃべりをしては いけない。', 'Tidak boleh mengobrol selama pelajaran berlangsung.'),
('ex_n3_auto_2194', 'v_n3_auto_2194', '失敗を恐れずに挑戦することが大切だ。', 'しっぱいを おそれずに ちょうせん することが たいせつだ。', 'Mencoba tanpa takut gagal adalah hal yang penting.'),
('ex_n3_auto_2195', 'v_n3_auto_2195', 'ゆうべ、恐ろしい夢を見て目が覚めた。', 'ゆうべ、 おそろしい ゆめを みて めが さめた。', 'Semalam aku terbangun karena mimpi buruk yang mengerikan.'),
('ex_n3_auto_2196', 'v_n3_auto_2196', 'お互いに助け合って生きていく。', 'おたがいに たすけあって いきていく。', 'Hidup dengan saling membantu satu sama lain.'),
('ex_n3_auto_2197', 'v_n3_auto_2197', 'あそこに立っている男の人は誰ですか。', 'あそこに たっている おとこのひとは だれ ですか。', 'Siapakah pria yang berdiri di sana?'),
('ex_n3_auto_2198', 'v_n3_auto_2198', 'この製品は性能の点で他社より劣る。', 'この せいひんは せいのうの てんで たしゃより おとる。', 'Produk ini dalam hal performa lebih rendah dari perusahaan lain.'),
('ex_n3_auto_2199', 'v_n3_auto_2199', '日本の昔話にはよく鬼が登場する。', 'にほんの むかしばなしには よく おにが とうじょう する。', 'Dalam dongeng kuno Jepang sering muncul iblis.'),
('ex_n3_auto_2200', 'v_n3_auto_2200', '浴衣を着て、きれいに帯を結んだ。', 'ゆかたを きて、 きれいに おびを むすんだ。', 'Memakai yukata dan mengikat obi dengan indah.'),
('ex_n3_auto_2201', 'v_n3_auto_2201', 'お昼を食べに近くの食堂へ行く。', 'おひるを たべに ちかくの しょくどうへ いく。', 'Pergi ke warung makan terdekat untuk makan siang.'),
('ex_n3_auto_2202', 'v_n3_auto_2202', '海で溺れそうになったところを助けられた。', 'うみで おぼれそうに なった ところを たすけられた。', 'Diselamatkan saat hampir tenggelam di laut.'),
('ex_n3_auto_2203', 'v_n3_auto_2203', 'お前、明日のテストの準備はできたか。', 'おまえ、 あしたの テストの じゅんびは できたか。', 'Kamu, apakah persiapan untuk ujian besok sudah siap?'),
('ex_n3_auto_2204', 'v_n3_auto_2204', '先生にお目に掛かれて光栄です。', 'せんせいに おめにかかれて こうえい です。', 'Suatu kehormatan bisa bertemu dengan guru.'),
('ex_n3_auto_2205', 'v_n3_auto_2205', '良い解決策をふと思いついた。', 'よい かいけつさくを ふと おもいついた。', 'Tiba-tiba terlintas solusi yang baik di pikiranku.'),
('ex_n3_auto_2206', 'v_n3_auto_2206', '高校時代の思い出は一生忘れない。', 'こうこう じだいの おもいでは いっしょう わすれない。', 'Kenangan masa SMA tidak akan kulupakan seumur hidup.'),
('ex_n3_auto_2207', 'v_n3_auto_2207', '彼の泳ぎはとてもスピードがある。', 'かれの およぎは とても スピードが ある。', 'Gaya berenangnya sangat memiliki kecepatan.'),
('ex_n3_auto_2208', 'v_n3_auto_2208', '地球温暖化は環境に悪影響を及ぼす。', 'ちきゅう おんだんかは かんきょうに あくえいきょうを およぼす。', 'Pemanasan global memberikan pengaruh buruk pada lingkungan.'),
('ex_n3_auto_2209', 'v_n3_auto_2209', '荷物を棚から下ろすのを手伝って。', 'にもつを たなから おろすのを てつだって。', 'Tolong bantu aku menurunkan barang dari rak.'),
('ex_n3_auto_2210', 'v_n3_auto_2210', '隣の部屋からピアノの音が聞こえる。', 'となりの へやから ピアノの おとが きこえる。', 'Terdengar suara piano dari kamar sebelah.'),
('ex_n3_auto_2211', 'v_n3_auto_2211', 'この地方は一年を通じて温暖な気候だ。', 'この ちほうは いちねんを つうじて おんだんな きこうだ。', 'Wilayah ini memiliki iklim yang hangat sepanjang tahun.'),
('ex_n3_auto_2212', 'v_n3_auto_2212', '部屋の温度をエアコンで調節する。', 'へやの おんどを エアコンで ちょうせつ する。', 'Mengatur suhu ruangan dengan AC.'),
('ex_n3_auto_2213', 'v_n3_auto_2213', 'この製品のテスト結果は可だった。', 'この せいひんの テスト けっかは か だった。', 'Hasil pengujian produk ini adalah cukup.'),
('ex_n3_auto_2214', 'v_n3_auto_2214', '海辺で美しい貝を拾った。', 'うみべで うつくしい かいを ひろった。', 'Memungut kerang yang indah di tepi laut.'),
('ex_n3_auto_2215', 'v_n3_auto_2215', '喫煙は健康に多くの害をもたらす。', 'きつえんは けんこうに おおくの がいをもたらす。', 'Merokok mendatangkan banyak bahaya bagi kesehatan.'),
('ex_n3_auto_2216', 'v_n3_auto_2216', 'スポーツクラブの会員になる。', 'スポーツクラブの かいいんに なる。', 'Menjadi anggota klub olahraga.'),
('ex_n3_auto_2217', 'v_n3_auto_2217', '美術館で有名な絵画を鑑賞する。', 'びじゅつかんで ゆうめいな かいがを かんしょう する。', 'Menikmati lukisan terkenal di museum seni.'),
('ex_n3_auto_2218', 'v_n3_auto_2218', '夏休みに海外旅行に行く計画を立てる。', 'なつやすみに かいがい りょこうに いく けいかくを たてる。', 'Membuat rencana pergi berlibur ke luar negeri pada libur musim panas.'),
('ex_n3_auto_2219', 'v_n3_auto_2219', '食事の後にレジで会計を済ませる。', 'しょくじの あとに レジで かいけいを すませる。', 'Menyelesaikan pembayaran di kasir setelah makan.'),
('ex_n3_auto_2220', 'v_n3_auto_2220', '明日の午後に親睦の会合を開く。', 'あしたの ごごに しんぼくの かいごうを ひらく。', 'Mengadakan pertemuan keakraban besok siang.'),
('ex_n3_auto_2221', 'v_n3_auto_2221', 'まもなく会議が開始されます。', 'まもなく かいぎが かいし されます。', 'Sebentar lagi rapat akan dimulai.'),
('ex_n3_auto_2222', 'v_n3_auto_2222', 'この文章の解釈にはいくつかの方法がある。', 'この ぶんしょうの かいしゃくには いくつかの ほうほうがある。', 'Ada beberapa metode untuk penafsiran kalimat ini.'),
('ex_n3_auto_2223', 'v_n3_auto_2223', '風が強いので、今日の外出は控える。', 'かぜが つよいので、 きょうの がいしゅつは ひかえる。', 'Karena angin kencang, menahan diri untuk pergi keluar hari ini.'),
('ex_n3_auto_2224', 'v_n3_auto_2224', '彼は病気から無事に回復した。', 'かれは びょうきから ぶじに かいふく した。', 'Dia telah pulih dari penyakitnya dengan selamat.'),
('ex_n3_auto_2225', 'v_n3_auto_2225', '遅くなったので、子供を早く家に帰す。', 'おそくなったので、 こどもを はやく いえに かえす。', 'Karena sudah larat malam, segera memulangkan anak ke rumah.'),
('ex_n3_auto_2226', 'v_n3_auto_2226', '台所から美味しそうなカレーの香りが漂ってくる。', 'だいどころから おいしそうな カレーの かおりが ただよってくる。', 'Aroma kari yang lezat tercium menyebar dari dapur.'),
('ex_n3_auto_2227', 'v_n3_auto_2227', '大学で化学を専攻している。', 'だいがくで かがくを せんこう している。', 'Mengambil jurusan kimia di universitas.'),
('ex_n3_auto_2228', 'v_n3_auto_2228', '夜空に満天の星が輝いている。', 'よぞらに まんてんの ほしが かがやいている。', 'Bintang-bintang di seluruh langit bersinar di langit malam.'),
('ex_n3_auto_2229', 'v_n3_auto_2229', 'イベントの受付係を任された。', 'イベントの うけつけがかりを まかされた。', 'Diserahi tugas sebagai petugas penerima tamu acara.'),
('ex_n3_auto_2230', 'v_n3_auto_2230', '新型のインフルエンザに罹ってしまった。', 'しんがたの インフルエンザに かかって しまった。', 'Aku terjangkit virus influenza tipe baru.'),
('ex_n3_auto_2231', 'v_n3_auto_2231', '参加者は先着１０名に限ります。', 'さんかしゃは せんちゃく じゅうめいに かぎります。', 'Peserta dibatasi hanya untuk 10 pendaftar pertama.'),
('ex_n3_auto_2232', 'v_n3_auto_2232', '花のにおいを鼻で嗅ぐ。', 'はなの においを はなで かぐ。', 'Mencium wangi bunga dengan hidung.'),
('ex_n3_auto_2233', 'v_n3_auto_2233', '彼は学問の道をひたすら進んだ。', 'かれは がくもんの みちを ひたすら すすんだ。', 'Dia terus melaju menempuh jalan keilmuan.'),
('ex_n3_auto_2234', 'v_n3_auto_2234', 'どんな困難も乗り越える覚悟だ。', 'どんな こんなんも のりこえる かくごだ。', 'Aku bertekad untuk melewati kesulitan apa pun.'),
('ex_n3_auto_2235', 'v_n3_auto_2235', '彼なら確実に約束を守るだろう。', 'かれなら かくじつに やくそくを まもるだろう。', 'Jika dia, dia pasti akan menepati janji.'),
('ex_n3_auto_2236', 'v_n3_auto_2236', '私の祖父は言語学者でした。', 'わたしの そふは げんごがくしゃ でした。', 'Kakek saya dahulu adalah seorang ilmuwan bahasa.'),
('ex_n3_auto_2237', 'v_n3_auto_2237', '効果的な学習方法を見つける。', 'こうかてきな がくしゅう ほうほうを みつける。', 'Menemukan metode belajar yang efektif.'),
('ex_n3_auto_2238', 'v_n3_auto_2238', '画像を２倍に拡大して印刷する。', 'がぞうを にばいに かくだい して いんさつ する。', 'Mencetak gambar setelah memperbesarnya menjadi 2 kali lipat.'),
('ex_n3_auto_2239', 'v_n3_auto_2239', '学問に励む若者を支援する。', 'がくもんに はげむ わかものを しえん する。', 'Mendukung para pemuda yang giat dalam menuntut ilmu.'),
('ex_n3_auto_2240', 'v_n3_auto_2240', '夕日に照らされて影が長く伸びる。', 'ゆうひに てらされて かげが ながく のびる。', 'Disinari oleh matahari terbenam bayangan memanjang.'),
('ex_n3_auto_2241', 'v_n3_auto_2241', 'お体の加減はいかがですか。', 'おからだの かげんは いかが ですか。', 'Bagaimanakah kondisi tubuh Anda?'),
('ex_n3_auto_2242', 'v_n3_auto_2242', '過去の失敗を繰り返さないようにする。', 'かこの しっぱいを くりかえさない ように する。', 'Berusaha agar tidak mengulangi kesalahan masa lalu.'),
('ex_n3_auto_2243', 'v_n3_auto_2243', '買い物かごに果物をたくさん入れた。', 'かいものかごに くだものを たくさん いれた。', 'Memasukkan banyak buah ke dalam keranjang belanja.'),
('ex_n3_auto_2244', 'v_n3_auto_2244', 'テーブルを囲んでみんなで話し合う。', 'テーブルを かこんで みんなで はなしあう。', 'Semua orang berbicara bersama dengan mengelilingi meja.'),
('ex_n3_auto_2245', 'v_n3_auto_2245', '冬は乾燥して火災が発生しやすい。', 'ふゆは かんそう して かさいが はっせい しやすい。', 'Musim dingin cenderung terjadi kebakaran karena udaranya kering.'),
('ex_n3_auto_2246', 'v_n3_auto_2246', '本を机の上に何冊も重ねる。', 'ほんを つくえの うえに なんさつも かさねる。', 'Menumpuk beberapa buah buku di atas meja.'),
('ex_n3_auto_2247', 'v_n3_auto_2247', 'クリスマスツリーに飾りをつける。', 'クリスマスツリーに かざりを つける。', 'Memasang hiasan pada pohon natal.'),
('ex_n3_auto_2248', 'v_n3_auto_2248', '料理や洗濯などの家事を分担する。', 'りょうりや せんたく などの かじを ぶんたん する。', 'Membagi tugas pekerjaan rumah seperti memasak dan mencuci.'),
('ex_n3_auto_2249', 'v_n3_auto_2249', '最新型のスマートフォンを購入した。', 'さいしんがたの スマートフォンを こうにゅう した。', 'Membeli ponsel pintar tipe terbaru.'),
('ex_n3_auto_2250', 'v_n3_auto_2250', '集まった方々に感謝します。', 'あつまった かたがたに かんしゃ します。', 'Berterima kasih kepada orang-orang yang telah berkumpul.'),
('ex_n3_auto_2251', 'v_n3_auto_2251', '部屋がようやくきれいに片付いた。', 'へやが ようやく きれいに かたづいた。', 'Kamar akhirnya beres dengan rapi.'),
('ex_n3_auto_2252', 'v_n3_auto_2252', '侍は腰に日本刀を差していた。', 'さむらいは こしに にほんとうを さしていた。', 'Samurai menyelipkan katana Jepang di pinggangnya.'),
('ex_n3_auto_2253', 'v_n3_auto_2253', '祖父が戦時の体験を熱心に語った。', 'そふが せんじの たいけんを ねっしんに かたった。', 'Kakek menceritakan pengalaman masa perangnya dengan antusias.'),
('ex_n3_auto_2254', 'v_n3_auto_2254', '彼は新チームで大いに活躍している。', 'かれは しんチームで おおいに かつやく している。', 'Dia sangat berkiprah aktif di tim yang baru.'),
('ex_n3_auto_2255', 'v_n3_auto_2255', '限られた資源を有効に活用する。', 'かぎられた しげんを ゆうこうに かつよう する。', 'Memanfaatkan sumber daya yang terbatas secara efektif.'),
('ex_n3_auto_2256', 'v_n3_auto_2256', 'この計画は一定の仮定に基づいている。', 'この けいかくは いっていの かていに もとづいている。', 'Rencana ini didasarkan pada pengandaian tertentu.'),
('ex_n3_auto_2257', 'v_n3_auto_2257', 'ペットの死を深く悲しむ。', 'ペットの しを ふかく かなしむ。', 'Sangat bersedih atas kematian hewan peliharaan.'),
('ex_n3_auto_2258', 'v_n3_auto_2258', '旅行に行くためにお金を貯める。', 'りょこうに いく ために おかねを ためる。', 'Menabung uang untuk pergi berlibur.'),
('ex_n3_auto_2259', 'v_n3_auto_2259', '企業の株を購入して投資する。', 'きぎょうの かぶを こうにゅう して とうし する。', 'Membeli saham perusahaan untuk berinvestasi.'),
('ex_n3_auto_2260', 'v_n3_auto_2260', '日差しが強いので帽子を被る。', 'ひざしが つよいので ぼうしを かぶる。', 'Memakai topi karena sengatan matahari yang kuat.'),
('ex_n3_auto_2261', 'v_n3_auto_2261', '痛みを我慢して走り続けた。', 'いたみを がまん して はしりつづけた。', 'Menahan rasa sakit dan terus berlari.'),
('ex_n3_auto_2262', 'v_n3_auto_2262', '病気が治るように神に祈る。', 'びょうきが なおる ように かみに いのる。', 'Berdoa kepada Tuhan agar penyakitnya sembuh.'),
('ex_n3_auto_2263', 'v_n3_auto_2263', '風で髪の毛が乱れてしまった。', 'かぜで かみのけが みだれて しまった。', 'Rambut kepalaku menjadi acak-acakan karena angin.'),
('ex_n3_auto_2264', 'v_n3_auto_2264', 'あなたの好きな科目は何ですか。', 'あなたの すきな かもくは なん ですか。', 'Apa mata pelajaran kesukaan Anda?'),
('ex_n3_auto_2265', 'v_n3_auto_2265', '中身がない空の箱を捨てる。', 'なかみが ない からの はこを すてる。', 'Membuang kotak kosong yang tidak ada isinya.'),
('ex_n3_auto_2266', 'v_n3_auto_2266', '庭の雑草を刈る作業をする。', 'にわの ざっそうを かる さぎょうを する。', 'Melakukan pekerjaan memotong rumput liar di halaman.'),
('ex_n3_auto_2267', 'v_n3_auto_2267', '捨てられた子犬が可愛そうだ。', 'すてられた こいぬが かわいそうだ。', 'Anak anjing yang dibuang itu kasihan.'),
('ex_n3_auto_2268', 'v_n3_auto_2268', '彼女は可愛らしいリボンをつけている。', 'かのじょは かわいらしい リボンを つけている。', 'Dia memakai pita yang manis.'),
('ex_n3_auto_2269', 'v_n3_auto_2269', '濡れた髪をドライヤーで乾かす。', 'ぬれた かみを ドライヤーで かわかす。', 'Mengeringkan rambut yang basah dengan pengering rambut.'),
('ex_n3_auto_2270', 'v_n3_auto_2270', 'のどが渇いたので水が飲みたい。', 'のどが かわいたので みずが のみたい。', 'Aku ingin minum air karena tenggorokan terasa haus.'),
('ex_n3_auto_2271', 'v_n3_auto_2271', '空き缶をリサイクルの箱に入れる。', 'あきかんを リサイクルの はこに いれる。', 'Memasukkan kaleng kosong ke kotak daur ulang.'),
('ex_n3_auto_2272', 'v_n3_auto_2272', '自分の考えを相手にしっかり伝える。', 'じぶんの かんがえを あいてに しっかり つたえる。', 'Menyampaikan pemikiran sendiri dengan mantap kepada lawan bicara.'),
('ex_n3_auto_2273', 'v_n3_auto_2273', '寒さで手の指の感覚がなくなった。', 'さむさで ての ゆびの かんかくが なくなった。', 'Kehilangan indra peraba jari tangan karena dingin.'),
('ex_n3_auto_2274', 'v_n3_auto_2274', '新しいメンバーを心から歓迎する。', 'あたらしい メンバーを こころから かんげい する。', 'Menyambut baik anggota baru dari lubuk hati.'),
('ex_n3_auto_2275', 'v_n3_auto_2275', '植物の成長の様子を毎日観察する。', 'しょくぶつの せいちょうの ようすを まいにち かんさつ する。', 'Mengamati kondisi pertumbuhan tanaman setiap hari.'),
('ex_n3_auto_2276', 'v_n3_auto_2276', 'あの人には優しい感じがする。', 'あの ひとには やさしい かんじが する。', 'Orang itu memberikan kesan yang ramah.'),
('ex_n3_auto_2277', 'v_n3_auto_2277', '医師が患者の容態をチェックする。', 'いしが かんじゃの ようだいを チェック する。', 'Dokter memeriksa kondisi kesehatan pasien.'),
('ex_n3_auto_2278', 'v_n3_auto_2278', '彼の親切な行いには本当に感心した。', 'かれの しんせつな おこないには ほんとうに かんしん した。', 'Aku benar-benar kagum atas tindakan ramahnya.'),
('ex_n3_auto_2279', 'v_n3_auto_2279', '日本の文化に関する本を読む。', 'にほんの ぶんかに かんする ほんを よむ。', 'Membaca buku berkaitan dengan budaya Jepang.'),
('ex_n3_auto_2280', 'v_n3_auto_2280', '新しいビルがようやく完成した。', 'あたらしい ビルが ようやく かんせい した。', 'Gedung baru akhirnya selesai dibangun.'),
('ex_n3_auto_2281', 'v_n3_auto_2281', '冬は空気が乾燥しやすい。', 'ふゆは くうきが かんそう しやすい。', 'Udara mudah mengering saat musim dingin.'),
('ex_n3_auto_2282', 'v_n3_auto_2282', '彼のスピーチを聞いて深く感動した。', 'かれの スピーチを きいて ふかく かんどう した。', 'Aku merasa sangat terharu mendengarkan pidatonya.'),
('ex_n3_auto_2283', 'v_n3_auto_2283', '彼は映画監督として有名だ。', 'かれは えいが かんとく として ゆうめいだ。', 'Dia terkenal sebagai sutradara film.'),
('ex_n3_auto_2284', 'v_n3_auto_2284', 'ファイルのダウンロードが完了した。', 'ファイルの ダウンロードが かんりょう した。', 'Pengunduhan berkas telah selesai.'),
('ex_n3_auto_2285', 'v_n3_auto_2285', '二つの事件の関連性を調査する。', 'ふたつの じけんの かんれんせいを ちょうさ する。', 'Menyelidiki kaitan di antara kedua peristiwa itu.'),
('ex_n3_auto_2286', 'v_n3_auto_2286', '国会議員が新しい法律について議論する。', 'こっかいぎいんが あたらしい ほうりつについて ぎろん する。', 'Anggota dewan parlemen berdiskusi tentang undang-undang baru.'),
('ex_n3_auto_2287', 'v_n3_auto_2287', '子供のころの記憶が薄れていく。', 'こどもの ころの きおくが うすれていく。', 'Ingatan masa kanak-kanak sedang memudar.'),
('ex_n3_auto_2288', 'v_n3_auto_2288', '船が川の岸に近づいていく。', 'ふねが かわの きしに ちかづいていく。', 'Perahu mendekat ke tepi sungai.'),
('ex_n3_auto_2289', 'v_n3_auto_2289', '彼は機械技師として工場で働いている。', 'かれは きかいぎし として こうじょうで はたらいている。', 'Dia bekerja di pabrik sebagai teknisi mesin.'),
('ex_n3_auto_2290', 'v_n3_auto_2290', '新聞記者が事件の現場を取材する。', 'しんぶんきしゃが じけんの げんばを しゅざい する。', 'Wartawan surat kabar meliput di tempat kejadian perkara.'),
('ex_n3_auto_2291', 'v_n3_auto_2291', '親の期待に応えるために勉強する。', 'おやの きたいに こたえる ために べんきょう する。', 'Belajar untuk memenuhi ekspektasi orang tua.'),
('ex_n3_auto_2292', 'v_n3_auto_2292', '仕事が終わって、すぐに帰宅した。', 'しごとが おわって、 すぐに きたく した。', 'Pekerjaan selesai, dan langsung pulang ke rumah.'),
('ex_n3_auto_2293', 'v_n3_auto_2293', '貴重なご意見をいただきありがとうございます。', 'きちょうな ごいけんを いただき ありがとう ございます。', 'Terima kasih banyak atas saran Anda yang berharga.'),
('ex_n3_auto_2294', 'v_n3_auto_2294', '会議の議長が新しい規則を説明した。', 'かいぎの ぎちょうが あたらしい きそくを せつめい した。', 'Ketua rapat menjelaskan peraturan yang baru.'),
('ex_n3_auto_2295', 'v_n3_auto_2295', 'このデザインが気に入りました。', 'この デザインが きにいりました。', 'Saya menyukai desain ini.'),
('ex_n3_auto_2296', 'v_n3_auto_2296', '申請書に必要事項を記入する。', 'しんせいしょに ひつよう じこうを きにゅう する。', 'Mengisi hal-hal yang diperlukan pada surat permohonan.'),
('ex_n3_auto_2297', 'v_n3_auto_2297', '創立１０周年の記念式典を行う。', 'そうりつ じゅっしゅうねんの きねん しきてんを おこなう。', 'Mengadakan upacara peringatan hari jadi pendirian yang ke-10.'),
('ex_n3_auto_2298', 'v_n3_auto_2298', '事故に遭ったと聞いて、本当にお気の毒に思います。', 'じこに あったと きいて、 ほんとうに おきのどくに おもいます。', 'Mendengar dia mengalami kecelakaan, saya benar-benar merasa prihatin.'),
('ex_n3_auto_2299', 'v_n3_auto_2299', '何事も基本を学ぶことが大切だ。', 'なにごとも きほんを まなぶ ことが たいせつだ。', 'Mempelajari dasar dari apa pun adalah hal yang penting.'),
('ex_n3_auto_2300', 'v_n3_auto_2300', '学校の決まりをしっかり守る。', 'がっこうの きまりを しっかり まもる。', 'Mematuhi peraturan sekolah dengan baik.'),
('ex_n3_auto_2301', 'v_n3_auto_2301', '風邪気味なので、今日は早めに寝る。', 'かぜぎみ なので、 きょうは はやめに ねる。', 'Karena agak terserang flu, hari ini tidur lebih awal.'),
('ex_n3_auto_2302', 'v_n3_auto_2302', '真夜中に奇妙な音が聞こえた。', 'まよなかに きみょうな おとが きこえた。', 'Terdengar suara aneh di tengah malam.'),
('ex_n3_auto_2303', 'v_n3_auto_2303', '彼の説明には多くの疑問が残る。', 'かれの せつめいには おおくの ぎもんが のこる。', 'Pada penjelasannya menyisakan banyak keraguan.'),
('ex_n3_auto_2304', 'v_n3_auto_2304', '予想とは逆の結果になった。', 'よそうとは ぎゃくの けっかに なった。', 'Hasilnya menjadi kebalikan dari apa yang diperkirakan.'),
('ex_n3_auto_2305', 'v_n3_auto_2305', '旧友と久しぶりに会って食事をした。', 'きゅうゆうと ひさしぶりに あって しょくじを した。', 'Bertemu dan makan bersama teman lama setelah sekian lama.')
ON CONFLICT (id) DO NOTHING;
