-- Seed data for N4 Vocabulary Examples (Total: 644)

INSERT INTO public.vocabulary_examples (id, vocab_id, japanese, reading, translation) VALUES
('ex_n4_auto_1', 'v_n4_auto_1', '友達にプレゼントを送りました。', 'ともだち に プレゼント を おくりました。', 'Saya telah mengirim hadiah kepada teman.'),
('ex_n4_auto_2', 'v_n4_auto_2', '失くした鍵を探しています。', 'なくした かぎ を さがしています。', 'Saya sedang mencari kunci yang hilang.'),
('ex_n4_auto_3', 'v_n4_auto_3', '急げば電車に間に合います。', 'いそげば でんしゃ に まにあいます。', 'Jika bergegas, kita akan sempat naik kereta.'),
('ex_n4_auto_4', 'v_n4_auto_4', '道で財布を拾いました。', 'みち で さいふ を ひろいました。', 'Saya memungut dompet di jalan.'),
('ex_n4_auto_5', 'v_n4_auto_5', '毎日電車で大学に通っています。', 'まいにち でんしゃ で だいがく に かよっています。', 'Setiap hari saya pulang pergi kuliah naik kereta.'),
('ex_n4_auto_6', 'v_n4_auto_6', 'みんなで盆踊りを踊りましょう。', 'みんな で ぼんおどり を おどりましょう。', 'Mari kita menari tarian Bon bersama.'),
('ex_n4_auto_7', 'v_n4_auto_7', 'ご飯はよく噛んで食べてください。', 'ごはん は よく かんで たべて ください。', 'Makanlah nasi dengan mengunyahnya baik-baik.'),
('ex_n4_auto_8', 'v_n4_auto_8', 'たくさんの中から好きなものを選んでください。', 'たくさん の なか から すきな もの を えらんで ください。', 'Pilihlah yang Anda sukai dari sekian banyak pilihan.'),
('ex_n4_auto_9', 'v_n4_auto_9', '友達を映画に誘いました。', 'ともだち を えいが に さそいました。', 'Saya mengajak teman menonton film.'),
('ex_n4_auto_10', 'v_n4_auto_10', '明日、朝六時に起こしてください。', 'あした、あさ ろくじ に おこして ください。', 'Tolong bangunkan saya besok jam 6 pagi.'),
('ex_n4_auto_11', 'v_n4_auto_11', '彼は納得した様子でうなずきました。', 'かれ は なっとく した ようす で うなずきました。', 'Dia mengangguk seolah mengerti/setuju.'),
('ex_n4_auto_12', 'v_n4_auto_12', '先生を怒らせてしまいました。', 'せんせい を おこらせて しまいました。', 'Saya tidak sengaja membuat guru marah.'),
('ex_n4_auto_13', 'v_n4_auto_13', '今日は私が昼ご飯をおごりましょう。', 'きょう は わたし が ひるごはん を おごりましょう。', 'Hari ini biar saya yang traktir makan siang.'),
('ex_n4_auto_14', 'v_n4_auto_14', '母の料理を手伝います。', 'はは の りょうり を てつだいます。', 'Saya membantu ibu memasak.'),
('ex_n4_auto_15', 'v_n4_auto_15', 'レジでお金を払いました。', 'レジ で おかね を はらいました。', 'Saya membayar uang di kasir.'),
('ex_n4_auto_16', 'v_n4_auto_16', '彼女はいつも楽しそうに笑います。', 'かのじょ は いつも たのしそう に わらいます。', 'Dia selalu tertawa dengan tampak senang.'),
('ex_n4_auto_17', 'v_n4_auto_17', '泥棒が警察に捕まりました。', 'どろぼう が けいさつ に つかまりました。', 'Pencuri ditangkap oleh polisi.'),
('ex_n4_auto_18', 'v_n4_auto_18', '今、駅に向かっています。', 'いま、えき に むかっています。', 'Sekarang saya sedang menuju ke stasiun.'),
('ex_n4_auto_19', 'v_n4_auto_19', '風邪が弟にうつってしまいました。', 'かぜ が おとうと に うつって しまいました。', 'Penyakit flu menular ke adik laki-laki saya.'),
('ex_n4_auto_20', 'v_n4_auto_20', '洗濯物が太陽の光で乾きました。', 'せんたくもの が たいよう の ひかり で かわきました。', 'Cucian sudah kering karena sinar matahari.'),
('ex_n4_auto_21', 'v_n4_auto_21', 'ドライヤーを使って髪を乾かします。', 'ドライヤー を つかって かみ を かわかします。', 'Mengeringkan rambut menggunakan hair dryer.'),
('ex_n4_auto_22', 'v_n4_auto_22', 'この試験は難しいと思います。', 'この しけん は むずかしい と おもいます。', 'Saya pikir ujian ini sulit.'),
('ex_n4_auto_23', 'v_n4_auto_23', '会議は来週行われます。', 'かいぎ は らいしゅう おこなわれます。', 'Rapat akan diadakan minggu depan.'),
('ex_n4_auto_24', 'v_n4_auto_24', 'すぐ事務所に戻ります。', 'すぐ じむしょ に もどります。', 'Saya akan segera kembali ke kantor.'),
('ex_n4_auto_25', 'v_n4_auto_25', 'おもちゃを壊してしまいました。', 'おもちゃ を こわして しまいました。', 'Saya tidak sengaja merusak mainannya.'),
('ex_n4_auto_26', 'v_n4_auto_26', '部長の代わりに出張へ行きます。', 'ぶちょう の かわり に しゅっちょう へ いきます。', 'Pergi dinas untuk menggantikan Manajer.'),
('ex_n4_auto_27', 'v_n4_auto_27', '自転車のパンクを直しました。', 'じてんしゃ の パンク を なおしました。', 'Saya memperbaiki ban sepeda yang bocor.'),
('ex_n4_auto_28', 'v_n4_auto_28', 'このつまみを右に回してください。', 'この つまみ を みぎ に まわして ください。', 'Tolong putar tombol ini ke kanan.'),
('ex_n4_auto_29', 'v_n4_auto_29', '熱いお茶を少し冷ましてから飲みます。', 'あつい おちゃ を すこし さまして から のみます。', 'Mendinginkan teh panas sedikit sebelum meminumnya.'),
('ex_n4_auto_30', 'v_n4_auto_30', '不注意でコップを倒してしまいました。', 'ふちゅうい で コップ を たおして しまいました。', 'Saya tidak sengaja menjatuhkan gelas karena kurang hati-hati.'),
('ex_n4_auto_31', 'v_n4_auto_31', '駅の近くに新しいビルが建ちました。', 'えき の ちかく に あたらしい ビル が たちました。', 'Gedung baru telah didirikan di dekat stasiun.'),
('ex_n4_auto_32', 'v_n4_auto_32', '食べ物を残さないでください。', 'たべもの を のこさないで ください。', 'Tolong jangan menyisakan makanan.'),
('ex_n4_auto_33', 'v_n4_auto_33', 'お湯を沸かしてコーヒーを淹れます。', 'おゆ を わかして コーヒー を いれます。', 'Mendidihkan air panas lalu menyeduh kopi.'),
('ex_n4_auto_34', 'v_n4_auto_34', 'スープの味が薄いので塩を足します。', 'スープ の あじ が うすい ので しお を たします。', 'Menambahkan garam karena rasa supnya hambar.'),
('ex_n4_auto_35', 'v_n4_auto_35', '針に糸を通すのは根気が要ります。', 'はり に いと を とおす の は こんき が いります。', 'Memasukkan benang ke jarum membutuhkan kesabaran.'),
('ex_n4_auto_36', 'v_n4_auto_36', '荷物を別の部屋に移しました。', 'にもつ を べつの へや に うつしました。', 'Saya memindahkan barang bawaan ke kamar lain.'),
('ex_n4_auto_37', 'v_n4_auto_37', 'どこかで財布を落としてしまいました。', 'どこか で さいふ を おとす て しまいました。', 'Saya tidak sengaja menjatuhkan dompet di suatu tempat.'),
('ex_n4_auto_38', 'v_n4_auto_38', '田舎の両親から荷物が届きました。', 'いなか の りょうしん から にもつ が とどきました。', 'Paket dari orang tua di desa telah sampai.'),
('ex_n4_auto_39', 'v_n4_auto_39', '公園で子供たちが遊んでいます。', 'こうえん で こどもたち が あそんでいます。', 'Anak-anak sedang bermain di taman.'),
('ex_n4_auto_40', 'v_n4_auto_40', '友達に手を振って挨拶をしました。', 'ともだち に て を ふって あいさつ を しました。', 'Melambaikan tangan kepada teman untuk memberi salam.'),
('ex_n4_auto_41', 'v_n4_auto_41', '人口が減って学校が閉鎖されました。', 'じんこう が へって がっこう が へいさ されました。', 'Sekolah ditutup karena jumlah penduduk berkurang.'),
('ex_n4_auto_42', 'v_n4_auto_42', '日本での生活を楽しんでいます。', 'にほん で の せいかつ を たのしんでいます。', 'Saya sedang menikmati kehidupan di Jepang.'),
('ex_n4_auto_43', 'v_n4_auto_43', '体重を減らすために運動を始めました。', 'たいじゅう を へらす ため に うんどう を はじめました。', 'Mulai berolahraga untuk mengurangi berat badan.'),
('ex_n4_auto_44', 'v_n4_auto_44', 'スマホは生活にとても役立ちます。', 'スマホ は せいかつ に とても やくだちます。', 'Smartphone sangat bermanfaat dalam kehidupan sehari-hari.'),
('ex_n4_auto_45', 'v_n4_auto_45', '電車の中で足を踏まれました。', '電しゃ の なか で あし を ふまれました。', 'Kaki saya terinjak di dalam kereta.'),
('ex_n4_auto_46', 'v_n4_auto_46', 'プレゼントを綺麗な紙で包みました。', 'プレゼント を きれいな かみ で つつみました。', 'Saya membungkus kado dengan kertas yang indah.'),
('ex_n4_auto_47', 'v_n4_auto_47', '朝の電車はとても込んでいます。', 'あさ の でんしゃ は とても こんでいます。', 'Kereta pagi hari sangat padat.'),
('ex_n4_auto_48', 'v_n4_auto_48', '素晴らしいビジネスのアイデアを思いつきました。', 'すばらしい ビジネス の アイデア を おもいつきました。', 'Saya memikirkan ide bisnis yang luar biasa.'),
('ex_n4_auto_49', 'v_n4_auto_49', '彼の失礼な態度に苛立ちました。', 'かれ の しつれいな たいど に いらだちました。', 'Saya merasa gusar dengan sikapnya yang tidak sopan.'),
('ex_n4_auto_50', 'v_n4_auto_50', '赤ちゃんが大きな声で泣いています。', 'あかちゃん が おおきな こえ で ないています。', 'Bayi sedang menangis dengan suara keras.'),
('ex_n4_auto_51', 'v_n4_auto_51', 'この青いシャツがとても気に入りました。', 'この あおい シャツ が とても きにいりました。', 'Saya sangat menyukai kemeja biru ini.'),
('ex_n4_auto_52', 'v_n4_auto_52', '自分の間違いにすぐ気がつきました。', 'じぶん の まちがい に すぐ き が つきました。', 'Saya segera menyadari kesalahan saya.'),
('ex_n4_auto_53', 'v_n4_auto_53', '親と同じ間違いを繰り返さないでください。', 'おなじ まちがい を くりかえさないで ください。', 'Jangan mengulangi kesalahan yang sama.'),
('ex_n4_auto_54', 'v_n4_auto_54', '彼は一人で静かに暮らしています。', 'かれ は ひとり で しずかに くらしています。', 'Dia hidup sendirian dengan tenang.'),
('ex_n4_auto_55', 'v_n4_auto_55', '私たちのチームが試合に勝ちました。', 'わたし たち の チーム が しあい に かちました。', 'Tim kami menang dalam pertandingan.'),
('ex_n4_auto_56', 'v_n4_auto_56', '先生のご自宅に伺いました。', 'せんせい の ごじたく に うかがいました。', 'Saya berkunjung ke kediaman Guru.'),
('ex_n4_auto_57', 'v_n4_auto_57', '子供は注射を嫌がります。', 'こども は ちゅうしゃ を いやがります。', 'Anak-anak tidak menyukai suntikan.'),
('ex_n4_auto_58', 'v_n4_auto_58', '友達の誕生日をみんなでお祝いします。', 'ともだち の たんじょうび を みんな で おわいします。', 'Merayakan hari ulang tahun teman bersama-sama.'),
('ex_n4_auto_59', 'v_n4_auto_59', '車を止めました。', 'くるま を とめました。', 'Saya menghentikan mobil.'),
('ex_n4_auto_60', 'v_n4_auto_60', '鍵を見つけました。', 'かぎ を みつけました。', 'Saya menemukan kunci.'),
('ex_n4_auto_61', 'v_n4_auto_61', '仕事を始めましょう。', 'しごと を はじめましょう。', 'Mari kita mulai pekerjaan.'),
('ex_n4_auto_62', 'v_n4_auto_62', '将来のことを考えます。', 'しょうらい の こと を かんがえます。', 'Saya memikirkan masa depan.'),
('ex_n4_auto_63', 'v_n4_auto_63', '辞書で言葉を調べます。', 'じしょ で ことば を しらべます。', 'Saya memeriksa kata di kamus.'),
('ex_n4_auto_64', 'v_n4_auto_64', '勉強を続けます。', 'べんきょう を つづけます。', 'Saya melanjutkan belajar.'),
('ex_n4_auto_65', 'v_n4_auto_65', '計画を立てました。', 'けいかく を たてました。', 'Saya menyusun rencana.'),
('ex_n4_auto_66', 'v_n4_auto_66', '家を建てました。', 'いえ を たてました。', 'Saya membangun rumah.'),
('ex_n4_auto_67', 'v_n4_auto_67', '旅行の日程を決めました。', 'りょこう の にってい を きめました。', 'Saya memutuskan jadwal perjalanan.'),
('ex_n4_auto_68', 'v_n4_auto_68', '彼を信じています。', 'かれ を しんじて います。', 'Saya mempercayainya.'),
('ex_n4_auto_69', 'v_n4_auto_69', '結果を知らせます。', 'けっか を しらせます。', 'Saya akan memberitahu hasilnya.'),
('ex_n4_auto_70', 'v_n4_auto_70', '花を育てています。', 'はな を そだてています。', 'Saya menanam/memelihara bunga.'),
('ex_n4_auto_71', 'v_n4_auto_71', '試合に負けました。', 'しあい に まけました。', 'Saya kalah dalam pertandingan.'),
('ex_n4_auto_72', 'v_n4_auto_72', '授業に遅れました。', 'じゅぎょう に おくれました。', 'Saya terlambat sekolah.'),
('ex_n4_auto_73', 'v_n4_auto_73', '庭に木を植えます。', 'にわ に き を うえます。', 'Menanam pohon di kebun.'),
('ex_n4_auto_74', 'v_n4_auto_74', '弱い立場の人をいじめてはいけません。', 'よわい たちば の ひと を いじめて は いけません。', 'Tidak boleh merundung orang yang posisinya lemah.'),
('ex_n4_auto_75', 'v_n4_auto_75', 'カメラが壊れました。', 'カメラ が こわれました。', 'Kamera telah rusak.'),
('ex_n4_auto_76', 'v_n4_auto_76', '皿が割れました。', 'さら が われました。', 'Piringnya pecah.'),
('ex_n4_auto_77', 'v_n4_auto_77', '枝が折れました。', 'えだ が おれました。', 'Dahannya patah.'),
('ex_n4_auto_78', 'v_n4_auto_78', '紙が破れました。', 'かみ が やぶれました。', 'Kertasnya robek.'),
('ex_n4_auto_79', 'v_n4_auto_79', '靴が汚れました。', 'くつ が よごれました。', 'Sepatunya kotor.'),
('ex_n4_auto_80', 'v_n4_auto_80', '番号を間違えました。', 'ばんごう を まちがえました。', 'Saya salah nomor.'),
('ex_n4_auto_81', 'v_n4_auto_81', '机の上を片付けます。', 'つくえ の うえ を かたづけます。', 'Membereskan bagian atas meja.'),
('ex_n4_auto_82', 'v_n4_auto_82', '誕生日をお祝いしました。', 'たんじょうび を おいわいしました。', 'Merayakan hari ulang tahun.'),
('ex_n4_auto_83', 'v_n4_auto_83', '彼を紹介します。', 'かれ を しょうかいします。', 'Memperkenalkan dia.'),
('ex_n4_auto_84', 'v_n4_auto_84', '京都をご案内します。', 'きょうと を ごあんないします。', 'Memandu Anda di Kyoto.'),
('ex_n4_auto_85', 'v_n4_auto_85', '文法を説明します。', 'ぶんぽう を せつめいします。', 'Menjelaskan tata bahasa.'),
('ex_n4_auto_86', 'v_n4_auto_86', '日本へ留学したいです。', 'にほん へ りゅうがく したい です。', 'Saya ingin belajar di Jepang.'),
('ex_n4_auto_87', 'v_n4_auto_87', 'トラックを運転します。', 'トラック を うんてんします。', 'Mengemudikan truk.'),
('ex_n4_auto_88', 'v_n4_auto_88', '席を予約しました。', 'せき を よやくしました。', 'Memesan tempat duduk.'),
('ex_n4_auto_89', 'v_n4_auto_89', '医師に相談しました。', 'いし に そうだんしました。', 'Berkonsultasi dengan dokter.'),
('ex_n4_auto_90', 'v_n4_auto_90', '明日連絡します。', 'あした れんらく します。', 'Besok saya hubungi.'),
('ex_n4_auto_91', 'v_n4_auto_91', '旅行を準備します。', 'りょこう を じゅんびします。', 'Mempersiapkan perjalanan.'),
('ex_n4_auto_92', 'v_n4_auto_92', '宿題を復習します。', 'しゅくだい を ふくしゅうします。', 'Mengulang PR.'),
('ex_n4_auto_93', 'v_n4_auto_93', '次の課を予習します。', 'つぎ の か を よしゅうします。', 'Mempersiapkan bab selanjutnya.'),
('ex_n4_auto_94', 'v_n4_auto_94', '大学を卒業します。', 'だいがく を そつぎょうします。', 'Lulus dari universitas.'),
('ex_n4_auto_95', 'v_n4_auto_95', '毎日運動しています。', 'まいにち うんどうしています。', 'Berolahraga setiap hari.'),
('ex_n4_auto_96', 'v_n4_auto_96', '子供を心配します。', 'こども を しんぱいします。', 'Khawatir dengan anak.'),
('ex_n4_auto_97', 'v_n4_auto_97', '彼を招待しました。', 'かれ を しょうたいしました。', 'Mengundang dia.'),
('ex_n4_auto_98', 'v_n4_auto_98', '途中で諦めないでください。', 'とちゅう で あきらめないで ください。', 'Tolong jangan menyerah di tengah jalan.'),
('ex_n4_auto_99', 'v_n4_auto_99', '遅刻したことを先生に謝りました。', 'ちこく した こと を せんせい に あやまりました。', 'Saya meminta maaf kepada guru karena terlambat.'),
('ex_n4_auto_100', 'v_n4_auto_100', '遅れそうなので急いでいます。', 'おくれそう なので いそいで います。', 'Saya bergegas karena sepertinya akan terlambat.'),
('ex_n4_auto_101', 'v_n4_auto_101', '家族の健康を神様に祈ります。', 'かぞく の けんこう を かみさま に いのります。', 'Berdoa kepada Tuhan demi kesehatan keluarga.'),
('ex_n4_auto_102', 'v_n4_auto_102', '来月、日本語能力試験を受けます。', 'らいげつ、にほんご のうりょく しけん を うけます。', 'Bulan depan saya akan mengikuti Ujian Kemampuan Bahasa Jepang.'),
('ex_n4_auto_103', 'v_n4_auto_103', 'この機械は電気で動きます。', 'この きかい は でんき で うごきます。', 'Mesin ini bergerak/berfungsi dengan listrik.'),
('ex_n4_auto_104', 'v_n4_auto_104', '黒板の字をノートに写しました。', 'こくばん の じ を ノート に うつしました。', 'Saya menyalin tulisan di papan tulis ke buku catatan.'),
('ex_n4_auto_105', 'v_n4_auto_105', '来週、隣の街に引っ越しで移ります。', 'らいしゅう、となり の まち に ひっこし で うつります。', 'Minggu depan saya pindah ke kota sebelah.'),
('ex_n4_auto_106', 'v_n4_auto_106', '木から木の葉が落ちました。', 'き から このは が おちました。', 'Daun pohon jatuh dari pohon.'),
('ex_n4_auto_107', 'v_n4_auto_107', '先生がそうおっしゃいました。', 'せんせい が そう おっしゃいました。', 'Guru berkata demikian.'),
('ex_n4_auto_108', 'v_n4_auto_108', 'そのニュースを聞いて驚きました。', 'その ニュース を きいて おどろきました。', 'Saya terkejut mendengar berita itu.'),
('ex_n4_auto_109', 'v_n4_auto_109', '子供の頃のことを思い出しました。', 'こども の ころ の こと を おもいだしました。', 'Saya teringat masa kecil dahulu.'),
('ex_n4_auto_110', 'v_n4_auto_110', '紙を半分に折ってください。', 'かみ を はんぶん に おって ください。', 'Tolong lipat kertasnya menjadi dua.'),
('ex_n4_auto_111', 'v_n4_auto_111', '部屋に綺麗な花を飾りました。', 'へや に きれいな はな を かざりました。', 'Saya menghias kamar dengan bunga yang indah.'),
('ex_n4_auto_112', 'v_n4_auto_112', '部屋がやっと片付きました。', 'へや が やっと かたづきました。', 'Kamarnya akhirnya rapi juga.'),
('ex_n4_auto_113', 'v_n4_auto_113', '信号が赤から緑に変わりました。', 'しんごう が あか から みどり に かわりました。', 'Lampu lalu lintas berubah dari merah ke hijau.'),
('ex_n4_auto_114', 'v_n4_auto_114', '予定を少し変えました。', 'よてい を すこし かえました。', 'Saya sedikit mengubah jadwal rencana.'),
('ex_n4_auto_115', 'v_n4_auto_115', '試験に合格するために頑張ります。', 'しけん に ごうかく する ため に がんばります。', 'Saya akan berjuang keras untuk lulus ujian.'),
('ex_n4_auto_116', 'v_n4_auto_116', '出発の日が決まりました。', 'しゅっぱつ の ひ が きまりました。', 'Hari keberangkatan telah diputuskan.'),
('ex_n4_auto_117', 'v_n4_auto_117', '二つのカメラの性能を比べます。', 'ふたつ の カメラ の せいのう を くらべます。', 'Membandingkan performa dua kamera.'),
('ex_n4_auto_118', 'v_n4_auto_118', '友達が本をくれました。', 'ともだち が ほん を くれました。', 'Teman memberi saya buku.'),
('ex_n4_auto_119', 'v_n4_auto_119', '熱が下がって良くなりました。', 'ねつ が さがって よく なりました。', 'Demamnya sudah turun dan membaik.'),
('ex_n4_auto_120', 'v_n4_auto_120', '音量を少し下げてください。', 'おんりょう を すこし さげて ください。', 'Tolong turunkan sedikit volumenya.'),
('ex_n4_auto_121', 'v_n4_auto_121', '教室で騒いではいけません。', 'きょうしつ で さわいでは いけません。', 'Tidak boleh membuat keributan di kelas.'),
('ex_n4_auto_122', 'v_n4_auto_122', '展示品に触らないでください。', 'てんじひん に さわらないで ください。', 'Tolong jangan menyentuh barang pajangan.'),
('ex_n4_auto_123', 'v_n4_auto_123', '宿題をしなかったので叱られました。', 'しゅくだい を しなかった ので しかられました。', 'Saya dimarahi karena tidak mengerjakan PR.'),
('ex_n4_auto_124', 'v_n4_auto_124', '約束の時間を過ぎてしまいました。', 'やくそく の じかん を すぎて しまいました。', 'Waktunya sudah melewati jam perjanjian.'),
('ex_n4_auto_125', 'v_n4_auto_125', 'お腹が空きましたね。', 'おなか が すきました ね。', 'Perut sudah lapar ya.'),
('ex_n4_auto_126', 'v_n4_auto_126', '計画は順調に進んでいます。', 'けいかく は じんちょう に すすんでいます。', 'Rencananya berjalan/maju dengan lancar.'),
('ex_n4_auto_127', 'v_n4_auto_127', '道が凍って滑りやすいです。', 'みち が こおって すべりやすい です。', 'Jalanan membeku sehingga mudah terpeleset.'),
('ex_n4_auto_128', 'v_n4_auto_128', '田舎で健康に育ちました。', 'いなか で けんこう に そだちました。', 'Tumbuh besar dengan sehat di desa.'),
('ex_n4_auto_129', 'v_n4_auto_129', '台風で木が倒れました。', 'たいふう で き が たおれました。', 'Pohon tumbang karena angin topan.'),
('ex_n4_auto_130', 'v_n4_auto_130', '困っている人を助けます。', 'こまっている ひと を たすけます。', 'Menolong orang yang sedang kesulitan.'),
('ex_n4_auto_131', 'v_n4_auto_131', '週末に先生の家を訪ねました。', 'しゅうまつ に せんせい の いえ を たずねました。', 'Saya mengunjungi rumah guru pada akhir pekan.'),
('ex_n4_auto_132', 'v_n4_auto_132', '生活費はこれで足ります。', 'せいかつひ は これ で たります。', 'Uang biaya hidup cukup dengan ini.'),
('ex_n4_auto_133', 'v_n4_auto_133', '彼に伝言を伝えてください。', 'かれ に でんごん を つたえて ください。', 'Tolong sampaikan pesan kepada dia.'),
('ex_n4_auto_134', 'v_n4_auto_134', '雨が何日も続いています。', 'あめ が なんにち も つづいています。', 'Hujan terus berlanjut selama beberapa hari.'),
('ex_n4_auto_135', 'v_n4_auto_135', '子供を動物園へ連れて行きます。', 'こども を どうぶつえん へ つれて いきます。', 'Membawa anak pergi ke kebun binatang.'),
('ex_n4_auto_136', 'v_n4_auto_136', '毎日この道を通って通勤します。', 'まいにち この みち を とおって つうきん します。', 'Setiap hari saya melewati jalan ini untuk pergi kerja.'),
('ex_n4_auto_137', 'v_n4_auto_137', '荷物を午後にお届けします。', 'にもつ を ごご に おとどけ します。', 'Saya akan mengantarkan paket pada siang hari.'),
('ex_n4_auto_138', 'v_n4_auto_138', '京都の古い旅館に泊まりました。', 'きょうと の ふるい りょかん に とまりました。', 'Saya menginap di penginapan kuno di Kyoto.'),
('ex_n4_auto_139', 'v_n4_auto_139', '電球を取り替えました。', 'でんきゅう を とりかえました。', 'Saya mengganti bola lampunya.'),
('ex_n4_auto_140', 'v_n4_auto_140', 'ボールを遠くに投げてください。', 'ボール を とおく に なげて ください。', 'Tolong lempar bolanya ke tempat jauh.'),
('ex_n4_auto_141', 'v_n4_auto_141', '先月、祖母が亡くなりました。', 'せんげつ、そぼ が なくなりました。', 'Bulan lalu, nenek saya meninggal dunia.'),
('ex_n4_auto_142', 'v_n4_auto_142', 'ガソリンが無くなってしまいました。', 'ガソリン が なくなって しまいました。', 'Bensinnya sudah habis.'),
('ex_n4_auto_143', 'v_n4_auto_143', '風邪がやっと治りました。', 'かぜ が やっと なおりました。', 'Penyakit flunya akhirnya sembuh.'),
('ex_n4_auto_144', 'v_n4_auto_144', '日本の生活に慣れました。', 'にほん の せいかつ に なれました。', 'Saya sudah terbiasa dengan kehidupan di Jepang.'),
('ex_n4_auto_145', 'v_n4_auto_145', '泥棒は警察から逃げました。', 'どろぼう は けいさつ から にげました。', 'Pencuri itu melarikan diri dari polisi.'),
('ex_n4_auto_146', 'v_n4_auto_146', '彼は父親にとても似ています。', 'かれ は ちちおや に とても にています。', 'Dia sangat mirip dengan ayahnya.'),
('ex_n4_auto_147', 'v_n4_auto_147', '誰かが私の傘を盗みました。', 'だれか が わたし の かさ を ぬすみました。', 'Seseorang mencuri payung saya.'),
('ex_n4_auto_148', 'v_n4_auto_148', 'パンにバターを塗ります。', 'パン に バター を ぬります。', 'Mengoleskan mentega pada roti.'),
('ex_n4_auto_149', 'v_n4_auto_149', '雨で靴が濡れてしまいました。', 'あめ で くつ が ぬれて しまいました。', 'Sepatu saya basah karena hujan.'),
('ex_n4_auto_150', 'v_n4_auto_150', '昨日は八時間ぐっすり眠りました。', 'きのう は はちじかん ぐっすり ねむりました。', 'Kemarin saya tidur nyenyak selama delapan jam.'),
('ex_n4_auto_151', 'v_n4_auto_151', 'クラスに二人だけ残っています。', 'クラス に ふたり だけ のこっています。', 'Hanya tersisa dua orang di kelas.'),
('ex_n4_auto_152', 'v_n4_auto_152', '次の駅で地下鉄に乗り換えます。', 'つぎ の えき で ちかてつ に に りかえます。', 'Saya transit naik MRT di stasiun berikutnya.'),
('ex_n4_auto_153', 'v_n4_auto_153', '重い荷物を二階へ運びました。', 'おもい にもつ を にかい へ はこびました。', 'Saya membawa barang bawaan berat ke lantai dua.'),
('ex_n4_auto_154', 'v_n4_auto_154', '初日の出を静かに拝みました。', 'ハつひので を しずかに おがみました。', 'Memuja matahari terbit pertama di awal tahun dengan tenang.'),
('ex_n4_auto_155', 'v_n4_auto_155', '人気のコンサートのチケットは売り切れました。', 'にんき の コンサート の チケット は うりきれました。', 'Tiket konser yang populer telah habis terjual.'),
('ex_n4_auto_156', 'v_n4_auto_156', '夜になって空気が冷えてきました。', 'よる に なって くうき が ひえて きました。', 'Udara mulai mendingin saat malam tiba.'),
('ex_n4_auto_157', 'v_n4_auto_157', 'ビールを冷蔵庫で冷やします。', 'ビール を れいぞうこ で ひやします。', 'Meninginkan bir di dalam kulkas.'),
('ex_n4_auto_158', 'v_n4_auto_158', '夜空に星が光っています。', 'よぞら に ほし が ひかっています。', 'Bintang bersinar di langit malam.'),
('ex_n4_auto_159', 'v_n4_auto_159', '日本語を学ぶ人が増えています。', 'にほんご を まなぶ ひと が ふえています。', 'Orang yang belajar bahasa Jepang meningkat.'),
('ex_n4_auto_160', 'v_n4_auto_160', '貯金を少しずつ増やしています。', 'ちょきん を すこしずつ ふやしています。', 'Saya menambah tabungan sedikit demi sedikit.'),
('ex_n4_auto_161', 'v_n4_auto_161', 'テーブルの上を雑巾で拭きました。', 'テーブル の うえ を ぞうきん で ふきました。', 'Saya mengelap bagian atas meja dengan kain lap.'),
('ex_n4_auto_162', 'v_n4_auto_162', 'テストで満点を取って褒められました。', 'テスト で まんてん を とって ほめられました。', 'Saya dipuji karena mendapat nilai sempurna saat ujian.'),
('ex_n4_auto_163', 'v_n4_auto_163', '明日、十時にそちらへ参ります。', 'あした、じゅうじ に そちら へ まいります。', 'Besok jam 10 saya akan datang ke sana.'),
('ex_n4_auto_164', 'v_n4_auto_164', '次の角を右に曲がってください。', 'つぎ の かど を みぎ に まがって ください。', 'Tolong belok kanan di pojokan berikutnya.'),
('ex_n4_auto_165', 'v_n4_auto_165', '法律や規則は守らなければなりません。', 'ほうりつ や きそく は まもらなければ なりません。', 'Kita harus mematuhi hukum dan peraturan.'),
('ex_n4_auto_166', 'v_n4_auto_166', '道に迷ってしまいました。', 'みち に まよって しまいました。', 'Saya tersesat di jalan.'),
('ex_n4_auto_167', 'v_n4_auto_167', 'ここから富士山が見えます。', 'ここ から ふじさん が みえます。', 'Gunung Fuji terlihat dari sini.'),
('ex_n4_auto_168', 'v_n4_auto_168', '駅で彼を見かけました。', 'えき で かれ を みかけました。', 'Saya kebetulan melihat dia di stasiun.'),
('ex_n4_auto_169', 'v_n4_auto_169', '失くした鍵が見つかりました。', 'なくした かぎ が みつかりました。', 'Kunci yang hilang telah ditemukan.'),
('ex_n4_auto_170', 'v_n4_auto_170', '空港へ友達を迎えに行きます。', 'くうこう へ ともだち を むかえ に いきます。', 'Saya pergi ke bandara untuk menjemput teman.'),
('ex_n4_auto_171', 'v_n4_auto_171', '使った道具は元の場所に戻してください。', 'つかった どうぐ は もと の ばしょ に もどして ください。', 'Tolong kembalikan peralatan yang digunakan ke tempat semula.'),
('ex_n4_auto_172', 'v_n4_auto_172', '心からお礼を申し上げます。', 'こころ から おれい を もうしあげます。', 'Saya menyampaikan terima kasih dari lubuk hati.'),
('ex_n4_auto_173', 'v_n4_auto_173', '庭でバーベキューの肉を焼きます。', 'にわ で バーベキュー の にく を やきます。', 'Memanggang daging barbekyu di kebun.'),
('ex_n4_auto_174', 'v_n4_auto_174', 'パンが美味しく焼けました。', 'パン が おいしく やけました。', 'Rotinya sudah terpanggang dengan lezat.'),
('ex_n4_auto_175', 'v_n4_auto_175', 'ダイエットをして少し痩せました。', 'ダイエット を して すこし やせました。', 'Saya kurusan sedikit karena berdiet.'),
('ex_n4_auto_176', 'v_n4_auto_176', '会社を辞めることにしました。', 'かいしゃ を やめる こと に しました。', 'Saya memutuskan untuk berhenti dari perusahaan.'),
('ex_n4_auto_177', 'v_n4_auto_177', '犬にエサをやりました。', 'いぬ に エサ を やりました。', 'Saya memberi makan anjing.'),
('ex_n4_auto_178', 'v_n4_auto_178', '靴を泥で汚してしまいました。', 'くつ を どろ で よごして しまいました。', 'Saya mengotori sepatu dengan lumpur.'),
('ex_n4_auto_179', 'v_n4_auto_179', 'プレゼントをあげたら彼はとても喜びました。', 'プレゼント を あげたら かれ は とても よろこびました。', 'Dia sangat gembira saat saya beri hadiah.'),
('ex_n4_auto_180', 'v_n4_auto_180', 'お湯が沸きましたよ。', 'おゆ が わきました よ。', 'Air panasnya sudah mendidih lho.'),
('ex_n4_auto_181', 'v_n4_auto_181', '蚊に足を刺されて痒いです。', 'か に あし を さされて かゆいです。', 'Kaki saya gatal karena digigit nyamuk.'),
('ex_n4_auto_182', 'v_n4_auto_182', '卵を割ってボウルに入れます。', 'たまご を わって ボウル に いれます。', 'Memecahkan telur lalu memasukkannya ke mangkuk.'),
('ex_n4_auto_183', 'v_n4_auto_183', '合格してとても嬉しいです。', 'ごうかく して とても うれしい です。', 'Saya sangat gembira karena lulus.'),
('ex_n4_auto_184', 'v_n4_auto_184', 'ペットが死んで悲しいです。', 'ペット が しんで かなしい です。', 'Saya sedih karena hewan peliharaan saya mati.'),
('ex_n4_auto_185', 'v_n4_auto_185', '人前で間違えて恥ずかしかったです。', 'ひとまえ で まちがえて はずかしかった です。', 'Saya malu karena salah di depan umum.'),
('ex_n4_auto_186', 'v_n4_auto_186', 'この花はとても珍しい種類です。', 'この はな は とても メズラシイ しゅるい です。', 'Bunga ini adalah jenis yang sangat langka.'),
('ex_n4_auto_187', 'v_n4_auto_187', '私たちの学校は規則が厳しいです。', 'わたし たち の がっこう は きそく が きびしい です。', 'Sekolah kami memiliki aturan yang tegas.'),
('ex_n4_auto_188', 'v_n4_auto_188', 'あの先生はいつも優しく教えてくれます。', 'あの せんせい は いつも やさしく おしえて くれます。', 'Guru itu selalu mengajar dengan baik hati.'),
('ex_n4_auto_189', 'v_n4_auto_189', '正しい答えに丸をつけてください。', 'ただしい こたえ に まる を つけて ください。', 'Tolong beri tanda lingkaran pada jawaban yang benar.'),
('ex_n4_auto_190', 'v_n4_auto_190', '山頂からの景色は美しかったです。', 'さんちょう から の けしき は うつくしかった です。', 'Pemandangan dari puncak gunung indah sekali.'),
('ex_n4_auto_191', 'v_n4_auto_191', '彼のバイオリンの演奏は素晴らしかったです。', 'かれ の バイオリン の えんそう は すばらしかった です。', 'Pertunjukan biola dia luar biasa hebat.'),
('ex_n4_auto_192', 'v_n4_auto_192', '彼は歴史についてとても詳しいです。', 'かれ は れきし について とても くわしい です。', 'Dia paham betul mengenai sejarah.'),
('ex_n4_auto_193', 'v_n4_auto_193', 'この川は深いので泳いではいけません。', 'この かわ は ふかい ので およいでは いけません。', 'Sungai ini dalam, jadi tidak boleh berenang.'),
('ex_n4_auto_194', 'v_n4_auto_194', 'このプールは浅いので子供でも安全です。', 'この プール は あさい ので こども でも あんぜん です。', 'Kolam ini dangkal jadi aman untuk anak-anak sekalipun.'),
('ex_n4_auto_195', 'v_n4_auto_195', '暗い夜道を一人で歩くのは怖いです。', 'くらい よみち を ひとり で あるく の は こわいです。', 'Berjalan sendirian di jalan malam yang gelap itu menakutkan.'),
('ex_n4_auto_196', 'v_n4_auto_196', '彼の英語のスキルは本当に凄いです。', 'かれ の えいご の スキル は ほんとう に すごいです。', 'Kemampuan bahasa Inggrisnya benar-benar luar biasa.'),
('ex_n4_auto_197', 'v_n4_auto_197', '試合に一敗して悔しいです。', 'しあい に いっぱい して くやしい です。', 'Saya kesal karena kalah satu kali dalam pertandingan.'),
('ex_n4_auto_198', 'v_n4_auto_198', '古い写真を見てとても懐かしかったです。', 'ふるい しゃしん を みて とても なつかしかった です。', 'Melihat foto lama membuat saya sangat nostalgia.'),
('ex_n4_auto_199', 'v_n4_auto_199', '彼はいつも丁寧な言葉遣いをします。', 'かれ は いつも ていねいな ことばづかい を します。', 'Dia selalu menggunakan pilihan kata yang sopan.'),
('ex_n4_auto_200', 'v_n4_auto_200', 'この問題は複雑すぎて解けません。', 'この もんだい は ふくざつ すぎて とけません。', 'Masalah ini terlalu rumit hingga tidak bisa diselesaikan.'),
('ex_n4_auto_201', 'v_n4_auto_201', 'テストは思ったより簡単でした。', 'テスト は おもった より かんたん でした。', 'Ujiannya ternyata lebih mudah dari dugaan.'),
('ex_n4_auto_202', 'v_n4_auto_202', 'この踏切は安全対策がされています。', 'この ふみきり は あんぜん たいさく が されています。', 'Perlintasan kereta ini telah dipasangi pengaman.'),
('ex_n4_auto_203', 'v_n4_auto_203', '夜遅くに一人で歩くのは危険です。', 'よる おそく に ひとり で あるく の は きけん です。', 'Berjalan sendirian saat larut malam adalah hal berbahaya.'),
('ex_n4_auto_204', 'v_n4_auto_204', '雨で遠足が中止になって残念です。', 'あめ で えんそく が ちゅうし に なって ざんねん です。', 'Sayang sekali karyawisata dibatalkan karena hujan.'),
('ex_n4_auto_205', 'v_n4_auto_205', 'そんなに無理をしないでください。', 'そんな に むり を しないで ください。', 'Tolong jangan memaksakan diri seperti itu.'),
('ex_n4_auto_206', 'v_n4_auto_206', 'ビザの申請には写真が必要になります。', 'ビザ の しんせい には しゃしん が ひつよう に なります。', 'Pasfoto akan diperlukan untuk pengajuan visa.'),
('ex_n4_auto_207', 'v_n4_auto_207', '今日は私たちの特別な記念日です。', 'きょう は わたし たち の とくべつな きねんび です。', 'Hari ini adalah hari peringatan khusus kami.'),
('ex_n4_auto_208', 'v_n4_auto_208', '駅から遠いので生活が少し不便です。', 'えき から とおい ので せいかつ が すこし ふべん です。', 'Hidup agak sedikit tidak praktis karena jauh dari stasiun.'),
('ex_n4_auto_209', 'v_n4_auto_209', '近所の人はみんな親切です。', 'きんじょ の ひと は みんな しんせつ です。', 'Tetangga semuanya ramah.'),
('ex_n4_auto_210', 'v_n4_auto_210', '通り道に車を置くと邪魔になります。', 'とおりみち に くるま を おくと じゃま に なります。', 'Akan menjadi penghalang jika meletakkan mobil di jalur lewat.'),
('ex_n4_auto_211', 'v_n4_auto_211', 'この靴はとても軽くて歩くのが楽です。', 'この くつ は とても かるくて あるく の が らく です。', 'Sepatu ini sangat ringan dan nyaman untuk berjalan.'),
('ex_n4_auto_212', 'v_n4_auto_212', '自分に適当な仕事を見つけました。', 'じぶん に てきとうな しごと を みつけました。', 'Saya menemukan pekerjaan yang cocok bagi saya.'),
('ex_n4_auto_213', 'v_n4_auto_213', 'あと一歩で優勝できたので本当に惜しかったです。', 'あと いっぽ で ゆうしょう できた ので ほんとう に おしかったです。', 'Sangat disayangkan karena tinggal selangkah lagi bisa juara.'),
('ex_n4_auto_214', 'v_n4_auto_214', '彼とは子供の頃からの親しい友人です。', 'かれ と は こども の ころ から の したしい ゆうじん です。', 'Dia adalah teman akrab saya sejak masa kecil.'),
('ex_n4_auto_215', 'v_n4_auto_215', 'このスープは少し塩辛いです。', 'この スープ は すこし しおからい です。', 'Sup ini agak sedikit asin.'),
('ex_n4_auto_216', 'v_n4_auto_216', 'レモンは酸っぱい味がします。', 'レモン は すっぱい あじ が します。', 'Lemon memiliki rasa asam.'),
('ex_n4_auto_217', 'v_n4_auto_217', '良薬は口に苦しと言います。', 'りょうやく は くち に にがし と いいます。', 'Ada pepatah mengatakan obat mujarab rasanya pahit.'),
('ex_n4_auto_218', 'v_n4_auto_218', '彼の冗談はとてもおかしいです。', 'かれ の じょうだん は とても おかしい です。', 'Leluconnya sangat lucu.'),
('ex_n4_auto_219', 'v_n4_auto_219', '走った後、息が苦しいです。', 'はしった あと、いき が くるしい です。', 'Napas terasa sesak setelah berlari.'),
('ex_n4_auto_220', 'v_n4_auto_220', '細かいお金を持っていません。', 'こまかい おかね を もっていません。', 'Saya tidak membawa uang receh.'),
('ex_n4_auto_221', 'v_n4_auto_221', '一人暮らしは少し寂しいです。', 'ひとりぐらし は すこし さびしい です。', 'Hidup sendirian agak sedikit sepi.'),
('ex_n4_auto_222', 'v_n4_auto_222', '夜中に家の周りを歩く怪しい人を見ました。', 'よなか に いえ の まわり を あるく あやしい ひと を みました。', 'Saya melihat orang mencurigakan berjalan di sekitar rumah tengah malam.'),
('ex_n4_auto_223', 'v_n4_auto_223', 'この映画はつまらなかったです。', 'この えいが は つまらなかった です。', 'Film ini membosankan.'),
('ex_n4_auto_224', 'v_n4_auto_224', 'ゆうべ遅かったので、今日は眠いです。', 'ゆうべ おそかった ので、きょう は ねむい です。', 'Saya mengantuk hari ini karena tadi malam tidur larut.'),
('ex_n4_auto_225', 'v_n4_auto_225', '彼はひどい嘘をつきました。', 'かれ は ひどい うそ を つきました。', 'Dia telah berbohong dengan sangat buruk.'),
('ex_n4_auto_226', 'v_n4_auto_226', 'この二つの三角形の面積は等しいです。', 'この ふたつ の さんかくけい の めんせき は ひとしい です。', 'Luas kedua segitiga ini adalah sama.'),
('ex_n4_auto_227', 'v_n4_auto_227', 'お名前を伺ってもよろしいですか。', 'おなまえ を うかがっても よろしい です か。', 'Bolehkah saya menanyakan nama Anda?'),
('ex_n4_auto_228', 'v_n4_auto_228', '彼は大人しい性格の子供です。', 'かれ は おとなしい せいかく の こども です。', 'Dia adalah anak dengan kepribadian yang tenang.'),
('ex_n4_auto_229', 'v_n4_auto_229', 'あの犬はとても賢いですね。', 'あの いぬ は とても かしこい です ね。', 'Anjing itu sangat cerdas ya.'),
('ex_n4_auto_230', 'v_n4_auto_230', '家族と一緒に過ごせて幸せです。', 'かぞく と いっしょ に すごせて しあわせ です。', 'Saya bahagia bisa menghabiskan waktu bersama keluarga.'),
('ex_n4_auto_231', 'v_n4_auto_231', '市場で新鮮な魚を買いました。', 'いちば で しんせんな さかな を かいました。', 'Saya membeli ikan segar di pasar.'),
('ex_n4_auto_232', 'v_n4_auto_232', '彼女は日本語を熱心に勉強しています。', 'かのじょ は にほんご を ねっしんに べんきょう しています。', 'Dia belajar bahasa Jepang dengan rajin.'),
('ex_n4_auto_233', 'v_n4_auto_233', '彼は真面目な学生で毎日予習します。', 'かれ は まじめな がくせい で まいにち よしゅう します。', 'Dia adalah siswa yang rajin dan bersiap setiap hari.'),
('ex_n4_auto_234', 'v_n4_auto_234', 'この地域は昔から農業が盛んです。', 'この ちいき は むかし から のうぎょう が さかん です。', 'Wilayah ini sejak dulu pertaniannya sangat aktif.'),
('ex_n4_auto_235', 'v_n4_auto_235', '彼は立派な大人になりました。', 'かれ は りっぱな おとな に なりました。', 'Dia telah tumbuh menjadi orang dewasa yang hebat.'),
('ex_n4_auto_236', 'v_n4_auto_236', '外は激しい雨が降っています。', 'そと は はげしい あめ が フっています。', 'Di luar sedang turun hujan lebat.'),
('ex_n4_auto_237', 'v_n4_auto_237', '彼女はいつも明るい笑顔を見せます。', 'かのじょ は いつも あかるい えがお を みせます。', 'Dia selalu menunjukkan senyum yang ceria.'),
('ex_n4_auto_238', 'v_n4_auto_238', '夜空に浮かぶ月が丸くて綺麗です。', 'よぞら に うかぶ つき が まるくて きれい です。', 'Rembulan yang terapung di langit malam itu bulat dan indah.'),
('ex_n4_auto_239', 'v_n4_auto_239', '蚊に刺されて腕がとても痒いです。', 'か に さされて うで が とても かゆいです。', 'Lengan saya sangat gatal karena digigit nyamuk.'),
('ex_n4_auto_240', 'v_n4_auto_240', '酷い風邪をひいてしまいました。', 'ひどい かぜ を ひいて しまいました。', 'Saya tidak sengaja terkena flu parah.'),
('ex_n4_auto_241', 'v_n4_auto_241', '彼の英語がペラペラなのが羨ましいです。', 'かれ の えいご が ペラペラ な の が うらやましい です。', 'Saya iri melihat dia fasih berbahasa Inggris.'),
('ex_n4_auto_242', 'v_n4_auto_242', 'このラーメンのスープはぬるいです。', 'この ラーメン の スープ は ぬるい です。', 'Kuah ramen ini suam-suam kuku.'),
('ex_n4_auto_243', 'v_n4_auto_243', '朝日が眩しくて目を覚ましました。', 'あさひ が まぶしくて メ を さましました。', 'Saya terbangun karena matahari pagi yang silau.'),
('ex_n4_auto_244', 'v_n4_auto_244', '食べ残しを捨てるのはもったいないです。', 'たべのこし を すてる の は もったいない です。', 'Membuang makanan sisa adalah hal yang mubazir.'),
('ex_n4_auto_245', 'v_n4_auto_245', '彼女は料理がとてもうまいです。', 'かのじょ は りょうり が とても うまい です。', 'Dia sangat pandai memasak.'),
('ex_n4_auto_246', 'v_n4_auto_246', '犯人の卑劣な行為が憎いです。', 'はんにん の ひれつな こうい が にくい です。', 'Saya benci tindakan pengecut pelaku kejahatan tersebut.'),
('ex_n4_auto_247', 'v_n4_auto_247', '隣の部屋の話し声がやかましいです。', 'となり の へや の はなしごえ が やかましい です。', 'Suara obrolan dari kamar sebelah sangat bising.'),
('ex_n4_auto_248', 'v_n4_auto_248', '空が急に暗くなって雨が降ってきました。', 'そら が きゅうに くらくなって あめ が ふって きました。', 'Langit tiba-tiba menggelap dan mulai turun hujan.'),
('ex_n4_auto_249', 'v_n4_auto_249', '今年の夏は非常に暑いですね。', 'ことし の なつ は ひじょうに あつい です ね。', 'Musim panas tahun ini sangat panas sekali ya.'),
('ex_n4_auto_250', 'v_n4_auto_250', '宿題はほとんど終わりました。', 'しゅくだい は ほとんど おわりました。', 'PR hampir seluruhnya selesai.'),
('ex_n4_auto_251', 'v_n4_auto_251', '日本語がずいぶん上手になりましたね。', 'にほんご が ずいぶん じょうず に なりました ね。', 'Bahasa Jepang Anda sudah lumayan mahir ya.'),
('ex_n4_auto_252', 'v_n4_auto_252', '難しい試験にやっと合格しました。', 'むずかしい しけん に やっと ごうかくしました。', 'Akhirnya saya lulus ujian yang sulit.'),
('ex_n4_auto_253', 'v_n4_auto_253', '十年間住んだアパートをとうとう引っ越しました。', 'じゅうねんかん すんだ アパート を とうとう ひっこしました。', 'Akhirnya saya pindah dari apartemen yang ditinggali 10 tahun.'),
('ex_n4_auto_254', 'v_n4_auto_254', '約束は必ず守ってください。', 'やくそく は かならず まもって ください。', 'Tolong pastikan Anda menepati janji.'),
('ex_n4_auto_255', 'v_n4_auto_255', '今度ぜひ私の家に遊びに来てください。', 'こんど ぜひ わたし の いえ に あそび に きて ください。', 'Kapan-kapan, tentu saja Anda harus datang main ke rumah saya.'),
('ex_n4_auto_256', 'v_n4_auto_256', '明日はたぶん雨になるでしょう。', 'あした は たぶん あめ に なる でしょう。', 'Besok mungkin akan turun hujan.'),
('ex_n4_auto_257', 'v_n4_auto_257', 'しばらくここで待っていてください。', 'しばらく ここ で まっていて ください。', 'Tolong tunggu di sini sementara waktu.'),
('ex_n4_auto_258', 'v_n4_auto_258', '私の顔をはっきり見て話してください。', 'わたし の かお を はっきり みて はなして ください。', 'Tolong tatap wajah saya dengan jelas ketika berbicara.'),
('ex_n4_auto_259', 'v_n4_auto_259', '週末は家でのんびり過ごします。', 'しゅうまつ は いえ で のんびり すごします。', 'Saya menghabiskan akhir pekan secara santai di rumah.'),
('ex_n4_auto_260', 'v_n4_auto_260', '時間なので、そろそろ失礼します。', 'じかん なので、そろそろ しつれい します。', 'Karena sudah waktunya, sebentar lagi saya mohon pamit.'),
('ex_n4_auto_261', 'v_n4_auto_261', '日本語がどんどん上達していますね。', 'にほんご が どんどん じょうたつ しています ね。', 'Bahasa Jepang Anda meningkat dengan cepat ya.'),
('ex_n4_auto_262', 'v_n4_auto_262', '皆さん、今日の会議はお疲れ様でした。', 'みなさん、きょう の かいぎ は おつかれさまでした。', 'Semuanya, terima kasih atas kerja kerasnya pada rapat hari ini.'),
('ex_n4_auto_263', 'v_n4_auto_263', '用事があるので、お先に失礼します。', 'ようじ が ある ので、おさき に しつれい します。', 'Saya permisi pulang duluan karena ada keperluan.'),
('ex_n4_auto_264', 'v_n4_auto_264', 'おかげさまで、体調が良くなりました。', 'おかげさまで、たいちょう が よく なりました。', 'Berkat doa Anda, kondisi kesehatan saya sudah membaik.'),
('ex_n4_auto_265', 'v_n4_auto_265', '実は、明日から日本へ旅行に行きます。', 'じつは、あした から にほん へ りょこう に いきます。', 'Sebenarnya, mulai besok saya akan berwisata ke Jepang.'),
('ex_n4_auto_266', 'v_n4_auto_266', 'もちろん、私も手伝いますよ。', 'もちろん、わたし も てつだいます よ。', 'Tentu saja, saya juga akan membantu.'),
('ex_n4_auto_267', 'v_n4_auto_267', '温かいお茶はいかがですか。', 'あたたかい おちゃ は いかが です か。', 'Bagaimana kalau minum teh hangat?'),
('ex_n4_auto_268', 'v_n4_auto_268', '最近はあまり忙しくありません。', 'さいきん は あまり いそがしく ありません。', 'Akhir-akhir ini saya tidak terlalu sibuk.'),
('ex_n4_auto_269', 'v_n4_auto_269', '日本の料理はいかがですか。', 'にほん の りょうり は いかが です か。', 'Bagaimana cita rasa masakan Jepang?'),
('ex_n4_auto_270', 'v_n4_auto_270', 'いくら高くても、この辞書を買います。', 'いくら たかくても、この じしょ を かいます。', 'Meskipun mahal berapa pun, saya akan membeli kamus ini.'),
('ex_n4_auto_271', 'v_n4_auto_271', '一生懸命日本語を練習しています。', 'いっしょうけんめい にほんご を れんしゅう しています。', 'Saya sedang berlatih bahasa Jepang dengan sungguh-sungguh.'),
('ex_n4_auto_272', 'v_n4_auto_272', 'この秘密を決して誰にも言わないでください。', 'この ひみつ を けっして だれ にも いわないで ください。', 'Tolong jangan sekali-kali membocorkan rahasia ini kepada siapapun.'),
('ex_n4_auto_273', 'v_n4_auto_273', 'この間、駅の近くで彼と会いました。', 'このあいだ、えき の ちかく で かれ と あいました。', 'Tempo hari saya bertemu dengannya di dekat stasiun.'),
('ex_n4_auto_274', 'v_n4_auto_274', 'これからもっと頑張って勉強します。', 'これから もっと がんばって べんきょう します。', 'Mulai sekarang saya akan belajar lebih keras lagi.'),
('ex_n4_auto_275', 'v_n4_auto_275', 'さっき彼が事務所に来ました。', 'さっき かれ が じむしょ に きました。', 'Tadi dia datang ke kantor.'),
('ex_n4_auto_276', 'v_n4_auto_276', '桜の葉がすっかり落ちてしまいました。', 'さくら の は が すっかり おちて しまいました。', 'Daun sakura sudah sepenuhnya berguguran.'),
('ex_n4_auto_277', 'v_n4_auto_277', '彼の方が私よりずっと背が高いです。', 'かれ の ほう が わたし より ずっと せ が たかい です。', 'Dia jauh lebih tinggi daripada saya.'),
('ex_n4_auto_278', 'v_n4_auto_278', '昨日のテストは全然できませんでした。', 'きのう の テスト は ぜんぜん できません でした。', 'Ujian kemarin sama sekali tidak bisa saya kerjakan.'),
('ex_n4_auto_279', 'v_n4_auto_279', '日曜日には大抵家で休んでいます。', 'にちようび には たいてい いえ で やすんでいます。', 'Hari Minggu biasanya saya beristirahat di rumah.'),
('ex_n4_auto_280', 'v_n4_auto_280', '病気はだいぶ良くなりました。', 'びょうき は だいぶ よく なりました。', 'Penyakitnya sudah lumayan membaik.'),
('ex_n4_auto_281', 'v_n4_auto_281', 'その本はちっとも面白くありません。', 'その ほん は ちっとも おもしろく ありません。', 'Buku itu sedikit pun tidak menarik.'),
('ex_n4_auto_282', 'v_n4_auto_282', 'ちょうど十二時になったところです。', 'ちょうど じゅうにじ に なった ところ です。', 'Tepat baru saja menunjukkan jam 12.'),
('ex_n4_auto_283', 'v_n4_auto_283', '彼はついに新しい小説を書き終えました。', 'かれ は ついに あたらしい しょうせつ を かきおえました。', 'Dia akhirnya selesai menulis novel baru.'),
('ex_n4_auto_284', 'v_n4_auto_284', '日本の果物では特にイチゴが好きです。', 'にほん の くだもの では とくに イチゴ が すき です。', 'Di antara buah-buahan Jepang, saya terutama suka stroberi.'),
('ex_n4_auto_285', 'v_n4_auto_285', 'なるべく毎日漢字を練習してください。', 'なるべく まいにち かんじ を れんしゅう してください。', 'Tolong sebisa mungkin berlatih kanji setiap hari.'),
('ex_n4_auto_286', 'v_n4_auto_286', 'もし明日雨なら、旅行は中止です。', 'もし あした あめ なら、りょこう は ちゅうし です。', 'Jika besok hujan, perjalanannya dibatalkan.'),
('ex_n4_auto_287', 'v_n4_auto_287', 'やはり彼は約束を守りませんでした。', 'やはり かれ は やくそく を まもりませんでした。', 'Seperti dugaan, dia tetap saja tidak menepati janji.'),
('ex_n4_auto_288', 'v_n4_auto_288', '鍵がない、おかしいな。', 'かぎ が ない、おかしい な。', 'Kuncinya tidak ada, aneh ya...'),
('ex_n4_auto_289', 'v_n4_auto_289', '山田さん、しばらくでしたね。', 'やまだ さん、しばらく でした ね。', 'Yamada-san, sudah lama tidak berjumpa ya.'),
('ex_n4_auto_290', 'v_n4_auto_290', 'お先に失礼します。', 'おさき に しつれい します。', 'Saya permisi pulang duluan.'),
('ex_n4_auto_291', 'v_n4_auto_291', '遠くへ行っても、どうぞお元気で。', 'とおく へ いっても、どうぞ おげんき で。', 'Meskipun pergi jauh, semoga sehat selalu ya.'),
('ex_n4_auto_292', 'v_n4_auto_292', 'どうもありがとうございました。', 'どうも ありがとう ございました。', 'Terima kasih banyak.'),
('ex_n4_auto_293', 'v_n4_auto_293', '仕事、いってらっしゃい！', 'しごと、いってらっしゃい！', 'Selamat jalan bekerja!'),
('ex_n4_auto_294', 'v_n4_auto_294', '学校へいってきます。', 'がっこう へ いってきます。', 'Saya berangkat ke sekolah dulu.'),
('ex_n4_auto_295', 'v_n4_auto_295', '今、家に帰りました。ただいま！', 'いま、いえ に かえりました。ただいま！', 'Saya baru pulang ke rumah. Saya pulang!'),
('ex_n4_auto_296', 'v_n4_auto_296', 'お疲れ様でした。おかえりなさい！', 'おつかれさまでした。おかえりなさい！', 'Terima kasih atas kerja kerasnya. Selamat datang kembali!'),
('ex_n4_auto_297', 'v_n4_auto_297', 'お誕生日おめでとうございます！', 'おたんじょうび おめでとう ございます！', 'Selamat hari ulang tahun!'),
('ex_n4_auto_298', 'v_n4_auto_298', '歯が痛いので、歯医者に見てもらいました。', 'は が いたい ので、はいしゃ に みて もらいました。', 'Saya memeriksakan diri ke dokter gigi karena sakit gigi.'),
('ex_n4_auto_299', 'v_n4_auto_299', '会議の準備が全て整いました。', 'かいぎ の じゅんび が すべて ととのいました。', 'Persiapan rapat telah sepenuhnya selesai.'),
('ex_n4_auto_300', 'v_n4_auto_300', '夏休みの旅行計画を立てています。', 'なつやすみ の りょこう けいかく を たてています。', 'Saya sedang menyusun rencana perjalanan liburan musim panas.'),
('ex_n4_auto_301', 'v_n4_auto_301', '彼の説明は簡潔で分かりやすいです。', 'かれ の せつめい は かんけつ で わかりやすい です。', 'Penjelasan dia singkat padat dan mudah dipahami.'),
('ex_n4_auto_302', 'v_n4_auto_302', '空港までタクシーで行きます。', 'くうこう まで タクシー で いきます。', 'Saya pergi ke bandara menggunakan taksi.'),
('ex_n4_auto_303', 'v_n4_auto_303', '人気レストランなので予約が必要です。', 'にんき レストラン なので よやく が ひつよう です。', 'Karena restoran populer, diperlukan pemesanan terlebih dahulu.'),
('ex_n4_auto_304', 'v_n4_auto_304', '外国語を勉強するのは面白いです。', 'がいこくご を べんきょう する の は おもしろい です。', 'Belajar bahasa asing sangatlah menarik.'),
('ex_n4_auto_305', 'v_n4_auto_305', '試験の結果がメールで送られてきました。', 'しけん の けっか が メール で おくられて きました。', 'Hasil ujian telah dikirimkan via email.'),
('ex_n4_auto_306', 'v_n4_auto_306', '現代の社会問題について議論しました。', 'げんだい の しゃかい もんだい について ぎろん しました。', 'Kami mendiskusikan isu sosial masyarakat modern.'),
('ex_n4_auto_307', 'v_n4_auto_307', '私たちは地球の環境を守らなければなりません。', 'わたし たち は ちきゅう の かんきょう を まもらなければ なりません。', 'Kita harus melindungi lingkungan bumi.'),
('ex_n4_auto_308', 'v_n4_auto_308', '散歩をすると気持ちが良いです。', 'さんぽ を する と きもち が いい です。', 'Berjalan-jalan membuat perasaan menjadi tenang/nyaman.'),
('ex_n4_auto_309', 'v_n4_auto_309', 'お客様には丁寧な対応を心がけています。', 'おきゃくさま には ていねいな たいおう を こころがけて います。', 'Kami mengutamakan pelayanan sopan santun kepada pelanggan.'),
('ex_n4_auto_310', 'v_n4_auto_310', '都会の交通システムは複雑です。', 'とかい の こうつう システム は ふくざつ です。', 'Sistem transportasi kota metropolitan sangat rumit.'),
('ex_n4_auto_311', 'v_n4_auto_311', '遅刻の理由を教えてください。', 'ちこく の りゆう を おしえて ください。', 'Tolong beritahu alasan keterlambatan Anda.'),
('ex_n4_auto_312', 'v_n4_auto_312', '長時間の運転は疲れます。', 'ちょうじかん の うんてん は つかれます。', 'Menyetir dalam waktu lama melelahkan.'),
('ex_n4_auto_313', 'v_n4_auto_313', '健康のために毎朝朝食を食べます。', 'けんこう の ため に まいあさ ちょうしょく を たべます。', 'Saya sarapan pagi setiap hari demi kesehatan.'),
('ex_n4_auto_314', 'v_n4_auto_314', 'この料理の材料を買ってきました。', 'この りょうり の ざいりょう を かって きました。', 'Saya telah membeli bahan makanan untuk masakan ini.'),
('ex_n4_auto_315', 'v_n4_auto_315', '生活費を節約するために自炊しています。', 'せいかつひ を せつやく する ため に じすい しています。', 'Saya memasak sendiri untuk menghemat biaya hidup.'),
('ex_n4_auto_316', 'v_n4_auto_316', '朝早く起きる習慣をつけたいです。', 'あさ はやく おきる しゅうかん を つけたい です。', 'Saya ingin membiasakan kebiasaan bangun pagi.'),
('ex_n4_auto_317', 'v_n4_auto_317', '私の祖父は今年で八十歳になります。', 'わたし の そふ は ことし で はちじゅっさい に なります。', 'Kakek saya akan berusia 80 tahun tahun ini.'),
('ex_n4_auto_318', 'v_n4_auto_318', '明日の午後はご都合が良いですか。', 'あした の ごご は ごつごう が よい です か。', 'Apakah besok siang jadwal Anda luang?'),
('ex_n4_auto_319', 'v_n4_auto_319', 'スマートフォンの普及は素晴らしいです。', 'スマートフォン の ふきゅう は すばらしい です。', 'Penyebaran ponsel pintar sangatlah luar biasa.'),
('ex_n4_auto_320', 'v_n4_auto_320', 'データをUSBに保存しました。', 'データ を USB に ほぞん しました。', 'Saya telah menyimpan data ke USB.'),
('ex_n4_auto_321', 'v_n4_auto_321', 'ホテルの窓から見た景色は最高でした。', 'ホテル の まど から みた けしき は さいこう でした。', 'Pemandangan dari jendela hotel sangatlah luar biasa.'),
('ex_n4_auto_322', 'v_n4_auto_322', '地域の住民が集まってイベントを行いました。', 'ちいき の じゅうみん が あつまって イベント を おこないました。', 'Warga lokal berkumpul mengadakan sebuah acara.'),
('ex_n4_auto_323', 'v_n4_auto_323', '会議で自分の意見をはっきり言いました。', 'かいぎ で じぶん の いけん を はっきり いいました。', 'Saya mengutarakan pendapat saya dengan jelas di rapat.'),
('ex_n4_auto_324', 'v_n4_auto_324', '簡潔な文章で報告書を書きました。', 'かんけつな ぶんしょう で ほうこくしょ を かきました。', 'Saya menulis laporan dengan kalimat yang singkat padat.'),
('ex_n4_auto_325', 'v_n4_auto_325', 'バスの出発時間は朝八時です。', 'バス の しゅっぱつ じかん は あさ はちじ です。', 'Waktu keberangkatan bus adalah jam 8 pagi.'),
('ex_n4_auto_326', 'v_n4_auto_326', '親は常に子供の心配をしています。', 'おや は つねに こども の しんぱい を しています。', 'Orang tua selalu memiliki kekhawatiran terhadap anaknya.'),
('ex_n4_auto_327', 'v_n4_auto_327', '日本の科学技術は進歩しています。', 'にほん の かがくぎじゅつ は しんぽ しています。', 'Ilmu pengetahuan dan teknologi Jepang terus maju.'),
('ex_n4_auto_328', 'v_n4_auto_328', '大学生は政治に関心を持つべきです。', 'だいがくせい は せいじ に かんしん を もつべき です。', 'Mahasiswa sebaiknya memiliki ketertarikan pada politik.'),
('ex_n4_auto_329', 'v_n4_auto_329', '世界経済のニュースを毎朝チェックします。', 'せかいけいざい の ニュース を まいあさ チェック します。', 'Memeriksa berita ekonomi dunia setiap pagi.'),
('ex_n4_auto_330', 'v_n4_auto_330', '法律を守るのは市民の義務です。', 'ほうりつ を ままおる の は しみん の ぎむ です。', 'Mematuhi hukum adalah kewajiban warga negara.'),
('ex_n4_auto_331', 'v_n4_auto_331', 'クリスマスを恋人と過ごしました。', 'クリスマス を こいびと と すごしました。', 'Saya menghabiskan hari Natal bersama pacar.'),
('ex_n4_auto_332', 'v_n4_auto_332', '彼らは仲が良い夫婦です。', 'かれら は なか が いい ふうふ です。', 'Mereka adalah pasangan suami istri yang rukun.'),
('ex_n4_auto_333', 'v_n4_auto_333', 'お正月は親戚が集まります。', 'おしょうがつ は しんせき が あつまります。', 'Kerabat berkumpul pada hari Tahun Baru.'),
('ex_n4_auto_334', 'v_n4_auto_334', '社長に新しい計画書を提出しました。', 'しゃちょう に あたらしい けいかくしょ を ていしゅつ します。', 'Saya menyerahkan draf rencana baru kepada direktur.'),
('ex_n4_auto_335', 'v_n4_auto_335', '姉は公務員として市役所で働いています。', 'あね は こうむいん として しやくしょ で はたらいています。', 'Kakak perempuan saya bekerja di balai kota sebagai PNS.'),
('ex_n4_auto_336', 'v_n4_auto_336', '病院で優しい看護師さんに手当てをしてもらいました。', 'びょういん で やさしい かんごしさん に てあて を して もらいました。', 'Saya dirawat oleh perawat ramah di rumah sakit.'),
('ex_n4_auto_337', 'v_n4_auto_337', '日本の有名な小説を読んでいます。', 'にほん の ゆうめいな しょうせつ を よんでいます。', 'Saya sedang membaca novel Jepang yang terkenal.'),
('ex_n4_auto_338', 'v_n4_auto_338', '毎朝、天気予報を確認してから外出します。', 'まいあさ、てんきよほう を かくにん して から がいしゅつ します。', 'Setiap pagi saya memeriksa prakiraan cuaca sebelum bepergian.'),
('ex_n4_auto_339', 'v_n4_auto_339', '近所で大きな火事がありました。', 'きんじょ で おおきな かじ が ありました。', 'Telah terjadi kebakaran besar di sekitar rumah.'),
('ex_n4_auto_340', 'v_n4_auto_340', '交差点で交通事故を目撃しました。', 'こうさてん で こうつうじこ を もくげき しました。', 'Saya menyaksikan kecelakaan lalu lintas di persimpangan.'),
('ex_n4_auto_341', 'v_n4_auto_341', '今日の予定をカレンダーに書き込みました。', 'きょう の よてい を カレンダー に かきこみました。', 'Saya menulis jadwal hari ini pada kalender.'),
('ex_n4_auto_342', 'v_n4_auto_342', '話をするときは相手の目を見てください。', 'はなし を する とき は あいて の め を みて ください。', 'Tataplah mata lawan bicara Anda ketika berbicara.'),
('ex_n4_auto_343', 'v_n4_auto_343', '旅行に行くための用意ができました。', 'りょこう に いく ため の ようい が できました。', 'Persiapan untuk pergi melakukan perjalanan telah selesai.'),
('ex_n4_auto_344', 'v_n4_auto_344', '理科 of 授業で化学の実験を行いました。', 'りか の じゅぎょう で かがく の じっけん を おこないました。', 'Kami melakukan eksperimen kimia di kelas sains.'),
('ex_n4_auto_345', 'v_n4_auto_345', '家の中に泥棒が入って警察を呼びました。', 'いえ の なか に どろぼう が はいって けいさつ を よびました。', 'Seorang pencuri masuk ke dalam rumah sehingga kami memanggil polisi.'),
('ex_n4_auto_346', 'v_n4_auto_346', '家族が全員無事で安心しました。', 'かぞく が ぜんいん ぶじ で あんしん しました。', 'Merasa lega karena seluruh anggota keluarga selamat.'),
('ex_n4_auto_347', 'v_n4_auto_347', 'この料理はどんな味がしますか。', 'この りょうり は どんな あじ が します か。', 'Makanan ini rasanya seperti apa?'),
('ex_n4_auto_348', 'v_n4_auto_348', '子供にとって遊びはとても大切です。', 'こども にとって あそび は とても たいせつ です。', 'Bagi anak-anak, bermain sangatlah penting.'),
('ex_n4_auto_349', 'v_n4_auto_349', '自動車に注意して道路を渡りましょう。', 'じどうしゃ に ちゅうい して どうろ を わたりましょう。', 'Mari menyeberang jalan dengan memperhatikan mobil.'),
('ex_n4_auto_350', 'v_n4_auto_350', '彼の新しい提案に反対が多かったです。', 'かれ の あたらしい ていあん に はんたい が おおかった です。', 'Banyak pertentangan terhadap usulan barunya.'),
('ex_n4_auto_351', 'v_n4_auto_351', '会議での決定に賛成を表明しました。', 'かいぎ で の けってい に さんせい を ひょうめい しました。', 'Menyatakan setuju terhadap keputusan dalam rapat.'),
('ex_n4_auto_352', 'v_n4_auto_352', '駅から近いアパートに住んでいます。', 'えき から ちかい アパート に すんでいます。', 'Saya tinggal di apartemen dekat stasiun.'),
('ex_n4_auto_353', 'v_n4_auto_353', '週末に従姉妹が家に遊びに来ます。', 'しゅうまつ に いとこ が いえ に あそび に きます。', 'Akhir pekan ini saudara sepupu saya akan datang main ke rumah.'),
('ex_n4_auto_354', 'v_n4_auto_354', 'その問題は今回の件と関係がありません。', 'その もんだい は こんかい の けん と かんけい が ありません。', 'Masalah tersebut tidak ada hubungannya dengan kasus kali ini.'),
('ex_n4_auto_355', 'v_n4_auto_355', '大学の研究所でがんの研究をしています。', 'だいがく の けいきゅうじょ で がん の けんきゅう を しています。', 'Sedang meneliti kanker di lembaga penelitian universitas.'),
('ex_n4_auto_356', 'v_n4_auto_356', '化学の授業で面白い実験をしました。', 'かがく の じゅぎょう で おもしろい じっけん を しました。', 'Melakukan eksperimen menarik di kelas kimia.'),
('ex_n4_auto_357', 'v_n4_auto_357', '子供におもちゃを買ってあげました。', 'こども に おもちゃ を かって あげました。', 'Saya membelikan mainan untuk anak.'),
('ex_n4_auto_358', 'v_n4_auto_358', '高校生活は良い思い出です。', 'こうこう せいかつ は よい おもいで です。', 'Kehidupan SMA adalah kenangan yang indah.'),
('ex_n4_auto_359', 'v_n4_auto_359', '日本の科学技術は世界をリードしています。', 'にほん の かがくぎじゅつ は せかい を リード しています。', 'Teknologi sains Jepang memimpin dunia.'),
('ex_n4_auto_360', 'v_n4_auto_360', '日本語の会話の練習をしましょう。', 'にほんご の かいわ の れんしゅう を しましょう。', 'Mari berlatih percakapan bahasa Jepang.'),
('ex_n4_auto_361', 'v_n4_auto_361', '仕事の帰りにスーパーに寄りました。', 'しごと の かえり に スーパー に よりました。', 'Saya mampir ke supermarket di jalan pulang kerja.'),
('ex_n4_auto_362', 'v_n4_auto_362', '鏡を見てネクタイを直しました。', 'かがみ を みて ネクタイ を なおしました。', 'Saya merapikan dasi sambil melihat cermin.'),
('ex_n4_auto_363', 'v_n4_auto_363', '科学の進歩は私たちの生活を豊かにします。', 'かがく の しんぽ は わたし たち の せいかつ を ゆたかに します。', 'Kemajuan sains memperkaya kehidupan kita.'),
('ex_n4_auto_364', 'v_n4_auto_364', '週末はいつも家事で忙しいです。', 'しゅうまつ は いつも かじ で いそがしい です。', 'Akhir pekan selalu sibuk dengan pekerjaan rumah tangga.'),
('ex_n4_auto_365', 'v_n4_auto_365', 'この石は変わった形をしていますね。', 'この いし は かわった かたち を しています ね。', 'Batu ini memiliki bentuk yang aneh ya.'),
('ex_n4_auto_366', 'v_n4_auto_366', 'お金を大切に使ってください。', 'おかね を たいせつ に つかって ください。', 'Tolong gunakan uang dengan hemat/bijaksana.'),
('ex_n4_auto_367', 'v_n4_auto_367', '壁に綺麗な絵を掛けました。', 'かべ に きれいな え を かけました。', 'Saya menggantung lukisan indah di dinding.'),
('ex_n4_auto_368', 'v_n4_auto_368', '美容院で髪を短く切りました。', 'びよういん で かみ を みじかく きりました。', 'Saya memotong rambut menjadi pendek di salon.'),
('ex_n4_auto_369', 'v_n4_auto_369', '神様に日々感謝しています。', 'かみさま に ひび かんしゃ しています。', 'Setiap hari saya bersyukur kepada Tuhan.'),
('ex_n4_auto_370', 'v_n4_auto_370', '世界の経済について新聞で読みました。', 'せかい の けいざい について しんぶん で よみました。', 'Membaca tentang perekonomian dunia di koran.'),
('ex_n4_auto_371', 'v_n4_auto_371', '予定をカレンダーに書いておきます。', 'よてい を カレンダー に かいて おきます。', 'Saya menulis jadwal acara pada kalender terlebih dahulu.'),
('ex_n4_auto_372', 'v_n4_auto_372', '若者も政治に関心を持つべきです。', 'わかもの も せいじ に かんしん を もつ べき です。', 'Pemuda juga harus menaruh perhatian pada politik.'),
('ex_n4_auto_373', 'v_n4_auto_373', '日本の四季の季節はどれも美しいです。', 'にほん の しき の きせつ は どれ も うつくしい です。', 'Musim dari empat musim di Jepang semuanya indah.'),
('ex_n4_auto_374', 'v_n4_auto_374', '学校の規則は必ず守らなければなりません。', 'がっこう の きそく は かならず まもらなければ なりません。', 'Peraturan sekolah harus selalu dipatuhi.'),
('ex_n4_auto_375', 'v_n4_auto_375', 'この古いお寺は長い歴史を持っています。', 'この ふるい おてら は ながい れきし を もっています。', 'Kuil kuno ini memiliki sejarah yang panjang.'),
('ex_n4_auto_376', 'v_n4_auto_376', '日本の地理は山が多くて特徴的です。', 'にほん の ちり は やま が おおくて とくちょうてき です。', 'Geografi Jepang ditandai dengan banyaknya pegunungan.'),
('ex_n4_auto_377', 'v_n4_auto_377', 'このスカーフは高級な絹で作られています。', 'この スカーフ は こうきゅうな きぬ で つくられています。', 'Syal ini terbuat dari sutra berkualitas tinggi.'),
('ex_n4_auto_378', 'v_n4_auto_378', '体調が悪くて、気分がすぐれません。', 'たいちょう が わるくて、きぶん が すぐれません。', 'Kondisi badan buruk, saya merasa kurang sehat.'),
('ex_n4_auto_379', 'v_n4_auto_379', 'お正月には綺麗な着物を着ます。', 'おしょうがつ には きれいな きものを きます。', 'Kami memakai Kimono indah pada hari Tahun Baru.'),
('ex_n4_auto_380', 'v_n4_auto_380', '店にお客さんがたくさん並んでいます。', 'みせ に おきゃくさん が たくさん ならんでいます。', 'Banyak pelanggan yang antre di toko.'),
('ex_n4_auto_381', 'v_n4_auto_381', 'この駅には急行電車が止まりません。', 'この えき には きゅうこう でんしゃ が とまりません。', 'Kereta ekspres tidak berhenti di stasiun ini.'),
('ex_n4_auto_382', 'v_n4_auto_382', '私は日本の文化にとても興味があります。', 'わたし は にほん の ぶんか に とても きょうみ が あります。', 'Saya sangat tertarik dengan kebudayaan Jepang.'),
('ex_n4_auto_383', 'v_n4_auto_383', '駅から家までの距離は一キロです。', 'えき から いえ まで の きょうり は いち キロ です。', 'Jarak stasiun ke rumah adalah satu kilometer.'),
('ex_n4_auto_384', 'v_n4_auto_384', '山の朝は霧が深くて前が見えません。', 'やま の あさ は きり が ふかくて まえ が みえません。', 'Pagi hari di gunung kabutnya tebal hingga depan tidak terlihat.'),
('ex_n4_auto_385', 'v_n4_auto_385', '近所の人といつも挨拶を交わします。', 'きんじょ の ひと と いつも あいさつ を かわします。', 'Saya selalu saling menyapa dengan orang tetangga sekitar.'),
('ex_n4_auto_386', 'v_n4_auto_386', '台風の接近により強い雨が降っています。', 'たいふう の せっきん に より つよい あめ が フっています。', 'Hujan lebat turun akibat mendekatnya angin topan.'),
('ex_n4_auto_387', 'v_n4_auto_387', '昨夜、震度三の地震が発生しました。', 'さくや、しんど さん の じしん が はっせい しました。', 'Tadi malam terjadi gempa bumi berkekuatan skala 3.'),
('ex_n4_auto_388', 'v_n4_auto_388', '学校の年間行事の予定表をもらいました。', 'がっこう の ねんかん ぎょうじ の よていひょう を もらいました。', 'Saya menerima jadwal agenda kegiatan tahunan sekolah.'),
('ex_n4_auto_389', 'v_n4_auto_389', '地震が発生したので津波に注意してください。', 'じしん が はっせい した ので つなみ に ちゅうい してください。', 'Tolong berhati-hati terhadap tsunami karena terjadi gempa.'),
('ex_n4_auto_390', 'v_n4_auto_390', '庭の草を綺麗に刈りました。', 'にわ の くさ を きれい に かりました。', 'Saya memotong rumput di kebun dengan rapi.'),
('ex_n4_auto_391', 'v_n4_auto_391', '大雨の影響で各地で洪水が起きました。', 'おおあめ の えいきょう で かくち で こうずい が おきました。', 'Banjir terjadi di berbagai tempat akibat pengaruh hujan lebat.'),
('ex_n4_auto_392', 'v_n4_auto_392', '空気が乾燥していると火事が起きやすいです。', 'くうき が かんそう している と かじ が おきやすい です。', 'Kebakaran mudah terjadi jika udara kering.'),
('ex_n4_auto_393', 'v_n4_auto_393', '交差点で車の衝突事故を目撃しました。', 'こうさてん で くるま の しょうとつじこ を もくげき しました。', 'Menyaksikan kecelakaan tabrakan mobil di persimpangan jalan.'),
('ex_n4_auto_394', 'v_n4_auto_394', '朝の挨拶はコミュニケーションの基本です。', 'あさ の あいさつ は コミュニケーション の きほん です。', 'Salam pagi hari adalah dasar dari komunikasi.'),
('ex_n4_auto_395', 'v_n4_auto_395', '質問に対してすぐ返事をしてください。', 'しつもん に たいして すぐ へんじ を してください。', 'Tolong segera berikan jawaban atas pertanyaan.'),
('ex_n4_auto_396', 'v_n4_auto_396', '彼は将来への希望に満ちています。', 'かれ は しょうらい へ の きぼう に みちています。', 'Dia penuh dengan harapan untuk masa depan.'),
('ex_n4_auto_397', 'v_n4_auto_397', 'パソコンを使いすぎて首が疲れました。', 'パソコン を つかいすぎて くび が つかれました。', 'Leher saya lelah karena terlalu banyak menggunakan komputer.'),
('ex_n4_auto_398', 'v_n4_auto_398', '青い空に白い雲が浮かんでいます。', 'あおい そら に しろい くも が うかんでいます。', 'Awan putih mengapung di langit biru.'),
('ex_n4_auto_399', 'v_n4_auto_399', '暗闇の中で猫の目が光っています。', 'くらやみ の なか で ねこ の め が ひかっています。', 'Mata kucing bersinar di dalam kegelapan.'),
('ex_n4_auto_400', 'v_n4_auto_400', '明日の会議は十時に始まります。', 'あした の かいぎ は じゅうじ に はじまります。', 'Rapat besok akan dimulai jam 10.'),
('ex_n4_auto_401', 'v_n4_auto_401', '彼は自動車の工場で働いています。', 'かれ は じどうしゃ の こうじょう で はたらいています。', 'Dia bekerja di pabrik mobil.'),
('ex_n4_auto_402', 'v_n4_auto_402', '事務所の場所を教えてください。', 'じむしょ の ばしょ を おしえて ください。', 'Tolong beritahu letak kantor Anda.'),
('ex_n4_auto_403', 'v_n4_auto_403', '受付で名前を記入してください。', 'うけつけ で なまえ を きにゅう してください。', 'Tolong tulis nama Anda di resepsionis.'),
('ex_n4_auto_404', 'v_n4_auto_404', 'この工場では電子製品を作っています。', 'この こうじょう では でんし せいひん を つくっています。', 'Pabrik ini memproduksi barang elektronik.'),
('ex_n4_auto_405', 'v_n4_auto_405', '機械の使い方を習いました。', 'きかい の つかいかた を ならいました。', 'Saya belajar cara mengoperasikan mesin.'),
('ex_n4_auto_406', 'v_n4_auto_406', '仕事の道具をカバンに入れました。', 'しごと の どうぐ を カバン に いれました。', 'Saya memasukkan peralatan kerja ke dalam tas.'),
('ex_n4_auto_407', 'v_n4_auto_407', '私の趣味は映画鑑賞です。', 'わたし の しゅみ は えいがかんしょう です。', 'Hobi saya adalah menonton film.'),
('ex_n4_auto_408', 'v_n4_auto_408', 'この製品の特徴を説明してください。', 'この せいひん の とくちょう を せつめい してください。', 'Tolong jelaskan keunikan produk ini.'),
('ex_n4_auto_409', 'v_n4_auto_409', '遅れた理由を説明します。', 'おくれた りゆう を せつめい します。', 'Saya akan menjelaskan alasan keterlambatan saya.'),
('ex_n4_auto_410', 'v_n4_auto_410', '日本に来た目的は勉強です。', 'にほん に きた もくてき は べんきょう です。', 'Tujuan saya datang ke Jepang adalah untuk belajar.'),
('ex_n4_auto_411', 'v_n4_auto_411', '火事の原因はまだ分かっていません。', 'かじ の げんいん は まだ わかっていません。', 'Penyebab kebakaran belum diketahui.'),
('ex_n4_auto_412', 'v_n4_auto_412', '留学は良い経験になります。', 'りゅうがく は よい けいけん に なります。', 'Belajar di luar negeri akan menjadi pengalaman yang baik.'),
('ex_n4_auto_413', 'v_n4_auto_413', '彼は私の大切な親友です。', 'かれ は わたし の たいせつな しんゆう です。', 'Dia adalah sahabat karib saya.'),
('ex_n4_auto_414', 'v_n4_auto_414', '今月の目標は本を五冊読むことです。', 'こんげつ の もくひょう は ほん を ごさつ よむ こと です。', 'Target bulan ini adalah membaca lima buah buku.'),
('ex_n4_auto_415', 'v_n4_auto_415', 'この新しい風邪薬は効果が早いです。', 'この あたらしい かぜぐすり は こうか が はやいです。', 'Obat flu baru ini khasiatnya cepat.'),
('ex_n4_auto_416', 'v_n4_auto_416', '姉に赤ちゃんが生まれました。', 'あね に あかちゃん が うまれました。', 'Kakak perempuan saya melahirkan seorang bayi.'),
('ex_n4_auto_417', 'v_n4_auto_417', 'あの男性は私の大学の先輩です。', 'あの だんせい は わたし の だいがく の せんぱい です。', 'Laki-laki itu adalah senior saya di universitas.'),
('ex_n4_auto_418', 'v_n4_auto_418', '日本の女性の平均寿命は長いです。', 'にほん の じょせい の へいきんじゅみょう は ながい です。', 'Harapan hidup rata-rata wanita Jepang cukup panjang.'),
('ex_n4_auto_419', 'v_n4_auto_419', '彼女は日本で大人気の歌手です。', 'かのじょ は にほん で だいにんき の かしゅ です。', 'Dia adalah penyanyi yang sangat populer di Jepang.'),
('ex_n4_auto_420', 'v_n4_auto_420', '観光業はこの町の主要な産業です。', 'かんこうぎょう は この まち の しゅような さんぎょう です。', 'Industri pariwisata adalah industri utama di kota ini.'),
('ex_n4_auto_421', 'v_n4_auto_421', '電車の車内で面白い広告を見ました。', 'でんしゃ の しゃない で おもしろい こうこく を みました。', 'Saya melihat iklan menarik di dalam kereta.'),
('ex_n4_auto_422', 'v_n4_auto_422', 'テレビでニュースを見ました。', 'テレビ で ニュース を みました。', 'Saya menonton berita di TV.'),
('ex_n4_auto_423', 'v_n4_auto_423', '昨日の夜、大きな地震がありました。', 'きのう の よる、おおきな じしん が ありました。', 'Ada gempa bumi besar kemarin malam.'),
('ex_n4_auto_424', 'v_n4_auto_424', '台風で電車が止まる可能性があります。', 'たいふう で でんしゃ が とまる かのうせい が あります。', 'Ada kemungkinan kereta berhenti karena angin topan.'),
('ex_n4_auto_425', 'v_n4_auto_425', '警察が事件を調査しています。', 'けいさつ が じけん を ちょうさ しています。', 'Polisi sedang menyelidiki kasus tersebut.'),
('ex_n4_auto_426', 'v_n4_auto_426', '私たちは戦争に反対します。', 'わたし たち は せんそう に はんたい します。', 'Kami menentang perang.'),
('ex_n4_auto_427', 'v_n4_auto_427', '世界の平和を祈っています。', 'せかい の へいわ を いのっています。', 'Saya mendoakan perdamaian dunia.'),
('ex_n4_auto_428', 'v_n4_auto_428', '大学生は自由な時間が多いです。', 'だいがくせい は じゆうな じかん が おおい です。', 'Mahasiswa memiliki banyak waktu luang/bebas.'),
('ex_n4_auto_429', 'v_n4_auto_429', 'リーダーには大きな責任があります。', 'リーダー には おおきな せきにん が あります。', 'Seorang pemimpin memiliki tanggung jawab besar.'),
('ex_n4_auto_430', 'v_n4_auto_430', 'みんなの協力が必要です。', 'みんな の きょうりょく が ひつよう です。', 'Diperlukan kerja sama dari semua orang.'),
('ex_n4_auto_431', 'v_n4_auto_431', '新しい計画の成功を祈ります。', 'あたらしい けいかく の せいこう を いのります。', 'Saya mendoakan kesuksesan rencana baru.'),
('ex_n4_auto_432', 'v_n4_auto_432', '学生たちは四人のグループに分かれました。', 'がくせい たち は よにん の グループ に わかれました。', 'Para siswa dibagi ke dalam kelompok yang terdiri dari empat orang.'),
('ex_n4_auto_433', 'v_n4_auto_433', '資料のコピーを十部作ってください。', 'しりょう の コピー を じゅうぶ つくってください。', 'Tolong fotokopi dokumen ini sebanyak sepuluh rangkap.'),
('ex_n4_auto_434', 'v_n4_auto_434', '燃えるゴミは月曜日に出してください。', 'もえる ゴミ は げつようび に だしてください。', 'Tolong buang sampah organik/bisa dibakar pada hari Senin.'),
('ex_n4_auto_435', 'v_n4_auto_435', '日本のお米はモチモチしていて美味しいです。', 'にほん の おこめ は モチモチ していて おいしい です。', 'Beras Jepang sangat kenyal dan lezat.'),
('ex_n4_auto_436', 'v_n4_auto_436', 'この坂を登ると、海が見える公園があります。', 'この さか を のぼる と、うみ が みえる こうえん が あります。', 'Jika mendaki jalan menanjak ini, ada taman yang menampilkan laut.'),
('ex_n4_auto_437', 'v_n4_auto_437', '日本の伝統文化である茶道を習いたいです。', 'にほん の でんとう ぶんか で ある さどう を ならいたいです。', 'Saya ingin mempelajari upacara minum teh yang merupakan kebudayaan tradisional Jepang.'),
('ex_n4_auto_438', 'v_n4_auto_438', '駅の周辺は商業のエリアとして発展しています。', 'えき の しゅうへん は しょうぎょう の エリア として はってん しています。', 'Sekitar stasiun berkembang sebagai area bisnis/perdagangan.'),
('ex_n4_auto_439', 'v_n4_auto_439', '日本は世界の多くの国々と貿易を行っています。', 'にほん は せかい の おおく の くにぐに と ぼうえき を おこなっています。', 'Jepang melakukan perdagangan dengan banyak negara di dunia.'),
('ex_n4_auto_440', 'v_n4_auto_440', '住民登録の手続きで市役所へ行きました。', 'じゅうみん とうろく の てつづき で しやしよ へ いきました。', 'Saya pergi ke balai kota untuk mengurus prosedur pendaftaran kependudukan.'),
('ex_n4_auto_441', 'v_n4_auto_441', '彼は社交的な性格で友達が多いです。', 'かれ は しゃこうてきな せいかく で ともだち が おおい です。', 'Dia berkepribadian supel/mudah bergaul dan punya banyak teman.'),
('ex_n4_auto_442', 'v_n4_auto_442', '毎朝、出勤する前にシャワーを浴びます。', 'まいあさ、しゅっきん する まえ に シャワー を あびます。', 'Setiap pagi saya mandi shower sebelum berangkat kerja.'),
('ex_n4_auto_443', 'v_n4_auto_443', '面白そうな小説を図書館で借りました。', 'おもしろそうな しょうせつ を としょかん で かりました。', 'Saya meminjam novel yang kelihatannya menarik di perpustakaan.'),
('ex_n4_auto_444', 'v_n4_auto_444', '将来は医者になって人々を助けたいです。', 'しょうらい は いしゃ に なって ひとびと を たすけたい です。', 'Di masa depan saya ingin menjadi dokter untuk menolong orang-orang.'),
('ex_n4_auto_445', 'v_n4_auto_445', '非常用に三日分の食料を準備しています。', 'ひじょうよう に みっかぶん の しょくりょう を じゅんび しています。', 'Saya menyiapkan persediaan pangan untuk tiga hari sebagai cadangan darurat.'),
('ex_n4_auto_446', 'v_n4_auto_446', '日本から車や機械が世界へ輸出されます。', 'にほん から くるま や きかい が せかい へ ゆしゅつ されます。', 'Mobil dan mesin diekspor dari Jepang ke dunia.'),
('ex_n4_auto_447', 'v_n4_auto_447', '週末に家族で寿司を食べに行きました。', 'しゅうまつ に かぞく で すし を たべ に いきました。', 'Akhir pekan kemarin saya pergi makan Sushi bersama keluarga.'),
('ex_n4_auto_448', 'v_n4_auto_448', '日本の生活にもう慣れましたか。', 'にほん の せいかつ に もう なれました か。', 'Apakah Anda sudah terbiasa dengan kehidupan di Jepang?'),
('ex_n4_auto_449', 'v_n4_auto_449', 'この地域はみかんの生産が盛んです。', 'この ちいき は みかん の せいさん が さかん です。', 'Daerah ini sangat produktif dalam memproduksi jeruk mandarin.'),
('ex_n4_auto_450', 'v_n4_auto_450', '大学での私の専門は情報工学です。', 'だいがく で の わたし の せんもん は じょうほう こうがく です。', 'Keahlian khusus/jurusan saya di universitas adalah Teknik Informatika.'),
('ex_n4_auto_451', 'v_n4_auto_451', '大学の卒業式は三月に行われます。', 'だいがく の そつぎょうしき は さんがつ に おこなわれます。', 'Upacara kelulusan universitas diadakan pada bulan Maret.'),
('ex_n4_auto_452', 'v_n4_auto_452', '私の祖母は田舎で一人で暮らしています。', 'わたし の そぼ は いなか で ひとり で くらしています。', 'Nene saya tinggal sendirian di desa.'),
('ex_n4_auto_453', 'v_n4_auto_453', '今日の体育の授業はサッカーをしました。', 'きょう の たいいく の じゅぎょう は サッカー を しました。', 'Pada jam pelajaran olahraga hari ini kami bermain sepak bola.'),
('ex_n4_auto_454', 'v_n4_auto_454', '食料品の多くを海外から輸入しています。', 'しょくりょうひん の おおく を かいがい から ゆにゅう しています。', 'Mengimpor sebagian besar bahan makanan dari luar negeri.'),
('ex_n4_auto_455', 'v_n4_auto_455', '荷物が多いので空港までタクシーに乗ります。', 'にもつ が おおい ので くうこう まで タクシー に のります。', 'Saya naik taksi ke bandara karena barang bawaannya banyak.'),
('ex_n4_auto_456', 'v_n4_auto_456', '毎日新しい単語を十個ずつ覚えています。', 'まいにち あたらしい たんご を じゅっこずつ おぼえています。', 'Saya menghafal sepuluh kosa kata baru setiap hari.'),
('ex_n4_auto_457', 'v_n4_auto_457', 'この工場では最新 of スマホを生産しています。', 'この こうじょう で は さいしん の スマホ を せいさん しています。', 'Pabrik ini memproduksi smartphone terbaru.'),
('ex_n4_auto_458', 'v_n4_auto_458', '私の弟は今年から中学生になりました。', 'わたし の おとうと は ことし から ちゅうがくせい に なりました。', 'Adik laki-laki saya menjadi siswa SMP mulai tahun ini.'),
('ex_n4_auto_459', 'v_n4_auto_459', '冬は電気の消費量が増える傾向があります。', 'ふゆ は でんき の しょうひりょう が ふえる けいこう が あります。', 'Konsumsi listrik cenderung meningkat di musim dingin.'),
('ex_n4_auto_460', 'v_n4_auto_460', '毎日の通勤に一時間半かかります。', 'まいにち の つうきん に いちじかんはん かかります。', 'Komuting kerja setiap hari memakan waktu satu setengah jam.'),
('ex_n4_auto_461', 'v_n4_auto_461', '秋の風に心地よい冷たさを感じます。', 'あき の かぜ に ここちよい つめたさ を かんじます。', 'Saya merasakan kedinginan yang nyaman pada angin musim gugur.'),
('ex_n4_auto_462', 'v_n4_auto_462', '冬の寒い日は手袋をしないと手が凍えます。', 'ふゆ の さむい ひ は てぶくろ を しない と て が こごえます。', 'Tangan akan membeku saat hari dingin musim dingin jika tidak memakai sarung tangan.'),
('ex_n4_auto_463', 'v_n4_auto_463', '日本の和食の中で天ぷらが一番好きです。', 'にほん の わしょく の なか で てんぷら が いちばん すき です。', 'Di antara makanan Jepang, saya paling suka Tempura.'),
('ex_n4_auto_464', 'v_n4_auto_464', '美術館で新しい絵画の展示が始まりました。', 'びじゅつかん で あたらしい かいが の てんじ が はじまりました。', 'Pajangan lukisan baru dimulai di museum seni.'),
('ex_n4_auto_465', 'v_n4_auto_465', '世界中が平和になることを切に願います。', 'せかいじゅう が へいわ に なる こと を せつに ねがいます。', 'Berdoa dengan tulus agar seluruh dunia menjadi damai.'),
('ex_n4_auto_466', 'v_n4_auto_466', '戦争のない社会を作らなければなりません。', 'せんそう の ない しゃかい を つくらなければ なりません。', 'Kita harus membuat masyarakat yang bebas dari perang.'),
('ex_n4_auto_467', 'v_n4_auto_467', '髪が伸びてきたので床屋へ行って切りました。', 'かみ が のびて きた ので とこや へ いって きりました。', 'Saya pergi ke barbershop untuk memotong rambut karena sudah panjang.'),
('ex_n4_auto_468', 'v_n4_auto_468', 'この国では言論の自由が保障されています。', 'この くに で は げんろん の じゆう が ほしょう されています。', 'Kebebasan berbicara dijamin di negara ini.'),
('ex_n4_auto_469', 'v_n4_auto_469', '雨の日のサッカーでユニフォームが泥だらけになりました。', 'あめ の ひ の サッカー で ユニフォーム が どろだらけ に なりました。', 'Seragam menjadi penuh lumpur karena bermain sepak bola di hari hujan.'),
('ex_n4_auto_470', 'v_n4_auto_470', '家に泥棒が入らないように鍵を二つかけました。', 'いえ に どろぼう が はいらない ように かぎ を ふたつ かけました。', 'Saya memasang dua kunci agar pencuri tidak masuk rumah.'),
('ex_n4_auto_471', 'v_n4_auto_471', '誰にでも幸せに生きる権利があります。', 'だれ に でも しあわせ に いきる けんり が あります。', 'Siapa pun memiliki hak untuk hidup bahagia.'),
('ex_n4_auto_472', 'v_n4_auto_472', '彼女は世界各国の可愛い人形を集めています。', 'かのじょ は せかい かっこく の かわいい にんぎょう を あつめています。', 'Dia mengoleksi boneka lucu dari berbagai negara di dunia.'),
('ex_n4_auto_473', 'v_n4_auto_473', '風邪をひいて三十八度の熱が出ました。', 'かぜ を ひいて さんじゅうはちど の ねつ が でました。', 'Saya terkena flu dan mengalami demam 38 derajat.'),
('ex_n4_auto_474', 'v_n4_auto_474', '日本の友達に手書きの年賀状を送りました。', 'にほん の ともだち に てがき の ねんがじょう を おくりました。', 'Saya mengirim kartu tahun baru tulisan tangan kepada teman di Jepang.'),
('ex_n4_auto_475', 'v_n4_auto_475', '春になると野原にたくさんの花が咲きます。', 'はる に なる と のはら に たくさん の はな が さきます。', 'Banyak bunga bermekaran di padang rumput saat musim semi tiba.'),
('ex_n4_auto_476', 'v_n4_auto_476', '税金を納めることは国民の義務です。', 'ぜいきん を おさめる こと は こくみん の ぎむ です。', 'Membayar pajak adalah kewajiban warga negara.'),
('ex_n4_auto_477', 'v_n4_auto_477', '私の夢は漫画家になることです。', 'わたし の ゆめ は まんがか に なる こと です。', 'Mimpi saya adalah menjadi seorang komikus.'),
('ex_n4_auto_478', 'v_n4_auto_478', '彼は有名なSF小説の作家です。', 'かれ は ゆうめいな SF しょうせつ の さっか です。', 'Dia adalah penulis novel fiksi ilmiah yang terkenal.'),
('ex_n4_auto_479', 'v_n4_auto_479', '彼女はフランスで画家の勉強をしました。', 'かのじょ は フランス で がか の べんきょう を しました。', 'Dia belajar melukis di Prancis.'),
('ex_n4_auto_480', 'v_n4_auto_480', '科学者たちが新しい薬を開発しています。', 'かがくしゃ たち が あたらしい くすり を かいはつ しています。', 'Para ilmuwan sedang mengembangkan obat baru.'),
('ex_n4_auto_481', 'v_n4_auto_481', '多くの政治家がその会議に参加しました。', 'おおく の せいじか が その かいぎ に さんか しました。', 'Banyak politikus yang berpartisipasi dalam rapat itu.'),
('ex_n4_auto_482', 'v_n4_auto_482', '弁護士に法律の相談をしました。', 'べんごし に ほうりつ の そうだん を しました。', 'Saya berkonsultasi masalah hukum dengan pengacara.'),
('ex_n4_auto_483', 'v_n4_auto_483', '交差点に警察官が立っています。', 'こうさてん に けいさつかん が たっています。', 'Ada petugas polisi berdiri di persimpangan.'),
('ex_n4_auto_484', 'v_n4_auto_484', '消防士たちが火事に立ち向かいました。', 'しょうぼうし たち が かじ に たちむかいました。', 'Petugas pemadam kebakaran menghadapi kebakaran itu.'),
('ex_n4_auto_485', 'v_n4_auto_485', '大学で宇宙の研究者をしています。', 'だいがく で うちゅう の けんきゅうしゃ を しています。', 'Saya adalah peneliti luar angkasa di universitas.'),
('ex_n4_auto_486', 'v_n4_auto_486', '将来は翻訳者になりたいです。', 'しょうらい は ほんやくしゃ に なりたい です。', 'Masa depan saya ingin menjadi seorang penerjemah.'),
('ex_n4_auto_487', 'v_n4_auto_487', '彼の面会にお祖父さんが来ました。', 'かれ の めんかい に おじいさん が きました。', 'Kakeknya datang untuk menjenguknya.'),
('ex_n4_auto_488', 'v_n4_auto_488', 'お祖母さんはとてもお元気そうですね。', 'おばあさん は とても おげんきそう です ね。', 'Nenek Anda terlihat sangat sehat ya.'),
('ex_n4_auto_489', 'v_n4_auto_489', 'ご両親はどちらにお住まいですか。', 'ごりょうしん は どちら に おすまい です か。', 'Di mana orang tua Anda tinggal?'),
('ex_n4_auto_490', 'v_n4_auto_490', 'お子さんは今年何歳になりますか。', 'おこさん は ことし なんさい に なります か。', 'Berapa usia anak Anda tahun ini?'),
('ex_n4_auto_491', 'v_n4_auto_491', 'ご主人はお元気ですか。', 'ごしゅじん は おげんき です か。', 'Bagaimana kabar suami Anda?'),
('ex_n4_auto_492', 'v_n4_auto_492', '今日は用事があるので早く失礼します。', 'きょう は ようじ が ある ので はやく しつれい します。', 'Hari ini saya mohon pamit awal karena ada urusan.'),
('ex_n4_auto_493', 'v_n4_auto_493', '風は北東の方向に吹いています。', 'かぜ は ほくとう の ほうこう に ふいています。', 'Angin sedang bertiup ke arah timur laut.'),
('ex_n4_auto_494', 'v_n4_auto_494', '北西の空に黒い雲が見えます。', 'ほくせい の そら に くろい くも が みえます。', 'Tampak awan hitam di langit barat laut.'),
('ex_n4_auto_495', 'v_n4_auto_495', '南東の風が気持ちいいです。', 'なんとう の かぜ が きもちいい です。', 'Angin tenggara terasa sangat sejuk/nyaman.'),
('ex_n4_auto_496', 'v_n4_auto_496', '南西へ向かって進んでください。', 'なんせい へ むかって すすんで ください。', 'Tolong maju ke arah barat daya.'),
('ex_n4_auto_497', 'v_n4_auto_497', '街の中央に大きな駅があります。', 'まち の ちゅうおう に おおきな えき が あります。', 'Ada stasiun besar di pusat kota.'),
('ex_n4_auto_498', 'v_n4_auto_498', '池の周囲をゆっくり散歩しました。', 'いけ の しゅうい を ゆっくり さんぽ しました。', 'Saya berjalan-jalan santai di sekeliling kolam.'),
('ex_n4_auto_499', 'v_n4_auto_499', '旅行は一週間の予定です。', 'りょこう は いっしゅうかん の よてい です。', 'Perjalanan direncanakan selama satu minggu.'),
('ex_n4_auto_500', 'v_n4_auto_500', '二週間の休みをもらいました。', 'にしゅうかん の やすみ を もらいました。', 'Saya mendapat libur selama dua minggu.'),
('ex_n4_auto_501', 'v_n4_auto_501', '日本語を勉強して一ヶ月になります。', 'にほんご を べんきょう して いっかげつ に なります。', 'Sudah berjalan satu bulan sejak saya belajar bahasa Jepang.'),
('ex_n4_auto_502', 'v_n4_auto_502', '日本に来て三ヶ月が経ちました。', 'にほん に きて さんかげつ が たちました。', 'Sudah tiga bulan berlalu sejak saya datang ke Jepang.'),
('ex_n4_auto_503', 'v_n4_auto_503', '半年で日本語がとても上手になりました。', 'はんねん で にほんご が とても じょうず に なりました。', 'Bahasa Jepang Anda meningkat pesat dalam setengah tahun.'),
('ex_n4_auto_504', 'v_n4_auto_504', '一年の年間予定表を作りました。', 'いちねん の ねんかん よていひょう を つくりました。', 'Saya membuat tabel rencana tahunan selama satu tahun.'),
('ex_n4_auto_505', 'v_n4_auto_505', '彼は中学校の数学の先生です。', 'かれ は ちゅうがっこう の すうがく の せんせい です。', 'Dia adalah guru matematika SMP.'),
('ex_n4_auto_506', 'v_n4_auto_506', '子供は近くの小学校に通っています。', 'こども は ちかく の しょうがっこう に かよっています。', 'Anak saya sekolah di SD terdekat.'),
('ex_n4_auto_507', 'v_n4_auto_507', '娘は毎日楽しそうに幼稚園に行きます。', 'むすめ は まいにち たのしそう に ようちえん に いきます。', 'Anak perempuan saya berangkat ke TK dengan gembira setiap hari.'),
('ex_n4_auto_508', 'v_n4_auto_508', '大学院で歴史の研究を続けたいです。', 'だいがくいん で れきし の けんきゅう を つづけたい です。', 'Saya ingin melanjutkan penelitian sejarah di pascasarjana.'),
('ex_n4_auto_509', 'v_n4_auto_509', '授業の前に教科書を開けてください。', 'じゅぎょう の まえ に きょうかしょ を あけて ください。', 'Tolong buka buku pelajaran sebelum kelas dimulai.'),
('ex_n4_auto_510', 'v_n4_auto_510', 'レポートの締め切りは今週の金曜日です。', 'レポート の しめきり は こんしゅう の きんようび です。', 'Batas waktu pengumpulan laporan adalah Jumat minggu ini.'),
('ex_n4_auto_511', 'v_n4_auto_511', '大雨で川が氾濫し洪水が起きました。', 'おおあめ で かわ が はんらん し こうずい が おきました。', 'Sungai meluap karena hujan lebat sehingga memicu banjir.'),
('ex_n4_auto_512', 'v_n4_auto_512', '警察が事件の解決に向けて動いています。', 'けいさつ が じけん の かいけつ に むけて うごいています。', 'Polisi bergerak mengusut penyelesaian kasus tersebut.'),
('ex_n4_auto_513', 'v_n4_auto_513', '泥棒に高価な指輪を盗まれました。', 'どろぼう に こうかな ゆびわ を ぬすまれました。', 'Cincin berharga saya dicuri oleh pencuri.'),
('ex_n4_auto_514', 'v_n4_auto_514', '事件の裁判は来月行われる予定です。', 'じけん の さいばん は らいげつ おこなわれる よてい です。', 'Sidang pengadilan kasus tersebut dijadwalkan bulan depan.'),
('ex_n4_auto_515', 'v_n4_auto_515', '日本の歴史についてもっと知りたいです。', 'にほん の れきし について もっと しりたい です。', 'Saya ingin mengetahui lebih banyak tentang sejarah Jepang.'),
('ex_n4_auto_516', 'v_n4_auto_516', '今日は1日です。', 'きょう は ついたち です。', 'Hari ini adalah tanggal 1.'),
('ex_n4_auto_517', 'v_n4_auto_517', '今日は2日です。', 'きょう は ふつか です。', 'Hari ini adalah tanggal 2.'),
('ex_n4_auto_518', 'v_n4_auto_518', '今日は3日です。', 'きょう は みっか です。', 'Hari ini adalah tanggal 3.'),
('ex_n4_auto_519', 'v_n4_auto_519', '今日は4日です。', 'きょう は よっか です。', 'Hari ini adalah tanggal 4.'),
('ex_n4_auto_520', 'v_n4_auto_520', '今日は5日です。', 'きょう は いつか です。', 'Hari ini adalah tanggal 5.'),
('ex_n4_auto_521', 'v_n4_auto_521', '今日は6日です。', 'きょう は むいか です。', 'Hari ini adalah tanggal 6.'),
('ex_n4_auto_522', 'v_n4_auto_522', '今日は7日です。', 'きょう は なのか です。', 'Hari ini adalah tanggal 7.'),
('ex_n4_auto_523', 'v_n4_auto_523', '今日は8日です。', 'きょう は ようか です。', 'Hari ini adalah tanggal 8.'),
('ex_n4_auto_524', 'v_n4_auto_524', '今日は9日です。', 'きょう は ここのか です。', 'Hari ini adalah tanggal 9.'),
('ex_n4_auto_525', 'v_n4_auto_525', '今日は10日です。', 'きょう は とおか です。', 'Hari ini adalah tanggal 10.'),
('ex_n4_auto_526', 'v_n4_auto_526', '今日は11日です。', 'きょう は じゅういちにち です。', 'Hari ini adalah tanggal 11.'),
('ex_n4_auto_527', 'v_n4_auto_527', '今日は12日です。', 'きょう は じゅうににち です。', 'Hari ini adalah tanggal 12.'),
('ex_n4_auto_528', 'v_n4_auto_528', '今日は13日です。', 'きょう は じゅうさんにち です。', 'Hari ini adalah tanggal 13.'),
('ex_n4_auto_529', 'v_n4_auto_529', '今日は14日です。', 'きょう は じゅうよっか です。', 'Hari ini adalah tanggal 14.'),
('ex_n4_auto_530', 'v_n4_auto_530', '今日は15日です。', 'きょう は じゅうごにち です。', 'Hari ini adalah tanggal 15.'),
('ex_n4_auto_531', 'v_n4_auto_531', '今日は16日です。', 'きょう は じゅうろくにち です。', 'Hari ini adalah tanggal 16.'),
('ex_n4_auto_532', 'v_n4_auto_532', '今日は17日です。', 'きょう は じゅうしちにち です。', 'Hari ini adalah tanggal 17.'),
('ex_n4_auto_533', 'v_n4_auto_533', '今日は18日です。', 'きょう は じゅうはちにち です。', 'Hari ini adalah tanggal 18.'),
('ex_n4_auto_534', 'v_n4_auto_534', '今日は19日です。', 'きょう は じゅうくにち です。', 'Hari ini adalah tanggal 19.'),
('ex_n4_auto_535', 'v_n4_auto_535', '今日は20日です。', 'きょう は はつか です。', 'Hari ini adalah tanggal 20.'),
('ex_n4_auto_536', 'v_n4_auto_536', '今日は21日です。', 'きょう は にじゅういちにち です。', 'Hari ini adalah tanggal 21.'),
('ex_n4_auto_537', 'v_n4_auto_537', '今日は22日です。', 'きょう は にじゅうににち です。', 'Hari ini adalah tanggal 22.'),
('ex_n4_auto_538', 'v_n4_auto_538', '今日は23日です。', 'きょう は にじゅうさんにち です。', 'Hari ini adalah tanggal 23.'),
('ex_n4_auto_539', 'v_n4_auto_539', '今日は24日です。', 'きょう は にじゅうよっか です。', 'Hari ini adalah tanggal 24.'),
('ex_n4_auto_540', 'v_n4_auto_540', '今日は25日です。', 'きょう は にじゅうごにち です。', 'Hari ini adalah tanggal 25.'),
('ex_n4_auto_541', 'v_n4_auto_541', '今日は26日です。', 'きょう は にじゅうろくにち です。', 'Hari ini adalah tanggal 26.'),
('ex_n4_auto_542', 'v_n4_auto_542', '今日は27日です。', 'きょう は にじゅうしちにち です。', 'Hari ini adalah tanggal 27.'),
('ex_n4_auto_543', 'v_n4_auto_543', '今日は28日です。', 'きょう は にじゅうはちにち です。', 'Hari ini adalah tanggal 28.'),
('ex_n4_auto_544', 'v_n4_auto_544', '今日は29日です。', 'きょう は にじゅうくにち です。', 'Hari ini adalah tanggal 29.'),
('ex_n4_auto_545', 'v_n4_auto_545', '今日は30日です。', 'きょう は さんじゅうにち です。', 'Hari ini adalah tanggal 30.'),
('ex_n4_auto_546', 'v_n4_auto_546', '今日は31日です。', 'きょう は さんじゅういちにち です。', 'Hari ini adalah tanggal 31.'),
('ex_n4_auto_547', 'v_n4_auto_547', '来年の一月に日本に行きます。', 'らいねん の いちがつ に にほん に いきます。', 'Saya akan pergi ke Jepang pada bulan Januari tahun depan.'),
('ex_n4_auto_548', 'v_n4_auto_548', '来年の二月に日本に行きます。', 'らいねん の にがつ に にほん に いきます。', 'Saya akan pergi ke Jepang pada bulan Februari tahun depan.'),
('ex_n4_auto_549', 'v_n4_auto_549', '来年の三月に日本に行きます。', 'らいねん の さんがつ に にほん に いきます。', 'Saya akan pergi ke Jepang pada bulan Maret tahun depan.'),
('ex_n4_auto_550', 'v_n4_auto_550', '来年の四月に日本に行きます。', 'らいねん の しがつ に にほん に いきます。', 'Saya akan pergi ke Jepang pada bulan April tahun depan.'),
('ex_n4_auto_551', 'v_n4_auto_551', '来年の五月に日本に行きます。', 'らいねん の ごがつ に にほん に いきます。', 'Saya akan pergi ke Jepang pada bulan Mei tahun depan.'),
('ex_n4_auto_552', 'v_n4_auto_552', '来年の六月に日本に行きます。', 'らいねん の ろくがつ に にほん に いきます。', 'Saya akan pergi ke Jepang pada bulan Juni tahun depan.'),
('ex_n4_auto_553', 'v_n4_auto_553', '来年の七月に日本に行きます。', 'らいねん の しちがつ に にほん に いきます。', 'Saya akan pergi ke Jepang pada bulan Juli tahun depan.'),
('ex_n4_auto_554', 'v_n4_auto_554', '来年の八月に日本に行きます。', 'らいねん の はちがつ に にほん に いきます。', 'Saya akan pergi ke Jepang pada bulan Agustus tahun depan.'),
('ex_n4_auto_555', 'v_n4_auto_555', '来年の九月に日本に行きます。', 'らいねん の くがつ に にほん に いきます。', 'Saya akan pergi ke Jepang pada bulan September tahun depan.'),
('ex_n4_auto_556', 'v_n4_auto_556', '来年の十月に日本に行きます。', 'らいねん の じゅうがつ に にほん に いきます。', 'Saya akan pergi ke Jepang pada bulan Oktober tahun depan.'),
('ex_n4_auto_557', 'v_n4_auto_557', '来年の十一月に日本に行きます。', 'らいねん の じゅういちがつ に にほん に いきます。', 'Saya akan pergi ke Jepang pada bulan November tahun depan.'),
('ex_n4_auto_558', 'v_n4_auto_558', '来年の十二月に日本に行きます。', 'らいねん の じゅうにがつ に にほん に いきます。', 'Saya akan pergi ke Jepang pada bulan Desember tahun depan.'),
('ex_n4_auto_559', 'v_n4_auto_559', '車が二台あります。', 'くるま が にだい あります。', 'Ada dua buah mobil.'),
('ex_n4_auto_560', 'v_n4_auto_560', '切符を三枚買いました。', 'きっぷ を さんまい かいました。', 'Saya membeli tiga lembar tiket.'),
('ex_n4_auto_561', 'v_n4_auto_561', '本を五冊読みました。', 'ほん を ごさつ よみました。', 'Saya telah membaca lima buah buku.'),
('ex_n4_auto_562', 'v_n4_auto_562', 'ビールを二本飲みました。', 'ビール を にほん のみました。', 'Saya minum dua botol bir.'),
('ex_n4_auto_563', 'v_n4_auto_563', '猫を三匹飼っています。', 'ねこ を さんびき かっています。', 'Saya memelihara tiga ekor kucing.'),
('ex_n4_auto_564', 'v_n4_auto_564', 'コーヒーを一杯ください。', 'コーヒー を いっぱい ください。', 'Tolong secangkir kopi.'),
('ex_n4_auto_565', 'v_n4_auto_565', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_566', 'v_n4_auto_566', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_567', 'v_n4_auto_567', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_568', 'v_n4_auto_568', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_569', 'v_n4_auto_569', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_570', 'v_n4_auto_570', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_571', 'v_n4_auto_571', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_572', 'v_n4_auto_572', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_573', 'v_n4_auto_573', '机の上の不要な書類を整理しました。', 'つくえ の うえ の ふような しょるい を せいり しました。', 'Merapikan dokumen yang tidak diperlukan di atas meja.'),
('ex_n4_auto_574', 'v_n4_auto_574', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_575', 'v_n4_auto_575', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_576', 'v_n4_auto_576', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_577', 'v_n4_auto_577', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_578', 'v_n4_auto_578', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_579', 'v_n4_auto_579', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_580', 'v_n4_auto_580', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_581', 'v_n4_auto_581', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_582', 'v_n4_auto_582', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_583', 'v_n4_auto_583', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_584', 'v_n4_auto_584', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_585', 'v_n4_auto_585', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_586', 'v_n4_auto_586', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_587', 'v_n4_auto_587', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_588', 'v_n4_auto_588', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_589', 'v_n4_auto_589', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_590', 'v_n4_auto_590', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_591', 'v_n4_auto_591', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_592', 'v_n4_auto_592', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_593', 'v_n4_auto_593', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_594', 'v_n4_auto_594', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_595', 'v_n4_auto_595', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_596', 'v_n4_auto_596', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_597', 'v_n4_auto_597', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_598', 'v_n4_auto_598', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_599', 'v_n4_auto_599', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_600', 'v_n4_auto_600', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_601', 'v_n4_auto_601', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_602', 'v_n4_auto_602', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_603', 'v_n4_auto_603', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_604', 'v_n4_auto_604', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_605', 'v_n4_auto_605', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_606', 'v_n4_auto_606', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_607', 'v_n4_auto_607', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_608', 'v_n4_auto_608', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_609', 'v_n4_auto_609', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_610', 'v_n4_auto_610', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_611', 'v_n4_auto_611', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_612', 'v_n4_auto_612', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_613', 'v_n4_auto_613', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_614', 'v_n4_auto_614', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_615', 'v_n4_auto_615', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_616', 'v_n4_auto_616', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_617', 'v_n4_auto_617', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_618', 'v_n4_auto_618', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_619', 'v_n4_auto_619', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_620', 'v_n4_auto_620', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_621', 'v_n4_auto_621', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_622', 'v_n4_auto_622', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_623', 'v_n4_auto_623', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_624', 'v_n4_auto_624', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_625', 'v_n4_auto_625', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_626', 'v_n4_auto_626', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_627', 'v_n4_auto_627', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_628', 'v_n4_auto_628', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_629', 'v_n4_auto_629', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_630', 'v_n4_auto_630', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_631', 'v_n4_auto_631', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_632', 'v_n4_auto_632', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_633', 'v_n4_auto_633', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_634', 'v_n4_auto_634', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_635', 'v_n4_auto_635', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_636', 'v_n4_auto_636', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_637', 'v_n4_auto_637', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_638', 'v_n4_auto_638', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_639', 'v_n4_auto_639', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_640', 'v_n4_auto_640', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_641', 'v_n4_auto_641', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_642', 'v_n4_auto_642', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_643', 'v_n4_auto_643', 'undefined', 'undefined', 'undefined'),
('ex_n4_auto_644', 'v_n4_auto_644', 'undefined', 'undefined', 'undefined');
