-- Seed data for N4 Vocabularies (Total: 644)

INSERT INTO public.vocabularies (id, level, kanji, kana, romaji, meaning, type) VALUES
('v_n4_auto_1', 'N4', '送る', 'おくる', 'okuru', 'mengirim / mengantar', 'Verb (Godan)'),
('v_n4_auto_2', 'N4', '探す', 'さがす', 'sagasu', 'mencari', 'Verb (Godan)'),
('v_n4_auto_3', 'N4', '間に合う', 'まにあう', 'maniau', 'keburu / sempat / tepat waktu', 'Verb (Godan)'),
('v_n4_auto_4', 'N4', '拾う', 'ひろう', 'hirou', 'memungut / mengambil', 'Verb (Godan)'),
('v_n4_auto_5', 'N4', '通う', 'かよう', 'kayou', 'pulang pergi (sekolah/kantor)', 'Verb (Godan)'),
('v_n4_auto_6', 'N4', '踊る', 'おどる', 'odoru', 'menari', 'Verb (Godan)'),
('v_n4_auto_7', 'N4', '噛む', 'かむ', 'kamu', 'mengunyah / menggigit', 'Verb (Godan)'),
('v_n4_auto_8', 'N4', '選ぶ', 'えらぶ', 'erabu', 'memilih', 'Verb (Godan)'),
('v_n4_auto_9', 'N4', '誘う', 'さそう', 'sasou', 'mengajak / mengundang', 'Verb (Godan)'),
('v_n4_auto_10', 'N4', '起こす', 'おこす', 'okosu', 'membangunkan', 'Verb (Godan)'),
('v_n4_auto_11', 'N4', '頼む', 'たのむ', 'tanomu', 'meminta / memohon', 'Verb (Godan)'),
('v_n4_auto_12', 'N4', '怒る', 'おこる', 'okoru', 'marah', 'Verb (Godan)'),
('v_n4_auto_13', 'N4', '違う', 'ちがう', 'chigau', 'berbeda / salah', 'Verb (Godan)'),
('v_n4_auto_14', 'N4', '手伝う', 'てつだう', 'tetsudau', 'membantu', 'Verb (Godan)'),
('v_n4_auto_15', 'N4', '払う', 'はらう', 'harau', 'membayar', 'Verb (Godan)'),
('v_n4_auto_16', 'N4', '笑う', 'わらう', 'warau', 'tertawa / tersenyum', 'Verb (Godan)'),
('v_n4_auto_17', 'N4', '歌う', 'うたう', 'utau', 'bernyanyi', 'Verb (Godan)'),
('v_n4_auto_18', 'N4', '向かう', 'むかう', 'mukau', 'menuju ke', 'Verb (Godan)'),
('v_n4_auto_19', 'N4', '吸う', 'すう', 'suu', 'menghisap / merokok', 'Verb (Godan)'),
('v_n4_auto_20', 'N4', '洗う', 'あらう', 'arau', 'mencuci', 'Verb (Godan)'),
('v_n4_auto_21', 'N4', '言う', 'いう', 'iu', 'berkata / mengatakan', 'Verb (Godan)'),
('v_n4_auto_22', 'N4', '思う', 'おもう', 'omou', 'berpikir / mengira', 'Verb (Godan)'),
('v_n4_auto_23', 'N4', '行う', 'おこなう', 'okonau', 'melaksanakan / mengadakan', 'Verb (Godan)'),
('v_n4_auto_24', 'N4', '戻る', 'もどる', 'modoru', 'kembali', 'Verb (Godan)'),
('v_n4_auto_25', 'N4', '壊す', 'こわす', 'kowasu', 'merusak / memecahkan', 'Verb (Godan)'),
('v_n4_auto_26', 'N4', '消す', 'けす', 'kesu', 'memadamkan / mematikan', 'Verb (Godan)'),
('v_n4_auto_27', 'N4', '直す', 'なおす', 'naosu', 'memperbaiki / membenarkan', 'Verb (Godan)'),
('v_n4_auto_28', 'N4', '回す', 'まわす', 'mawasu', 'memutar', 'Verb (Godan)'),
('v_n4_auto_29', 'N4', '返す', 'かえす', 'kaesu', 'mengembalikan (barang)', 'Verb (Godan)'),
('v_n4_auto_30', 'N4', '渡す', 'わたす', 'watasu', 'menyerahkan', 'Verb (Godan)'),
('v_n4_auto_31', 'N4', '話す', 'はなす', 'hanasu', 'berbicara / mengobrol', 'Verb (Godan)'),
('v_n4_auto_32', 'N4', '残す', 'のこす', 'nokosu', 'menyisakan / meninggalkan', 'Verb (Godan)'),
('v_n4_auto_33', 'N4', '沸かす', 'わかす', 'wakasu', 'mendidihkan (air)', 'Verb (Godan)'),
('v_n4_auto_34', 'N4', '押す', 'おす', 'osu', 'menekan / mendorong', 'Verb (Godan)'),
('v_n4_auto_35', 'N4', '貸す', 'かす', 'kasu', 'meminjamkan', 'Verb (Godan)'),
('v_n4_auto_36', 'N4', '移す', 'うつす', 'utsusu', 'memindahkan', 'Verb (Godan)'),
('v_n4_auto_37', 'N4', '落とす', 'おとす', 'otosu', 'menjatuhkan / menghilangkan', 'Verb (Godan)'),
('v_n4_auto_38', 'N4', '死ぬ', 'しぬ', 'shinu', 'meninggal / mati', 'Verb (Godan)'),
('v_n4_auto_39', 'N4', '遊ぶ', 'あそぶ', 'asobu', 'bermain / bersenang-senang', 'Verb (Godan)'),
('v_n4_auto_40', 'N4', '呼ぶ', 'よぶ', 'yobu', 'memanggil / mengundang', 'Verb (Godan)'),
('v_n4_auto_41', 'N4', '飛ぶ', 'とぶ', 'tobu', 'terbang / melompat', 'Verb (Godan)'),
('v_n4_auto_42', 'N4', '楽しむ', 'たのしむ', 'tanoshimu', 'menikmati', 'Verb (Godan)'),
('v_n4_auto_43', 'N4', '住む', 'すむ', 'sumu', 'tinggal / bermukim', 'Verb (Godan)'),
('v_n4_auto_44', 'N4', '休む', 'やすむ', 'yasumu', 'beristirahat / libur', 'Verb (Godan)'),
('v_n4_auto_45', 'N4', '踏む', 'ふむ', 'fumu', 'menginjak', 'Verb (Godan)'),
('v_n4_auto_46', 'N4', '包む', 'つつむ', 'tsutsumu', 'membungkus', 'Verb (Godan)'),
('v_n4_auto_47', 'N4', '込む', 'こむ', 'komu', 'padat / ramai / sesak', 'Verb (Godan)'),
('v_n4_auto_48', 'N4', '曇る', 'くもる', 'kumoru', 'mendung / berawan', 'Verb (Godan)'),
('v_n4_auto_49', 'N4', '走る', 'はしる', 'hashiru', 'berlari', 'Verb (Godan)'),
('v_n4_auto_50', 'N4', '乗る', 'のる', 'noru', 'naik (kendaraan)', 'Verb (Godan)'),
('v_n4_auto_51', 'N4', '降る', 'ふる', 'furu', 'turun (hujan/salju)', 'Verb (Godan)'),
('v_n4_auto_52', 'N4', '取る', 'とる', 'toru', 'mengambil / meraih', 'Verb (Godan)'),
('v_n4_auto_53', 'N4', '要る', 'いる', 'iru', 'memerlukan / butuh', 'Verb (Godan)'),
('v_n4_auto_54', 'N4', '知る', 'しる', 'shiru', 'tahu / mengenal', 'Verb (Godan)'),
('v_n4_auto_55', 'N4', '勝つ', 'かつ', 'katsu', 'menang', 'Verb (Godan)'),
('v_n4_auto_56', 'N4', '吹く', 'ふく', 'fuku', 'meniup / bertiup', 'Verb (Godan)'),
('v_n4_auto_57', 'N4', '引く', 'ひく', 'hiku', 'menarik / merujuk (kamus)', 'Verb (Godan)'),
('v_n4_auto_58', 'N4', '立つ', 'たつ', 'tatsu', 'berdiri', 'Verb (Godan)'),
('v_n4_auto_59', 'N4', '止める', 'とめる', 'tomeru', 'menghentikan / memarkir', 'Verb (Ichidan)'),
('v_n4_auto_60', 'N4', '見つける', 'みつける', 'mitsukeru', 'menemukan', 'Verb (Ichidan)'),
('v_n4_auto_61', 'N4', '始める', 'はじめる', 'hajimeru', 'memulai', 'Verb (Ichidan)'),
('v_n4_auto_62', 'N4', '考える', 'かんがえる', 'kangaeru', 'berpikir', 'Verb (Ichidan)'),
('v_n4_auto_63', 'N4', '調べる', 'しらべる', 'shiraberu', 'memeriksa / menyelidiki', 'Verb (Ichidan)'),
('v_n4_auto_64', 'N4', '続ける', 'つづける', 'tsuduzeru', 'melanjutkan', 'Verb (Ichidan)'),
('v_n4_auto_65', 'N4', '立てる', 'たてる', 'tateru', 'mendirikan / menyusun', 'Verb (Ichidan)'),
('v_n4_auto_66', 'N4', '建てる', 'たてる', 'tateru', 'membangun (gedung)', 'Verb (Ichidan)'),
('v_n4_auto_67', 'N4', '決める', 'きめる', 'kimeru', 'memutuskan', 'Verb (Ichidan)'),
('v_n4_auto_68', 'N4', '信じる', 'しんじる', 'shinjiru', 'mempercayai', 'Verb (Ichidan)'),
('v_n4_auto_69', 'N4', '知らせる', 'しらせる', 'shiraseru', 'memberitahu', 'Verb (Ichidan)'),
('v_n4_auto_70', 'N4', '育てる', 'そだてる', 'sodateru', 'membesarkan', 'Verb (Ichidan)'),
('v_n4_auto_71', 'N4', '負ける', 'まける', 'makeru', 'kalah', 'Verb (Ichidan)'),
('v_n4_auto_72', 'N4', '遅れる', 'おくれる', 'okureru', 'terlambat', 'Verb (Ichidan)'),
('v_n4_auto_73', 'N4', '植える', 'うえる', 'ueru', 'menanam', 'Verb (Ichidan)'),
('v_n4_auto_74', 'N4', '消える', 'きえる', 'kieru', 'padam', 'Verb (Ichidan)'),
('v_n4_auto_75', 'N4', '壊れる', 'こわれる', 'kowareru', 'rusak', 'Verb (Ichidan)'),
('v_n4_auto_76', 'N4', '割れる', 'われる', 'wareru', 'pecah', 'Verb (Ichidan)'),
('v_n4_auto_77', 'N4', '折れる', 'おれる', 'oreru', 'patah', 'Verb (Ichidan)'),
('v_n4_auto_78', 'N4', '破れる', 'やぶれる', 'yabureru', 'robek', 'Verb (Ichidan)'),
('v_n4_auto_79', 'N4', '汚れる', 'よごれる', 'yogoreru', 'kotor', 'Verb (Ichidan)'),
('v_n4_auto_80', 'N4', '間違える', 'まちがえる', 'machigaeru', 'salah', 'Verb (Ichidan)'),
('v_n4_auto_81', 'N4', '片付ける', 'かたづける', 'katadukeru', 'membereskan', 'Verb (Ichidan)'),
('v_n4_auto_82', 'N4', 'お祝いする', 'おいわいする', 'oiwaisuru', 'merayakan', 'Verb (Irregular)'),
('v_n4_auto_83', 'N4', '紹介する', 'しょうかいする', 'shoukaishuru', 'memperkenalkan', 'Verb (Irregular)'),
('v_n4_auto_84', 'N4', '案内する', 'あんないする', 'annaisuru', 'memandu', 'Verb (Irregular)'),
('v_n4_auto_85', 'N4', '説明する', 'せつめいする', 'setsumeisuru', 'menjelaskan', 'Verb (Irregular)'),
('v_n4_auto_86', 'N4', '留学する', 'りゅうがくする', 'ryuugakusuru', 'belajar di luar negeri', 'Verb (Irregular)'),
('v_n4_auto_87', 'N4', '運転する', 'うんてんする', 'untensuru', 'mengemudi', 'Verb (Irregular)'),
('v_n4_auto_88', 'N4', '予約する', 'よやくする', 'yoyakusuru', 'memesan', 'Verb (Irregular)'),
('v_n4_auto_89', 'N4', '相談する', 'そうだんする', 'soudansuru', 'berkonsultasi', 'Verb (Irregular)'),
('v_n4_auto_90', 'N4', '連絡する', 'れんらくする', 'renrakusuru', 'menghubungi', 'Verb (Irregular)'),
('v_n4_auto_91', 'N4', '準備する', 'じゅんびする', 'junbisuru', 'mempersiapkan', 'Verb (Irregular)'),
('v_n4_auto_92', 'N4', '復習する', 'ふくしゅうする', 'fukushuusuru', 'mengulang', 'Verb (Irregular)'),
('v_n4_auto_93', 'N4', '予習する', 'よしゅうする', 'yoshuusuru', 'mempersiapkan', 'Verb (Irregular)'),
('v_n4_auto_94', 'N4', '卒業する', 'そつぎょうする', 'sotsugyousuru', 'lulus', 'Verb (Irregular)'),
('v_n4_auto_95', 'N4', '運動する', 'うんどうする', 'undousuru', 'berolahraga', 'Verb (Irregular)'),
('v_n4_auto_96', 'N4', '心配する', 'しんぱいする', 'shinpaisuru', 'khawatir', 'Verb (Irregular)'),
('v_n4_auto_97', 'N4', '招待する', 'しょうたいする', 'shoutaisuru', 'mengundang', 'Verb (Irregular)'),
('v_n4_auto_98', 'N4', '諦める', 'あきらめる', 'akirameru', 'menyerah', 'Verb (Ichidan)'),
('v_n4_auto_99', 'N4', '謝る', 'あやまる', 'ayamaru', 'meminta maaf', 'Verb (Godan)'),
('v_n4_auto_100', 'N4', '急ぐ', 'いそぐ', 'isogu', 'bergegas / terburu-buru', 'Verb (Godan)'),
('v_n4_auto_101', 'N4', '祈る', 'いのる', 'inoru', 'berdoa', 'Verb (Godan)'),
('v_n4_auto_102', 'N4', '受ける', 'うける', 'ukeru', 'menerima / mengikuti (ujian)', 'Verb (Ichidan)'),
('v_n4_auto_103', 'N4', '動く', 'うごく', 'ugoku', 'bergerak / berfungsi', 'Verb (Godan)'),
('v_n4_auto_104', 'N4', '写す', 'うつす', 'utsusu', 'menyalin / memotret', 'Verb (Godan)'),
('v_n4_auto_105', 'N4', '移る', 'うつる', 'utsuru', 'pindah (tempat/penyakit)', 'Verb (Godan)'),
('v_n4_auto_106', 'N4', '落ちる', 'おちる', 'ochiru', 'jatuh / gugur', 'Verb (Ichidan)'),
('v_n4_auto_107', 'N4', 'おっしゃる', 'おっしゃる', 'ossharu', 'berkata (hormat)', 'Verb (Godan)'),
('v_n4_auto_108', 'N4', '驚く', 'おどろく', 'odoroku', 'terkejut / heran', 'Verb (Godan)'),
('v_n4_auto_109', 'N4', '思い出す', 'おもいだす', 'omoidasu', 'mengingat kembali / teringat', 'Verb (Godan)'),
('v_n4_auto_110', 'N4', '折る', 'おる', 'oru', 'melipat / mematahkan', 'Verb (Godan)'),
('v_n4_auto_111', 'N4', '飾る', 'かざる', 'kazaru', 'menghias / memajang', 'Verb (Godan)'),
('v_n4_auto_112', 'N4', '片付く', 'かたづく', 'kataduku', 'rapi / beres', 'Verb (Godan)'),
('v_n4_auto_113', 'N4', '変わる', 'かわる', 'kawaru', 'berubah', 'Verb (Godan)'),
('v_n4_auto_114', 'N4', '変える', 'かえる', 'kaeru', 'mengubah / menukar', 'Verb (Ichidan)'),
('v_n4_auto_115', 'N4', '頑張る', 'がんばる', 'ganbaru', 'berjuang / berusaha keras', 'Verb (Godan)'),
('v_n4_auto_116', 'N4', '決まる', 'きまる', 'kimaru', 'diputuskan / ditetapkan', 'Verb (Godan)'),
('v_n4_auto_117', 'N4', '比べる', 'くらべる', 'kuraberu', 'membandingkan', 'Verb (Ichidan)'),
('v_n4_auto_118', 'N4', 'くれる', 'くれる', 'kureru', 'memberi (kepada saya)', 'Verb (Ichidan)'),
('v_n4_auto_119', 'N4', '下がる', 'さがる', 'sagaru', 'turun / mundur', 'Verb (Godan)'),
('v_n4_auto_120', 'N4', '下げる', 'さげる', 'sageru', 'menurunkan', 'Verb (Ichidan)'),
('v_n4_auto_121', 'N4', '騒ぐ', 'さわぐ', 'sawagu', 'membuat keributan / berisik', 'Verb (Godan)'),
('v_n4_auto_122', 'N4', '触る', 'さわる', 'sawaru', 'menyentuh / memegang', 'Verb (Godan)'),
('v_n4_auto_123', 'N4', '叱る', 'しかる', 'shikaru', 'memarahi', 'Verb (Godan)'),
('v_n4_auto_124', 'N4', '過ぎる', 'すぎる', 'sugiru', 'melewati / melampaui / terlalu', 'Verb (Ichidan)'),
('v_n4_auto_125', 'N4', '空く', 'すく', 'suku', 'menjadi kosong / lapar', 'Verb (Godan)'),
('v_n4_auto_126', 'N4', '進む', 'すすむ', 'susumu', 'maju / berkembang', 'Verb (Godan)'),
('v_n4_auto_127', 'N4', '滑る', 'すべる', 'suberu', 'terpeleset / licin', 'Verb (Godan)'),
('v_n4_auto_128', 'N4', '育つ', 'そだつ', 'sodatsu', 'tumbuh besar', 'Verb (Godan)'),
('v_n4_auto_129', 'N4', '倒れる', 'たおれる', 'taoreteru', 'tumbang / pingsan / roboh', 'Verb (Ichidan)'),
('v_n4_auto_130', 'N4', '助ける', 'たすける', 'tasukeru', 'menolong / menyelamatkan', 'Verb (Ichidan)'),
('v_n4_auto_131', 'N4', '訪ねる', 'たずねる', 'tazuneru', 'mengunjungi', 'Verb (Ichidan)'),
('v_n4_auto_132', 'N4', '足りる', 'たりる', 'tariru', 'cukup', 'Verb (Ichidan)'),
('v_n4_auto_133', 'N4', '伝える', 'つたえる', 'tsutaeru', 'menyampaikan', 'Verb (Ichidan)'),
('v_n4_auto_134', 'N4', '続く', 'つづく', 'tsuduku', 'berlanjut', 'Verb (Godan)'),
('v_n4_auto_135', 'N4', '連れる', 'つれる', 'tsureru', 'membawa (orang/hewan)', 'Verb (Ichidan)'),
('v_n4_auto_136', 'N4', '通る', 'とおる', 'tooru', 'melewati / melalui', 'Verb (Godan)'),
('v_n4_auto_137', 'N4', 'お届けする', 'おとどけする', 'otodokesuru', 'mengantarkan (sopan)', 'Verb (Irregular)'),
('v_n4_auto_138', 'N4', '泊まる', 'とまる', 'tomaru', 'menginap', 'Verb (Godan)'),
('v_n4_auto_139', 'N4', '取り替える', 'とりかえる', 'torikaeru', 'menukar / mengganti', 'Verb (Ichidan)'),
('v_n4_auto_140', 'N4', '投げる', 'なげる', 'nageru', 'melempar', 'Verb (Ichidan)'),
('v_n4_auto_141', 'N4', '亡くなる', 'なくなる', 'nakunaru', 'meninggal dunia', 'Verb (Godan)'),
('v_n4_auto_142', 'N4', '無くなる', 'なくなる', 'nakunaru', 'hilang / habis', 'Verb (Godan)'),
('v_n4_auto_143', 'N4', '治る', 'なおる', 'naoru', 'sembuh / membaik', 'Verb (Godan)'),
('v_n4_auto_144', 'N4', '慣れる', 'なれる', 'nareru', 'terbiasa', 'Verb (Ichidan)'),
('v_n4_auto_145', 'N4', '逃げる', 'nigeru', 'nigeru', 'melarikan diri / kabur', 'Verb (Ichidan)'),
('v_n4_auto_146', 'N4', '似る', 'にる', 'niru', 'mirip', 'Verb (Ichidan)'),
('v_n4_auto_147', 'N4', '盗む', 'ぬすむ', 'nusumu', 'mencuri', 'Verb (Godan)'),
('v_n4_auto_148', 'N4', '塗る', 'ぬる', 'nuru', 'mengoleskan / mengecat', 'Verb (Godan)'),
('v_n4_auto_149', 'N4', '濡れる', 'ぬれる', 'nureru', 'basah', 'Verb (Ichidan)'),
('v_n4_auto_150', 'N4', '眠る', 'nemuru', 'nemuru', 'tidur nyenyak', 'Verb (Godan)'),
('v_n4_auto_151', 'N4', '残る', 'のこる', 'nokoru', 'tersisa', 'Verb (Godan)'),
('v_n4_auto_152', 'N4', '乗り換える', 'のりかえる', 'norikaeru', 'transit / berganti kendaraan', 'Verb (Ichidan)'),
('v_n4_auto_153', 'N4', '運ぶ', 'hakobu', 'hakobu', 'mengangkut / membawa', 'Verb (Godan)'),
('v_n4_auto_154', 'N4', '始まる', 'はじまる', 'hajimaru', 'mulai / dimulai', 'Verb (Godan)'),
('v_n4_auto_155', 'N4', '晴れる', 'はれる', 'hareru', 'cerah', 'Verb (Ichidan)'),
('v_n4_auto_156', 'N4', '冷える', 'ひえる', 'hieru', 'menjadi dingin', 'Verb (Ichidan)'),
('v_n4_auto_157', 'N4', '冷やす', 'ひやす', 'hiyasu', 'mendinginkan', 'Verb (Godan)'),
('v_n4_auto_158', 'N4', '光る', 'ひかる', 'hikaru', 'bersinar / bercahaya', 'Verb (Godan)'),
('v_n4_auto_159', 'N4', '増える', 'ふえる', 'fueru', 'bertambah / meningkat', 'Verb (Ichidan)'),
('v_n4_auto_160', 'N4', '増やす', 'ふやす', 'fuyasu', 'menambah / meningkatkan', 'Verb (Godan)'),
('v_n4_auto_161', 'N4', '拭く', 'ふく', 'fuku', 'menyeka / mengelap', 'Verb (Godan)'),
('v_n4_auto_162', 'N4', '褒める', 'ほめる', 'homeru', 'memuji', 'Verb (Ichidan)'),
('v_n4_auto_163', 'N4', '参る', 'まいる', 'mairu', 'datang / pergi (rendah hati)', 'Verb (Godan)'),
('v_n4_auto_164', 'N4', '曲がる', 'まがる', 'magaru', 'berbelok / melengkung', 'Verb (Godan)'),
('v_n4_auto_165', 'N4', '守る', 'まもる', 'mamoru', 'melindungi / mematuhi', 'Verb (Godan)'),
('v_n4_auto_166', 'N4', '迷う', 'まよう', 'mayou', 'tersesat / ragu-ragu', 'Verb (Godan)'),
('v_n4_auto_167', 'N4', '見える', 'みえる', 'mieru', 'terlihat', 'Verb (Ichidan)'),
('v_n4_auto_168', 'N4', '見かける', 'みかける', 'mikakeru', 'kebetulan melihat / berpapasan', 'Verb (Ichidan)'),
('v_n4_auto_169', 'N4', '見つかる', 'みつかる', 'mitsukaru', 'ditemukan', 'Verb (Godan)'),
('v_n4_auto_170', 'N4', '迎える', 'むかえる', 'mukaeru', 'menjemput / menyambut', 'Verb (Ichidan)'),
('v_n4_auto_171', 'N4', '戻す', 'もどす', 'modosu', 'mengembalikan (ke posisi awal)', 'Verb (Godan)'),
('v_n4_auto_172', 'N4', '申し上げる', 'もうしあげる', 'moushiageru', 'mengatakan (rendah hati)', 'Verb (Ichidan)'),
('v_n4_auto_173', 'N4', '焼く', 'やく', 'yaku', 'memanggang / membakar', 'Verb (Godan)'),
('v_n4_auto_174', 'N4', '焼ける', 'やける', 'yakeru', 'terpanggang / terbakar', 'Verb (Ichidan)'),
('v_n4_auto_175', 'N4', '痩せる', 'やせる', 'yaseru', 'menjadi kurus', 'Verb (Ichidan)'),
('v_n4_auto_176', 'N4', '辞める', 'やめる', 'yameru', 'berhenti (kerja/sekolah) / membatalkan', 'Verb (Ichidan)'),
('v_n4_auto_177', 'N4', 'やる', 'やる', 'yaru', 'melakukan / memberi makan', 'Verb (Godan)'),
('v_n4_auto_178', 'N4', '汚す', 'よごす', 'yogosu', 'mengotori', 'Verb (Godan)'),
('v_n4_auto_179', 'N4', '喜ぶ', 'よろこぶ', 'yorokobu', 'bergembira / senang', 'Verb (Godan)'),
('v_n4_auto_180', 'N4', '沸く', 'わく', 'waku', 'mendidih', 'Verb (Godan)'),
('v_n4_auto_181', 'N4', '渡る', 'わたる', 'wataru', 'menyeberang', 'Verb (Godan)'),
('v_n4_auto_182', 'N4', '割る', 'わる', 'waru', 'memecahkan / membagi', 'Verb (Godan)'),
('v_n4_auto_183', 'N4', '嬉しい', 'うれしい', 'ureshii', 'senang / gembira', 'Adjective (I)'),
('v_n4_auto_184', 'N4', '悲しい', 'かなしい', 'kanashii', 'sedih', 'Adjective (I)'),
('v_n4_auto_185', 'N4', '恥ずかしい', 'はずかしい', 'hazukashii', 'malu', 'Adjective (I)'),
('v_n4_auto_186', 'N4', '珍しい', 'めずらしい', 'mezurashii', 'langka / tidak biasa', 'Adjective (I)'),
('v_n4_auto_187', 'N4', '厳しい', 'きびしい', 'kibishii', 'tegas / keras / galak', 'Adjective (I)'),
('v_n4_auto_188', 'N4', '優しい', 'やさしい', 'yasashii', 'baik hati / ramah', 'Adjective (I)'),
('v_n4_auto_189', 'N4', '正しい', 'ただしい', 'tadashii', 'benar / tepat', 'Adjective (I)'),
('v_n4_auto_190', 'N4', '美しい', 'うつくしい', 'utsukushii', 'indah / cantik', 'Adjective (I)'),
('v_n4_auto_191', 'N4', '素晴らしい', 'すばらしい', 'subarashii', 'luar biasa / hebat', 'Adjective (I)'),
('v_n4_auto_192', 'N4', '詳しい', 'くわしい', 'kuwashii', 'detail / rinci / paham betul', 'Adjective (I)'),
('v_n4_auto_193', 'N4', '深い', 'ふかい', 'fukai', 'dalam', 'Adjective (I)'),
('v_n4_auto_194', 'N4', '浅い', 'あさい', 'asai', 'dangkal', 'Adjective (I)'),
('v_n4_auto_195', 'N4', '厚い', 'あつい', 'atsui', 'tebal (buku, kain, dll)', 'Adjective (I)'),
('v_n4_auto_196', 'N4', '薄い', 'うすい', 'usui', 'tipis / hambar (rasa)', 'Adjective (I)'),
('v_n4_auto_197', 'N4', '悔しい', 'くやしい', 'kuyashii', 'menyesal / kesal (karena kalah)', 'Adjective (I)'),
('v_n4_auto_198', 'N4', '懐かしい', 'なつかしい', 'natsukashii', 'rindu / membuat nostalgia', 'Adjective (I)'),
('v_n4_auto_199', 'N4', '丁寧', 'ていねい', 'teinei', 'sopan / teliti', 'Adjective (Na)'),
('v_n4_auto_200', 'N4', '複雑', 'ふくざつ', 'fukuzatsu', 'rumit / kompleks', 'Adjective (Na)'),
('v_n4_auto_201', 'N4', '簡単', 'かんたん', 'kantan', 'mudah / simpel', 'Adjective (Na)'),
('v_n4_auto_202', 'N4', '安全', 'あんぜん', 'anzen', 'aman', 'Adjective (Na)'),
('v_n4_auto_203', 'N4', '危険', 'きけん', 'kiken', 'bahaya', 'Adjective (Na)'),
('v_n4_auto_204', 'N4', '残念', 'ざんねん', 'zannen', 'sayang sekali / mengecewakan', 'Adjective (Na)'),
('v_n4_auto_205', 'N4', '無理', 'むり', 'muri', 'mustahil / memaksakan diri', 'Adjective (Na)'),
('v_n4_auto_206', 'N4', '必要', 'ひつよう', 'hitsuyou', 'perlu / butuh', 'Adjective (Na)'),
('v_n4_auto_207', 'N4', '特別', 'tokubetsu', 'tokubetsu', 'khusus / istimewa', 'Adjective (Na)'),
('v_n4_auto_208', 'N4', '不便', 'ふべん', 'fuben', 'tidak praktis / menyusahkan', 'Adjective (Na)'),
('v_n4_auto_209', 'N4', '親切', 'しんせつ', 'shinsetsu', 'ramah / baik hati', 'Adjective (Na)'),
('v_n4_auto_210', 'N4', '邪魔', 'じゃま', 'jama', 'mengganggu / penghalang', 'Adjective (Na)'),
('v_n4_auto_211', 'N4', '楽', 'らく', 'raku', 'nyaman / mudah', 'Adjective (Na)'),
('v_n4_auto_212', 'N4', '適当', 'てきとう', 'tekitou', 'cocok / sesuai', 'Adjective (Na)'),
('v_n4_auto_213', 'N4', '甘い', 'あまい', 'amai', 'manis', 'Adjective (I)'),
('v_n4_auto_214', 'N4', '辛い', 'からい', 'karai', 'pedas', 'Adjective (I)'),
('v_n4_auto_215', 'N4', '塩辛い', 'しおからい', 'shiokarai', 'asin', 'Adjective (I)'),
('v_n4_auto_216', 'N4', '酸っぱい', 'すっぱい', 'suppai', 'asam', 'Adjective (I)'),
('v_n4_auto_217', 'N4', '苦い', 'にがい', 'nigai', 'pahit', 'Adjective (I)'),
('v_n4_auto_218', 'N4', 'おかしい', 'おかしい', 'okashii', 'aneh / lucu', 'Adjective (I)'),
('v_n4_auto_219', 'N4', '苦しい', 'くるしい', 'kurushii', 'menderita / sesak / sulit', 'Adjective (I)'),
('v_n4_auto_220', 'N4', '細かい', 'こまかい', 'komakai', 'kecil / rinci / uang receh', 'Adjective (I)'),
('v_n4_auto_221', 'N4', '寂しい', 'さびしい', 'sabishii', 'sepi / kesepian', 'Adjective (I)'),
('v_n4_auto_222', 'N4', '近い', 'ちかい', 'chikai', 'dekat', 'Adjective (I)'),
('v_n4_auto_223', 'N4', 'つまらない', 'つまらない', 'tsumaranai', 'membosankan / tidak menarik', 'Adjective (I)'),
('v_n4_auto_224', 'N4', '眠い', 'ねむい', 'nemui', 'mengantuk', 'Adjective (I)'),
('v_n4_auto_225', 'N4', 'ひどい', 'ひどい', 'hidoi', 'kejam / parah / buruk sekali', 'Adjective (I)'),
('v_n4_auto_226', 'N4', '欲しい', 'ほしい', 'hoshii', 'ingin / menginginkan (barang)', 'Adjective (I)'),
('v_n4_auto_227', 'N4', 'よろしい', 'よろしい', 'yoroshii', 'boleh / baik (formal)', 'Adjective (I)'),
('v_n4_auto_228', 'N4', '大人しい', 'おとなしい', 'otonashii', 'pendiam / penurut / tenang', 'Adjective (Na)'),
('v_n4_auto_229', 'N4', '賢い', 'かしこい', 'kashikoi', 'pintar / cerdas', 'Adjective (I)'),
('v_n4_auto_230', 'N4', '幸せ', 'しあわせ', 'shiawase', 'bahagia', 'Adjective (Na)'),
('v_n4_auto_231', 'N4', '新鮮', 'しんせん', 'shinsen', 'segar (makanan/udara)', 'Adjective (Na)'),
('v_n4_auto_232', 'N4', '熱心', 'ねっしん', 'nesshin', 'tekun / antusias / rajin', 'Adjective (Na)'),
('v_n4_auto_233', 'N4', '真面目', 'まじめ', 'majime', 'serius / jujur / rajin', 'Adjective (Na)'),
('v_n4_auto_234', 'N4', '有名', 'ゆうめい', 'yuumei', 'terkenal / populer', 'Adjective (Na)'),
('v_n4_auto_235', 'N4', '立派', 'りっぱ', 'rippa', 'megah / mulia / hebat', 'Adjective (Na)'),
('v_n4_auto_236', 'N4', '暗い', 'くらい', 'kurai', 'gelap / suram', 'Adjective (I)'),
('v_n4_auto_237', 'N4', '明るい', 'あかるい', 'akarui', 'terang / ceria', 'Adjective (I)'),
('v_n4_auto_238', 'N4', '汚い', 'きたない', 'kitanai', 'kotor / jorok', 'Adjective (I)'),
('v_n4_auto_239', 'N4', '危ない', 'あぶない', 'abunai', 'bahaya', 'Adjective (I)'),
('v_n4_auto_240', 'N4', '酷い', 'ひどい', 'hidoi', 'parah / buruk sekali', 'Adjective (I)'),
('v_n4_auto_241', 'N4', '若い', 'わかい', 'wakai', 'muda', 'Adjective (I)'),
('v_n4_auto_242', 'N4', '長い', 'ながい', 'nagai', 'panjang', 'Adjective (I)'),
('v_n4_auto_243', 'N4', '短い', 'みじかい', 'mijikai', 'pendek', 'Adjective (I)'),
('v_n4_auto_244', 'N4', '重い', 'おもい', 'omoi', 'berat', 'Adjective (I)'),
('v_n4_auto_245', 'N4', '軽い', 'かるい', 'karui', 'ringan', 'Adjective (I)'),
('v_n4_auto_246', 'N4', '広い', 'ひろい', 'hiroi', 'luas', 'Adjective (I)'),
('v_n4_auto_247', 'N4', '狭い', 'せまい', 'semai', 'sempit', 'Adjective (I)'),
('v_n4_auto_248', 'N4', '急に', 'きゅうに', 'kyuu ni', 'tiba-tiba', 'Adverb'),
('v_n4_auto_249', 'N4', '非常に', 'ひじょうに', 'hijo ni', 'sangat / amat', 'Adverb'),
('v_n4_auto_250', 'N4', 'ほとんど', 'ほとんど', 'hotondo', 'hampir seluruhnya', 'Adverb'),
('v_n4_auto_251', 'N4', 'ずいぶん', 'ずいぶん', 'zuibun', 'lumayan / sangat', 'Adverb'),
('v_n4_auto_252', 'N4', 'やっと', 'やっと', 'yatto', 'akhirnya (setelah bersusah payah)', 'Adverb'),
('v_n4_auto_253', 'N4', 'とうとう', 'とうとう', 'toutou', 'akhirnya', 'Adverb'),
('v_n4_auto_254', 'N4', '必ず', 'かならず', 'kanarazu', 'pasti / harus / selalu', 'Adverb'),
('v_n4_auto_255', 'N4', 'ぜひ', 'ぜひ', 'zehi', 'tentu saja / sangat (ajakan)', 'Adverb'),
('v_n4_auto_256', 'N4', 'たぶん', 'たぶん', 'tabun', 'mungkin / barangkali', 'Adverb'),
('v_n4_auto_257', 'N4', 'しばらく', 'しばらく', 'shibaraku', 'sementara waktu / beberapa lama', 'Adverb'),
('v_n4_auto_258', 'N4', 'はっきり', 'はっきり', 'hakkiri', 'dengan jelas', 'Adverb'),
('v_n4_auto_259', 'N4', 'のんびり', 'のんびり', 'nonbiri', 'secara santai', 'Adverb'),
('v_n4_auto_260', 'N4', 'そろそろ', 'そろそろ', 'sorosoro', 'perlahan-lahan / sebentar lagi', 'Adverb'),
('v_n4_auto_261', 'N4', 'どんどん', 'どんどん', 'dondon', 'dengan cepat / berturut-turut', 'Adverb'),
('v_n4_auto_262', 'N4', 'お疲れ様でした', 'おつかれさまでした', 'otsukaresama deshita', 'terima kasih atas kerja kerasnya', 'Expression'),
('v_n4_auto_263', 'N4', 'お先に失礼します', 'おさきにしつれいします', 'osaki ni shitsurei shimasu', 'permisi pulang duluan', 'Expression'),
('v_n4_auto_264', 'N4', 'おかげさまで', 'おかげさまで', 'okagesama de', 'berkat doa Anda (Alhamdulillah)', 'Expression'),
('v_n4_auto_265', 'N4', '実は', 'じつは', 'jitsu wa', 'sebenarnya', 'Expression'),
('v_n4_auto_266', 'N4', 'もちろん', 'もちろん', 'mochiron', 'tentu saja', 'Expression'),
('v_n4_auto_267', 'N4', 'いかがですか', 'いかがですか', 'ikaga desu ka', 'bagaimana?', 'Expression'),
('v_n4_auto_268', 'N4', 'あまり', 'あまり', 'amari', 'tidak begitu / tidak terlalu', 'Adverb'),
('v_n4_auto_269', 'N4', 'いかが', 'いかが', 'ikaga', 'bagaimana (sopan)', 'Adverb'),
('v_n4_auto_270', 'N4', 'いくら', 'いくら', 'ikura', 'berapa pun / meskipun berapa', 'Adverb'),
('v_n4_auto_271', 'N4', '一生懸命', 'いっしょうけんめい', 'isshoukenmei', 'dengan sungguh-sungguh', 'Adverb'),
('v_n4_auto_272', 'N4', '決して', 'けっして', 'kesshite', 'sekali-kali tidak / tidak pernah', 'Adverb'),
('v_n4_auto_273', 'N4', 'この間', 'このあいだ', 'kono aida', 'tempo hari / baru-baru ini', 'Adverb'),
('v_n4_auto_274', 'N4', 'これから', 'これから', 'kore kara', 'mulai sekarang / dari sekarang', 'Adverb'),
('v_n4_auto_275', 'N4', 'さっき', 'さっき', 'sakki', 'tadi / baru saja', 'Adverb'),
('v_n4_auto_276', 'N4', 'すっかり', 'すっかり', 'sukkari', 'sepenuhnya / seluruhnya', 'Adverb'),
('v_n4_auto_277', 'N4', 'ずっと', 'ずっと', 'zutto', 'jauh lebih / terus-menerus', 'Adverb'),
('v_n4_auto_278', 'N4', '全然', 'ぜんぜん', 'zenzen', 'sama sekali tidak', 'Adverb'),
('v_n4_auto_279', 'N4', '大抵', 'たいてい', 'taitei', 'biasanya / umumnya', 'Adverb'),
('v_n4_auto_280', 'N4', 'だいぶ', 'だいぶ', 'daibu', 'lumayan / sebagian besar', 'Adverb'),
('v_n4_auto_281', 'N4', 'ちっとも', 'ちっとも', 'chittomo', 'sedikit pun tidak', 'Adverb'),
('v_n4_auto_282', 'N4', 'ちょうど', 'ちょうど', 'choudo', 'pas / tepat / baru saja', 'Adverb'),
('v_n4_auto_283', 'N4', 'ついに', 'ついに', 'tsui ni', 'akhirnya (setelah proses panjang)', 'Adverb'),
('v_n4_auto_284', 'N4', '特に', 'とくに', 'toku ni', 'khususnya / terutama', 'Adverb'),
('v_n4_auto_285', 'N4', 'なるべく', 'なるべく', 'narebeku', 'sebisa mungkin', 'Adverb'),
('v_n4_auto_286', 'N4', 'もし', 'もし', 'moshi', 'jika / seandainya', 'Adverb'),
('v_n4_auto_287', 'N4', 'やはり', 'やはり', 'yahari', 'tetap saja / seperti dugaan', 'Adverb'),
('v_n4_auto_288', 'N4', 'おかしいな', 'おかしいな', 'okashii na', 'aneh ya...', 'Expression'),
('v_n4_auto_289', 'N4', 'しばらくでした', 'しばらくでした', 'shibaraku deshita', 'sudah lama tidak jumpa', 'Expression'),
('v_n4_auto_290', 'N4', '失礼します', 'しつれいします', 'shitsurei shimasu', 'permisi / mohon maaf', 'Expression'),
('v_n4_auto_291', 'N4', 'どうぞお元気で', 'どうぞおげんきで', 'douzo ogenki de', 'semoga sehat selalu', 'Expression'),
('v_n4_auto_292', 'N4', 'どうも', 'どうも', 'doumo', 'terima kasih / salam', 'Expression'),
('v_n4_auto_293', 'N4', 'いってらっしゃい', 'いてらっしゃい', 'itte rasshai', 'selamat jalan / hati-hati di jalan', 'Expression'),
('v_n4_auto_294', 'N4', 'いってきます', 'いってきます', 'itte kimasu', 'saya berangkat dulu', 'Expression'),
('v_n4_auto_295', 'N4', 'ただいま', 'ただいま', 'tadaima', 'saya pulang / baru kembali', 'Expression'),
('v_n4_auto_296', 'N4', 'おかえりなさい', 'おかえりなさい', 'okaeri nasai', 'selamat datang kembali di rumah', 'Expression'),
('v_n4_auto_297', 'N4', 'おめでとうございます', 'おめでとうございます', 'omedetou gozaimasu', 'selamat!', 'Expression'),
('v_n4_auto_298', 'N4', '医者', 'いしゃ', 'isha', 'dokter', 'Noun'),
('v_n4_auto_299', 'N4', '準備', 'じゅんび', 'junbi', 'persiapan', 'Noun'),
('v_n4_auto_300', 'N4', '計画', 'けいかく', 'keikaku', 'rencana / perencanaan', 'Noun'),
('v_n4_auto_301', 'N4', '説明', 'せつめい', 'setsumei', 'penjelasan / keterangan', 'Noun'),
('v_n4_auto_302', 'N4', '空港', 'くうこう', 'kuukou', 'bandara', 'Noun'),
('v_n4_auto_303', 'N4', '予約', 'よやく', 'yoyaku', 'reservasi / pemesanan', 'Noun'),
('v_n4_auto_304', 'N4', '外国語', 'がいこくご', 'gaikokugo', 'bahasa asing', 'Noun'),
('v_n4_auto_305', 'N4', '結果', 'けっか', 'kekka', 'hasil', 'Noun'),
('v_n4_auto_306', 'N4', '社会', 'しゃかい', 'shakai', 'masyarakat / sosial', 'Noun'),
('v_n4_auto_307', 'N4', '環境', 'かんきょう', 'kankyou', 'lingkungan', 'Noun'),
('v_n4_auto_308', 'N4', '気持ち', 'きもち', 'kimochi', 'perasaan / suasana hati', 'Noun'),
('v_n4_auto_309', 'N4', '丁寧', 'ていねい', 'teinei', 'sopan santun', 'Noun'),
('v_n4_auto_310', 'N4', '複雑', 'ふくざつ', 'fukuzatsu', 'kerumitan', 'Noun'),
('v_n4_auto_311', 'N4', '遅刻', 'ちこく', 'chikoku', 'keterlambatan', 'Noun'),
('v_n4_auto_312', 'N4', '運転', 'うんてん', 'unten', 'pengemudian / menyetir', 'Noun'),
('v_n4_auto_313', 'N4', '朝食', 'ちょうしょく', 'choushoku', 'sarapan pagi', 'Noun'),
('v_n4_auto_314', 'N4', '材料', 'ざいりょう', 'zairyou', 'bahan baku / material', 'Noun'),
('v_n4_auto_315', 'N4', '生活費', 'せいかつひ', 'seikatsuhi', 'biaya hidup', 'Noun'),
('v_n4_auto_316', 'N4', '習慣', 'しゅうかん', 'shuukan', 'kebiasaan / adat', 'Noun'),
('v_n4_auto_317', 'N4', '祖父', 'そふ', 'sofu', 'kakek (pihak sendiri)', 'Noun'),
('v_n4_auto_318', 'N4', '兄弟', 'きょうだい', 'kyoudai', 'saudara kandung / kakak adik', 'Noun'),
('v_n4_auto_319', 'N4', '普及', 'ふきゅう', 'fukyuu', 'penyebaran / popularitas umum', 'Noun'),
('v_n4_auto_320', 'N4', '保存', 'ほぞん', 'hozon', 'penyimpanan / pengawetan', 'Noun'),
('v_n4_auto_321', 'N4', '景色', 'けしき', 'keshiki', 'pemandangan', 'Noun'),
('v_n4_auto_322', 'N4', '住民', 'じゅうみん', 'juumin', 'penduduk / warga lokal', 'Noun'),
('v_n4_auto_323', 'N4', '意見', 'いけん', 'iken', 'pendapat / opini', 'Noun'),
('v_n4_auto_324', 'N4', '簡潔', 'かんけつ', 'kanketsu', 'kepadatan / kesingkatan', 'Noun'),
('v_n4_auto_325', 'N4', '出発', 'しゅっぱつ', 'shuppatsu', 'keberangkatan', 'Noun'),
('v_n4_auto_326', 'N4', '心配', 'しんぱい', 'shinpai', 'kekhawatiran', 'Noun'),
('v_n4_auto_327', 'N4', '技術', 'ぎじゅつ', 'gijutsu', 'teknologi / teknik', 'Noun'),
('v_n4_auto_328', 'N4', '政治', 'せいじ', 'seiji', 'politik', 'Noun'),
('v_n4_auto_329', 'N4', '経済', 'けいざい', 'keizai', 'ekonomi', 'Noun'),
('v_n4_auto_330', 'N4', '法律', 'ほうりつ', 'houritsu', 'hukum / undang-undang', 'Noun'),
('v_n4_auto_331', 'N4', '恋人', 'こいびと', 'koibito', 'pacar / kekasih', 'Noun'),
('v_n4_auto_332', 'N4', '夫婦', 'ふうふ', 'fuufu', 'suami istri', 'Noun'),
('v_n4_auto_333', 'N4', '親戚', 'しんせき', 'shinseki', 'kerabat / saudara sepupu/ipar dll', 'Noun'),
('v_n4_auto_334', 'N4', '社長', 'しゃちょう', 'shachou', 'direktur utama / bos', 'Noun'),
('v_n4_auto_335', 'N4', '公務員', 'こうむいん', 'koumuin', 'pegawai negeri sipil (PNS)', 'Noun'),
('v_n4_auto_336', 'N4', '看護師', 'かんごし', 'kangoshi', 'perawat', 'Noun'),
('v_n4_auto_337', 'N4', '小説', 'しょうせつ', 'shousetsu', 'novel', 'Noun'),
('v_n4_auto_338', 'N4', '天気予報', 'てんきよほう', 'tenkiyohou', 'prakiraan cuaca', 'Noun'),
('v_n4_auto_339', 'N4', '火事', 'かじ', 'kaji', 'kebakaran', 'Noun'),
('v_n4_auto_340', 'N4', '事故', 'じこ', 'jiko', 'kecelakaan', 'Noun'),
('v_n4_auto_341', 'N4', '予定', 'よてい', 'yotei', 'jadwal / rencana acara', 'Noun'),
('v_n4_auto_342', 'N4', '相手', 'あいて', 'aite', 'lawan bicara / mitra / partner', 'Noun'),
('v_n4_auto_343', 'N4', '留学生', 'りゅうがくせい', 'ryuugakusei', 'mahasiswa asing / siswa internasional', 'Noun'),
('v_n4_auto_344', 'N4', '実験', 'じっけん', 'jikken', 'eksperimen / uji coba', 'Noun'),
('v_n4_auto_345', 'N4', '泥棒', 'どろぼう', 'dorobou', 'pencuri / maling', 'Noun'),
('v_n4_auto_346', 'N4', '秋', 'あき', 'aki', 'musim gugur', 'Noun'),
('v_n4_auto_347', 'N4', '味', 'あじ', 'aji', 'rasa', 'Noun'),
('v_n4_auto_348', 'N4', '遊び', 'あそび', 'asobi', 'permainan / liburan / hiburan', 'Noun'),
('v_n4_auto_349', 'N4', '頭', 'あたま', 'atama', 'kepala', 'Noun'),
('v_n4_auto_350', 'N4', '姉', 'あね', 'ane', 'kakak perempuan (sendiri)', 'Noun'),
('v_n4_auto_351', 'N4', '兄', 'あに', 'ani', 'kakak laki-laki (sendiri)', 'Noun'),
('v_n4_auto_352', 'N4', 'アパート', 'アパート', 'apaato', 'apartemen', 'Noun'),
('v_n4_auto_353', 'N4', '従姉妹', 'いとこ', 'itoko', 'saudara sepupu', 'Noun'),
('v_n4_auto_354', 'N4', '意味', 'いみ', 'imi', 'arti / makna', 'Noun'),
('v_n4_auto_355', 'N4', '妹', 'いもうと', 'imouto', 'adik perempuan (sendiri)', 'Noun'),
('v_n4_auto_356', 'N4', '入口', 'いりぐち', 'iriguchi', 'pintu masuk', 'Noun'),
('v_n4_auto_357', 'N4', 'おもちゃ', 'おもちゃ', 'omocha', 'mainan', 'Noun'),
('v_n4_auto_358', 'N4', '思い出', 'おもいで', 'omoide', 'kenangan', 'Noun'),
('v_n4_auto_359', 'N4', '音楽', 'おんがく', 'ongaku', 'musik', 'Noun'),
('v_n4_auto_360', 'N4', '会話', 'かいわ', 'kaiwa', 'percakapan / obrolan', 'Noun'),
('v_n4_auto_361', 'N4', '帰り', 'かえり', 'kaeri', 'kepulangan / jalan pulang', 'Noun'),
('v_n4_auto_362', 'N4', '鏡', 'かがみ', 'kagami', 'cermin', 'Noun'),
('v_n4_auto_363', 'N4', '科学', 'かがく', 'kagaku', 'sains / ilmu pengetahuan', 'Noun'),
('v_n4_auto_364', 'N4', '家事', 'かじ', 'kaji', 'pekerjaan rumah tangga', 'Noun'),
('v_n4_auto_365', 'N4', '形', 'かたち', 'katachi', 'bentuk', 'Noun'),
('v_n4_auto_366', 'N4', '金', 'かね', 'kane', 'uang / logam mulia / bel', 'Noun'),
('v_n4_auto_367', 'N4', '壁', 'かべ', 'kabe', 'dinding / tembok', 'Noun'),
('v_n4_auto_368', 'N4', '髪', 'かみ', 'kami', 'rambut', 'Noun'),
('v_n4_auto_369', 'N4', '神様', 'かみさま', 'kamisama', 'Tuhan / Dewa', 'Noun'),
('v_n4_auto_370', 'N4', '体', 'からだ', 'karada', 'tubuh / badan', 'Noun'),
('v_n4_auto_371', 'N4', 'カレンダー', 'カレンダー', 'karendaar', 'kalender', 'Noun'),
('v_n4_auto_372', 'N4', '漢字', 'かんじ', 'kanji', 'huruf Kanji', 'Noun'),
('v_n4_auto_373', 'N4', '季節', 'きせつ', 'kisetsu', 'musim', 'Noun'),
('v_n4_auto_374', 'N4', '規則', 'きそく', 'kisoku', 'peraturan / aturan', 'Noun'),
('v_n4_auto_375', 'N4', '切手', 'きって', 'kitte', 'perangko', 'Noun'),
('v_n4_auto_376', 'N4', '切符', 'きっぷ', 'kippu', 'tiket (kereta/bis)', 'Noun'),
('v_n4_auto_377', 'N4', '絹', 'きぬ', 'kinu', 'sutra', 'Noun'),
('v_n4_auto_378', 'N4', '気分', 'きぶん', 'kibun', 'suasana hati / kondisi badan', 'Noun'),
('v_n4_auto_379', 'N4', '着物', 'きもの', 'kimono', 'Kimono', 'Noun'),
('v_n4_auto_380', 'N4', '客', 'きゃく', 'kyaku', 'tamu / pelanggan / konsumen', 'Noun'),
('v_n4_auto_381', 'N4', '急行', 'きゅうこう', 'kyuukou', 'kereta ekspres / cepat', 'Noun'),
('v_n4_auto_382', 'N4', '興味', 'きょうみ', 'kyoumi', 'minat / ketertarikan', 'Noun'),
('v_n4_auto_383', 'N4', '距離', 'きょうり', 'kyori', 'jarak', 'Noun'),
('v_n4_auto_384', 'N4', '霧', 'きり', 'kiri', 'kabut', 'Noun'),
('v_n4_auto_385', 'N4', '近所', 'きんじょ', 'kinjo', 'tetangga / lingkungan sekitar', 'Noun'),
('v_n4_auto_386', 'N4', '牛肉', 'ぎゅうにく', 'gyuuniku', 'daging sapi', 'Noun'),
('v_n4_auto_387', 'N4', '牛乳', 'ぎゅうにゅう', 'gyuunyuu', 'susu sapi', 'Noun'),
('v_n4_auto_388', 'N4', '行事', 'ぎょうじ', 'gyouji', 'acara / agenda kegiatan / festival', 'Noun'),
('v_n4_auto_389', 'N4', '銀行', 'ぎんこう', 'ginkou', 'bank', 'Noun'),
('v_n4_auto_390', 'N4', '草', 'くさ', 'kusa', 'rumput', 'Noun'),
('v_n4_auto_391', 'N4', '薬', 'くすり', 'kusuri', 'obat', 'Noun'),
('v_n4_auto_392', 'N4', '果物', 'くだもの', 'kudamono', 'buah-buahan', 'Noun'),
('v_n4_auto_393', 'N4', '口', 'くち', 'kuchi', 'mulut / pintu masuk / lubang', 'Noun'),
('v_n4_auto_394', 'N4', '靴', 'くつ', 'kutsu', 'sepatu', 'Noun'),
('v_n4_auto_395', 'N4', '靴下', 'くつした', 'kutsushita', 'kaos kaki', 'Noun'),
('v_n4_auto_396', 'N4', '国', 'くに', 'kuni', 'negara / kampung halaman', 'Noun'),
('v_n4_auto_397', 'N4', '首', 'くび', 'kubi', 'leher', 'Noun'),
('v_n4_auto_398', 'N4', '雲', 'くも', 'kumo', 'awan', 'Noun'),
('v_n4_auto_399', 'N4', '暗闇', 'くらやみ', 'kurayami', 'kegelapan', 'Noun'),
('v_n4_auto_400', 'N4', '会議', 'かいぎ', 'kaigi', 'rapat', 'Noun'),
('v_n4_auto_401', 'N4', '工場', 'こうじょう', 'koujou', 'pabrik', 'Noun'),
('v_n4_auto_402', 'N4', '事務所', 'じむしょ', 'jimusho', 'kantor', 'Noun'),
('v_n4_auto_403', 'N4', '受付', 'うけつけ', 'uketsuke', 'resepsionis', 'Noun'),
('v_n4_auto_404', 'N4', '製品', 'せいひん', 'seihin', 'produk / barang buatan', 'Noun'),
('v_n4_auto_405', 'N4', '機械', 'きかい', 'kikai', 'mesin', 'Noun'),
('v_n4_auto_406', 'N4', '道具', 'どうぐ', 'dougu', 'peralatan', 'Noun'),
('v_n4_auto_407', 'N4', '趣味', 'しゅみ', 'shumi', 'hobi', 'Noun'),
('v_n4_auto_408', 'N4', '特徴', 'tokuchou', 'tokuchou', 'ciri khas / keunikan', 'Noun'),
('v_n4_auto_409', 'N4', '理由', 'りゆう', 'riyuu', 'alasan', 'Noun'),
('v_n4_auto_410', 'N4', '目的', 'もくてき', 'mokuteki', 'tujuan', 'Noun'),
('v_n4_auto_411', 'N4', '原因', 'げんいん', 'gen''in', 'penyebab', 'Noun'),
('v_n4_auto_412', 'N4', '経験', 'けいけん', 'keiken', 'pengalaman', 'Noun'),
('v_n4_auto_413', 'N4', '親友', 'しんゆう', 'shinyuu', 'sahabat karib', 'Noun'),
('v_n4_auto_414', 'N4', '両親', 'りょうしん', 'ryoushin', 'kedua orang tua', 'Noun'),
('v_n4_auto_415', 'N4', '大人', 'おとな', 'otona', 'orang dewasa', 'Noun'),
('v_n4_auto_416', 'N4', '赤ちゃん', 'あかちゃん', 'akachan', 'bayi', 'Noun'),
('v_n4_auto_417', 'N4', '男性', 'だんせい', 'dansei', 'laki-laki', 'Noun'),
('v_n4_auto_418', 'N4', '女性', 'じょせい', 'josei', 'perempuan', 'Noun'),
('v_n4_auto_419', 'N4', '歌手', 'かしゅ', 'kashu', 'penyanyi', 'Noun'),
('v_n4_auto_420', 'N4', '新聞', 'しんぶん', 'shinbun', 'koran', 'Noun'),
('v_n4_auto_421', 'N4', '広告', 'こうこく', 'koukoku', 'iklan', 'Noun'),
('v_n4_auto_422', 'N4', 'ニュース', 'ニュース', 'nyuusu', 'berita', 'Noun'),
('v_n4_auto_423', 'N4', '地震', 'じしん', 'jishin', 'gempa bumi', 'Noun'),
('v_n4_auto_424', 'N4', '台風', 'たいふう', 'taifuu', 'angin topan', 'Noun'),
('v_n4_auto_425', 'N4', '事件', 'じけん', 'jiken', 'kasus / insiden', 'Noun'),
('v_n4_auto_426', 'N4', '戦争', 'せんそう', 'sensou', 'perang', 'Noun'),
('v_n4_auto_427', 'N4', '平和', 'へいわ', 'heiwa', 'perdamaian', 'Noun'),
('v_n4_auto_428', 'N4', '自由', 'じゆう', 'jiyuu', 'kebebasan', 'Noun'),
('v_n4_auto_429', 'N4', '責任', 'せきにん', 'sekinin', 'tanggung jawab', 'Noun'),
('v_n4_auto_430', 'N4', '協力', 'きょうりょく', 'kyouryoku', 'kerja sama', 'Noun'),
('v_n4_auto_431', 'N4', '成功', 'せいこう', 'seikou', 'kesuksesan / keberhasilan', 'Noun'),
('v_n4_auto_432', 'N4', 'グループ', 'グループ', 'guruupu', 'kelompok / grup', 'Noun'),
('v_n4_auto_433', 'N4', 'コピー', 'コピー', 'kopii', 'fotokopi / salinan', 'Noun'),
('v_n4_auto_434', 'N4', 'ゴミ', 'ゴミ', 'gomi', 'sampah', 'Noun'),
('v_n4_auto_435', 'N4', '米', 'こめ', 'kome', 'beras / padi', 'Noun'),
('v_n4_auto_436', 'N4', '坂', 'さか', 'saka', 'lereng / jalan menanjak', 'Noun'),
('v_n4_auto_437', 'N4', '茶道', 'さどう', 'sadou', 'upacara minum teh', 'Noun'),
('v_n4_auto_438', 'N4', '砂糖', 'さとう', 'satou', 'gula', 'Noun'),
('v_n4_auto_439', 'N4', '塩', 'しお', 'shio', 'garam', 'Noun'),
('v_n4_auto_440', 'N4', '市役所', 'しやくしょ', 'shiyakusho', 'balai kota / kantor kelurahan', 'Noun'),
('v_n4_auto_441', 'N4', '社交', 'しゃこう', 'shakou', 'hubungan sosial / pertemanan', 'Noun'),
('v_n4_auto_442', 'N4', 'シャワー', 'シャワー', 'shawaa', 'pancuran air / shower', 'Noun'),
('v_n4_auto_443', 'N4', '小説', 'しょうせつ', 'shousetsu', 'novel', 'Noun'),
('v_n4_auto_444', 'N4', '将来', 'しょうらい', 'shourai', 'masa depan', 'Noun'),
('v_n4_auto_445', 'N4', '食料', 'しょくりょう', 'shokuryou', 'persediaan makanan / pangan', 'Noun'),
('v_n4_auto_446', 'N4', '新聞', 'しんぶん', '新聞', 'koran / surat kabar', 'Noun'),
('v_n4_auto_447', 'N4', '寿司', 'すし', 'sushi', 'Sushi', 'Noun'),
('v_n4_auto_448', 'N4', '生活', 'せいかつ', 'seikatsu', 'kehidupan / keseharian', 'Noun'),
('v_n4_auto_449', 'N4', '生産', 'せいさん', 'seisan', 'produksi', 'Noun'),
('v_n4_auto_450', 'N4', '専門', 'せんもん', 'senmon', 'jurusan kuliah / keahlian khusus', 'Noun'),
('v_n4_auto_451', 'N4', '卒業', 'そつぎょう', 'sotsugyou', 'kelulusan', 'Noun'),
('v_n4_auto_452', 'N4', '祖母', 'そぼ', 'sobo', 'nenek (pihak sendiri)', 'Noun'),
('v_n4_auto_453', 'N4', '体育', 'たいいく', 'taiiku', 'olahraga / pendidikan jasmani', 'Noun'),
('v_n4_auto_454', 'N4', '台所', 'だいどころ', 'daidokoro', 'dapur', 'Noun'),
('v_n4_auto_455', 'N4', 'タクシー', 'タクシー', 'takushii', 'taksi', 'Noun'),
('v_n4_auto_456', 'N4', '単語', 'たんご', 'tango', 'kosa kata', 'Noun'),
('v_n4_auto_457', 'N4', '地下鉄', 'ちかてつ', 'chikatetsu', 'kereta bawah tanah / MRT', 'Noun'),
('v_n4_auto_458', 'N4', '中学生', 'ちゅうがくせい', 'chuugakusei', 'siswa SMP', 'Noun'),
('v_n4_auto_459', 'N4', '地図', 'ちず', 'chizu', 'peta', 'Noun'),
('v_n4_auto_460', 'N4', '通勤', 'つうきん', 'tsuukin', 'pulang pergi kerja / komuting', 'Noun'),
('v_n4_auto_461', 'N4', '冷たさ', 'つめたさ', 'tsumetasa', 'kedinginan / kesejukan', 'Noun'),
('v_n4_auto_462', 'N4', '手袋', 'てぶくろ', 'tebukuro', 'sarung tangan', 'Noun'),
('v_n4_auto_463', 'N4', 'てんぷら', 'てんぷら', 'tenpura', 'Tempura', 'Noun'),
('v_n4_auto_464', 'N4', '展示', 'てんじ', 'tenji', 'pameran / pajangan', 'Noun'),
('v_n4_auto_465', 'N4', '動物', 'どうぶつ', 'doubutsu', 'hewan / binatang', 'Noun'),
('v_n4_auto_466', 'N4', '図書館', 'としょかん', 'toshokan', 'perpustakaan', 'Noun'),
('v_n4_auto_467', 'N4', '床屋', 'とこや', 'tokoya', 'barbershop / pangkas rambut', 'Noun'),
('v_n4_auto_468', 'N4', '友達', 'ともだち', 'tomodachi', 'teman / sahabat', 'Noun'),
('v_n4_auto_469', 'N4', '泥', 'どろ', 'doro', 'lumpur', 'Noun'),
('v_n4_auto_470', 'N4', '泥棒', 'どろぼう', 'dorobou', 'pencuri / perampok', 'Noun'),
('v_n4_auto_471', 'N4', '肉', 'にく', 'niku', 'daging', 'Noun'),
('v_n4_auto_472', 'N4', '人形', 'にんぎょう', 'ningyou', 'boneka', 'Noun'),
('v_n4_auto_473', 'N4', '熱', 'ねつ', 'netsu', 'panas / demam', 'Noun'),
('v_n4_auto_474', 'N4', '年賀状', 'ねんが状', 'nengajou', 'kartu ucapan tahun baru', 'Noun'),
('v_n4_auto_475', 'N4', '野原', 'のはら', 'nohara', 'padang rumput / lapangan hijau', 'Noun'),
('v_n4_auto_476', 'N4', '飲み物', 'のみもの', 'nomimono', 'minuman', 'Noun'),
('v_n4_auto_477', 'N4', '漫画家', 'まんがか', 'mangaka', 'komikus / pembuat komik', 'Noun'),
('v_n4_auto_478', 'N4', '作家', 'さっか', 'sakka', 'penulis / pengarang', 'Noun'),
('v_n4_auto_479', 'N4', '画家', 'がか', 'gaka', 'pelukis', 'Noun'),
('v_n4_auto_480', 'N4', '科学者', 'かがくしゃ', 'kagakusha', 'ilmuwan / peneliti sains', 'Noun'),
('v_n4_auto_481', 'N4', '政治家', 'せいじか', 'seijika', 'politikus', 'Noun'),
('v_n4_auto_482', 'N4', '弁護士', 'べんごし', 'bengoshi', 'pengacara', 'Noun'),
('v_n4_auto_483', 'N4', '警察官', 'けいさつかん', 'keisatsukan', 'petugas polisi', 'Noun'),
('v_n4_auto_484', 'N4', '消防士', 'しょうぼうし', 'shouboushi', 'petugas pemadam kebakaran', 'Noun'),
('v_n4_auto_485', 'N4', '研究者', 'けんきゅうしゃ', 'kenkyuusha', 'peneliti', 'Noun'),
('v_n4_auto_486', 'N4', '翻訳者', 'ほんやくしゃ', 'honyakusha', 'penerjemah (dokumen/tulisan)', 'Noun'),
('v_n4_auto_487', 'N4', 'お祖父さん', 'おじいさん', 'ojiisan', 'kakek (orang lain)', 'Noun'),
('v_n4_auto_488', 'N4', 'お祖母さん', 'おばあさん', 'obaasan', 'nenek (orang lain)', 'Noun'),
('v_n4_auto_489', 'N4', 'ご両親', 'ごりょうしん', 'goryoushin', 'orang tua (orang lain)', 'Noun'),
('v_n4_auto_490', 'N4', 'お子さん', 'おこさん', 'okosan', 'anak (orang lain)', 'Noun'),
('v_n4_auto_491', 'N4', 'ご主人', 'ごしゅじん', 'goshujin', 'suami (orang lain)', 'Noun'),
('v_n4_auto_492', 'N4', '奥さん', 'おくさん', 'okusan', 'istri (orang lain)', 'Noun'),
('v_n4_auto_493', 'N4', '北東', 'ほくとう', 'hokutou', 'timur laut', 'Noun'),
('v_n4_auto_494', 'N4', '北西', 'ほくせい', 'hokutou', 'barat laut', 'Noun'),
('v_n4_auto_495', 'N4', '南東', 'なんとう', 'nantou', 'tenggara', 'Noun'),
('v_n4_auto_496', 'N4', '南西', 'nansei', 'nansei', 'barat daya', 'Noun'),
('v_n4_auto_497', 'N4', '中央', 'ちゅうおう', 'chuuou', 'pusat / tengah', 'Noun'),
('v_n4_auto_498', 'N4', '周囲', 'しゅうい', 'shuui', 'sekeliling / lingkaran', 'Noun'),
('v_n4_auto_499', 'N4', '一週間', 'いっしゅうかん', 'isshuukan', 'satu minggu (durasi)', 'Noun'),
('v_n4_auto_500', 'N4', '二週間', 'にしゅうかん', 'nishuukan', 'dua minggu (durasi)', 'Noun'),
('v_n4_auto_501', 'N4', '一ヶ月', 'いっかげつ', 'ikkatsu', 'satu bulan (durasi)', 'Noun'),
('v_n4_auto_502', 'N4', '三ヶ月', 'さんかげつ', 'sankatsu', 'tiga bulan (durasi)', 'Noun'),
('v_n4_auto_503', 'N4', '半年', 'はんねん', 'hannen', 'setengah tahun (durasi)', 'Noun'),
('v_n4_auto_504', 'N4', '年間', 'ねんかん', 'nenkan', 'selama satu tahun (durasi)', 'Noun'),
('v_n4_auto_505', 'N4', '中学校', 'ちゅうがっこう', 'chuugakkou', 'Sekolah Menengah Pertama (SMP)', 'Noun'),
('v_n4_auto_506', 'N4', '小学校', 'しょうがっこう', 'shougakkou', 'Sekolah Dasar (SD)', 'Noun'),
('v_n4_auto_507', 'N4', '幼稚園', 'ようちえん', 'youchien', 'Taman Kanak-kanak (TK)', 'Noun'),
('v_n4_auto_508', 'N4', '大学院', 'だいがくいん', 'daigakuin', 'Pascasarjana / S2 / S3', 'Noun'),
('v_n4_auto_509', 'N4', '教科書', 'きょうかしょ', 'kyoukasho', 'buku pelajaran / buku paket', 'Noun'),
('v_n4_auto_510', 'N4', '締め切り', 'しめきり', 'shimekiri', 'batas waktu / deadline', 'Noun'),
('v_n4_auto_511', 'N4', '洪水', 'こうずい', 'kouzui', 'banjir', 'Noun'),
('v_n4_auto_512', 'N4', '事件', 'じけん', 'jiken', 'kasus kriminal / insiden', 'Noun'),
('v_n4_auto_513', 'N4', '泥棒', 'どろぼう', 'dorobou', 'pencuri / perampok', 'Noun'),
('v_n4_auto_514', 'N4', '裁判', 'さいばん', 'saiban', 'pengadilan / persidangan', 'Noun'),
('v_n4_auto_515', 'N4', '歴史', 'れきし', 'rekishi', 'sejarah', 'Noun'),
('v_n4_auto_516', 'N4', '1日', 'ついたち', 'tsuitachi', 'tanggal 1', 'Noun'),
('v_n4_auto_517', 'N4', '2日', 'ふつか', 'futsuka', 'tanggal 2', 'Noun'),
('v_n4_auto_518', 'N4', '3日', 'みっか', 'mikka', 'tanggal 3', 'Noun'),
('v_n4_auto_519', 'N4', '4日', 'よっか', 'yokka', 'tanggal 4', 'Noun'),
('v_n4_auto_520', 'N4', '5日', 'いつか', 'itsuka', 'tanggal 5', 'Noun'),
('v_n4_auto_521', 'N4', '6日', 'むいか', 'muika', 'tanggal 6', 'Noun'),
('v_n4_auto_522', 'N4', '7日', 'なのか', 'nanoka', 'tanggal 7', 'Noun'),
('v_n4_auto_523', 'N4', '8日', 'ようか', 'youka', 'tanggal 8', 'Noun'),
('v_n4_auto_524', 'N4', '9日', 'ここのか', 'kokonoka', 'tanggal 9', 'Noun'),
('v_n4_auto_525', 'N4', '10日', 'とおか', 'tooka', 'tanggal 10', 'Noun'),
('v_n4_auto_526', 'N4', '11日', 'じゅういちにち', 'juuichinichi', 'tanggal 11', 'Noun'),
('v_n4_auto_527', 'N4', '12日', 'じゅうににち', 'juuninichi', 'tanggal 12', 'Noun'),
('v_n4_auto_528', 'N4', '13日', 'じゅうさんにち', 'juusannichi', 'tanggal 13', 'Noun'),
('v_n4_auto_529', 'N4', '14日', 'じゅうよっか', 'juuyokka', 'tanggal 14', 'Noun'),
('v_n4_auto_530', 'N4', '15日', 'じゅうごにち', 'juugonichi', 'tanggal 15', 'Noun'),
('v_n4_auto_531', 'N4', '16日', 'じゅうろくにち', 'juurokunichi', 'tanggal 16', 'Noun'),
('v_n4_auto_532', 'N4', '17日', 'じゅうしちにち', 'juushichinichi', 'tanggal 17', 'Noun'),
('v_n4_auto_533', 'N4', '18日', 'じゅうはちにち', 'juuhachinichi', 'tanggal 18', 'Noun'),
('v_n4_auto_534', 'N4', '19日', 'じゅうくにち', 'juukunichi', 'tanggal 19', 'Noun'),
('v_n4_auto_535', 'N4', '20日', 'はつか', 'hatsuka', 'tanggal 20', 'Noun'),
('v_n4_auto_536', 'N4', '21日', 'にじゅういちにち', 'nijuuichinichi', 'tanggal 21', 'Noun'),
('v_n4_auto_537', 'N4', '22日', 'にじゅうににち', 'nijuuninichi', 'tanggal 22', 'Noun'),
('v_n4_auto_538', 'N4', '23日', 'にじゅうさんにち', 'nijuusannichi', 'tanggal 23', 'Noun'),
('v_n4_auto_539', 'N4', '24日', 'にじゅうよっか', 'nijuuyokka', 'tanggal 24', 'Noun'),
('v_n4_auto_540', 'N4', '25日', 'にじゅうごにち', 'nijuugonichi', 'tanggal 25', 'Noun'),
('v_n4_auto_541', 'N4', '26日', 'にじゅうろくにち', 'nijuurokunichi', 'tanggal 26', 'Noun'),
('v_n4_auto_542', 'N4', '27日', 'にじゅうしちにち', 'nijuushichinichi', 'tanggal 27', 'Noun'),
('v_n4_auto_543', 'N4', '28日', 'にじゅうはちにち', 'nijuuhachinichi', 'tanggal 28', 'Noun'),
('v_n4_auto_544', 'N4', '29日', 'にじゅうくにち', 'nijuukunichi', 'tanggal 29', 'Noun'),
('v_n4_auto_545', 'N4', '30日', 'さんじゅうにち', 'sanjuunichi', 'tanggal 30', 'Noun'),
('v_n4_auto_546', 'N4', '31日', 'さんじゅういちにち', 'sanjuuichinichi', 'tanggal 31', 'Noun'),
('v_n4_auto_547', 'N4', '一月', 'いちがつ', 'ichigatsu', 'Januari', 'Noun'),
('v_n4_auto_548', 'N4', '二月', 'にがつ', 'nigatsu', 'Februari', 'Noun'),
('v_n4_auto_549', 'N4', '三月', 'さんがつ', 'sangatsu', 'Maret', 'Noun'),
('v_n4_auto_550', 'N4', '四月', 'しがつ', 'shigatsu', 'April', 'Noun'),
('v_n4_auto_551', 'N4', '五月', 'ごがつ', 'gogatsu', 'Mei', 'Noun'),
('v_n4_auto_552', 'N4', '六月', 'ろくがつ', 'rokugatsu', 'Juni', 'Noun'),
('v_n4_auto_553', 'N4', '七月', 'しちがつ', 'shichigatsu', 'Juli', 'Noun'),
('v_n4_auto_554', 'N4', '八月', 'はちがつ', 'hachigatsu', 'Agustus', 'Noun'),
('v_n4_auto_555', 'N4', '九月', 'くがつ', 'kugatsu', 'September', 'Noun'),
('v_n4_auto_556', 'N4', '十月', 'じゅうがつ', 'juugatsu', 'Oktober', 'Noun'),
('v_n4_auto_557', 'N4', '十一月', 'じゅういちがつ', 'juuichigatsu', 'November', 'Noun'),
('v_n4_auto_558', 'N4', '十二月', 'じゅうにがつ', 'juunigatsu', 'Desember', 'Noun'),
('v_n4_auto_559', 'N4', '〜台', '〜だい', '-dai', 'counter untuk mesin/kendaraan', 'Noun'),
('v_n4_auto_560', 'N4', '〜枚', '〜まい', '-mai', 'counter untuk benda tipis/lembaran', 'Noun'),
('v_n4_auto_561', 'N4', '〜冊', '〜さつ', '-satsu', 'counter untuk buku/majalah', 'Noun'),
('v_n4_auto_562', 'N4', '〜本', '〜ほん', '-hon', 'counter untuk benda panjang/silinder', 'Noun'),
('v_n4_auto_563', 'N4', '〜匹', '〜ひき', '-hiki', 'counter untuk hewan kecil (kucing, anjing dll)', 'Noun'),
('v_n4_auto_564', 'N4', '〜杯', '〜はい', '-hai', 'counter untuk gelas/cangkir', 'Noun'),
('v_n4_auto_565', 'N4', 'お土産', 'おみやげ', 'omiyage', 'oleh-oleh', 'Noun'),
('v_n4_auto_566', 'N4', 'お祭り', 'おまつり', 'omatsuri', 'festival / perayaan', 'Noun'),
('v_n4_auto_567', 'N4', '将来', 'しょうらい', 'shourai', 'masa depan', 'Noun'),
('v_n4_auto_568', 'N4', '専門', 'せんもん', 'senmon', 'keahlian khusus / jurusan', 'Noun'),
('v_n4_auto_569', 'N4', '温泉', '温泉', 'onsen', 'pemandian air panas alam', 'Noun'),
('v_n4_auto_570', 'N4', '住所', 'じゅうしょ', 'juusho', 'alamat rumah', 'Noun'),
('v_n4_auto_571', 'N4', '市役所', 'しやくしょ', 'shiyakusho', 'kantor walikota / kelurahan', 'Noun'),
('v_n4_auto_572', 'N4', '警察', 'けいさつ', 'keisatsu', 'polisi / kepolisian', 'Noun'),
('v_n4_auto_573', 'N4', 'お祝い', 'お祝い', 'oiwai', 'perayaan / ucapan selamat', 'Noun'),
('v_n4_auto_574', 'N4', 'お菓子', 'おかし', 'okashi', 'kue / permen / cemilan', 'Noun'),
('v_n4_auto_575', 'N4', 'お寺', 'おてら', 'otera', 'kuil Buddha', 'Noun'),
('v_n4_auto_576', 'N4', '神社', 'じんじゃ', 'jinja', 'kuil Shinto', 'Noun'),
('v_n4_auto_577', 'N4', '教会', 'きょうかい', 'kyoukai', 'gereja', 'Noun'),
('v_n4_auto_578', 'N4', '空気', 'くうき', 'kuuki', 'udara / atmosfer', 'Noun'),
('v_n4_auto_579', 'N4', '具合', 'ぐあい', 'guai', 'kondisi (kesehatan/mesin)', 'Noun'),
('v_n4_auto_580', 'N4', '効果', 'こうか', 'kouka', 'efek / khasiat', 'Noun'),
('v_n4_auto_581', 'N4', '合計', 'ごうけい', 'goukei', 'jumlah total', 'Noun'),
('v_n4_auto_582', 'N4', '郊外', 'こうがい', 'kougai', 'pinggiran kota', 'Noun'),
('v_n4_auto_583', 'N4', '講義', 'こうぎ', 'kougi', 'kuliah', 'Noun'),
('v_n4_auto_584', 'N4', '工業', 'こうぎょう', 'kougyou', 'industri', 'Noun'),
('v_n4_auto_585', 'N4', '交通', '交通', 'koutsuu', 'lalu lintas / transportasi', 'Noun'),
('v_n4_auto_586', 'N4', '後半', 'こうはん', 'kouhan', 'paruh kedua', 'Noun'),
('v_n4_auto_587', 'N4', '誤解', 'ごかい', 'gokai', 'kesalahpahaman', 'Noun'),
('v_n4_auto_588', 'N4', 'ごちそう', 'ごちそう', 'gochisou', 'hidangan lezat / pesta', 'Noun'),
('v_n4_auto_589', 'N4', '国境', '国境', 'kokkyou', 'perbatasan negara', 'Noun'),
('v_n4_auto_590', 'N4', '言辞', 'ことば', 'kotoba', 'kata / ucapan', 'Noun'),
('v_n4_auto_591', 'N4', 'ゴミ箱', 'ゴミばこ', 'gomibako', 'tempat sampah', 'Noun'),
('v_n4_auto_592', 'N4', '最後', 'さいご', 'saigo', 'terakhir', 'Noun'),
('v_n4_auto_593', 'N4', '最近', 'さいきん', 'saikin', 'akhir-akhir ini / baru-baru ini', 'Noun'),
('v_n4_auto_594', 'N4', '最初', 'さいしょ', 'saisho', 'pertama / awal', 'Noun'),
('v_n4_auto_595', 'N4', '最低', 'さいてい', 'saitei', 'paling rendah / terburuk', 'Noun'),
('v_n4_auto_596', 'N4', '才能', 'さいのう', 'sainou', 'bakat / talenta', 'Noun'),
('v_n4_auto_597', 'N4', '財布', 'さいふ', 'saifu', 'dompet', 'Noun'),
('v_n4_auto_598', 'N4', '坂', 'さか', 'saka', 'tanjakan / lereng', 'Noun'),
('v_n4_auto_599', 'N4', '茶道', 'さどう', 'sadou', 'upacara minum teh', 'Noun'),
('v_n4_auto_600', 'N4', '小説家', 'しょうせつか', 'shousetsuka', 'penulis novel', 'Noun'),
('v_n4_auto_601', 'N4', '社員', 'しゃいん', 'shain', 'karyawan perusahaan', 'Noun'),
('v_n4_auto_602', 'N4', '店員', 'てんいん', 'tenin', 'pegawai toko / pramuniaga', 'Noun'),
('v_n4_auto_603', 'N4', '駅員', 'えきいん', 'ekiin', 'petugas stasiun', 'Noun'),
('v_n4_auto_604', 'N4', '銀行員', 'ぎんこういん', 'ginkouin', 'pegawai bank', 'Noun'),
('v_n4_auto_605', 'N4', '郵便局', 'ゆうびんきょく', 'yuubinkyoku', 'kantor pos', 'Noun'),
('v_n4_auto_606', 'N4', '郵便屋', 'ゆうびんや', 'yuubinya', 'tukang pos', 'Noun'),
('v_n4_auto_607', 'N4', '地下', 'ちか', 'chika', 'bawah tanah', 'Noun'),
('v_n4_auto_608', 'N4', 'お辞儀', 'おじぎ', 'ojigi', 'ojigi (membungkuk memberi hormat)', 'Noun'),
('v_n4_auto_609', 'N4', '敬語', 'けいご', 'keigo', 'Keigo (bahasa Jepang sopan/formal)', 'Noun'),
('v_n4_auto_610', 'N4', 'お湯', 'おゆ', 'oyu', 'air panas', 'Noun'),
('v_n4_auto_611', 'N4', '風', 'かぜ', 'kaze', 'angin', 'Noun'),
('v_n4_auto_612', 'N4', '地震', 'じしん', 'jishin', 'gempa bumi', 'Noun'),
('v_n4_auto_613', 'N4', '趣味', 'しゅみ', 'shumi', 'hobi', 'Noun'),
('v_n4_auto_614', 'N4', '習慣', 'しゅうかん', 'shuukan', 'kebiasaan / adat istiadat', 'Noun'),
('v_n4_auto_615', 'N4', '住所', 'じゅうしょ', 'juusho', 'alamat rumah', 'Noun'),
('v_n4_auto_616', 'N4', '授業', 'じゅぎょう', 'jugyou', 'kelas / jam pelajaran', 'Noun'),
('v_n4_auto_617', 'N4', '宿題', 'しゅくだい', 'shukudai', 'PR (Pekerjaan Rumah)', 'Noun'),
('v_n4_auto_618', 'N4', '紹介', 'しょうかい', 'shoukai', 'perkenalan / rekomendasi', 'Noun'),
('v_n4_auto_619', 'N4', '小学校', 'しょうがっこう', 'shougakkou', 'Sekolah Dasar (SD)', 'Noun'),
('v_n4_auto_620', 'N4', '中学校', 'ちゅうがっこう', 'chuugakkou', 'Sekolah Menengah Pertama (SMP)', 'Noun'),
('v_n4_auto_621', 'N4', '高校', 'こうこう', 'koukou', 'Sekolah Menengah Atas (SMA)', 'Noun'),
('v_n4_auto_622', 'N4', '大学', 'だいがく', 'daigaku', 'universitas / perguruan tinggi', 'Noun'),
('v_n4_auto_623', 'N4', '大学院', 'だいがくいん', 'daigakuin', 'pascasarjana (S2/S3)', 'Noun'),
('v_n4_auto_624', 'N4', '教科書', 'きょうかしょ', 'kyoukasho', 'buku pelajaran', 'Noun'),
('v_n4_auto_625', 'N4', '講義', 'こうぎ', 'kougi', 'kuliah / ceramah akademik', 'Noun'),
('v_n4_auto_626', 'N4', '作文', 'さくぶん', 'sakubun', 'karangan / esai', 'Noun'),
('v_n4_auto_627', 'N4', '試験', 'しけん', 'shiken', 'ujian / tes', 'Noun'),
('v_n4_auto_628', 'N4', '辞書', 'じしょ', 'jisho', 'kamus', 'Noun'),
('v_n4_auto_629', 'N4', '質問', 'しつもん', 'shitsumon', 'pertanyaan', 'Noun'),
('v_n4_auto_630', 'N4', '宿舎', 'しゅくしゃ', 'shukusha', 'asrama / tempat mondok', 'Noun'),
('v_n4_auto_631', 'N4', '宿屋', 'やどや', 'yadoya', 'penginapan tradisional (Ryokan/Inn)', 'Noun'),
('v_n4_auto_632', 'N4', '下着', 'したぎ', 'shitagi', 'pakaian dalam', 'Noun'),
('v_n4_auto_633', 'N4', '上着', 'うわぎ', 'uwagi', 'jaket / jas / baju luar', 'Noun'),
('v_n4_auto_634', 'N4', '和食', 'わしょく', 'washoku', 'kuliner tradisional Jepang', 'Noun'),
('v_n4_auto_635', 'N4', '洋食', 'ようしょく', 'youshoku', 'kuliner ala Barat (di Jepang)', 'Noun'),
('v_n4_auto_636', 'N4', '昼食', 'ちゅうしょく', 'chuushoku', 'makan siang', 'Noun'),
('v_n4_auto_637', 'N4', '夕食', 'ゆうしょく', 'yuushoku', 'makan malam', 'Noun'),
('v_n4_auto_638', 'N4', '間食', 'かんしょく', 'kanshoku', 'cemilan di antara waktu makan', 'Noun'),
('v_n4_auto_639', 'N4', '夜食', 'やしょく', 'yashoku', 'makan larut malam / supper', 'Noun'),
('v_n4_auto_640', 'N4', '給食', 'きゅうしょく', 'kyuushoku', 'makan siang sekolah disediakan', 'Noun'),
('v_n4_auto_641', 'N4', '弁当', 'べんとう', 'bentou', 'Bento / kotak makan siang', 'Noun'),
('v_n4_auto_642', 'N4', '食器', 'しょっき', 'shokki', 'peralatan makan (piring/mangkok)', 'Noun'),
('v_n4_auto_643', 'N4', '水道', 'すいどう', 'suidou', 'saluran air bersih / keran air', 'Noun'),
('v_n4_auto_644', 'N4', '電気', 'でんき', 'denki', 'listrik / lampu listrik', 'Noun');
