-- SQL FIX FOR UNDEFINED N4 VOCABULARIES
-- Copy and run this script directly in the Supabase SQL Editor

INSERT INTO public.vocabularies (id, level, kanji, kana, romaji, meaning, type) VALUES
('v_n4_auto_565', 'N4', '受付係', 'うけつけがかり', 'uketsukegakari', 'petugas resepsionis', 'Noun'),
('v_n4_auto_566', 'N4', '部長', 'ぶちょう', 'buchou', 'kepala bagian / manajer departemen', 'Noun'),
('v_n4_auto_567', 'N4', '係長', 'かかりちょう', 'kakarichou', 'kepala seksi', 'Noun'),
('v_n4_auto_568', 'N4', '課長', 'かちょう', 'kachou', 'kepala divisi', 'Noun'),
('v_n4_auto_569', 'N4', '主人', 'しゅじん', 'shujin', 'suami (sendiri)', 'Noun'),
('v_n4_auto_570', 'N4', '家内', 'かない', 'kanai', 'istri (sendiri)', 'Noun'),
('v_n4_auto_571', 'N4', '息子', 'むすこ', 'musuko', 'putra / anak laki-laki (sendiri)', 'Noun'),
('v_n4_auto_572', 'N4', '娘', 'むすめ', 'musume', 'putri / anak perempuan (sendiri)', 'Noun'),
('v_n4_auto_573', 'N4', '整理', '整理', 'seiri', 'penataan/perapihan', 'Noun'),
('v_n4_auto_574', 'N4', '試験', 'しけん', 'shiken', 'ujian / tes', 'Noun'),
('v_n4_auto_575', 'N4', '成績', 'せいせき', 'seiseki', 'nilai / prestasi', 'Noun'),
('v_n4_auto_576', 'N4', '教育', 'きょういく', 'kyouiku', 'pendidikan', 'Noun'),
('v_n4_auto_577', 'N4', '留学', 'りゅうがく', 'ryuugaku', 'belajar di luar negeri', 'Noun'),
('v_n4_auto_578', 'N4', '奨学金', 'しょうがくきん', 'shougakukin', 'beasiswa', 'Noun'),
('v_n4_auto_579', 'N4', '入学', 'にゅうがく', 'nyuugaku', 'masuk sekolah / penerimaan siswa baru', 'Noun'),
('v_n4_auto_580', 'N4', '退学', 'たいがく', 'taigaku', 'keluar dari sekolah / drop out', 'Noun'),
('v_n4_auto_581', 'N4', '授業料', 'じゅぎょうりょう', 'jugyouryou', 'biaya kuliah / SPP', 'Noun'),
('v_n4_auto_582', 'N4', '研究室', 'けんきゅうしつ', 'kenkyuushitsu', 'laboratorium / ruang penelitian', 'Noun'),
('v_n4_auto_583', 'N4', '論文', 'ろんぶん', 'ronbun', 'tesis / makalah ilmiah', 'Noun'),
('v_n4_auto_584', 'N4', '発表', 'はっぴょう', 'happyou', 'presentasi / pengumuman', 'Noun'),
('v_n4_auto_585', 'N4', '参加', 'さんか', 'sanka', 'partisipasi / ikut serta', 'Noun'),
('v_n4_auto_586', 'N4', '申し込み', 'もうしこみ', 'moushikomi', 'pendaftaran / pengajuan', 'Noun'),
('v_n4_auto_587', 'N4', '手続き', 'てつづき', 'tetsuduki', 'prosedur / proses administrasi', 'Noun'),
('v_n4_auto_588', 'N4', '書類', 'しょるい', 'shorui', 'dokumen / surat', 'Noun'),
('v_n4_auto_589', 'N4', '契約', 'けいやく', 'keiyaku', 'kontrak / perjanjian', 'Noun'),
('v_n4_auto_590', 'N4', '給料', 'きゅうりょう', 'kyuuryou', 'gaji', 'Noun'),
('v_n4_auto_591', 'N4', '残業', 'ざんぎょう', 'zangyou', 'kerja lembur', 'Noun'),
('v_n4_auto_592', 'N4', '休暇', 'きゅうか', 'kyuuka', 'cuti', 'Noun'),
('v_n4_auto_593', 'N4', '出張', 'しゅっちょう', 'shucchou', 'perjalanan dinas', 'Noun'),
('v_n4_auto_594', 'N4', '会議室', 'かいぎしつ', 'kaigishitsu', 'ruang rapat', 'Noun'),
('v_n4_auto_595', 'N4', '名刺', 'めいし', 'meishi', 'kartu nama', 'Noun'),
('v_n4_auto_596', 'N4', '電話番号', 'でんわばんごう', 'denwabangou', 'nomor telepon', 'Noun'),
('v_n4_auto_597', 'N4', '住所', 'じゅうしょ', 'juusho', 'alamat', 'Noun'),
('v_n4_auto_598', 'N4', '郵便番号', 'ゆうびんばんごう', 'yuubinbangou', 'kode pos', 'Noun'),
('v_n4_auto_599', 'N4', '交通', 'こうつう', 'koutsuu', 'transportasi / lalu lintas', 'Noun'),
('v_n4_auto_600', 'N4', '渋滞', 'じゅうたい', 'juutai', 'kemacetan', 'Noun'),
('v_n4_auto_601', 'N4', '信号', 'しんごう', 'shingou', 'lampu lalu lintas / sinyal', 'Noun'),
('v_n4_auto_602', 'N4', '横断歩道', 'おうだんほどう', 'oudanhodou', 'zebra cross / penyeberangan', 'Noun'),
('v_n4_auto_603', 'N4', '駐車場', 'ちゅうしゃじょう', 'chuushajou', 'tempat parkir', 'Noun'),
('v_n4_auto_604', 'N4', '入場料', 'にゅうじょうりょう', 'nyuujouryou', 'biaya masuk / tiket masuk', 'Noun'),
('v_n4_auto_605', 'N4', '割引', 'わりびき', 'waribiki', 'diskon / potongan harga', 'Noun'),
('v_n4_auto_606', 'N4', '値段', 'ねだん', 'nedan', 'harga', 'Noun'),
('v_n4_auto_607', 'N4', '消費税', 'しょうひぜい', 'shouhizei', 'pajak konsumsi / PPN', 'Noun'),
('v_n4_auto_608', 'N4', '領収書', 'りょうしゅうしょ', 'ryoushuusho', 'kwitansi / bukti pembayaran', 'Noun'),
('v_n4_auto_609', 'N4', '品物', 'しなもの', 'shinamono', 'barang / produk', 'Noun'),
('v_n4_auto_610', 'N4', '包み', 'つつみ', 'tsutsumi', 'bungkusan / paket', 'Noun'),
('v_n4_auto_611', 'N4', '配達', 'はいたつ', 'haitatsu', 'pengiriman / antar', 'Noun'),
('v_n4_auto_612', 'N4', '修理', 'しゅうり', 'shuuri', 'perbaikan / reparasi', 'Noun'),
('v_n4_auto_613', 'N4', '取扱い', 'とりあつかい', 'toriatsukai', 'penanganan / cara pakai', 'Noun'),
('v_n4_auto_614', 'N4', '故障', 'こしょう', 'koshou', 'kerusakan mesin / tidak berfungsi', 'Noun'),
('v_n4_auto_615', 'N4', '電池', 'でんち', 'denchi', 'baterai', 'Noun'),
('v_n4_auto_616', 'N4', '充電', 'じゅうでん', 'juuden', 'pengisian daya / charger', 'Noun'),
('v_n4_auto_617', 'N4', '予防', 'よぼう', 'yobou', 'pencegahan / preventif', 'Noun'),
('v_n4_auto_618', 'N4', '症状', 'しょうじょう', 'shoujou', 'gejala (penyakit)', 'Noun'),
('v_n4_auto_619', 'N4', '治療', 'ちりょう', 'chiryou', 'pengobatan / perawatan medis', 'Noun'),
('v_n4_auto_620', 'N4', '手術', 'しゅじゅつ', 'shujutsu', 'operasi (bedah)', 'Noun'),
('v_n4_auto_621', 'N4', '入院', 'にゅういん', 'nyuuin', 'rawat inap di rumah sakit', 'Noun'),
('v_n4_auto_622', 'N4', '退院', 'たいいん', 'taiin', 'keluar dari rumah sakit', 'Noun'),
('v_n4_auto_623', 'N4', '保険', 'ほけん', 'hoken', 'asuransi', 'Noun'),
('v_n4_auto_624', 'N4', '血液型', 'けつえきがた', 'ketsuekigata', 'golongan darah', 'Noun'),
('v_n4_auto_625', 'N4', 'アレルギー', 'アレルギー', 'arerugii', 'alergi', 'Noun'),
('v_n4_auto_626', 'N4', '文化', 'ぶんか', 'bunka', 'budaya / kebudayaan', 'Noun'),
('v_n4_auto_627', 'N4', '伝統', 'でんとう', 'dentou', 'tradisi', 'Noun'),
('v_n4_auto_628', 'N4', '祭り', 'まつり', 'matsuri', 'festival / perayaan', 'Noun'),
('v_n4_auto_629', 'N4', '神社', 'じんじゃ', 'jinja', 'kuil Shinto', 'Noun'),
('v_n4_auto_630', 'N4', 'お寺', 'おてら', 'otera', 'kuil Buddha', 'Noun'),
('v_n4_auto_631', 'N4', '城', 'しろ', 'shiro', 'istana / kastil', 'Noun'),
('v_n4_auto_632', 'N4', '温泉', 'おんせん', 'onsen', 'pemandian air panas', 'Noun'),
('v_n4_auto_633', 'N4', '観光', 'かんこう', 'kankou', 'wisata / pariwisata', 'Noun'),
('v_n4_auto_634', 'N4', '観光地', 'かんこうち', 'kankouchi', 'destinasi wisata', 'Noun'),
('v_n4_auto_635', 'N4', '旅館', 'りょかん', 'ryokan', 'penginapan tradisional Jepang', 'Noun'),
('v_n4_auto_636', 'N4', 'お土産', 'おみやげ', 'omiyage', 'oleh-oleh / buah tangan', 'Noun'),
('v_n4_auto_637', 'N4', '地方', 'ちほう', 'chihou', 'daerah / wilayah pedesaan', 'Noun'),
('v_n4_auto_638', 'N4', '田舎', 'いなか', 'inaka', 'pedesaan / kampung halaman', 'Noun'),
('v_n4_auto_639', 'N4', '都市', 'とし', 'toshi', 'kota besar / metropolitan', 'Noun'),
('v_n4_auto_640', 'N4', '人口', 'じんこう', 'jinkou', 'jumlah penduduk', 'Noun'),
('v_n4_auto_641', 'N4', '面積', 'めんせき', 'menseki', 'luas wilayah', 'Noun'),
('v_n4_auto_642', 'N4', '気候', 'きこう', 'kikou', 'iklim', 'Noun'),
('v_n4_auto_643', 'N4', '自然', 'しぜん', 'shizen', 'alam / alam semesta', 'Noun'),
('v_n4_auto_644', 'N4', '資源', 'しげん', 'shigen', 'sumber daya alam', 'Noun')
ON CONFLICT (id) DO UPDATE SET
  kanji = EXCLUDED.kanji,
  kana = EXCLUDED.kana,
  romaji = EXCLUDED.romaji,
  meaning = EXCLUDED.meaning,
  type = EXCLUDED.type;
