-- ==========================================
-- DDL SQL SCHEMA UNTUK SUPABASE DATABASE
-- ==========================================
-- Jalankan script ini langsung di SQL Editor Supabase Console Anda.

-- 1. TABEL: user_profiles (Menyimpan profil peserta ujian)
CREATE TABLE IF NOT EXISTS public.user_profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email TEXT NOT NULL,
    full_name TEXT,
    target_level TEXT CHECK (target_level IN ('N1', 'N2', 'N3', 'N4', 'N5')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- RLS (Row Level Security) untuk user_profiles
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pengguna bisa membaca profil mereka sendiri" 
    ON public.user_profiles FOR SELECT 
    USING (auth.uid() = id);

CREATE POLICY "Pengguna bisa memperbarui profil mereka sendiri" 
    ON public.user_profiles FOR UPDATE 
    USING (auth.uid() = id);

CREATE POLICY "Sistem bisa membuat profil baru"
    ON public.user_profiles FOR INSERT
    WITH CHECK (true);


-- 2. TABEL: questions (Menyimpan bank soal ujian JLPT)
CREATE TABLE IF NOT EXISTS public.questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level TEXT CHECK (level IN ('N1', 'N2', 'N3', 'N4', 'N5')) NOT NULL,
    section TEXT CHECK (section IN ('Vocabulary', 'Grammar', 'Reading', 'Listening')) NOT NULL,
    type TEXT NOT NULL, -- e.g. 'kanji-read', 'context', 'audio-listening'
    question TEXT NOT NULL,
    passage TEXT, -- Teks bacaan panjang (Reading)
    highlight TEXT, -- Kata bergaris bawah / sorot
    audio_url TEXT, -- Link file audio mendengarkan
    options TEXT[] NOT NULL, -- Array dari 4 opsi jawaban
    correct INTEGER NOT NULL CHECK (correct BETWEEN 0 AND 3), -- Indeks jawaban benar (0-3)
    explanation TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- RLS untuk questions (Siapa saja bisa baca soal, hanya admin yang bisa memodifikasi)
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Soal dapat dibaca oleh pengguna terautentikasi"
    ON public.questions FOR SELECT
    TO authenticated
    USING (true);


-- 3. TABEL: test_results (Menyimpan riwayat hasil try out peserta)
CREATE TABLE IF NOT EXISTS public.test_results (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    level TEXT CHECK (level IN ('N1', 'N2', 'N3', 'N4', 'N5')) NOT NULL,
    mode TEXT CHECK (mode IN ('simulasi', 'belajar')) NOT NULL,
    vocab_score NUMERIC DEFAULT 0,
    grammar_score NUMERIC DEFAULT 0,
    reading_score NUMERIC DEFAULT 0,
    listening_score NUMERIC DEFAULT 0,
    total_score NUMERIC DEFAULT 0 NOT NULL,
    correct_count INTEGER NOT NULL,
    total_questions INTEGER NOT NULL,
    time_spent INTEGER NOT NULL, -- dalam satuan detik
    weaknesses TEXT[], -- daftar kelemahan terdeteksi
    answers_history JSONB NOT NULL, -- menyimpan rekaman jawaban pengguna
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- RLS untuk test_results
ALTER TABLE public.test_results ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pengguna bisa membaca riwayat ujian mereka sendiri"
    ON public.test_results FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Pengguna bisa menyimpan hasil ujian baru"
    ON public.test_results FOR INSERT
    WITH CHECK (auth.uid() = user_id);


-- ==========================================
-- TRIGGER OTOMATIS: Membuat profil ketika user baru mendaftar (Sign Up)
-- ==========================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.user_profiles (id, email, full_name, target_level)
    VALUES (
        new.id,
        new.email,
        COALESCE(new.raw_user_meta_data->>'full_name', ''),
        'N5' -- default target level
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
